apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yaml
- renovate-env-secret.enc.yaml
configMapGenerator:
- name: renovate-values
  namespace: automation
  files:
  - values.yaml=renovate-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
