apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: automation
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:E7c3KhlExTYp5yfV1FAG3xogTFk=,iv:egapSFRWspK1U60MImkD7sejYBLpYfKni0DPVcwCU6Y=,tag:6QQbiOhW03DrLH1XKOLUzQ==,type:str]
  AWS_EC2_METADATA_DISABLED: ENC[AES256_GCM,data:reucxA==,iv:FvyFDDia51FgG3sw9Njs/0F4aMxWa8zOP01GjU9IQaU=,tag:IPHLYgyfwLNDf6j8n/dKoQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:RIOgog==,iv:5D2fKtWUaB9z0SVppMJrddpOXJg80ZvwBPqTWk7bm0I=,tag:2Kq0eqNd4jBCuXaCPkFZLQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iDkHOyLLHpaHMssOQkze7a+32lYfkrSF9bcLX21hYrf4/dvE0daT/g==,iv:+3yxa6KpCTRXVbcj6G0RrZFWGcL6eG9J6o887aC862I=,tag:L3GyUNjLHHv+2ca3H8G/YA==,type:str]
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:a8nt0hyiQwcai9bthyW5wblFBT4pcXxy08DVz2u2TepCstRlEC7cxYIcN+BqcwT8CI5CfXCcjKm9nwV0eseX7JthpxgnJ/4EW9hF76LeSI+9ptF13DWHKzhRjFki,iv:VF2lRLVVpqriXvLVztobdWSd6d7Vni8/mZbNH6Ttx7c=,tag:flDD8uh5xjsYZYA5titFgg==,type:str]
  RENOVATE_HOST_RULES: ENC[AES256_GCM,data:zFc9mdPmUJ/1xM6VgS/Xh5hXJTffCwemzbDAZfVdbU7xtOAkmeXOgQ97g2XfHlDkJPWcxwr0aRglliLxjyGEzTpKr8Ed0W5ovT1SFioVfF8VRg==,iv:FJdaVde3Yw4Tttex/kPCKJLjZXy0ezb5Y3svzJWbJoM=,tag:njomkUFvljo/3LqLtj/SmA==,type:str]
  RENOVATE_REDIS_PREFIX: ENC[AES256_GCM,data:IZRZwDbfjONp,iv:VjpcxMEcjj3N3E8rq0h8O1q1LzbfmhoBP8VcVwDYG6U=,tag:NtEH6A8H1hm6VEur6ORFKQ==,type:str]
  RENOVATE_REDIS_URL: ENC[AES256_GCM,data:BrJ7gFtKh5G1WTZead36u8AMjMQQQqX0evqsWYDsoN7K5Jx+5pA7h0N6reuLXStHQFGdiXcz,iv:KFXRrd4er8RDGEFD0uCPPmg4XG2q7PKmPkyn+9v7F6k=,tag:TRAi5D2oejPZZaijGYv3Yg==,type:str]
  RENOVATE_REPOSITORY_CACHE: ENC[AES256_GCM,data:eoyYXbABRA==,iv:fi2+zj5Sr7fSbYRe2K0LAhWYfhOmKiDotBLzjIxEEO4=,tag:4LjvkCesjWmz4e0aVM5Bxg==,type:str]
  RENOVATE_REPOSITORY_CACHE_TYPE: ENC[AES256_GCM,data:YZxcTrpZxe1cxcN8MA==,iv:y0eQn6d0/UwB3bumnmEW5bylddL5yyR2BX5dCBppV0Q=,tag:CLw0T8q0M1/Zfh2u4BoGVg==,type:str]
  RENOVATE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:Q7Ue4bPorfhNQc3YUIyLH+grEUs=,iv:rCG92Cg62M5vtOP3N6mbOl6d+Q7udfy09U5IGR9oMQ4=,tag:5NLltasqsRj2gCqrJoOFTg==,type:str]
  RENOVATE_S3_ENDPOINT: ENC[AES256_GCM,data:59llL1V3IrOQqscBSE65URA254cUAt/lIQzizbucYrc=,iv:pjxIRVr9lo/ISKa210vFNqf2sk5A6d1FFNV0A4v+EcY=,tag:uIci5SIPKMc4ln8J3wMtDQ==,type:str]
  RENOVATE_S3_PATH_STYLE: ENC[AES256_GCM,data:rN3U7g==,iv:kNceO9csSpZGVvrdlYiYvFcPwicTxmj3xerRP1lU/e0=,tag:70doU/EeLEaYEFj1CEOUrw==,type:str]
  RENOVATE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TnuGtbZr+N5+ZJl8xmdNGVFnNsh9NXfzacg/ET29CqmgOCRBBcrbHQ==,iv:tGeQKakzhJbZr5hFnP6VyH5o3aRlBQ75qXl+JQAsB20=,tag:wgeB6JgBZKfrnbSzfwEasQ==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:K4dlf/9BX8Z3z3c60mKn0WcV7oYlrkMnyG1+zxr2cZFSkaKvlDRygR5GmOGFR6h7+6oVOGUea/yzQ+HNwdq7dMZVR6/6XHAnx6SCIX7xIIwK3VC/FdSoOOqVQNJ+,iv:NGFtiUr0xWHF997DGXDFAyAt07KsXelpjrnAzKLbZvQ=,tag:jn5izkzSaFiYldcvThbhgA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeC93WlZIMEFKQU1PSzM1
        eG1STWNSMnVoVmVqTHFJeWlaWTJoZS9qVFRNCnU5dElFeUExeFBZQk9sOXdqN0h5
        Q2xwRWg2S2dLZExyTExrWjJLL3hXOTgKLS0tIFIwZjNNWlh2SEtvdzFaK21IRGY2
        TXd5THF1azM2SG9EL2ZXdTU3SmRTK00KQ6H8bQP7jI044mgB7zH93TuOTM872zH8
        ACEHjmNCzMyqrPyF0ItRUWx0czb4W8UxOo8Bpu1V83bYhyaJYG+55A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM0wzUU5teFdwMGE2d1o3
        WS80U1BCSmo0dlpWZC85VEp1T2NrM1p1RWtVClRXWHdwMVJIZ2tPM3RKMU9NNXhL
        U0NoUkwydHZVOHgwYUVxNXM2eFJGeVEKLS0tICtXdFRvSDJ4Tm1WY3MwRkNleGVN
        TmFqeTM2WkJPNk9uODRROVlyQ0xPb3cKpkLZ01K830oRFYkirdGAvuaBxq/UO8ei
        hOj//bAjIC1T5nGQOMC4XY/6dsvc5waYL2YFIP/JN/1Ec9L01cVwCQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRDZtV0xhcGZYVlNIN1Z3
        Sm1hcnhGdmMvY3FXQ0RTMWI5YUd1RXBKWWlvCkZVbmU4VXZZeW8yU0dnUlU2Q1Z3
        cStMZnBTN010aUhKNXdsRTFXb21SdHcKLS0tIE5oaDByRlowd09zODJIaTVMRlZG
        YU41OG9LV3BMdXhqdS8wcGVyVFJFL0EK/+lxpeYum0sqCkqghUmC8HP6ohUwlyPv
        0MRCoQMGgHLk5+hoOwdRwnD0URv7IlJSqbyHCAUXo9ETnz+PAbwJmw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T13:59:05Z"
  mac: ENC[AES256_GCM,data:L+Z26Q/Nl96b6rtua9eG/zkyF5pEc+4rVIF8Py72ESdcc1wVzc2ZzCcJhEALMil0fqLjHrsHkP4BBIzv+bs8jIcK2yPoiWkuTLjLLyp6gnowUKRUYQgi+ZbiX75G29RAMrfG/nKOS0u+XcAO54CqzBAPRIkPDfRbYnIjJewtzKw=,iv:g4zUbWkwnQC6k2SuUBUm7PtBvMi7fOw62/SM+Bd1Vv0=,tag:3CUf/bo8pXwpSK2rOvebWg==,type:str]
  version: 3.13.1
