apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: automation
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Kg+5dWhmO0a86/TJ0uvu/lMpI9o=,iv:cJO8NgAznCq1yDpnYxPgnp3Y6jCiqLp60dLfLWKwRH8=,tag:Dt3Aj7SgEQ1b5M/zhsdr8g==,type:str]
  AWS_EC2_METADATA_DISABLED: ENC[AES256_GCM,data:yP0w8A==,iv:duuETrhexi7Dfzwg7d9GQJEv+42zZZqgTdjrNJ7t0Ms=,tag:qEtG7IF/BugLD36xtoh6TQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:Yp2vsQ==,iv:islpzUDioj3W6N5HqxiTae10XCv4UZydPmVErh26yyY=,tag:52B16mbflMiRNj/KmwYAUQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Z1X7zEXynhFuTlhEEEXSxGqJVIYd4+r4wCZb30bIMwhr0P99FYvxmg==,iv:n+hnokXM0n1WvLt5nkUIWyi9mA9/SmS21eaBozfA3E4=,tag:77RLnFaDb+IUhQiNlZyH5w==,type:str]
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:ny99xLpvlsHxMgNRbvbQwTr6MDYmOYCiUnZpsoomVUw5eX9FPb/gySVtejdhROGPunNUr6Qar6OdbmUiXSt5+i6xRKtg2PG7WimxauUMvCW+7V9WPimJUThqLQ2X,iv:EzjwqC2iXkQayuhVUXKUhnLs93hA6Ne2mZeOeR59tls=,tag:44IDO1yf0vs+3cOBIPKuNg==,type:str]
  RENOVATE_HOST_RULES: ENC[AES256_GCM,data:qgOg4s8EnKXo558OMPb2IT9E13sKn9qe0EgRTmqYtbOW9WIKtPos96DYpoP0O4rxXAN7HerHeunhpSYfIcZ/P0jV2yX0xUWSp+YZd2PYaIgJMQ==,iv:IshUlhIjZLj2a4XGOPYukhFf554myteCKtXiAnQtTz4=,tag:7y6so/nw86+OuuTARwjj2w==,type:str]
  RENOVATE_REDIS_PREFIX: ENC[AES256_GCM,data:U3Crs45W1hKg,iv:CEwh7fmCVqUV2DoJ7gBktVmzmTmEUo1CJkN4PNWXosg=,tag:/9zkm4ewXpOYrM4vCCQ69Q==,type:str]
  RENOVATE_REDIS_URL: ENC[AES256_GCM,data:QBYLCeHnkzEfoz65bOPPbRNU68DeG6zshngspuKXlkr06ymKNaBLzqCDD6pvWKxW1/US01VV,iv:708cw4/vgioK7vmPnsMVJ8VH8FLleogYCAOR8m86n0Q=,tag:D81d76vPPY9UjWuYBCakVA==,type:str]
  RENOVATE_REPOSITORY_CACHE: ENC[AES256_GCM,data:/wuWhM+hug==,iv:giQqCTOOI3VyH0VsiTIgTv/VDMkrFfT+aRz6HO4t1oE=,tag:uu3O81x9Eqg4xtUiahG0ig==,type:str]
  RENOVATE_REPOSITORY_CACHE_TYPE: ENC[AES256_GCM,data:dh1XsXQLCbIoV1U24Q==,iv:KxoXDEJ/zsHXKJ0K+rMDppi0JUbQwWo/WwKGSuLBwQo=,tag:KWWLrXIxYp39T5HImZyGRQ==,type:str]
  RENOVATE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:AJIu0Y/eV5gv699JorXHUfEnJKs=,iv:hgMgpAcaVMo8wKQxEc1V4iiLjWFNWr2sGrMmvPi0HuU=,tag:M6011zvuryUXbwQWowSyNA==,type:str]
  RENOVATE_S3_ENDPOINT: ENC[AES256_GCM,data:ahxkyUQ2zwdAn1GCTaRI+ig+HZzJmIYV4Gy44XHuH38=,iv:JVdBbczm1cd6ZzBzNgbKWdnfxpRw04RZJfGmujjfclo=,tag:gERi+uCUbvyo94YYXwW/eg==,type:str]
  RENOVATE_S3_PATH_STYLE: ENC[AES256_GCM,data:dyBgwQ==,iv:pve4/CIzQSMgTc6CQ4nwQtUA+aQu+D4Hk2r1IEYxTFc=,tag:rMC4rMWHD2eXp5jr2kCJAA==,type:str]
  RENOVATE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FJ8SGO8uruuNNn2wgafuYuvnUm+7kM61daXvLfgL1tPQyQX96mFvjg==,iv:DYo/JvtK1YOdlVDJgMQJwt4t6s/bDtTgVUWrWWL0SdE=,tag:OfzRj7BH0e+IjdnfGVBhHw==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:srDPbtJ38XsHWxzsZaGs1+8VMNjC83WajqgOEQQYsET6DT7Z8CL8T/zRpfKF6QLfjvnRqeYEHSCuOLXqnZye2MMdEHN0zLG5nPLNIXFq/V1RzMcJSBA3Z5zXy01Y,iv:xaCS8LdSSh4VeIlQ0MV0iThONtzxDa1wGQIpaetH/Mo=,tag:QghvQbImKDvxmr5HGR3tfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVVFEUGM4L0J0Q1NyRUp3
        V3VlTlNGN0NxaVRGdTlndEVqSmFVV2FYYUFJCkloaThqSncxd2lGN3piTDZJTXNt
        MXBuTmorNkpmTERvWGk1T1I1MEhuOEUKLS0tIDFLa2h3ZW15SXhHbEc2czk0RnNL
        TExiamoyOWZEbjJobHdVSEV5MWlyN0UKjqSgbVneQpVasKBzCaAmD+5nl/P/OX+l
        ZHE2uM+gHev0I8ZFSLIpW5qxhsSoY8+KSg9FPKGTaWKqE/Dn8iOWwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcnNCNzJlbSsya1dzcE5k
        K0wrUU9lc21NZzJVM0RoenJtSDBHckJFM3k4CndzZndHWE5lYm83LzBnVkM3RWpU
        Zy9ncVdRWExZY0JwaEFHRkFmQUcwZ3MKLS0tIDVvRTFNRHEzR2VjMWNEZEFrbUZH
        MDhiYXYvc3czNDdBTjhHYWp5eVl4R1kKzqTs4WLZ51K599xcXt7aBl5hO0Hc/ySb
        yK0AjRsEMDzpC1DnjQutnm0s8kyBerW+vq9iRRBiAeLOGwTF414kpQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZlJFdWdPaEk3aXdoN2JJ
        REhLeVpLWHE5emZxM2NhOUk3RWp3cnNnR1RNCkh3RlU2SWErczVOWUoxM3JoRlVp
        Qm9EM1ZIdUxWQjdLRFVLTy91enhnT28KLS0tIFI4aVRJdDlqNFhtMGlIUVROQmJS
        ZE15VkM4VzBPMllZdmZKSUJ2OWRtbXcKvKKlAEtyWqNDmiJq5YPIpX0Cd04EGlT5
        od6SZsuqqRCibDaqM2bd1Vypd6v2YEMjjmeC2WSzUcLV5vOycPBmHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:o6G57uj+ciVJb76LNHM8b8NjtkIR7EeM+CXdxHHQTut2+3d1FlJRwyPdkjd4qxXwC8JscuIjoymLkWIQlZGe0tWy9D953b55z2595MIZ7s1JC9NL3XbKF/nEkBhD8WWuomLeg4i3kBTUg8UJuxwgUWY5ElOSQcmN1RrVi+oFagg=,iv:FwvP1J3XR/PbLxPm0bKFxYL2pEn+ksRDO/9JAmig5uU=,tag:TSLrhWRdwog/tPn1C48Qpw==,type:str]
  version: 3.13.1
