apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: automation
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0SMreBkZZWW51pTXQFKmdM9/A9hP7jZGH035Yw==,iv:fkYpMyQiDee/z7u9L6FuGNaEj6OYuXYkW9Gm3YjjpGQ=,tag:aLbJSaQuruzAElZBl3GXSA==,type:str]
  AWS_EC2_METADATA_DISABLED: ENC[AES256_GCM,data:Kq3d3rykfJU=,iv:gahkMVqtK2AmWGhFu7p9H3bnNIvvEeZ6jyOTTi722Ec=,tag:RZuHuxA8bk0hgbxxPgI2QQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:Trh9srkr2m8=,iv:WpWg44El1CybiCeFefq6nEEC6Qw6ZgpPTTpqUt9c8pI=,tag:u3RKAXZCy6Fg5NG/4IQAdw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XIvWZfpsBDgBRQe1B0COpc06bjMPTjJZ6eK+Ux9s/pcUdo65nC13jhVojP8lc5cUqyZc8UbhR1k=,iv:JkaXk1GkerU2waPX5J8eamVAUCLLyDMcptpG7kmXPRQ=,tag:Cy/yPyMeDJQjdBtiHT7B9Q==,type:str]
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:psdu65E1WD+CzqPRtIYbBWLifuzs2Uz12ix6upZW2PCTpIB8KtoUfS/1eSQU/aMJlr6ISPc+943QSj0AzU021U5sJDCchKOqC1VLWWNHyq75xJyPZr76QFRPh3hijgJyItZsZnAu1HnCkyhlONGLzqYA15+hKG+l31iHsQ==,iv:KiKdln1FbQXx21cYxYAkpl7tzx7xXSt2mmC0piwSgnw=,tag:aXP4w8Zr+Qezf5ouag7dvQ==,type:str]
  RENOVATE_DETECT_HOST_RULES_FROM_ENV: ENC[AES256_GCM,data:cN8TfP4T97c=,iv:uBbkXtQQBUHFl5j5GaPdyE6K4+4Wn+I/A6NTHHmsrlk=,tag:hQdKLRAS60v7/7/F39cnug==,type:str]
  RENOVATE_HOST_RULES_1_HOSTTYPE: ENC[AES256_GCM,data:22m6AI1VHQM=,iv:kQa/qafAXiJQoIYth9DTaDQUv8aEtQ0IBQLE7nJQpwg=,tag:a12WwSUZh1mEjMHeo+WoZQ==,type:str]
  RENOVATE_HOST_RULES_1_MATCHHOST: ENC[AES256_GCM,data:z351wJ61riXqtZ6bP8acoXCbwBQ4t0phAX15KQ==,iv:wTc9k18xxtKIHQZxQUZ4DgUkQgMprtfoMxAUBK1Wqt0=,tag:+t5CxO31ATpxbn896owYoA==,type:str]
  RENOVATE_HOST_RULES_1_PASSWORD: ENC[AES256_GCM,data:lJLISn2ujGkCUASl,iv:jTM/fGsD8GQySwzJgW6V3MSYo15RY29Gkm+KEj9Qmrc=,tag:bCfHsZejeMzpGSWikzHtjQ==,type:str]
  RENOVATE_HOST_RULES_1_USERNAME: ENC[AES256_GCM,data:JnAs5IDczPs=,iv:CKx725NxAkZcajj1fNsReRmAalOZ6Jb32SU7UF5C2Rk=,tag:q0kqWiJ7uLD7s/3hWP21LA==,type:str]
  RENOVATE_HOST_RULES_2_HOSTTYPE: ENC[AES256_GCM,data:+KB94eNLnhA=,iv:Wm2xB/6i71+uI1wja/ouumXyHWMlUC6lrCljF7nV7CU=,tag:4P3zYA+RkBbCSoTqaMYASw==,type:str]
  RENOVATE_HOST_RULES_2_MATCHHOST: ENC[AES256_GCM,data:rKifL+WQmkT23xOSn+eZftC4gF7IKg7cB//gbA==,iv:XpI83lh70KnNwZAYFH4TVm4/qBtzzZhT4l/L5QNLbLc=,tag:OvcVqH4NA1OjnM6qgz0S1Q==,type:str]
  RENOVATE_HOST_RULES_2_PASSWORD: ENC[AES256_GCM,data:2jvR4OLY0MezntH9,iv:vkc9ExFv9Vt8LPJ6cU0aHKEI7vYOntqT4W+6pS9losM=,tag:wjOhI4ke2NMBUI7vlDVZ8g==,type:str]
  RENOVATE_HOST_RULES_2_USERNAME: ENC[AES256_GCM,data:mG1oUK5BxYw=,iv:fStn63c1tN4izcJs0bjNBpQy6hKQSMXYBKtWfE67O/o=,tag:uJz1Zhyn4QmdW27JQ/716A==,type:str]
  RENOVATE_REDIS_PREFIX: ENC[AES256_GCM,data:vF3OyHxpxO6BbWzk,iv:301OYWcrtPnYXZpTWG4+BUPAifHM3l/uTiet95gk74c=,tag:kfAVMNjzSmYgU5Zbp7zJXw==,type:str]
  RENOVATE_REDIS_URL: ENC[AES256_GCM,data:y9pvIT+PnUriGLBjeMBBpZEXCOEwbztX1smMcDOfIoE5nBVJmQTCoKortJOGsR3h1GEAJ6RHVUmG9ZIDDfP97e8MvMhU7ppo,iv:XEPy6WQXdpRq5QT1//oLnWvrRB+H/sxdSMmHkTzruuw=,tag:v1LoMverp+U54WhUh1etoA==,type:str]
  RENOVATE_REPOSITORY_CACHE: ENC[AES256_GCM,data:X7NJibmMaUOq7iIP,iv:NDmtHRrhzBx5wue1VX95MraOiraTfrAjb7FvaMUYWRI=,tag:WcKA1aqI59aiO1ASgd5AHQ==,type:str]
  RENOVATE_REPOSITORY_CACHE_TYPE: ENC[AES256_GCM,data:qx3XcVyJKuzJ9AiyiuqcUy3HTV8=,iv:l6KVKTR86J0WP0wtpa41EMINELKCHhimEMPgGPbZT08=,tag:hEei4K+uO8OUUypBfq8uaQ==,type:str]
  RENOVATE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:PlZeozOYReKTvZBN7JjAFomXmNok/s2dwn20cA==,iv:M9cQIn2qcGcoDOM+1mNHk5t4YKTRefrFpxhZHRbGOok=,tag:XVu4JSs51/+hPazAd4jsBw==,type:str]
  RENOVATE_S3_ENDPOINT: ENC[AES256_GCM,data:8B8GXwLVWL0MVC6LjZiJrWCCorqtuwV5bpZvqX6mjOJOaz2hd/iC1rEI0k8=,iv:DQb1HLgAcw/uD4ADZUdmyYJdg9Q8krp5Q+MbnQ5P3ks=,tag:E7uDpLWSmRmNvVE52I2/yw==,type:str]
  RENOVATE_S3_PATH_STYLE: ENC[AES256_GCM,data:B/6/UjM72hU=,iv:B09BKwFBAU9EShAAb9Iq2zsjQI+Um0jhkpxAoF1dtmE=,tag:GJeRMfzBds1OjmJFIdb5fg==,type:str]
  RENOVATE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6bGyAITM+/IQpTy4lEqOanrFiPNeQoAxs48+ULz1qwf7BF3lFpspFH/2N27/qPaYf5maIjHVmaE=,iv:HflMFPda1RQcCW1b0EB84ddq8EfrWAb9AlpC2StnTVc=,tag:/XXgs50pfV4hj42Mc8Sw1g==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:FicBuI569FlKvhQ26OZ3VY7C0S2KNCYIa3YBilsnlnJyH50a8CefW6c61mIoiRIX3TAWtZW5+IGtueN/XNYEGm8KEmWwm6IUkxPRo2svEnCkeD3ckSRHDVonAORMQBXaP8FqftjRJy1pdTu3OAuIui71nMsXEPUD0zAeRg==,iv:MEggD0SL+L6R4F4UQaN8ZbNQ1zz5ENmhKNGN03ldGp0=,tag:wJSf2yiXqygSvsHybivExA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvREZUalFSRTN2bDAzRnBz
        akFTQTBnMGQ0Ni9KTlFLQW4yOXZQK1FuR2pRClJIblNDdWgyMjVkdDRJT0hhRkxw
        N2NqRUhNQ0IvSkVYNlNTa0VPdmhiTlUKLS0tIFkxUzRJVjBnZUlOSjdSOEZvVW00
        NlcxNEE5NTJmZXdXRk1kOXhmWi9wam8KyBb1kQj1MDq4d/EWikHh6cu2JNhOokO2
        iEsr9GH5iE0g5L9sNr8mH0fUfyYOOHSrUU5laVMYg7r7gI5tXQDFQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY3Q2aXBobUhmREwxTEwz
        OEtrS1FKYXpnN0pMSHNFbXBPVlJIMkQzaUZVCkd3R2dleXhiTEdJYVNRdDkwdEpW
        R3UzbnV1akliVW9XU0VjeklVb3h3UlkKLS0tIHBrS0t0dHh3aXRBcTkvb3YzKzhm
        NkZEaTVDcFVrbDl2VTBWZlpJaUE0bjQKNUWgvAVl5nInhUs1OLtFWm2/HX8ClbIK
        ti0jW6ORQWuvL5F+vhuHGG0T0uBYKiCwnLTSlVfPQRPHlZezxUeRlg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4T29aVnduUmJkOUhqU0pw
        YW80eXErMDQraWpRNjBiSzdJWVVXU0lKL2drCk8xNmh2QlNNNUJMVjdPc1BtbEhp
        NWl5RmJXUnZVK0MxMlowS1V4M2VvTHMKLS0tIGwxREc2T2JPY2ZMVXFjaEl1V2Ni
        dWhJZ2tFTnZMOE81dUxlKytSQ3A3VFEK5+awjh98SzprUgiU3u5zlnl0cpLv6Ax0
        M4xcg8vC2b+uaB/H5rJjCaRJC5PrZqtEwYFefTnQDrtN5O1Xb0ztGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:fWjVP7mUi6T7OxxXvp0Conz0t6x9KeqQiiCUUfYeQ1LMrJAJcLQBNW/owk/LAlTVq8XH4ngSA74KYNx2hjUNeUJu9E/hm96gE3IxgKy0bATOVT2eif4veBWskAn5tb13fe0PmyjKSPye3+52OXuac732auOhaFB4i0i/A0YWNwA=,iv:GHJ4isO+HxNjgKgiB0UxuS1Jw630YuDG+cO22TwawgM=,tag:pPmitRO6pD39q9JWPz0AaA==,type:str]
  version: 3.13.1
