apiVersion: v1
kind: Secret
metadata:
  name: bytestash
  namespace: bytestash
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:b1iNy+wIgfG2sPiB0j8YjuBZjJ8FNlPwcTWuw11BkQ7usfqwaLUAyjgjP/o=,iv:uJBu65aBOPmn+Jzm17GmSr23gWPLxUazS2QuZBM7oZg=,tag:cIo8CvMwKeibk5o+RwnLeQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRHBCLzBXZGFiZGdUSm9P
        R3ZhNGdGZ1g1ZXl5bFBKVnZKc29OaGFKa0ZNClhwMVRHeVJtVm91eWlCRDdFMmZv
        MTB0SnE1Mk5CcEt0d0hrTjc3TUQzcEEKLS0tIEs4QXJuRFJ0aExzYkdEWTVjcXZk
        Y05lSWtqaldoM3NScXREZDVaaDRoRGsKrtu959QRULz+ALwShTWhnrmlZL4mfyqG
        5qEGq40Aa9oPBWuzGd1INhPcvCK4IhQHkn7Zhsnquzx0xyy8T2VjWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMXVPRUJ6RCtXekxKRlV4
        MkVpbUhzbVNXbVQrZk9QY2pQT3U2RlhKNXhFCjU5TEdHY0lPZXlJMnNIR3hTV2o0
        bjNDMXAremJOQ1I5VzZRUkdxZ2poeWsKLS0tIDV0LzFoaWpaa1o0bXZXWG04bE5J
        bTFxbFIwYW53bTFaa0JCSllHdWUvRlEK9RiszleRzSLV5UlYctpJavQIBH8C7vC3
        8iXyhIXEcGGS/7Nv0kfg3nEHEuZBWEItiMO5irBERnsUzHMKxdsoqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNlpNYUtLRlVtQUFhOU1W
        VStMK3B1L3hZSmZSVGJpRFhGMVFkZmdEVkZJCmY4cFhGcjJIaVVaRlgvRmo2anRN
        VWt2czQ2ZzZIbmt0ZzEzSW14RzVrQm8KLS0tIDMzYWpFU24zSTQwOTNqbG5zai9r
        ZjFPYXljWFZ6Zk84UGFDK3ZTZzV5V3cKqISkXhILaEPzu4SWVSHgPuXJH8QM0R0F
        WK77h3qfWaybKysOwGGHKAiWP621i1kTaU+edq9JBwd6goIJKEXf1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T18:55:15Z"
  mac: ENC[AES256_GCM,data:fB7VAPTunhKUqaE6+J23+nk0wItY/oQ/xWy2vR7yw6+smrpLQJA1e4pJ83qSOa/IjDiLtBAGODR3wtJxJ1YLujhM33LMptZ7kNB2+/cMtcXyiwPA4vobMelQvqYa/lsjaWqysrou/bvlvNL5deW2Y6Q5mkz35q4UOiBT8lZ1X4A=,iv:zRSTvLFVo3i2oZFDy+SWSDznts6TEwrkhAzwQWYOTyQ=,tag:5pSLtjU1nIpKDy5Us7hy+Q==,type:str]
  version: 3.13.1
