---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bytestash-data
  namespace: bytestash
  labels:
    app.kubernetes.io/name: bytestash
    app.kubernetes.io/instance: bytestash
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-csi
  resources:
    requests:
      storage: 5Gi
