apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./homepage-rbac.yaml
  - ./homepage-configmap.yaml
  - ./homepage-deployment.yaml
  - ./homepage-service.yaml
  - ./httproute.yaml
  - ./security-policy.yaml
