---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: stirling-pdf-chart
      # renovate: datasource=helm depName=stirling-pdf-chart registryUrl=https://docs.stirlingpdf.com/Stirling-PDF-chart
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: stirling-pdf-values
  postRenderers:
  - kustomize:
      patches:
      - target:
          kind: Deployment
          name: stirling-pdf-stirling-pdf-chart
        patch: |-
          - op: replace
            path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
            value: 180
          - op: replace
            path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
            value: 5
          - op: replace
            path: /spec/template/spec/containers/0/livenessProbe/failureThreshold
            value: 6
          - op: replace
            path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
            value: 60
          - op: replace
            path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
            value: 5
          - op: add
            path: /spec/template/spec/containers/0/startupProbe
            value:
              httpGet:
                path: /api/v1/info/status
                port: http
                scheme: HTTP
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 36
