apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- helmrelease.yaml
- httproute.yaml
- security-policy.yaml
configMapGenerator:
- name: stirling-pdf-values
  namespace: stirling-pdf
  files:
  - values.yaml=stirling-pdf-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
