apiVersion: v1
kind: Secret
metadata:
  name: barman-minio-creds
  namespace: storage
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:movp3fE/Zw96TV6rtMLmr1qLBOc=,iv:umExlAvbaMRKoA+z1fUFQYkmwHL9WbEdCyCmTwTXOqU=,tag:1e9CHzYd/ZZj21DbSM6F/w==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:lMKjvrH/4aDJu2AnYLpq3Rpa2ri1IuK61nMlX2OhSg1h+ioBDQ2zAQ==,iv:0u3xi/gALwyFWNXOG1sbJXiYBwj0rEUbUBUOgNjCxGU=,tag:CWGSlAqr5s75TdXuQje78g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVN0Vob3BQYTBaTDZuK3Av
        d3pLenBrMjU4T0d1T1dBemxxQnI1Y2JCSVU4CnV3bjFWOUZMVis5M29uYlhTWDRD
        cWtEb2ZKY1N3d1MxQzltSjZ3T0RpcG8KLS0tIGRCK1B2MFlQYmlYZ05SRXRKeW9y
        Q0tXYVc4QlVrbldQY2owcGdSR0NIMEEKsGNb6/gWbOLaEH8u6wSJJds+FvxB00SI
        wEbWTAZBwujC26CCvWrrBk4gXjYy1iB5uJMJm6qS7ZQKcnwZsRJF0g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudEhxVDNOZXM5OWJRSzJJ
        MWpibm1tbnk0bnE1bVI1MkprRExZRXBhR2dJClBnc3h2Vk9wMThDQlhnQ0JWd3Bn
        cHk5cmYvR1V2ZkRnVy96bFdDeGZ0d1UKLS0tIGlyVlgxSVdNNlFLK3M2OXdzRmla
        VnZSZFhvZ3g2b2dacmpZVDVPaEZsbjAK5CVW2boahZ2KBgvsIE/BvAEiyA+hUxip
        V4AQaZijWHU4I7JyMmPBQxtZC5vIwPcajsi6k9hu8Ir6RgC3PktosQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNWxWNDNHZlpDd2gwZEM0
        V0kzczB4aUJGaCsyYnUxV1dGT2pyNUx1VVJvCkNrU3ljZ2JIMExBUEFBMTNMV2NQ
        N3B1ZC9LZCt6TEtka3g5SUJLZTV4MGcKLS0tIEcyYXJoMmVyNi9qb1B1SklCMkxV
        NUdjRGdpN3NLTS9TNVZxNE1DcnYweEkKko/dZsqtwi4nItIERI/GGfveDrQA9OCl
        InQ9H8/WhktXQRQuZc9iLmA2Fm66A5SPrichTpPobGqFjAVMzkgeDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T20:13:33Z"
  mac: ENC[AES256_GCM,data:MahzIUtscQJcpOSGISZG93/t4m8U2ETQTG1aiy7T+sN+hEkfiJNbeJVB+z0jsJbcvFgb/4QyqnXT07F7w2bmbCZvWsfvzt39MRyD10gcL1OVJ7A3q32tvyiGhZdnnUttIdXAcThJBdM4oyFyXHw7c175gD865MhZUk1DQo8s1u4=,iv:f9sYWMG6YXTHcZxBJH0aqP8sVHrR36QRN3NSpZRuWgc=,tag:C5ZUM69RJKAKpi73p1vZHQ==,type:str]
  version: 3.13.1
