---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cnpg
  namespace: storage
spec:
  instances: 3
  imageName: harbor.stevevaradi.me/stevevaradi/vector-pg:16
  imagePullPolicy: Always
  imagePullSecrets:
    - name: registry-pass

  storage:
    size: 50Gi
    storageClass: iscsi-csi
  walStorage:
    size: 10Gi
    storageClass: iscsi-csi

  postgresql:
    shared_preload_libraries:
      - pgaudit
      - vchord
      - vectors
    parameters:
      # required by pg_failover_slots
      hot_standby_feedback: "on"
      pg_failover_slots.synchronize_slot_names: "name_like:%"
      max_slot_wal_keep_size: "10GB"
    pg_hba:
      - hostssl immich streaming_replica all cert

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        passwordSecret:
          name: postgres-immich
      - name: mealie
        ensure: present
        login: true
        passwordSecret:
          name: mealie-postgres
      - name: penpot
        ensure: present
        login: true
        passwordSecret:
          name: postgres-penpot
      - name: planka
        ensure: present
        login: true
        passwordSecret:
          name: planka-password
  monitoring:
    enablePodMonitor: true
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          cnpg.io/cluster: pg-cnpg
  replicationSlots:
    highAvailability:
      enabled: true
