apiVersion: v1
kind: Secret
metadata:
  name: cnpg-apps
  namespace: storage
type: kubernetes.io/basic-auth
data:
  password: ENC[AES256_GCM,data:pCHfp859uX8=,iv:P8PGQWpYAf639dBnCZNj6JXDJSniwEH32v3BN47tgeY=,tag:mEAtSiJfZB+CoFXXinsAkQ==,type:str]
  username: ENC[AES256_GCM,data:W9+2HRl1ltc=,iv:pMnyHaelK1OwHxrIS3qqo1IR82bPBchB7EsN+FUCmug=,tag:UeLDh8QiDeJEsxLP5JzMHQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtLzRXalJDVExHZldUYUM0
        S0h4V3pBUkZBeFRMbDl4dVNkRWMvRENmOEdBCnZyRHc3Vi9FSkFuT092WFBuV0N4
        cDlvYkt0bi8rbzQwbTc2aWFENXlZZGMKLS0tIHVmOXZHSlRGTUNEcWloQmIxTG11
        bXZWZWlueXdGMUZvaFltUGFhalI3Y00KOm4NQNlKZ4Q5fy9XsO+XJTgCMPrTeEwe
        pEKjpk/ouGTrx9KrtVmR7sLQ9mRCvBMzFEV4oGGIQ3wcLP0enBJ8lw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYkNzT3g0OS9DcWJGNHY3
        ZCttakNaTWViWU5VTTYyWjM1QUozSXl5RzA0CkJoVDhMNHgyeStXOHV0bEZ6cnZY
        V0ZOSEtqVEx2QXR0akhPLzBNaE5kSEkKLS0tIC9VQmhtN2h1RE9WSGw0c05rQVBi
        Z1pzSHJ0YlY3bldzQ2dJTVNKRTZnMXcKEQGCapqHewWuxN5Bx1Xh/67OQyG1YsSw
        IHDRp3stXbPVwHw7/GdC1WhuUfPNSSv5fUImeDTJgEG4f7LUjN+CDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUEpJNkJ4TWRiT3NuYVk1
        NWs1cWloZngremV3cWMveTNOM2ZSNFIzL2h3Cnp4VXlDS0xOYm4yS2dOODQvSEZL
        NmVWbnZtRVBXSTF4REZNWkRkN1ArWEkKLS0tIFI4SnYxWWJOVDM4OUM4NFArS0pa
        djNMQTBrOENrN0tiQzNBVTYrQlhqSWMK4uEkWdXkm1lzMNJv7Cj/V7I1j0MUOUZ0
        VpQF4XoEEKGWPfwMZlnA4qikwTGG5P9g7iWQCaYVhsGDnurNgv1siQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVEhxb2JleGF1Z29RQ2Jh
        RVdpd0N4RWkxLzE5WUJ2WUJldGwyUmNPVXhrCnRzNWU0TjBFQmpOdStaeUNRdEJw
        WHRuN2FuRlRJK3ZTYWx3TllJVDhsR3cKLS0tIFQ3ZnVvTEIrK0YvMFcxKzZsU0Jv
        bTRDM2FjUUJDMG9vQWR3V2xMNHlNeTgKNZ8sD00SPMzbT38fg3ICcJvKDX5LZsZT
        3oh1cOh3LKAOaYQcDCLC96DDc0CNlIdyIDklTWdfFQJHwjUC+eePAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLODdqdUF2T0pKNTlQZmZi
        d3p6L0ZaTFB5SGVkanJsdHdicjlGTDJVUkFRCkZIU2F4YVFRVVZXRW9idEx0Smhw
        dzNad1BZK1h0SDQ2V2dZVkJ3WGZZbWcKLS0tIG04Ni9jTVV6Vll2MFI1NGs3emtv
        bTE0Wk43MUMrS3l0ZW9BUUVXajBmeVUK9otmf2tfRCn/6bH5eadBlhfeasTtNfEy
        QEeY4T2Lrg11f/wMipVyWCDFJ+D5eNUAWhx10eVmGEPoj1kE2lDczA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T0tyYXNtVTZ2YlFuTDNr
        bFpnbnAvTUNvOERiRlNBTGhob2RNOVE5Z0JzCjlQOGlmdUR5ZXdCQWxJOSs3Q2hE
        NHRwUEM3MmVKUnlYV1hNNFp2QWFTancKLS0tIDBIMTdjNy9ldlZ1azBINHduTitx
        ejgrdjFkc1BhREdBZUZlOXg1S1hxMk0KroXsgDGcjW+S/KSUkPjsKqa7DqN2m1yO
        2DkzfDOAvucl+v/I5IQtCaLI6CtR4EIh4CjVfzaFWSBy+0xToKLegw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUd25VRkNnS1d5SHdVTVhZ
        YWYySlJJd3JrOWlxRzRSS0ZpeHZiSkluQ0dZCmJiQlFnK0FBOTJBc2RnNjRwMGNV
        VnMwOTB0cGhvWnlyTmdqdGgyS0ZpMUUKLS0tIEtkaGFSYXkzZHJma1k3eEVqUnhO
        ZjlGcnFiY3dkZ2IweEFpUGgwQmlvcHMKz5wLyLKyvqmfTcaVcA8zG0HsrRsRx6q8
        fJrR/3RYhLJOWk+P5Nb0dIx2mFpoEm6lAqCCQToU9EjlEpRwRE52GQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdm45bEVDT21VdkhKczVk
        YU43eSt4Q2MrbUV2MnQrRlNOUW01SmlEelQ4CmhsUmlYWWt3WitDMGREdkpJMEZG
        cVJESGJlZXpibStxTXJyeTk3REJJVUkKLS0tIFVGeW1ZeXRGZ0RDLzhINExYbnZ1
        YVlyTEtPZDBlUmZQd250eExBTnIzM0kKebR3TCXoGi2d/cxG3tKGPzMisYe7es4e
        VbbkZu9DwLy3GQ4bvoUjsSkPqUmR4nkTxvm9hz0AaUWQIfysA1v3+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L29qT0hZWDlXbDdMRHBR
        UWVZd1Y5ZVRrdGgxbUNkNGZFVGRwTTZGMW4wCmV5MlNkMmV6RXNldVU2OFMrT3ZG
        Qy8vRHJqWm1mcXIrVGljVmNkbVBqRGcKLS0tIFhRQUlENlJTb2RpR2dKbUsvVUZJ
        UCtuclUyVUVERzFZN3c3VVVKbnRHRzgKExxeRcQBJUEv+3tw+So9t7Jd4QTt3rI/
        gUAmArOmwLX/Cxl37z5ALHXEDdYFnHPHE3SCB/JqfUzKucF+YmmByw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaXByRjN1bzlPak5wODlV
        ZXNsQUM1aTMwTzlaVXljSUVmMG1iL0FucG1rCnIyUVpCTUhPRGVUaXhaeHVjN2M3
        dW9IZkdqVFdWNE1OVEt2aWFBM3IxdzgKLS0tIERiWGI3djRvSmtJQ1MzNXZZNDdj
        VWtBWDJkZUI1Z3F2eDk5R3pUSlhHV0UKEOeVqs3gIVQstX8YPrJzf9/lanbi2Wpt
        gNXUGlL7WZrxJgtsvn9VBR327gDJClJvSra76QTUScn3V7aOSxOIow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:j0aKAnupDQzXJDKNHKDDZsnQwepJ5KEK7BsddxCgtY9K4CAghNZ09jKe3BtFNw0SAVPFp/29BnZ7T33ZppMhhst+jrnaPRittXLBfVLDX700iLJV6KR7XUQOrMpLVO2Ns/G4P35jq7aKviX97iu+iZVd5ypQHPKuzOwLJmY7iuc=,iv:crdViaQY8k2b0X6gE67rhJKwEuOq4Wq/U4fD4N4TEi4=,tag:82tjqZW6WbWxVvVht/ddVg==,type:str]
  version: 3.13.1
