apiVersion: v1
kind: Secret
metadata:
  name: cnpg-apps
  namespace: storage
type: kubernetes.io/basic-auth
data:
  password: ENC[AES256_GCM,data:0Q/vcF9dkDs=,iv:pIHdNSzoIkiTbA+pgnVw0rL+foIZ6ytHc15/LpdxZ3g=,tag:3Sv2AuLyBaiXOu80OVZvXg==,type:str]
  username: ENC[AES256_GCM,data:TXkZuwNSb7c=,iv:NXJ4ZtPosd4INV6yQUg6iZLNZ7A8Ta1bIyuNeVQulX8=,tag:OODX5DGID8ZO4d795PNYZA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcnJaang1eUxhUk01ZlU5
        Y1E1czBKTWY1eXNBVWtCS0hEVlJKNi9DV0Q0CnNNYmVBQkRrWHFKSWZKcE04bElZ
        QXAwZ2pyREJ6RFZJWW1ydDVHb2tudHcKLS0tIFN3MXJLWEFRTFpERlgybWVpRjE5
        bWU4S1dGb014b0tYYkgybm5tNkk3QW8K+57Jc3rxLDU5SzOJHz7AYynPdvDR2IGI
        Gegkl85DVrkjrgHQP4IfMeSLLckhcddMXy36Nh3aPYxCUfXd1VJqSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeExSUkkrKy9FcDlscWNq
        ZG5JZDFwUlNLV01TVWVqM0J3NnhzYzZJNlNrCnpzMjRpSTBSaWF1ZTRCcmtmZDRz
        ZnNvZTB5THdsV3BmeVpZdWhTUHFvQU0KLS0tIE1QNTVBOWRoKy9mNmZOc2w5Y1gx
        elpUMEtSMHV1NG94WWx1TG1YY2dMb2cKoDJFdYFmczAqd5EgZT/5ryL1r9A8glHK
        ptbYhKhueHbrX6SeKyLcwNJXbM9ohHLVo7T1oe3TLsJw5PdxH5gvmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQkoyUDZYdEZqbFNZZmF5
        YndQNHYySU9mOEtteVMrOHI4Q2NkSXlmQTFVClJtWXVISis4WnJxUFloM1FiMnEy
        QWs3eVRLcUxvajhpKzdLOVJ0b1kxRFUKLS0tIDZFTm5RKzBNN284MUJTb2F6QlA0
        NWlRclFacC9kWU02Y3AydkdPNDBhZ2cK7PsmIgtVdflym2vnBySLhMPRo//zDgLw
        R8qfFhwVfGvMzgFE17iVm/wnyWspMaODGuetI2JRie+8zs56ej3LaQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:UnLOMPtIVl0NUBghriiEYyb9lSSNSs6W9xhi7m26i+/Ev4SlZ7pQfsMxrin0Zmwd2Dsvy/sJ/WI+uvbecANo06in604QHUDJSSvHSAJSET0fcO6sEzcofBjJ+L2VvG9T8nNEEXU6a9hRik+uuPWi319GrRaqHQH7RIQp0lLyc0Q=,iv:GKjhMex6I+ceeGN/bW2epHoPN6DXMTEz5oBRlOuLUlI=,tag:9SNf2DqR0EJbi6NNmYRaDg==,type:str]
  version: 3.13.1
