apiVersion: v1
kind: Secret
metadata:
  name: cnpg-apps
  namespace: storage
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:yS0AfPY=,iv:4UCEP0tejEIRBOVfwDadHVLxn60ePRgo7H8dveYVUrw=,tag:gFzV0Lu0dtwOLS8wIYmBBA==,type:str]
  username: ENC[AES256_GCM,data:8iH3MA==,iv:TbZOwYkk0a5EizusSGa5/FmBHMvJ83tJ6YA5NA+fPRc=,tag:ueqz7V1CzdwoWB+lOWnmiA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbVNGVVV3ZG5FWnBWY2Yr
        VjVXZ2NEVnh5cjVxbWg3czZDNVA5NzR3OWlJClBwMURMZmZEdE05SnptRlBsZjJI
        L0U1Wk1EVUZERmU3OUVTc3JXdy83ajAKLS0tIDR3M3F0b1grVzFDc2huVFQvSjRF
        K0pNMmFrTWtNMk5sTWdSTVIvTytoNzgKak2d9qoS6gGahYDoNNJTzklBNBT6bK/j
        r32N56iI92k35b/dV5Nq4Cnu7oNSnQl92zqDrgk67hVoXlVyUDZlbg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U0JYamc1QndWNHVNL0Uy
        YTlIY1MzVkkrdE9VWktnR2RHTXNTczdIckRRCmdGM0g0UmNpMDBIVG8rbXNaK2dw
        VkF1cG00eGxLYXVjNkhtckFNbE5xR00KLS0tIFhWejlRQzg3YzI0cDdrVlRvVTZn
        OS9SZDFVRjVrcC91YzFhRTJRU1p5bU0KSGBmpSHLumXg691TryP2dOY7UqaScjCZ
        oF1EQc5S6ge8m7jlQQa32g5VqwHRgGFJpVnY+h+SZKNJ5JWjbUwLeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdTFaU1BQbndSTG04NmpO
        RjNnU2RvQ1FhNXAzdjVWT0Y4MjN5WjdmV1JZCkl4cFJkcWtUVUduSzl4RjRYVUla
        TStRWDdVaHk3R0FLV1Z0bERWUkhMYmcKLS0tIGFPZzNZZHVDaHc5ODMrSXVYUkk1
        MERpVk92ZFplN05yK0hkc1ZzMG1SODQKi0kvBalZiuzB0pxesbaz6wqIInmhmDjJ
        O4/EK2A/jWYljm7IyfHmmI3JJXve8XMVTylAl6KUdtfkRdhjHNh/ag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:ED5rmcyqBNIGD+KOE9K7sD3N5eOxJ+zTXrQ50FT7rWKbA4Rgn+QFrQrnsRHHvXiIjI5EJKGJ6s0IwQ+UCb4e7a8G/uhd6IiYGfBoTJ6Vx3E40oC/Q6lZIyg38xZn0I7jd8vHfVs4y4wVSPEdpIebBeYLQfYW6zh9kpQyFaNMxHc=,iv:USWDAOgHo0gV5mG8CZ4YbccB/6qUXEXwHD1GuKhpv7I=,tag:ZgFijpma3TyZSH3baqLoOg==,type:str]
  version: 3.13.1
