apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster.yaml
- cnpg-apps-secret.enc.yaml
- databases.yaml
- helmrelease.yaml
- mealie-postgres-storage-secret.enc.yaml
- planka-password-storage-secret.enc.yaml
- postgres-immich-storage-secret.enc.yaml
- postgres-penpot-storage-secret.enc.yaml
configMapGenerator:
- name: cnpg-values
  namespace: storage
  files:
  - values.yaml=cnpg-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
