apiVersion: v1
kind: Secret
metadata:
  name: mealie-postgres
  namespace: storage
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZxdaiNF9aKjyMu8dhmxJ/g==,iv:xSnIWRHoh7mUqYPT897REulSM5DsS8ILrQcbbdObyk8=,tag:JpaAf3ImCx1plwGUBNZl1g==,type:str]
  password: ENC[AES256_GCM,data:gvokRxpuzKIYnMh6BiSxJQ==,iv:HHfE9p1I1T8PcI5Z+RjxmnBgqlGM0V/n4rUmv966bSc=,tag:N3ck/+r0Uqu/JW4oJtWCgA==,type:str]
  username: ENC[AES256_GCM,data:+rcbX5eT,iv:la/FhICS+Yy4rOK/JFXLJZvFyb/pnOy/x/Jo/FjZcB0=,tag:JJJLXSgY4H+JxoI1P8Bj+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UVI4UzFSRUMxL1JkQUhQ
        NnZWR3E4dVUyWVBjdjdRMHpUN0IycWpVU2pnCkdRbTR6MzNJUytYRmdpaWJ5bTZm
        TURLdytkVU9EeXlVNWM2M1JoTWtRVDAKLS0tIGNsUjJZdXZONUFCT1MrQmJDMVJW
        YytYYndaUG54UEx3QUZDU0IzMks4K0kKRxQKd7CI7NPAWazPP0rPNDLjnPLQaDWP
        HYfQVZaTwLO9SLpI1FptX5TfxYh7Jb4FNPJCsRMRWEqS4Dr+1/sp7A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SHRBaEEzdk4wQ2JvTURw
        cmNEV2JkN24vQjFqK2xWVDNXYnI4UHd6c3dZCkdOaG42RXRWdmR5RUJIK0YraStT
        LzVaTUJ4aEJuelM1RFNCODhhQnFqaFUKLS0tIHFkRy9EZnNIdVBUMzAvcGhwK2VE
        bk1XVUdrK284MFlrUktzL0tiWW5SdFUKceBODdV0byDyDoslIdSRL2gCXPfKaigg
        Fsg4CUF4U56X5cAQvq1QE6h0P21fLEH0iu7E/Pcd/9lpJ+VbJDDkcg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnemUyTzYzQ0ViUitxa3NH
        T05lYWtId0txZG9qVmFvSFdvYUdNWEJTSkhzCmIzUXM5YTVqdUtZZU11Zy9GWHZ0
        ZDdpdG5iT2wraFR6MGcxNzc0NU5qdDgKLS0tIGRMVmxjS1h2UlFGb2ZuSDR0WExF
        c1RPNS9NeDc4MnZHeDhmekl6VXFsQjAK1IksyJq3o0PfIN3p9KwJyn+fnrHGlSJa
        uUrRr4nDnr4yrRFAq49QVgDZbUI0R1Zlt2HO7Ra5c1WBXPnN7UsWJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:KflQlC4bKv8c9XOtf6e2g+RijF1guJdXvhdzOFKFK40prdfRpIxaVsY0M3JINdsoiwdvS1BMbLpU3NHyDfGjYUYnAUZ8o/9xrBE5bB/AGtxr6WKRBjPLxHJM8bpbDmXNErhyME3HfO+4YbKcBrkia3Gy3OSGKTypwRrz2ALAJNM=,iv:ygHKtq3osk1VM7ylaCeRdKPacdsjV76dFgu1bhoNraw=,tag:2PaCuy4xfyt30rfaDlyffw==,type:str]
  version: 3.13.1
