apiVersion: v1
kind: Secret
metadata:
  name: mealie-postgres
  namespace: storage
type: Opaque
data:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:xJaVXFq5uVAQJIce0AGi2wAc2fTqDCYD,iv:a4QQrwQQpnwTovVyhaTHayOtAAmwF6toc5B+VwTqrPs=,tag:as2WtDziuoLa8EV1MotghQ==,type:str]
  password: ENC[AES256_GCM,data:SexAg8KRd+JOh3BVEt9Wtl2JnetuhvuC,iv:HgCmDVhlLnMwtT/EDieaoZJxiQMNpsL7uJSqoFNZm94=,tag:XBJDGGxJQ/sVDbcC/XJA3A==,type:str]
  username: ENC[AES256_GCM,data:VX4mbrZnFWI=,iv:nQMzNTRLsKLmTVgQ8H2UcSK6J34Tv249uH4sSGPxBUU=,tag:pSWMubZ1iiodFeYAuHaLsQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT1NOdzRhQXo1K1U3QzY1
        NVRTZzFQOGMrVUt2dHI0YUVIRllwNmFnQ3hzCnM5d1hiSmZBS0xMbWxuS3BaVkov
        UzZiNE03NHpHKzZucjN6UmwvMEJJeDAKLS0tIENMVUZwM2pBOExUemMyWVBaQlNH
        RTNnclRYRnhKRE9RSjZzcUxXUk9oK28KGxUwzgrmbAsjBfzhc7AFPZkkjznsBEmE
        nS74Rx6Efio3KH9gsGR/s7AB3nrqmHae9qvnIeENcVTJFfbt6C+q7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZTJWdzZDNS9JYkVxWCth
        RDN5eU5SenNGYkViQ0JqZ3B5amY4VDR3bXk4ClZUVnlXaUlsc09WSTVNYkhIK1VO
        OGdQb2QwSXZmSVVxZ1VNVnNpRDY1YmsKLS0tIGkxVHFBbVh6VUhYa2sraU9WY0d3
        UUNVQWRNam5VV1hNd1ZXYUtVK0NUMEUK3Xzi75o+jHC1USfTmUBFnkWIgl5ZYLOd
        aNRSVp7lTkJ+ppPdnm5W7LGwAByWIlEQ6a9MWhK9mvZpEVytRRNGYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMktOUmxtZkJDZzBuZUo0
        Z3RncDQ5YXFTTnU1enpHZlBCYWk4Yjl3NGxFCm5RQlZxbkMzeGFDbE1ZWWpTYXU0
        U2FxNHV3VWVVYW9YVDlhbUhHNkNUL00KLS0tIFR3YndjdEVsSERNbURST1RuNXZH
        WThIUU9TeWNiWFQvdHBBenAwTXJDK2sK9N1lADrtF51nktIjrk7yDOtspTCGS1pK
        sYztiKHvaEDShmEd8Opr8YJssTSfxItP5AgdFfEe+NfW68BsK+ahsQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:stmFqLW8qEik5gqy6Pg3T24Fxe+rOR/btvicym5e1dc1oS7fuzfVoE8B+9insOipy/aW+bJpfXQyB4l3qHZv/1g9hbOowxQ3Lspo6vZXKv2XOmgXWharY1mJfYzs0NaUaKyklAUWBZn897CaBWDyhDSI79WwqzcCnr7yHELIg8g=,iv:u8JUHNUpYYcw+XoCICYGqy0/0Da17NmopRo2Gq1Poz4=,tag:PNZKMLWHavn46NMwAAARfg==,type:str]
  version: 3.13.1
