apiVersion: v1
kind: Secret
metadata:
  name: planka-password
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  password: ENC[AES256_GCM,data:Hbb265N+63C5fzaepPk8YuNngcInwZ8UA5SouiA1420=,iv:pCZP17H21vvxH9Ah3EbSOthS5NsvWgCeI/ym3UlnW2o=,tag:uBsevDE2ZXfnyzLjzxLThw==,type:str]
  username: ENC[AES256_GCM,data:HnX2PpuZ8Qs=,iv:1a8uz7cDXAl0hpEvyxdTwa/wt012s/ymXhGTFWEAhBo=,tag:wA4+7mnldaqpIRzpHdaZEA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXazhMOHlOOGJNOEd4Mkoz
        cmg4dGxTcFhIODdxQk9XRVhPRmcxb2s3QXhzCkJnVWNaMGY4TXhSajFDVzJiVGIy
        blZ3eFNhY25CSDd6YU0xTHFBSVEwaWsKLS0tIGM3ckZrRUlqOW1NVHZlUUNGQ3JL
        Y0VQT28zUFBlZFI4d1VTU040dkpMTEUKoEusGAsLzwfkXFU6p0T1AOIgjdBjX2V1
        UNTgikW2ZAetI7DtWuFbiBJxBl11QLX1zsXX6/mI3O7dTaaMKyD90g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTlB0VmVCVHNvSUE5c0RH
        Q0RLU1NWU1NPc3BHcHE5QW9FUmZQbWJJR1ZRCnNZQUpKYWJDQW9mYWZhSmZyeUd3
        cWZEdEMra2J6bTQyTmZ5UUF3SUNSNG8KLS0tIG9KQzlYOW5vWjV6bWxZeHFFa2Ro
        enp5SlpGT05adjFTQ2YySklhTi91YncKO/zsVigCAdRkwUll1Ld5bk24R6/bNzLl
        G45t8HGTGYIx8g4am1rwwZexmshxMlvVdCLllvXG4FUUEnF3n/45BA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU1YySXZZUmNMVUFiSjNl
        V3JubTNLOU9heHkwRVpDT01mbDVJbE5JM1NVCnFWaGI2SWxleTlONG9CRis5WENR
        NDc5UHM0c2FKS3gyZFcwZ0tWODFnNGcKLS0tIFFMb2p1N2crV3BQZExYTlFaRE93
        dzI3UmJLZ3lVdWw4VUNrUGoyOHNWOTQK1VBoWlx+2OJOsHShlCGeWpqIqhjL2Lra
        gXP/BWUvILs1Z9hyz4LDBdpygDLM3bHVCE1XltGf89dcOpXp4JRItw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSlpYV3RYbC85MU54dVZw
        czNNV2ZsejUxbFdBTGlHZk8ybi8xNG90eWp3Ck14VFgwN2tlS2FtTDUyUGF0c3BO
        aEhJRC9RVzhtRnZQVEhZRjJ3N1RkUjAKLS0tIDU3dFJTdGtEd3lmN0VYWmtkRWIv
        SzM3MzRIcExtQlZXN2k2bUhXZHB1eFkKe7Jk+B50z5Z64Q5uMsrb9BLi9S0XCaAh
        npNI9mZra7B7zI0oBluldesGqsRoh6TYg+jvRdiSG66xjFCm6MQ3mQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaXFKYU14bkNPT1lDYVZF
        TGNwd0pFb3cyV2RBQjIzZzJuNFY4VEZndUhnCkRjVFExRDZnb3FoQ1pQM0ZpYWhT
        U0Rrak44azQ0UnA1bDl5dkRvcTVPaDAKLS0tIGk2MG1MTDlHSVREY2lzWTQzUC9u
        UlJHQitQaHhTZklNZmtrOHBIK3JyOTgKjMUK3WyVH8GRBM2M+JJFx3Qi4K+t1U0z
        LgCy9dG9iA+2WN4NpqBJeOI+srf9VESOH4lF++rjcwZDa+7W+57qqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRGY3dFJJa0ZqdUNrNUlQ
        WWluVFoxekovWUdzazBZYW9OREFKazRva2xRCmVTY1llSG4yKzRQQjM2cEh6OE9z
        aWJ6dVk0TU5mb2NhcjZkSG1ibE42czQKLS0tIEVjV0lYaW9uaGJ4bXc3UUhFV0tl
        SkVob2VkakN4RWZLR3BkZ2FZWVNURmcK0YmOnrM4Scgl/Aqn1XgCmctVWlX6V67N
        16akcf2cck1STBSM7MzCU2CZryqZmD2ffbo5q7ytYf/3VM7RGRDHFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbnFZZzVqT2Z1akRQelVY
        OTVGMENtUFROU1Y4dktQMFVoOUlOYkJ3Z2tRCmR6TTRYbkVFTkZud3kyTzB0TllF
        djZTL1Y0aHRTYmVPN3YwT3VOWU55YzQKLS0tIEkvenp0MldIZW4xaFJ2WHlzS09r
        T3VHMWJHRlhCM2pQNnpZaVJ5RW5CN0UKT1gSDu1Tt5MAQe1tqflZ23zyd93ezz2q
        kXzM+GJccVZQFDAKAnJDV5jMYBczqgsUYrOpbgj8tHJZmBvaUHul4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL3cyT3NKWnpjbHpqZ00y
        TkhhTXR4aEhiUjl1NmpGM2V3ejJrd3JOWlJjCkIxS0JwWVlNMkp2aVVMUC9BbGdY
        K0FKeWpVVkhBeU1zUzVROEdqTnl6MEUKLS0tIGIrMzUvN3lhOVlIVVdrblZoMjdL
        ZU1qQ2JGVktjQzRMTTZRQ1lXeEl5bVUKV9ZQ7Z8t7baj0Ep2cpkEmLgWaFOPQzhl
        /SZrAGKersvN0hjJOFqEuZ6DEpw/fRH+jDBGf2MAZhh6nTZyiIl0Sw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOFQwb2Y3dnhYMFhZeitU
        ZXcrSmpabTVCaXNzOWJha0FVUVVNaXZqRjFBCnYxWVkxQnB4RXJaMWVza25tV0Vl
        WTViUEF3QjRydVBRNzlyVC9ndHBRSU0KLS0tIEZMZUVOejJoeFI5N1duQXBhaE9N
        OTRFaHFEQzh6YnFkRGhFYkVwQ0lzeEEKgsSy8fn5dfAH672Ol14heW2jZ6ClUrw4
        gbjJAoY+qkjG1GgQKEkPiKvKBqf7LWinXcp4UwqKUlczi8xBxhteVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGNYR1JqTTd1YlVQMGsv
        c0NocTUrMitJMk9PVEJjbzNneUtJdGNyendJCjh2elVreU85RUdtRU9MY0RweE9E
        WlpQK29kRitiM3hCR2Fpd05aQmY0d2cKLS0tIHdWT2ZOMkdPWWlvUWpZVHMrWVBK
        Mk0zT1h1OW5EU21HTWthZ0s0b2d1QmMKprmqB2BNNT7gdB5Gf+8VjRPCkrQ3mw+1
        OCVKL2RIY+9x0+0OaNkju6NAZc2VRU/XMxfjBRbtT2a8KfoYSnmJHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:OtHUwLJrqkldOrqsbUMfrujgYVdFX7mtoyUc9mJvRUz+Pm/z4o0Eo0Jjqb7uH24e0YecJTpWlKrP8EiMTGnpZNsuDenZ7oOtKCFxI6CQBwEmr0dqohIVt43wDMCTsEefxulpoOrZzr4TPznmFWbdLQmBPE7QcMGiGdhO82OTn/U=,iv:bKO2pFOiXMnWkRXNCDU4Zp25xCY02l3rQsT2AFrEWxE=,tag:9yEl7w7H1p5IZbVPFqgkHQ==,type:str]
  version: 3.13.1
