apiVersion: v1
kind: Secret
metadata:
  name: planka-password
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  password: ENC[AES256_GCM,data:ZO5WwbOXpRZ1L9ICFX+vfnGx/Zne4tkN28VAPKiNHGI=,iv:toljXmvRKKan06Jt8cG8PWvXCTWNkjmUJj2nn3vJrsU=,tag:oYedlEN+xQt13C0p59ooBQ==,type:str]
  username: ENC[AES256_GCM,data:s22nsKl+FAQ=,iv:xiOHCXLVBCEvEOILKbldB/MjN0ww2IDPk66jw3dOFuE=,tag:5mIRyIAxR1neMIQ0npyHPQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaDZMb3ZiNkdqellJSWJH
        OUd1M2pRTUt3QXF5b1g5T2dUeFYrd3RZQkF3CnF0Y0c1WFRKOWhhZHY5ampjWS8x
        OGtWMG8zMmZSOWVqTHdhb0tHRTAxQXMKLS0tIGZ4TnE4MGczTzc1N1R2ckJoQUhJ
        bklDRzBiNXU2U0FrT21wb3p0YVlPbmMKyHQRyuI59jDoj2LCdKGp+nqjPnSsrsQN
        x+RG7v24K978g4Tcffo9vbzDgn1681Sjz4T9kg+6VWPh4iSl4jtyBw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNUxMZGxTZXNpQVY5TVpK
        NHhPT3FpODVRNnY1eXh2czBTTkh4dzJBK0VjCjE4TkdYRDQ2dE9yOEsvYVpWejdT
        ZVl3eHB5RER2Ty9NMXVneFNNZk5sRm8KLS0tIG9QYWs5Y24rclp2VWEySUJpRFBj
        cmYzZWQ1L2hTNDF0ZEQ3YzdKcTlGUXMKGNcKaAyj4TNyQ2tYplvnkMTdO59wcHsV
        ToyHXDqPCGhoF9CESnu1Xd2VAeyD6UlOwOpIqYqcMge6lz/5rMBhKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRStHaGJHeG1KRXJndmN1
        YS9VSnM4K2UyUERXeTVwVTBYcEVEWG5kZkdjCmlnQjlQem43V1hxbklMYXhpOTRs
        NlVtWjBKQi9ZRTRQUjUveFlYMldjdDgKLS0tIDRVT1VsVEx4djBFQkNudDA5WFIy
        dDRyaXpHeGVaNlVXN1VvcE9lQkluWWcKW3X74w9jh28ngrmAkHUnuUekEkEFdxpF
        xYVBrQliMqo8KoQSXx7emlM4ei44aTf+hXBhxINR/xjNXg3Jj7WUkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:2T4QWK4uoJYF6cJBlf8k/M2WWlSFaQLzztnF3xW69Gmywp9XHTkJnljfspz1o93J+Enuf/O5vtQI0y8k8/nUmimVUqg/fI3gP/Rvm9Eg9qyf0a1C9k5+jI7i/HV3jyDDYYGKutTmJOYMdByLYLoeutV934CBl3HNCzQx4MhYewQ=,iv:lJnyYTQ7DRkmqL8dCpZRAzcppt3pMdiwKFKbyN/frFA=,tag:ocV6LAW4amO0tARgO+MLbw==,type:str]
  version: 3.13.1
