apiVersion: v1
kind: Secret
metadata:
  name: planka-password
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:NKW1e5vQUTq8mrcU6WCmC0ISctjOvL3V,iv:o5V/QAVS+iroUYCYcEkChIwZ3rsq5dFT8rAwBcjtxhE=,tag:sVGhlmQUHbFcjFOgNY16NA==,type:str]
  username: ENC[AES256_GCM,data:UJJxIFUH,iv:kAxCP4OqrsacxBbHjXzZaqhTh0dMA3gTvr2fAHMNNoo=,tag:u/qjNYQO5OCTv2p0iEKYvw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWWpydFkzU0wxQzNlTFRG
        aEU2UVp3RW5pWkhsWjNsdEtrd2VlT0NwSm40CllyYWpYYlFCWWRCWWN3eks3Sml4
        eUl1OTFuS0VWWjEyZ0ZMdzJpRU5mbmsKLS0tIEJFeFdoTnd0OHpHaWxZdTBVS2tK
        am9wMnZQejdiL1dMcWRPNlVaS0NuRjAKg+TlnOE/5jV7tyPld8FI8AxEv9iVl+/h
        ylrIFTGrl8qQlVrfV0zVAkXosTcaYKgigEmRGYIkyMa4HdTkMFdbaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZnZzYUN5ZVlVOHJTWnhU
        YUhHUEpJT014QXZVZEg4OXdCZ1R4UmxQTzBrCmRGZk55Y3hhejlYYjlmZjFERlBR
        c1VTQ2hkQmlSd1V2Zi9jRlJQd2FwaTQKLS0tIGwzUjQ5Q09iQmkyaGZoUitjVFlh
        SlFOY3JRUHp0Mkl5RVJWMVBqbENScHcKHHSW5vOdYOAKkEUoypCuA1TFeJJxSTwr
        JrsQF4u4V4CdvfneG4IMuZ1xUeyjwHp3JT4HG+bzRmPjF+Do+zaWIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQnNxMUlZQ2kvYkVxQzNL
        ZERUdEp5aURDRFN6VE9zQlo3M21scnp5UUdVCnBDSEdMMUFUWFN3SHBPaUQ3b2l3
        YjFOampBVitUL1cvQ2N4MDNVTEJVUzAKLS0tIGdMdFZ5d00rcUlobVVJWkdyY0p5
        cnlKR2t3Z1dtOWhIWFBEK0NxY05selkKrOgZb/mbEuombeCfV0yXSa/6WzpmGmRu
        LsKP9U5+v0JWyh7UlipB7rfusdgDO6L0U03w+KyXRUJz/tdLS0dl7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:jsUAjr5lMQ0Ew20rRgDu5a4NRvzUoea9kTJGG6Hbf8Xq7Xa9dLwg5fbZGe/JfkmVMtyE6YCezu3TIILM9W9hJXBF4unvvLuSpFzPegFHg+PkcJ2Hlc1vykWa7Drbrix9SBrXvtUbe48mQVCXAKZ1PO/wz4dXVjufUaZ55LILRK0=,iv:315fNY4esqmBJ4I8a1yCzFsIqUPjyKysjvYpHskXDDk=,tag:Y0gQcDI1tJWycFyOqjfVBA==,type:str]
  version: 3.13.1
