apiVersion: v1
kind: Secret
metadata:
  name: postgres-immich
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: Opaque
data:
  password: ENC[AES256_GCM,data:O+vOQhbtgz/c4+L/VLOuFjrHDI/kIOAI,iv:smG9GJK2qsL1fCYIJKa1nsEauBjPPywyxPF9ZC5h/9M=,tag:Gc+n0Qrq3xnkz9mb8MWqWA==,type:str]
  username: ENC[AES256_GCM,data:c+1ncTWB3UA=,iv:Rp6kYR4qKQ2clA7XclPvwOc+8sNK3e74fBac0QtmVPY=,tag:gydJcRflDP/z+48GpG2CKQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZGNocC9pMno3b2hLNHhV
        a3BJMzcvYUhnRmlKdWdSRlFmS0RVRnNCb1NJCm9yTWVuREhVcUlvMXlld2VWMnYx
        clpSK2I0bEhjcHhEQnowU2ZVZkdJZW8KLS0tIHljeDFqbWQrUzEwamQ1QVIyTU9r
        bWt0bFhnbDNHWW5oQm11bjh3Tk5iYlkKa4EFCxO1cKmC3nIp/s208JuL8wcFCa98
        Av2p3jxMye4Zmmlyfv0dm5vqUdUSqDL/szjmp3j8X6tQRfpmPw8Vjw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYktkS0xJbURmaU1kMlli
        TUErcUlrNExMbU1LMXF0b25PREwxai9YbldZCnlMeGhjVm5nVnJWYTdFS3VFbVor
        N05kRWk3VHhtUHViOCtXSWFnRW5XWlUKLS0tIE54UUN4YnVlY3lzY01ERldzam0w
        YklyOHJlbkFXb3cyNlVjL0pNN1M1QTgK31TzLV8twnbVKH5tkfUOtBuR1lOl89Q1
        58CVxHhTMhdd/AvFjpqrXJXZ7Zq7FATBAZA5oyo9TgcjtANXJzfM6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcndMOEc5dWIwdWJubnVP
        eTU1T291MHEzZmlJS1dHeXZUNkVaZFYyTTNFCjhzNEZGZEZPMHBiWFlTWS92VExB
        TjZQNUhXVkNlSEZGZ3NQWnd4d1lEd0kKLS0tIDJYYmViS0VZWG1KMzd4NU1yVzhx
        ZG0vdDVKNmQ0bW0vUDlIaVFjSkdjN1EKhDpO23ZGYtDGwN/wg70w/4ofvLqtjd5O
        PQbhQPqUKRHgxAMmBPHNX5NHNQl0WqHbpE+93BHcXp/eNk1E/MTy+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:29mKsfYgjUs14AX8y0ZKqTy8pvm4HqHOwrcCaMhqHhmGgplYpucY3LgbpKa7TTYxox3UCjsxyqF8X4Jm1R4RY8RcYfX6ARc8aMz23OUmRKpET8GAWT/S/sc2F999+CNC9qLoWeUZjexmU8BQc7WOc1ll4WQMF/OnMBIqFD/ORfw=,iv:2Qh0pAxcZs4Z9OPaQguXn1FVA43Pw33IX/Z4puADfzw=,tag:70RZtQOizcWBxyG6zJZjKw==,type:str]
  version: 3.13.1
