apiVersion: v1
kind: Secret
metadata:
  name: postgres-immich
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:dULdvvWDVQijED0zfqO0ng==,iv:oyGxqFboE6PMOBcvu1ZHjLt3RkNMxrNoegJYNS4fu9c=,tag:xWeoI59kS+zB0xVYOJy5LQ==,type:str]
  username: ENC[AES256_GCM,data:dtUaOFUA,iv:E8YcDpy2gEkxYdBeJ14SaqXsD1ApiFT2SoSZ+HR7Bg8=,tag:zMnzVQV2tByhIOuLN0gHfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TXVsdEVFUU5Bb1kvc1JJ
        Wnk2NHdXbEg4SWR2WGpjNm1SaGpLL1RXb3hBCkJZaHoybndSNFhSM1FwNHFVT2Zm
        bHpSR1N3OWdvckVKQ2VYMkZxc20vVXcKLS0tIGlPdXhRYVlzZ1FRb2hKOTBVK1Qx
        YlBEUS85ck92U0RZSmZzRHhzQVg3ZFUKTcHl5q1E/6bcq1txkY4VdXNMpu4peGus
        +PTGn0gz2hbc9lBDjHaNSCzntaaQLIRoHrqw6loV2DJu1RdRSC0P5Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUFNYRmwxWHhFY0pHTHpL
        aFJpQjJnQ1V1Qk5CR0ZrbEF3N0poN2cyckFnClhhLyt3SEp5Q2w1aS9NUjN1a3FG
        MjhVN1Urbi9GQnY0djlvZlNQZG9EU3MKLS0tIEp6WVk5U0FINFFUYU9HYWtvUlVP
        NFpXQ3g3M21XaEtSWGFmYkVaUVQ5SDQKz5p0mGxEakssRZcSqoJ5Ctdbb87Ee06f
        Y8DlJ0W75feUthuDPI+I7BlTJcumaKgzZUKkUNlCelKLCgZ4/byffw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibW85T0lpRDhaTkhVN1Ny
        dDhFbDJvOG5QdlZmZzhJOUxDTW84WG9yeVNzCm45cHRNVXR5QnZUODBTaytXanNo
        QlY5eWlwc2h2SlVwMVZvTnRYVWduOW8KLS0tIGpoV0hSMGJ1MVZHaEhPNDRqL1li
        Y01IMXlCNU0zZjZxZEhpMmJTM2ErbU0KcI1TNJefv6fOxN922tTECe6JxUIV8rS+
        +V3jVRtjiwemj5ucWt2qDL0uSNWzALVkUb1Hh5w3RND6Uc6ckJ+fWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:ELp4zKSPIepePIhrxVOxVR6dfBm4h5FLsmS+UHgBzKNnYcrEDPP8qpPUJloIPaujNRDnUewxwJrPsys9ANPtxQCPC0YDnwhYASovkjPD4K+d3hSr1x4UDuGEFW9VHu+kdoHxKzRQLdC7TQIgtY/8hDg+BwxvjKQak2izBDl+nQ0=,iv:gEe8OOIWZAPbEwnGTnnEsCHb0hxh/UP84b6UPks7pY8=,tag:/ytLEJoHARCDxIhCrp62qA==,type:str]
  version: 3.13.1
