apiVersion: v1
kind: Secret
metadata:
  name: postgres-penpot
  namespace: storage
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:ciinAffExvHejjlWPkExdA==,iv:zaLBilurtjQ+LyUu3hzx8xYHmgwEOxfcIuowhumNYHY=,tag:A9d8mHmUzkYhr9pcaOX+Ng==,type:str]
  username: ENC[AES256_GCM,data:9EEJQuwm,iv:ZRIZGULXy1FQmcwvQEoRCbEu7wcCBAXmRdQvBDmz/Ag=,tag:rFZjRlpZHAxArOH3lD/pqA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeDY4d2tlamZKbUNtdUpN
        aWhySUlZdFFJVTF4NVpUaFdoMStwTEFKRDJ3ClFHcFNaOGl5MUZUT3lmWllHYm1u
        eWhMTXdzcVJyYWVqVXZVQXRDWjBNbkkKLS0tIHpvM0Y3RGVybEJSdXBTa1Jwand5
        R045elhlemVhMmNiR0ZXQXZJN0RLODQKbb4yCsfp59CZpkqq9ViwOu+FnbMAjLjX
        BM++uCqKxhs9Dj+D+nWw7wTL5NbI10fIgU2drkMbsYeoGAkSo/fiRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbnpUc0Z3SXl6ZkRQSGlv
        cnpKaDVLc0NSTU1JYThhN1p5dEMwcWprYjFZCnhxaUtmQnFpYXpjdVNvR2QrVGFO
        NkwyVm9keXlHeWRMYnNkQ2JtNG5YTFUKLS0tIGwyeUpML0NKYzdnai9KelVqSk5I
        QlBkNUtZb1UyanA5Yk1OSFZEcmdiaFkKKtlxWiE3d3ydOK87lRjHib2EP+puiHDq
        rrfG58dlvcCOaPG2eMBlcEMplXSNqF8o8Gty9hQiXQeQBNPL0xd8kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWDJBQXVPcGJhZGpVc1VY
        KzkxK2dIdGZvTzBmRDIyZ3J1S2FXOE44akdJCk9QaEwvczZPRjhEd2dsb242bCsz
        emp6L01oZzB6L3hFZ0RiVjdLcjNnNzgKLS0tIHVqQkRLc2hMRjYzOENvZDRCOE5v
        ZWJ1L2JrcXpqczB1dHNXcHRBVFpnK1EKvGE3mb+El/EoygGU8q60jtVI5punzCf6
        cEbzrYydb/b/CQ00ngeAi294GSoCHyT8QHXbnlxZxlyUA+l/iSXDcw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:AM0nACGe8I4VNvkBPl7xa6tQTOzZN+79xFqgzwsKYxapSn3ZkniL+kvBGu0E9Mvn0FRtuo5JXpKeUycf7udzLTGEXxFpiunHyb0r5Q7p7t+5XcyHb8QFWfqUxW1SJTEusSxoMghf8nzOtm2pKiki/XSUkwadTvOyh8ZIVL3Zmfs=,iv:RtOcHFlQ5qSZ8xqtSVTxDw+P5uZUb5lovPn5XY3ucU8=,tag:EBnnJPEHjepg+irVVfOPcQ==,type:str]
  version: 3.13.1
