apiVersion: v1
kind: Secret
metadata:
  name: postgres-penpot
  namespace: storage
type: Opaque
data:
  password: ENC[AES256_GCM,data:tQKHlKusc7BTC4P+wfM/fhW6uRSbIFbO,iv:ASakOp2yIPA2xD6hWXKZGwR8dAJBcs518UykJwT9ixc=,tag:REfchjnGFeJIJ5b6JH1MEQ==,type:str]
  username: ENC[AES256_GCM,data:lAiE3WsyDkI=,iv:IgB2foJh3yXa3MTlbT5jcHCUubedWOJSprdm96Wsnhk=,tag:WxHwLv6TfGx+vAF3aAlnSg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZGhPdDcwd0Y1NSt2S244
        M2NJd3J2eGplcllZL1NUUXRHVU4xRE8rRVRzCmxhU2ZheWNKM2RZL0R5T3kzakhX
        TDFpSzJpbDc1bklPT004Z0RJWEdQcXMKLS0tIDNFTUhoTW9Uc1BRNzFqc2ZFRXdV
        OXUyMVZIMDBETVpXN0UreGtmSlRvN2sKLEQGhzriZUs2MybiWInaXq/Z+UT0HPPK
        DXDl3RsX66w7SGMQorFl24lZ2JEL5HA08o9cA9PlpidT+UoNZm4A4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cGV0RGFaL3p6SXh4RWN3
        ejF0SmhVd3FGUFFKRUlZbmZpRlZHNUIxamlRClZnR24zT242anZ0d0hEc20xaStt
        NUlydGdkQXovZy9QazlWaERVSEdxdTgKLS0tIE1GalNGLzFUSlBDWlMrbS9qWm56
        VWo4V2JiVVRGTzBocWJLSHU4Z29oNEkKhQN1RStWTfWYd5xtHGay8GOldfdBWQGp
        apXXKAixLIv9nqks2tVeXMIjZ6zseoyHhhv90DAK+8xd9L5iUeF2mQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdDdTcWNpNE40K0ZhUzdN
        aTRQMlk1SUk3cStyUk1aTEYwdC9ZaHdqUzNrCnZqalFLemEvZm5KS0JpbktJNjZB
        cnZRMGNmckEwcGRiMWoxUmp4aityN1kKLS0tIHBXWkkzWDUraXBNUFNJK3dDaXR6
        RlVVZ3pPQVFjbGFiSjNEUDhBSjBlMVUK+CnbJ+wgVTredEX2RPvU10UvR00xTwQX
        Jx9l+MHArFLdxSEUltM7DHbCjWnbsIgy5+JLQ8HR+R0Qp8sbMLZelg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:P98OI8sXJUu591D5qa2gwjDyT8fBBr81xIqE4eXkNpjX+o0TcCO6azwqR72UnerXXBvGT3hrBwHVip6Q5cM5XHvHsbHvxTRaIvQCV5xjue3gQ4vQ+hc1VUeqNuxkzHH2eOgel2DtkDlPHn2xOZDPcpzJJg4LZfWQo3dEI/iJ3ic=,iv:9WGJgLp/zLufFF13OimdfDq7PANqfYL0Xfo6viU+WJI=,tag:gl3Uz8iFdYV0PZEjCQw7Mg==,type:str]
  version: 3.13.1
