apiVersion: v1
kind: Secret
metadata:
  name: postgres-immich
  namespace: storage
  labels:
    cnpg.io/reload: "true"
type: Opaque
data:
  password: ENC[AES256_GCM,data:dFM/Hf5265sRlDV27yxA0otgiFawpfLc,iv:ZpNXlqYJv7Yr5EiCr/Zu++ytxpTbvQfLTVUBoOFKSwk=,tag:JKN2w1j3lEFeRHjB688utA==,type:str]
  username: ENC[AES256_GCM,data:hNlDxBC4B+w=,iv:eAxbhx/P8oF3bt44mToFm09xiT2agfn82As8YExTbmY=,tag:L8OYWrFsJOw1mQkJ8UBAzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQk5ZdkpsYzF0NzdpZmNS
        Y201R3k0M2JmdUV4eG5aQ2VTQlN0c1dMTDJZCmRvc0VrNDRkcHk2NUJYK0lwZDJD
        cUkwWEk0c04zbWwxd3JsVGVoMnQ2UzQKLS0tIHNpZCs0Nk5qMGZsR3NCMWJ2S1Uv
        cHJ0QzdUUks3VzhzdDkxOTBhUGJETnMKndge8fPo3sbcjjGdE42Vj/Y5+MoJvMRV
        f+Sp1+To/xIecL4J9K8WodALmBUnMKbfK9yyyOfXqYjxHrsls9Jq5A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRGFnOE55MENzMzNBYzBi
        QWNIbWlTbXQ2Z2JzdTQ2aCsvN1JLNmhWN0VFCmNBaloxOWtiWndENTQwVWpDT2lK
        ZGo0V2hpWVo1RzV0eXBIYU9UVGRkQTQKLS0tIDJiTU91dkNEVVFVdHJZZ3ZYWGRm
        TzRyQ3NjbnJJSDJXYWNqTzdqZnBjUEUKblncCuUZ0uFKtdhHtICT3O+yHXefuIRw
        119dzRDwsIT4LtelylpYkiUk1Ma4fA4q198M1z2KzfbeoiS+F9eAjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa0hnem8yczJGNkxNUGFM
        S2JsdnphelNZOU5NU1JqTi8waEJ2N0VZM0JVCjB2cVZBY3cvaG0wMFJIbEI2eFBj
        a0w4ZjdTYTJ1a1NOUVZqWEsxbnVkZzQKLS0tIGozN21sUkw5SnJROFZRdmZyTlQw
        SUNZamdBTjlaQjVtWGh1eHdZL3NtTXcK5ldcoxvBVNJ2wog4BD7gluNb4SVbI5hP
        W4Lx5oGpH9eLmEj5uL7J/ZWEH2Zx5vB0qlhVR1HYKPLoAFKfmgVXvw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYng5aFFzM0JtWGVaajVj
        SFIrZkVja0VQUnpBUFRWdnpsM1UxNnYxNzJVCjJqbmxWVTBnS0wybkpET1RuRlVx
        TndTMEpJdnAydVVBaHpaQjJXaTFZT0UKLS0tIHBsalZ2UUg5Q2JzcGxJd0ZaeGNy
        ZitQMzdvd2dta0NnQkxrSjROUVNrSDAKH8UbjKRkFCeMKdkWLTWN+eKW4la7630W
        +CemJOIL1oEgyR6LUHq9LHqJ9qr9SH7dynxWzxfzDXb7XKDDLiB12Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK0VTOStaT2RBK29mMUhw
        K3BXRlhIMWdwd05HcFJkTzFUaGVPSXRYNzJnCkREUXJLR3h3VmRHL2ZVYTZoWnVG
        OWR0NmRHMHRYSE5GMjVQTW00NldtTDgKLS0tIDFCYXdPWHFrVzJ2eGVGOWMvdnA4
        NnJzcW51dVZJaW82UlBHVGtvajlqSDQKLgCgCoFQAE0+5TMuyWEeJTOjgJsySxyT
        Bh8rUusSrR/qvAIcaewXXEPIi9Ndglsu7qaQ04fu0dbBYkXCXE0HTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZFhQSWRyMkNGaytyalRu
        UEMzYWl3UTI0akRlVTZuWGx2M0pWNVJ6UVRnCldGUTV1RlBFd2hBSFF0clJNL3VM
        MXJMMkVBNllrOVVwYkJzYUVCQllrWWsKLS0tIFJoVUl5SXFaK0t6YWY0REZMaWFC
        UVptZHpyb09zdURRWTh1RHpvdk54V1kKm2HjI4JrIl3LLmlc2y/3tK9tpLu2/Ycj
        CeKgP8UjNtYjMLUg4GhI/rCEy6NpDs50AKLS/7a0XLOaffBKE3mWeg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZC9WWlJBY09vc095VnJB
        bmhvQnhJWnZzTk1wN2I2eVp3NnBQb0VHaWtRClpLL1U4VVErL3VBdm1hdVBTRmlB
        TTlzcWR3amQrZFVGWTJpTDhjVVZyNTgKLS0tIHFNTFVIbWFTU3I2Wkk1a2ZZN014
        Mk9YWm5RdU9SQTVpYVJWemVuVDVRY2sK1Nv4TxO6KqWiEfRkLwmAh+yU0//EPCv1
        0Fw7seA+tPl0Ic+T4V5Dr8gvNUaChJ8+23pu4MU6+lZsrTrhiVr6eA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS01oU1MrMDFmaWRETDZN
        c2h5NXlvY2luclpVWkhSeWxGbkxXeEZoa200Cmg5QTRFaFo5bWo1UUtTTGRCMEVw
        S25FTnNzVFBHVWpjaThUbDRYekEyTkUKLS0tIFQ1VUR4dEFVeDNGenpEMythVzR6
        dDdCZkVJRmIweUUzYmYvYjJScHJVckUKEniu6GAUwKWnFOSXIMq1Kgu0Y48KdQ53
        mArgiRjGnmz2WGL7+XA11GoJ8UqAYjCSD1XwsY8kxbIFfeoJt1+UYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc1dPbWUzTjZsWEhOQ2NI
        TnJxWEd6Qm43ZytvRDA1LzFvc3Y0S3VUWUJFCjV4RjlIQm44QjhzR3NzSitNbThG
        dmZkVGFZQlBhZzR0a3IvdkFwSmJCVzAKLS0tIFN2U2dDZUJmaFRlV0RSc1FmOXFZ
        RC9FQTRwd1Z4eFZBWGJQbnAxV25BMlkKL/JG6Y5tGlHTR9krsAO6v7ykIiiuJDvn
        MT9mVypeyLKZzzBS9GogRUFF9vdkVvuPKw1EZXhTkMgXklDtG4rBvw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsT2U2azJ5Z0RwM2c1encw
        NC9hcCtjVDdibTVuQkRwWVRtRjh0aDFXMFVZCkRGbmk5V3RjVGtrZ3lMYi8yaWpL
        RVBGVlp4bzB4R0FFV0dMNzA5Ni8yWkEKLS0tIFYrTXE0U1VjWHZjQjFqdklrT1Vm
        MjlJZEV0ajczTGZLQ2lOc2ExeW1ZOWsKhV94RVwURx4CV4Ex9EcpGYMiQdMm5qIu
        EAude8V544rmixkEIS1laOL420rjpb67hf2IOpADw69CuPR0Msyrow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:8YrPZccEYdCm7Fa+074/RL0r1eGKh7vflXjE7j2buyjtOfyLzEplXfRI3i1VSMWZhwjgX2DbwKg1GcVP+smbE/Q6dEbXk3UDVVcuf3X1GajLbL6LbFeTvEL7B/aP2NpjXNkrqSfBYdxaSCwBVNI7Mzf3YgIzvXuYJ0ln5sM+2ug=,iv:6fubtcQz2STs88xtTIHbRJ1mXjMFsOQuuwwZD6WwULE=,tag:Zyilq7ZsPWbSUrnuggBWfA==,type:str]
  version: 3.13.1
