---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: media
spec:
  parentRefs:
    - name: cilium-gateway-local
      namespace: network
      sectionName: https-jellyfin
  hostnames:
    - jellyfin.stevevaradi.me
  rules:
    - backendRefs:
        - name: jellyfin
          port: 8096
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyseer
  namespace: media
spec:
  parentRefs:
    - name: cilium-gateway-local
      namespace: network
      sectionName: https-jellyseer
  hostnames:
    - jellyseer.stevevaradi.me
  rules:
    - backendRefs:
        - name: jellyseer-seerr-chart
          port: 5055
