image:
  repository: docker.io/jellyfin/jellyfin
  tag: "10.10.7"
ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
  - host: jellyfin.stevevaradi.me
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: jellyfin-tls
    hosts:
    - jellyfin.stevevaradi.me
volumes:
- name: nfs-media
  nfs:
    server: 192.168.0.151
    path: /export/media
volumeMounts:
- name: nfs-media
  mountPath: /nfs_media
persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 25Gi
    storageClass: iscsi-csi
  media:
    enabled: false
securityContext:
  privileged: true
