env:
  DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
  DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
  DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
  IMMICH_MACHINE_LEARNING_URL: "http://192.168.0.109:3003"

immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: "immich-pvc"
  configuration: {}
    # trash:
    #   enabled: true
    #   days: 30
    # storageTemplate:
    #   enabled: true
    #   template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

server:
  image:
    repository: harbor.stevevaradi.me/ghcr/immich-app/immich-server
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/whitelist-source-range: >-
          192.168.0.1/24,
          10.192.1.1/24
      hosts:
        - host: immich.stevevaradi.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: immich-tls
          hosts:
            - immich.stevevaradi.me

machine-learning:
  enabled: true
  image:
    repository: harbor.stevevaradi.me/ghcr/immich-app/immich-machine-learning
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: pvc
      accessMode: ReadWriteMany
      storageClass: nfs-csi
