serviceAccount:
  enabled: true
  name: "penpot"

config:
  publicUri: "http://penpot.stevevaradi.me"
  flags: "enable-login-with-password disable-registration disable-email-verification enable-smtp"
  existingSecret: "penpot-api-key"
  secretKeys:
    apiSecretKey: "key"
  telemetryEnabled: false

  postgresql:
    host: "postgres-postgresql"
    port: 5432
    username: "penpot"
    database: "penpot"

  redis:
    existingSecret: "penpot-redis-uri"
    secretKeys:
      redisUriKey: "uri"

  assets:
    storageBackend: "assets-fs"
    filesystem:
      directory: "/opt/data/assets"

  autoFileSnapshot:
    every: 5
    timeout: "3h"

backend.image.repository: harbor.stevevaradi.me/hub/penpotapp/backend
frontend.image.repository: harbor.stevevaradi.me/hub/penpotapp/frontend
exporter.image.repository: harbor.stevevaradi.me/hub/penpotapp/exporter

persistence:
  assets:
    enabled: true
    storageClass: "nfs-csi-retain"
    size: 20Gi
    accessModes:
      - ReadWriteOnce
  exporter:
    enabled: true
    storageClass: "nfs-csi-retain"
    size: 10Gi
    accessModes:
      - ReadWriteOnce

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: >-
      192.168.0.1/24,
      10.192.1.1/24
  path: "/"
  hosts:
    - "penpot.stevevaradi.me"
  tls:
    - secretName: penpot.stevevaradi.me-tls
      hosts:
        - penpot.stevevaradi.me
