global:
  defaultStorageClass: "nfs-csi-retain"
  storageClass: "nfs-csi-retain"
  security:
    allowInsecureImages: true

diagnosticMode:
  enabled: false

image:
  registry: harbor.stevevaradi.me/stevevaradi
  repository: manyvector-pg
  tag: 16
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets:
    - registry-pass
  debug: false

auth:
  enablePostgresUser: true
  database: ""
  replicationUsername: repl_user
  username: "apps"
  existingSecret: "postgres-auth"
  secretKeys:
    adminPasswordKey: "adminpass"
    userPasswordKey: "userpass"
    replicationPasswordKey: "replicationpass"
  usePasswordFiles: true

architecture: standalone

containerPorts:
  postgresql: 5432

postgresqlSharedPreloadLibraries: "pgaudit,vectors.so,vchord.so"

primary:
  resourcesPreset: "small"

  podAnnotations:
    nginx.ingress.kubernetes.io/backend-protocol: "TCP"

  service:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "TCP"

  persistence:
    enabled: true
    volumeName: "data"
    existingClaim: ""
    storageClass: "nfs-csi-retain"
    accessModes:
      - ReadWriteOnce
    size: 8Gi

volumePermissions:
  enabled: true

serviceAccount:
  create: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
