global:
  security:
    allowInsecureImages: false

diagnosticMode:
  enabled: false

architecture: standalone
auth:
  enabled: true
  sentinel: true
  existingSecret: "redis-auth"
  existingSecretPasswordKey: "password"

master:
  resourcesPreset: "small"

  resources: {}
  persistence:
    enabled: true
    storageClass: "nfs-csi"
    accessModes:
      - ReadWriteOnce
    size: 8Gi

metrics:
  enabled: true
  prometheusRule:
    enabled: true

volumePermissions:
  enabled: true
