global:
  imageRegistry: harbor.stevevaradi.me/hub
  security:
    allowInsecureImages: true

diagnosticMode:
  enabled: false

image.repository: bitnamilegacy/redis

architecture: standalone
auth:
  enabled: true
  sentinel: true
  existingSecret: "redis-auth"
  existingSecretPasswordKey: "password"

master:
  resourcesPreset: "small"

  resources: {}
  persistence:
    enabled: true
    storageClass: "nfs-csi"
    accessModes:
      - ReadWriteOnce
    size: 8Gi

metrics:
  enabled: true
  image.repository: bitnamilegacy/redis-exporter
  prometheusRule:
    enabled: true

volumePermissions:
  enabled: true
  image.repository: bitnamilegacy/os-shell

kubectl.image.repository: bitnamilegacy/kubectl
