image:
  registry: harbor.stevevaradi.me/ghcr
  useFull: false

imagePullSecrets:
  - name: registry-pass

cronjob:
  schedule: "0 */3 * * *"
  timeZone: Europe/Amsterdam
  suspend: false
  concurrencyPolicy: Forbid
  parallelism: 1
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2
  jobRestartPolicy: Never

existingSecret: "renovate-env"

envFrom: []
env:
  LOG_LEVEL: debug

renovate:
  persistence:
    cache:
      enabled: false

  configIsSecret: false
  configIsJson5: true

  config: |
    {
      "platform": "github",

      // "autodiscover": true,
      // "autodiscoverFilter": ["varadiistvan/*"],

      "autodiscover": false,
      "repositories": [
        "varadiistvan/home-cluster",
        "varadiistvan/paytowin-kb",
        "varadiistvan/voorraadhokmap",
        "varadiistvan/rofi-alarm"
      ],

      "onboarding": true,

      "prConcurrentLimit": 20,

      "binarySource": "install",

      "enabledManagers": ["dockerfile", "docker-compose", "kubernetes", "helmv3", "terraform", "gomod", "cargo", "github-actions", "npm", "gradle", "gradle-wrapper"],

      "npm": {
        "postUpdateOptions": ["npmDedupe"],
        "ignoreScripts": true
      },

      "gradleWrapper": {
        "enabled": true
      },
      
      "packageRules": [
        {
          "matchDatasources": ["docker"],
          "matchPackagePatterns": ["^harbor\\.stevevaradi\\.me/ghcr/"],
          "registryUrls": ["https://ghcr.io"]
          // (optional) set hostRules for ghcr.io if private
        },

        {
          "matchDatasources": ["docker"],
          "matchPackagePatterns": ["^harbor\\.stevevaradi\\.me/quay/"],
          "registryUrls": ["https://quay.io"]
        },

        {
          "matchDatasources": ["docker"],
          "matchPackagePatterns": ["^harbor\\.stevevaradi\\.me/k8s-reg/"],
          "registryUrls": ["https://registry.k8s.io"]
        },

        {
          "matchDatasources": ["docker"],
          "matchPackagePatterns": ["^harbor\\.stevevaradi\\.me/hub/[^/]+/"],
          "registryUrls": ["https://index.docker.io"]
        },

        {
          "matchDatasources": ["docker"],
          "matchPackagePatterns": ["^harbor\\.stevevaradi\\.me/hub/library/"],
          "registryUrls": ["https://index.docker.io"]
        }
      ],

      "extends": ["config:recommended", ":dependencyDashboard"],
      "timezone": "Europe/Amsterdam"
    }
