replicaCount: 1

strategy:
  type: RollingUpdate

image:
  registry: harbor.stevevaradi.me/hub
  repository: stirlingtools/stirling-pdf

rootPath:

envs: []

envsFrom: []

serviceAccount:
  create: true

securityContext:
  enabled: true
  fsGroup: 1000

containerSecurityContext: {}

priorityClassName: ""

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  labels: {}
  path: /tmp
  storageClass: "nfs-csi-retain"

volumePermissions:
  image:
    registry: harbor.stevevaradi.me/hub
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always

ingress:
  enabled: true
  pathType: "ImplementationSpecific"

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: >-
      192.168.0.1/24,
      10.192.1.1/24
    nginx.ingress.kubernetes.io/proxy-body-size: 50m

  hosts:
    - name: stirling-pdf.stevevaradi.me
      path: /
      tls: true
      tlsSecret: stirling-pdf.stevevaradi.me-tls

deployment:
  extraVolumes:
    - name: stirling-pdf-config
      configMap:
        name: stirling-pdf-config
        items:
          - key: custom_settings.yml
            path: custom_settings.yml

  extraVolumeMounts:
    - name: stirling-pdf-config
      mountPath: /configs/custom_settings.yml
      subPath: custom_settings.yml
      readOnly: true
