---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
  namespace: system-upgrade
spec:
  interval: 24h
  timeout: 10m
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: tuppr
      # renovate: datasource=docker depName=ghcr.io/home-operations/charts/tuppr
      version: 0.2.x
      sourceRef:
        kind: HelmRepository
        name: home-operations
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: tuppr-values
