replicaCount: 2

priorityClassName: system-node-critical

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

controller:
  logLevel: info
  leaderElection:
    enabled: true

webhook:
  enabled: true
