---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-monitoring-values
  namespace: kube-system
data:
  values.yaml: |
    serviceMonitor:
      enabled: true
    prometheus:
      serviceMonitor:
        enabled: true
    operator:
      prometheus:
        serviceMonitor:
          enabled: true
    hubble:
      relay:
        prometheus:
          serviceMonitor:
            enabled: true
