apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-issuers.yaml
  - cilium-lb.yaml
  - cilium-monitoring-values.yaml
  - intel-device-plugin.yaml
  - nfd-rules.yaml
  - reloader-monitoring-values.yaml
