apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-issuers.yaml
  - cilium-lb.yaml
  - gateway.yaml
  - intel-device-plugin.yaml
  - nfd-rules.yaml
  - talos-upgrade.yaml
  - kubernetes-upgrade.yaml
  - kyverno-timezone-policy.yaml
