---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reloader-monitoring-values
  namespace: system
data:
  values.yaml: |
    reloader:
      podMonitor:
        enabled: true
        namespace: monitoring
