# This is the main values.yaml file for the mealie chart.
# More information can be found in the chart's README.md file.
#
# generated at: 2025-06-30T01:44:33+02:00
# compose files: docker-compose.yaml
# compose hash (sha1): ebbb80442f0148efb82e8da118381d3ef9716d96

# Name of the chart (required), basically the name of the project.
name: mealie
apiVersion: v2

# Version of the chart (required)
version: 0.1.1

# Version of the application (required).
# This should be the main application version.
appVersion: v2.8.0
description: A Helm chart for mealie
