apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:lwj0ju5vkDqG,iv:fP2YTQzBilrHZjRjRbRIDw9qpMYC/6lYaY+La5ygy1I=,tag:sU638u4phXkVeAufvxowGg==,type:str]
  admin-user: ENC[AES256_GCM,data:oejHp5AZ,iv:ayU4j++7QtmMC74vAfXLBH3U4vntAuN0vM2CMubHTyI=,tag:P1VmP83PMh4mfwHhSOAQiw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQitxcWVwMHQwcU1lMXZO
        MG9Kam8wWWJqMTdVN2xTV1RLWXlKSlUzZFV3ClZmQVd3M0Z3UXRKb3h5RjZBWTJy
        cWxmZ3orRExHV3RpTmdrbEJmMHhCejgKLS0tIC9USm5jMmRCU0lEZWF3Z2FDbEZj
        b1UySUtxU0hyM0E4bEtqWVE5VzF5a1EKkmfuOfkdI8MBjb7gd6Lav6MXAMgQ3Rla
        wA4LTpdgqvOBbzPUBBy7CBYP3s9c+bub/Tb1Uo2I3hdxLaB1uvvlFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdFdXSmRJbDFtVjJkanM0
        UE1LdGkrMVF2VnN0S0g1d3V4SkVQVU1XQ2kwClI4c29LdVFUYUNDSVJTcDJEb1RD
        TXlaUnp6cWg1emtKOVUycTBRUkVHT1kKLS0tIHJpMWhoWHl6OU03Ujk2Ti9xK3ps
        MUhWTlVVY0p4RUpLaTkvN1NHNER5OWcKG0EQFVFW5tLee4lTOtwBJyYQwWNTq7uw
        wk+5iOY/lqt/82MjtleGvtYOlxKWpMWHXJWJGXWhuG5FM4bpYYlLEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTTh6Vm93eUs0dXBYWnVa
        NEtJQUxQSW5KalRIcFdPZUdJNkFRUmxpRjNjCkRDeU1tZVZPT2ViTE5DRlFJTnFK
        SmpPdXl2alVZOHJXOURhOFV1czhyeU0KLS0tIHVlUjNZbXl4Uk1lRzhRaDRNMmUw
        a1FmQ3Mwc1RHdGFEdzhCazJza1g5QW8KDIYV7uxaCbbQZZ3D3e7YNSXBfoYeONdh
        JQDtPcHx3B7mdDIZsAD76cgecHP9memjZTFBQY5xezN4ueMxQT+lrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:13Z"
  mac: ENC[AES256_GCM,data:X4ruHobFRF6UYBzj5kDh4VwJcGjXTucOaUr/c4NzRELx255otceHAc/GJdqog+BB53sBz9eL0wRaN+yPHpEXTK4oq7bMG7tQWzinp11vNpMdt6hokl0TgK39xI4n/V8DlJv9OXbTJ+butSvrzTEUS22J3A+jdP0dca0yUB+eHKo=,iv:i3sL6PuhwDEfMXi+f/beIJznJMaoVizR9U25XxAFzXE=,tag:lGHVjRLzX37kRFllc5iMhA==,type:str]
  version: 3.13.1
