apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
data:
  admin-password: ENC[AES256_GCM,data:h/faYD6Hes0WRTND,iv:HxUqnOg42jkNS3xPmqijAMOUEniHWnTeqgfPraG2bxM=,tag:L3vyoQ+Eoy4yf0e/VAJSLg==,type:str]
  admin-user: ENC[AES256_GCM,data:CrfskxANwy0=,iv:RZ2JmdQPHArYycr1yoQdDXGFYOp2BIaOxs2OyIz3SW0=,tag:62efSQ1sNGgg4x71K8TmmQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaHhHUktsVlNVZytuQU9L
        THBHSzA2UTl0M2FzZnJ6Q25wVE5xR0R0bDJFClV2SVg5TE9qRWpUWWFkL0o1VGRB
        Si9ZYWVmSFlWVGw4VzVBdzNCbU5IWmsKLS0tIFp0a0xERXZOVWh0L2YybVVETUpJ
        U2w3RzcrYmpZOGg0Ti9rS3dNTDVFVzgKEfj8ukz1Hv7zbTuAP84B03B34g1w1xz/
        DVZtxNYxHb/+U0d0hzRlZgabTgtlOJmCYzzJLxUN0wgnDyaSrArJlA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAva0hhMDV3QUtISGpDeU1l
        N3dKMU9YTGMzUkwzcVgrTTg0WHVlSWg3ekdjClNKNnk1U3V2Y044OEgxNVNtcUFp
        enhiNG55dEZCUVpOWUJHYmVLZXQzVkkKLS0tIDdDQVE5MHR2aVlTWjVYbXpiekdr
        RG1DYzVmdEdHaEtoUXN3WnREc2Y2QTQKHX4cWTrC7LzzuAUPsEzGYQkxLey0rsQa
        vVHipqi94A3jqfQFBKjUBgxJzRLKXhCW/l1xUja1WiJROSYKF15ZVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNWdzbG1TV3BXZ3NjdXRJ
        am9nRHZ1Y1I5SDdrR3BmVzQwYXd0MVY1Z2xNClFXTWl1T0xoQ0oyZ2VxdzNIVmNY
        NWlnbTJ0Sy9xWnlBOUptRFlJRnZQTEkKLS0tIDhraUMzRnc0RFhoT3ZMWGhrUUg5
        d2pxOUl5UjBsKzZqWENjbEpPU2Rmb2MKEH+9MQsBTVsjxNwPfE1A5sVrZvamcztk
        ulajVFqf/f/oU813eLecRwqWwExtlw3gllIe1vtiYqgmfGv4kH4VCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVU45VFE5R2dLWFNnSFho
        T21uTlJVc0JEZVoyM0s2Mkg4ZHB1ZHlHWkZ3CnU0clVFNlludmFxTlg3VlRKVjhB
        K3IyZ05OUjMyamlQZnJJT1o5NktvNU0KLS0tIHJCYzJEU1ZsNGx5eHZJRVRsNk5L
        cVNIQy8zcXQ3WHRkNlN6L21ReWZPUDQK+S4px+nsGkttYfuDVerIhr3Hy99eBEPE
        xTiUuGM3+CQLF0+Azh9Aa+GMlHyvkJBrfjGAlyUXdkRags8547y+RA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNUtueFlUUFpQVldCN2hm
        SWc0c0t6N3ZVVkJPc1JHZ1UwdlFZZFdJUXdVClBYNkNmYlBQdTdES2F2TUUvdzJO
        dnFrWi9FQXJkc3J6RGptUWhCemlKK2sKLS0tIFI3MVRBRFJ2eHpEalZVWkdpRlA5
        TVJFVkpWbTlXd3Eva29qMUFyenljaWcKYTqiZrMdZGVN9J3uTnDUySUu6XzmcnMC
        V7VtbtjGzn2JEahdA5E8Y+JiHA3q0XIsQh5vkUuFFMLZyRpuxSBnmw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic0VIME9NYlRjOWVGU3RQ
        R3ZMaXVOM2Iwc2RrWENiNS80VXVNS2lLSHdZCnJYN0dKaUdZbTVWZndXd1Zpb0lP
        cVAyWXN0NXhCSzUxR3RZWCtWeUNLNm8KLS0tIGx3T0wzVFZ6UHcrQWxWQVlkck1R
        K3FjUGtpdzdVdER0MXZIL21OTklZdWsKnq+REVWMT9JBMNWfQz6p+6ibeJwObTQV
        kouIdp+d5gjz7PpdTOpReUG1uWYO3nhTBPoA89GBQZ27MJ/X96LDEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSm12SXQ3N1FBemVWL0U3
        TklOMlZ5SlJGdW4rNHI4ZVNRczR1RzYzOTNVCnZzVDZTUWZPdUNvTDVNTjE3TGp0
        QUNPa0IybzZoUksveHRORXEzajBFNWcKLS0tIEhIeTVnb0orYUtuOUJ0cHRJN0dK
        c2JGNjJUdU50cFFLMHhtNktHd0RXUzQKPTL3C9p4zuD98SSGx5NxKC0YD1ypqjwp
        D0jeR3oFoW23sZP38NzWLD4AOGd4+eoDC7nQCRL2ZlMGsdql+ZAeVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZGM0MVVtVkRQVFRyRjg2
        bnpsUFZod2FMS3dyS2xabXl3bEFsQXRNZDA0CncrWnVJTE15V3gxT0xxUUFCdnp3
        ZW4weWJ6Y0pPWW5ZbGlIQjRQTk5sRGcKLS0tIHJOaTRxTmlLdFZMOFRTNVJuU0ZT
        WUVwTHFOMWE5Rlp3VkZyT01GbEpHTUUKWTRAbfhfNXaZ0/vNZuCKwaZLY8xa9KkZ
        O1FfjTVxAidiSCBRG69GA2Yepun6SMU+2Y3yiaukqiza3nsLl3zyqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2dGRTlCdmZaWGxNdy9Y
        NzlsOThlTm1lKzhEVGZJY2dpdmh0Sk1ERjFnClpWWXBPUm9pdzRiejFxbFNGYVF6
        dDZZQUxSU2tjT0ZvWnVINDFrd0xXZ3cKLS0tIGg3Z1dwalVEejIzTlpQK3RPTnpF
        NXMrUlhZRm5zTENuOHRIUGFRSDVKWTQKyZiCus7aZMExOgxXPxqWqqr37BP24UEI
        PE8zybZ+L07eotJbXQamvg+ePCTHE0BZGZk8Rf9REbc1c5AySeNzSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQzV5Q1VLNVhybG1mRkZm
        OE5aMlhTOS9xOE11MDZzQ1RsU2hoZkNSeTBzCnVNc01JQXNRUDh2UkpxeWZTOFBY
        SlBWeU45ODlDZCs0N3NXZHAxVUJkbEkKLS0tIFZsMkp4YmcxT1JGRnB2VTZWSUpt
        TjFFbjBqRlJXTk1hQVArSWhGQkI3d2sKsnDmJzaO4zE0b+VwiFWr9mrKhb4Xa4lx
        8gHMT+Pvq1agzq1dKAh5kkVOAmFSqbrYXbbTpDnLzUDBkWoWjBKIIA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:pyuxjNQjnGXx2MILBEey20mR/SevVCTbUcXIk2qqx/Vy4baNUjce8idleLs+xG8odYlWfloDBbnwWQAxLL8ij9IXT7v7g57flS3bTt//kzhC/4VH+nZzt26YFkf/CXhnC1tvxd1RjwdmdcfiH2gp66E6k3NpdFVEYKVvWvFGH9Y=,iv:4l+QG+8rtyyofMWBWQNz79tAnq7n5e20AcbAXWNETSQ=,tag:eMPGBTmkXr8J+WOsA7OqPA==,type:str]
  version: 3.13.1
