apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
data:
  admin-password: ENC[AES256_GCM,data:m1lfJ97DlQalTSCn,iv:8yyWpZOWTgAIfghFYa5vkJh2B/jA9FHLzz/PuFhF+X4=,tag:BrI1A8unaCsgRCv8mdSGzA==,type:str]
  admin-user: ENC[AES256_GCM,data:3iHbWSqYpBU=,iv:jVIau+0p8gYcygDSh6GCAeAU+jZm11rHJaTovML6Hcs=,tag:JGE/irNgnOdOleGBWDgIaw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTmpYTS9HVE4xWDFjbXRp
        aFc1UWNQK0IyZW93YzIxNTlHN3E0amVqMmx3CllhRG14Y2RFL2ltUHVXSkFLdThs
        S1liZk1NaWRTOFowSlI5K3V0S0kyeGcKLS0tIHdTU2cvVjBIenFQd0Q4aUpNcGNB
        SmZNelg2RE93NXdIUHYxREFHeE5KY0UKqdDy0V1tnBRSnXb+TSFduXdor4kUo7So
        87N2oHhmeUukhImUVD14g7JijvdV4zsydZiPXmMjC/zycYjIBqm99w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeHJUTTUzTGY2Lzk0c2h4
        bWJKd2JnK1dvU0tFcXNEdHhwd0ErYncvbXp3CkkrQmxZOUtwQlM4SmVaQ09sdW1I
        R0JXK05JVGcydHJ3eVVkOTBWRmtoT3cKLS0tICt3dEhPaUN2ZEJydi85T2xLN0k4
        ZGlBVTh5Rk03L0FicmpKRS9tcWh2K0UKQ72DMdz4Kpin2qLypOi4upo1N5Ut8wyt
        6D6Bdnejz+2iXvQg5RSCx02bdjskK9YzC8LpqLyM4XC36Jrztal5RQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsakFvUnVDNkVYSzZhWlBV
        K2I3S3duUkZaVm1YM011SncyZ0xCRU9BVFNzCjF0QThaZE8yTExKZlVwRFNSYitk
        d2ZqYnJWS05aWlFHUVBBbU1zTGNhZ1EKLS0tIDM4UW5TWVpKT2hVUlp0d2lTTDNp
        ZkZIUWg2WFdnNEdsMGFoTzRnY2t0clUK5zSQTL2WSWgvqIFjMGMSag0hwm3Hfc3D
        PQgOcVhl01BtTdZNUncyne/9p6SNXdtu6UfKkwvnhnX3lFpz5IpKgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:XraYW3T9a267HqVV5yunTXA5hRKOj/q43yXA9wG3+yel4HDktlKcwyyO6dbepv8RqXFxGPDETpyhn7TohsWTXbEaEVyAiE6iiRvnrnrgVxGmsV/xRNWafSSr10aRJsKh+CyYqr27sJ5zADhLqGCOIknfbJvrUJWcf1rYNMzcMcs=,iv:qShEdybi8VvretqCTKV5V1imhE5IAZ9P5Cqd8kOtulA=,tag:NpCIEdZic37bQQj0UiI77g==,type:str]
  version: 3.13.1
