apiVersion: v1
kind: Secret
metadata:
  name: overleaf-mongodb
  namespace: storage
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:yZHjS27hzHo9IySigfilQQ0e0epDQZqS,iv:Kd2F7PX230GRwLp77FqnChO2VeRHke5Kfuqat6CKKTc=,tag:I3AaRTHwwQD7Wwgw4I3EmA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWk5GN0xQa01hR3BrRVpu
        eWpOSXRQQk1LVHBHbzFGRStORTgwTGQzZ0dvCkFhTkFSOE85R1BqQ0xMaHliVklC
        dldvSFU1U2ZpbE5HM2doenE0emZ3SW8KLS0tIDJsOGxsOXB1RnYvbmNOMlMrUlpl
        MnpIcUVJUkJxNTVJcitISkhTRVlqbHMKVeh4SvyewLigiiiIwKkWZHwLORcaO+9y
        oauxYVnuKgEWApOI16Ffxfdt6UlN15LKS+mmqF+bAB6YVrkgygz0Bw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa0FNb3BIYmdXZmMzVlRl
        aGlZdDBWZzQvbk1IcGZyWWY3a3M2MVAxOVhjCmtzYWR1bVhhTm9YZGg3R0w5clM2
        UDcrQlpKZlNEeFlwN25zT1JnRi90NTAKLS0tIDRwUGRRT255ZW5laGpBZmVzMWk4
        YWRxQXN5Q0VucUFKNit6SzJhOVJBcE0KdDCC4kqrQ24fUdZ5YwWABRwVerCmZp4M
        t1ql6THB9ke3vXjmLswYq2hSGD2GRNu+qZKW+qqxVQMkJIhEls6qxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVWpWZDdMMS9CaWJMSzA1
        bGwycEZnc2xFTjVicS9zNTBsbUYzVFFQQWlFClJkejNMQ3hBVTlYdzZneTJVZUpS
        TFBaSDk0MFpjSy9lajkxazlBVWtYK0UKLS0tIEkvNmQyYTlWWkZTRERuYnA2bHFh
        cFhScnZac25HbjNJZ2xWak5wVHl2a1UKuuUNlc0kM/Tj442Fg5WopCxCNOr6Vnr7
        DagnEbrrv4KFL2gAIedRcrt+fC9kEl1xljKk4ItF+bafYlgh94YwHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T18:50:52Z"
  mac: ENC[AES256_GCM,data:43H1SQL1vxAL98bZnEd+N2RDY89fIIXZUyw1o8eCQnl6RRPOesh9rrlXkElH2WfTmcZMO8Y6PcmnctbD2ELnRGOAumct/K1d+J3LFOUvvR36sNt/yb1FEMeucWgdwgsNMwST1nBKR2/cmADQpcfyH675MV9TPk7tnrz5V4av8PA=,iv:dhkGXrmd2Cv/ffCXZnkuSOC3dtm0Sng+pRcz8VSemFc=,tag:xmNIpyGVPIrePqGLU7s86g==,type:str]
  version: 3.13.1
