---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: overleaf-mongodb
  namespace: storage
spec:
  members: 1
  type: ReplicaSet
  featureCompatibilityVersion: "7.0"
  # renovate: datasource=docker depName=mongo versioning=semver
  version: "7.0.40"
  security:
    authentication:
      modes:
        - SCRAM
  users:
    - name: overleaf
      db: admin
      passwordSecretRef:
        name: overleaf-mongodb
      roles:
        - name: readWrite
          db: sharelatex
        - name: dbAdmin
          db: sharelatex
        - name: clusterMonitor
          db: admin
      scramCredentialsSecretName: overleaf-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: iscsi-csi
            resources:
              requests:
                storage: 20Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: nfs-csi
            resources:
              requests:
                storage: 2Gi
