apiVersion: v1
kind: Secret
metadata:
  name: overleaf
  namespace: storage
type: Opaque
stringData:
  OVERLEAF_INVITE_TOKEN_SECRET: ENC[AES256_GCM,data:62Sennv0FknuXjZzcjKoGz876fdjm9Gu4viTwdbVNz+TzpaFAkcC5NqwI0Y=,iv:7CKLAPXIPSsm6PC1Y4eo0Ay78y20aslHNLQEMVZwCWw=,tag:P05YSnRzW//xd3JqzZiC/g==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:YmWc3W3S9Et6Velq8hcaug==,iv:jE82xzS33BAAE04oXZxRdxQiAEIDOe7+C8zIxaIUuMc=,tag:DMK1/VmP3lH06S/0DCfNbQ==,type:str]
  OVERLEAF_REDIS_PASS: ENC[AES256_GCM,data:dmZWFERnAKG9MfBVF+ZAdA==,iv:Czn3inJ4k3KccRUNW8tz2hSrb0EbE44XdAs+4F9Pas0=,tag:HtGfCOiCrVQY7MAh+Ed+vg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK2ttcGJpZU5RdThYZVoy
        ZHdrNklxVFZZclFzUjlGS3JFdURuakdXWEY0CkVmLzlxRkg0K1hpYzNGbnRCUStl
        N0RldWkzUU4rNGxQS05JaXhoU0VDR3cKLS0tIEx1elB3RGY1d2RtRkZLWjlsQzRU
        WG9MWUJyZjhLWkhOdDlaVVhMam8wQ2MKIXsUPNhkAMZoYt4XLzXiivDtYfGxYCGr
        19yI7+cQQeA0mdV3MO335AXxZASlHdYtPB01tNcpED8PfPIQsZHZuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma24xelRpYzg4eGZoR1pJ
        YktsRWtWMlBzVlhpNm9SZlFSWUE5cGRsRFJNCjcyM1RHNUhNT2VDUWtnMlVVSWll
        NDhVczVkMFA2dTVPaEVvZVJTV1M2bVUKLS0tIDNRNW5UZGR2TXlLdzg5blJmeHRo
        MFU4eHlRQ2xmVXoreXkyYkdxMzYwMjgKfvkJzRGwah9ZCpRtoDFHb1oai58G40VY
        h7UrGlUTlMyveBrjoPFXNEyqwpd9J5VCG3aGzV4GwelA1gFzrRMRnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWFJ5N1VGRFRaT2NRdGtt
        OEErdU9MODF0anNjb3JEL0xyeTk2S0FWSFhjCityMC85ckdVWnNGUFdHRitVWU1p
        TUxYUGV1WnNTUXVmTVZHV1VIeWpIc3MKLS0tIG8wWnBqRjVHb1pqK3JKaWZnQTVG
        dDFhYlQvaDYzQXRoVWRiNFprb0ZydHMKfjg9r0K0ylUKMo7fxoMtY5QNhjb/5+j/
        U+ZQ+fCmolFXR2btRlZ8cpa+I72kasRmcbqcsL8V/dn+XgSSLn3ssg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T18:50:49Z"
  mac: ENC[AES256_GCM,data:pEtX/3NsYM1zXJSiGEitA4+K9oSop+OR4Xy2K1NC0coH6lhSHkCsqOof6QUCyuPkAoM05IFNIsEbowWSL8zCzpi8QGICW8EnwjpZ0Qf6D8tvu5X+jCe53oODN8FggMy8wmdJlcWFmhZ5DEJoW1bH41n+Caj79a9r50yWOZ9ySWg=,iv:wHhFl02i34HRZQU5cCysEv5yYZdczktcAm7mGYJMF9c=,tag:WN3pMY+UTSFuLWde3tePgg==,type:str]
  version: 3.13.1
