apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yaml
- httproute.yaml
configMapGenerator:
- name: cyberchef-values
  namespace: cyberchef
  files:
  - values.yaml=cyberchef-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
