apiVersion: v1
kind: Secret
metadata:
  name: unifi-mongodb
  namespace: home
type: Opaque
data:
  password: ENC[AES256_GCM,data:HgY/xSyMBqOFIt8RwEFwDWxiVxn1G49F,iv:jMJJdD0Y66UC03wwKEsrbjS5w7mwtrln7zTXRX9GvlA=,tag:JPN7Yns4m09Yn5XXk04J2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SWRtRU5ib1VJRkZHeTQx
        U0w0ZjVHSnlGNmNjV2l2eERvMitMbnAweGhjCm5obnpsbGRPajY0QmdSejIrNGlT
        TGZjeVJJelBoaytQYkZEVGxhejZaZjgKLS0tIFZsYzdacHVHeUpWMVJHYXdvNkRT
        WFNaYVN5dHZXYTZvUE9sMUpSUXBkSzAKVPexpi9MZBVv0klvoprbkByIN2L6trRi
        OstUaAgK4NZfr4MM5XhvPDXDeHDz0AqGckoORUb6frp8B56O9s0sGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTm5VSlo5RTU5Z0pnRHdF
        bDVjVVRyTmZlbWlIMnVSREJKR2Y4djNMNVRNCnliUEhaMHFnY1RORWVBNTQrdDN0
        cXlQTXk3d09XdUMwczU3bzdRcFY2eVkKLS0tIE9Gd2c5VzluTm5HLy9MVFN6dzVu
        Q1Bta0t0eWphd25oekY1UFBGWEdnSWcKrdsPXceZ8HZqQssrtwZSJA76NO8loeiD
        DPgh3lEbLZ99l3x/UXA/VqMejJmNdECsKxbyjsIn064Q7VzE0TYatQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM0FzQXduOURPK1gwaWdT
        cktCaXNZWWZRa3owQTVHelQ5VFEzSlNsMENVCndLd1NsdVZ6MUFUdVhkajEza0Iv
        dmZSZUFmZ2EzZU1ESG9KeWlhUlRCdUUKLS0tIFBiYzNPanBOUForRG5PNE9KRzlq
        aDN4ODJBRE1iUEpZeDZJUG16U3QzNVEKdGHMfSO3hLkeriDVLZICUt9gYiwedPyD
        GFOFpc/lC5/I9QNc+xSfjZlhjYaLJmHReftxqMKMiAOoXLwsJFzq4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZExRSUQzZi9rV3ZMd3Z0
        VnZwYThrcEZIYkN6ZGRlbU0zS3pTSWJ6d0VBCk1Ed2pWSmxoYUtWV3dLbjNKd2hj
        NUtRZHhFZFdPTlJxZGk3VGRpMC9Bdk0KLS0tIGZFQVZWajBud0lFVk5NTW84cThq
        Rk83U29PUFlpMXpEZnpYd2VBSUtJcFUKM43gWAjLBAFUIFLYc0Wu5lDyz+IdFxs2
        HehHdRhxMn5byMfcRu/+yy3/scktpbFr3N80ig0zs01+lonN+JV/+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVHJBL2xQR1B4VHBLTXNq
        MysvVTZFcFRlenhBMDdjazN0N0IycHdQaGw4ClNGS1E0dkZnV2xPc29zUEI3WjdF
        OWpQR0JFbXlRTkpNT2Q5bGlDVHB5TEEKLS0tIDFTU1lCOWZoVi9UbGNKUjYvc2ti
        cGo0Y0IrSXg1UzVPZ2d3M0p2WmpkQjAK3DcxgXr6l/sPZK92DqygO25D8NRrV6zj
        A9ubhB1MSmlEmubiS6Q0Jh6zOxpLDH4AXjp6cirMPKgJw881aGzZow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRGJtQ29ObmFwTWtQc3dm
        UWRrS2ozNDBxc2dTNGJDZXc1V0tuYkZyVkdnCloyWFhCRUY3Q1lyamljOU93R1di
        RGw2VFY0cEhrWHA1SXI0QW9QckNwWjgKLS0tIGN4RjhxekRhdEUxQnhrUkV0RFRr
        cVlEdUpxc0VWVG00eWZwSSsxdERjeWcK7Q/est800EUXlsB3RuhMCr7T4jstIqIi
        8VpudC6DHkVpj3oU4HblqrbkOpv9C4GEzzfKdR8BEJu6uEoVHrgX4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZWhycS83TTdxRE5Lbmhw
        bkYrVDBKaHNlQlU4Sm9IUzlveFl5VWt6bW5RCmY2aXN3NUlNQjk0cVpCeDRrQVM4
        RkF1VDFJQjF5YmRhYXVNamtLVW9HOVEKLS0tIG8xK3BhQ1BBYmdPN21OSE9vamsz
        WkdSK1ZPT1dtZmpVZnNyaTBFWllPSlkKewNFdsjHr8Or5QKASESVHOC6ga8UUwua
        27tUAMgDYOTDH+9Q/PCjokKia+GJllihqSL7u4PBAUfAsNVwQ6U97w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZ0tMMkNuc1dwMnNXUmYw
        anRTc0xhSm1zVlMyYWFTcEgrNWpub2tRNEY4CitFZXFMWG5ZUmsvTTAySzNQTGxp
        cDVORVc3NUhHL0F5bEsrZ1RBVy9IRmsKLS0tIGtRQWY0VTVDd2F6Q2xINXRHeFNG
        amFVa0VNYjI3YjVZdnVvVkQvdE9tMVUK0r6piZWrgFadlQ3Mj9tWtyLeUm0TVe//
        XRC+6K6T1PhPNR46gzhxilpmpiwnMi1aNGRq23tfwLfhjs0jm2S2qQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZnZBdEJhVEp1RzhTbyts
        Y2F1d2RhVFhIMUtXUFpURlJXMjVvYXhxYnlnCjVrYk9SS2pGd3AvcGNmUXZzSUlG
        clpYcGIyb2g3MlM0UHd1RFhGMTFIaGcKLS0tIEM1Yyt5a1ZlaWp2OHYxbmlJZlhh
        b25qRzhsU0s4a3JaTEIvdzNEYUtJLzAKVoYfVAX4dAjYtV/opRtR46LahHBH+Wbg
        7sdDRVNwD5VYw3V5Irsj+5ji/F+dy+55J7hUNFt3PkQVIwZV8d8SbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNDBQTnFHTWFsNFNZMS9m
        QzlpMUI2UzJRM0VNdTFJZmpNYzhCcXpMb25RCjBqdEM2dFp5RXFqczBuQ3dpRFJ6
        RTlSTHd3cUluNzAydVVBVWVPbkxEVkkKLS0tIDVPUnRBWEtTRDBZRTRsMWJKMHY1
        MnNURVFlT2x2dmd2NmZjSUprVjhuamMKlEZE8LiaskdSqLGTArOufSBeKDAwYJs/
        ZdRXvKjEpTMQJxE39eCuSr8chmqesaOJjP0+rAur0tMLfSv3GnNEXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:FfhBqNFR7uxmqNOTBWUo6gBTXXGdEC23esLTKFVqhuCGwZW5z6nwmlI2kPTIaCLnlONQi/ZjJDrSsZpx1mlN9H0kmOjA3lLYanOxl8tpnoODE79u+Fgm6A52/7zl13cjL83SeIO2oAY3Z1w+IKeVrbRdTlbWvRctalQBrYaLYJA=,iv:8f7j4P8XcNj71UAHdYELyjK/jhY+gOu91Xn6jm4zYhI=,tag:tlynuGPUmOmE2o7ZTqKlKA==,type:str]
  version: 3.13.1
