apiVersion: v1
kind: Secret
metadata:
  name: unifi-mongodb
  namespace: home
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:Ga8O3BmX9FQUMPl3RyUg9w==,iv:IoFbmgeMOtkUeWirsXU2bM00/legOqlFogbYpgNWjSs=,tag:sHxrCibaDUGqNjLTnvYRXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMW82S0M1TjVHMVFTV2tq
        cGorV0F4SmZWOThZNmQ0TmJnbzYvQUJNTVNVCmtBd001VloybFhScE1wYU5XNE1j
        TENGdlZ3dVo0VmJvMzFGQTNyUjMybGsKLS0tIG9hTDJVWE1qWHZLV09xRC9YRTZk
        SHgxeW83djJwY1N1QVBJTUMrelh0RWcK9j0RAjY7k63W6speG022hAqUhrqn4K5Q
        4I5xxd25UkNkXvHbW9AEzQi037AeLDt7oj/MZSki7BodUOF76lFHfw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCamtrQzBSNlR5d3E1ZXZy
        UWVCSy9vU0ZvR0RMbGJoMTNwMzYrSWh3bW5ZClUzRUZaM0tGNHcwR0pWSElGV2RZ
        WmhuTHJDem1PWVc4YXROMVRxRHBtSGsKLS0tIFkzVjc0OVcvT3RxN0E1ak0xRDVU
        dFBwRGJoZWxudkpOTk5QYmpTcnBwMjAKiXArmoWwTNq88rLggRTcq/gE6Hu5rojU
        MRYmLc0gfO1T9YEXyKzezUFrwyEkDeFRdSloRawvM7HhXeAEHee42Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUWtEUWQ0dkhpWU9rUWl1
        NGxMVysrSTZIYkN1TUJPVkFxZDFRVzFNL3lRCkxaR1dST2hyeS94bkdGQk00SnN0
        TzFxTy9vTmtCOFZRUkxzVkgvT2hxaU0KLS0tIDRCOHZRQ3p3ZWRiYVRET0VtZVRY
        blBkNEFkUnY1VGh6UWFkVDk2YVdjUGMKuLUmOwbzMMazO29Zpja9BJamX57xcd7C
        pcefCb7raQXsi9+0RCLyr8HXptIJCnoZdJU1bdAbPMLqKVit7HhUeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:iZyrpnpFgetr4v3aT85hpk00UyJ6QsegACRTlOm5qmomxdrFNgFEXo7ZF4nQKg7zPsyRn2o6hSvnFKZuVUT/fIaSv3IftGxRjk2UtKdqU8QLS0e8vm5Lt4RpzaHH7Xte32DVgxJ+yocHvzQmtxz0MSrdorjP88dUNj1e4hnfIjI=,iv:19DijSvuRnnyBbYrtkge+ab5m80WPT0iVp+pmTWP1gk=,tag:ofIk1WCJ/0V0LzAxHO+E6g==,type:str]
  version: 3.13.1
