image:
  repository: ghcr.io/jacobalberty/unifi-docker
  pullPolicy: IfNotPresent
securityContext: {}
podSecurityContext: {}
unifiedService:
  enabled: true
  type: LoadBalancer
  nodePort: {}
  annotations: {}
  labels: {}
  loadBalancerIP: 192.168.0.153
ingress:
  enabled: false
timezone: Europe/Amsterdam
bindPrivilegedPorts: true
runAsRoot: false
UID: 999
GID: 999
customCert:
  enabled: true
  isChain: false
  certName: tls.crt
  keyName: tls.key
  certSecret: unifi-tls
logging:
  promtail:
    enabled: false
    image:
      repository: grafana/promtail
      pullPolicy: IfNotPresent
    loki:
      url: http://loki.logs.svc.cluster.local:3100/loki/api/v1/push
mongodb:
  enabled: false
extraEnvVars:
  - name: MONGO_PASS
    valueFrom:
      secretKeyRef:
        name: unifi-mongodb
        key: password
  - name: DB_URI
    value: mongodb://unifi:$(MONGO_PASS)@unifi-mongodb-svc.home.svc.cluster.local:27017/ace?authSource=admin&replicaSet=unifi-mongodb
  - name: STATDB_URI
    value: mongodb://unifi:$(MONGO_PASS)@unifi-mongodb-svc.home.svc.cluster.local:27017/ace_stat?authSource=admin&replicaSet=unifi-mongodb
  - name: DB_NAME
    value: ace
persistence:
  enabled: true
  storageClass: ''
  existingClaim: ''
  accessMode: ReadWriteOnce
  size: 5Gi
  skipuninstall: true
extraVolumes: []
extraVolumeMounts: []
extraJvmOpts: []
jvmInitHeapSize: ''
jvmMaxHeapSize: 1024M
extraConfigFiles: {}
resources:
  requests:
    cpu: 10m
    memory: 768Mi
  limits:
    memory: 1792Mi
livenessProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
startupProbe:
  enabled: true
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 60
nodeSelector: {}
priorityClassName: ''
tolerations: []
affinity: {}
podAnnotations: {}
deploymentAnnotations: {}
