---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: talos-operator
  namespace: system-upgrade
spec:
  interval: 30m
  timeout: 10m
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: talos-operator
      # renovate: datasource=docker depName=ghcr.io/siderolabs/charts/talos-operator
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: siderolabs
        namespace: flux-system
