clusterResourceNamespace: system
crds:
  enabled: true
  keep: true

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 256Mi
cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 320Mi
webhook:
  resources:
    requests:
      cpu: 10m
      memory: 80Mi
    limits:
      memory: 256Mi
