apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: system
type: Opaque
data:
  api-key: ENC[AES256_GCM,data:EvLTATzaqgCsk54Jva0KsXb/DjTCXptSRwLJAYDZsfXFcHcmWooU80RmPih1fjKoGljWmbED82U=,iv:rHDI5Lg9duVh+BR9Tpmp3DYpGtIx5kunJE/+86XOmvs=,tag:L1F0CMWEXlXRF8Gp1jOUKA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSjY2MFliZUhlbzFmQm1a
        TE9KWW9oS2Z4Z3JKaE9jY09tT2xZcSttSUNNCjQwb2ozT3FjYTdZWWpGMWxReGJ5
        RUcydzZUUzFOZHdqRGk1Z1NGWXp2SW8KLS0tIGN5aUZoZk1LcDJDajdoNTY1dkU3
        NXlQbXhGeEd2dGNKbDBXaGVINmFDR2cKqBPJmO9flTmCd5Ghp4uH6QKzrMwgAkyE
        BfrKJdJDl3maZXhToks4/SzMP3Z/YPk/Vs19SOFfshO8vUxIwlQInw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMUNTdjRRNGxJMDBjVkxv
        SVN3ZnlyWlpOL0tIYStJLytESEgzNkphcmtZClVCQUE0RWptK0U2OTBzeU1KUmdh
        WTVPc2hDY1FMRXpCcHdvdVZkcG9HTVkKLS0tIHVHRVhFNFd6bTIzOXR0UmhsblFZ
        aldMcnNmcDBDK0REODVpdTJLN0tDd00K0+ct/fDxEZadZbC6cJoZXQOjP/8oXkHQ
        qNlVOLMlFnZzYS5B+hCyRxoiRUxebYILMXVq5qz5YD+ccNifkmx9Cg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNDhSeGNBK1ZGWHJlZGZh
        WDBvMnZabVYrQkdxZC9idkVDaDUxMzNzejF3CktFRzU1YXVNR1RKNmF5QW05aDY3
        THl3UnAxN1JFVFVlWTFDbWZ1Yk1mZEUKLS0tIGRXSFh5RnY5aHBqVnhJNnUxOG1Q
        T2NOTERLb1gzdFFXN0lIYU9xQWQzZzQKrlaOtswnhNakvavAOMX+Sjqrybdlx0hB
        MUhUwD5k6Ex7W30xg2B/8sMRFsG6fmSur5DsEx/b+yPN2kCvDstLBg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VFBZUGt2SGh2MnU3TTY1
        czZ1bDJaN1dpYXIrL0U2S0NwS0RsNkhwNjFFCld4ai9NRGR0cXJHTm1OQ29TTzY5
        a2V0UkJVQlJEU1EyNWxoMERPcEMyWjAKLS0tIGdlQUkwYkpvY0RRYmxrOGhiWU5N
        QStVOXo1YUJWSjFkWFYvL1FveVB2V28KM4iSh+QqZ2fPtmz2+4i/UniHBtO6QAvF
        sYIk3FNTBflDz8QJa41FiKvt8LLDIyto21Qb5CYteCJu3nJR1ANKRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZTVKVGNCa1U5THR1Y3o5
        Rno2N2lBeU9POUNOcTVUWVowZTFpZDF5OVdVCmFIWHRCV0I4VWNCYWVNaWNEaDM3
        TUtIazVUOEdxWWViL25YS1dJNkt6VUUKLS0tIDhGb3I0TGhXVktyVVRIQnM5OHBT
        WW9UWXk1UFdmT0w1eDdKWVRXV1g4dm8KBweIxAz40kLCDBAiF6CDj/+Ux3XaRNLb
        XhLWeXhZja/v+/chZ07NMjKSbvfBMbu1No0zjBPSMVq5MH3sCpfHjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVW1pdEIxc2ZqR3FieVpQ
        ZG9ML2w1OXRtZjlDWGpKbXB3MXZTWG9HR0NRCnlaaTByRGNmVFJxa1NwZkk0bTQ4
        Yk5OTlh2QnNBeFVIU1VIenltVDBkQnMKLS0tIC9qN3F5WGlQeEhOaitrOVpEOUZJ
        aFUzUS9RN1AzV2pUS1d3NmNkbTRBM3MKHMhnAOflBco4MxAW7w+FcsIOOL9K7/bt
        JtvWTEhf5sYXOuUobd23PVhG1OI+LqaYR9/atK8ZTFBfuwZ7LiVm+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ0VXRklVMXU4L1F2L29r
        N0lHWkRyVm5FWXhpaVBUUGZ3MlhuVjNSM2dNCnBBUzdSa2lvUVBzSStVWk9CTGNv
        MEk3RGJnQVZaUCtncUZJQXc0bWR0WEUKLS0tIGttS1MwQzZSRW1ndEFZcHFWVEJM
        QjFZSC80aVpLdFlWTDh6bE1lemR2bTAKGqxwtJvvbcIHy/ajW9ncW83DlJpDpYmb
        pXkC6ueObHKx5+DjyyIMBJrFbLMR343bD4KXf7Be4te5ZkmzVwaIaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRHBIdWNNM04vVGt2VDhm
        a3dYV1g5YWNKU3VkNzhQdEVXZzJseXBpczJVCmd6TStQTDlhc3FLN0hKSU5yRmZX
        dGpUb0lOY0pUandjSGg1ZzA1T2N4bkEKLS0tIHZHdm9FZDN5Q25ZU0tDeERzQm13
        SDQrK2pIRzZxNFU4cE1hSnAxeUgycTQKXBQ2Can3YLWycUwKvmSj7PIA9V1UezLn
        n17FxHt9al0ZbA5U4oX41Nb+6RHNnBcoEtjr8AXcl6Si6d8iwvlb6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT0x0Z2ZodGxHdUJvdTlT
        TnJZTXR3ZDlxVGxPaVhzOVJpVmR4Si9SYUdNCllyNUJUZUNvUWgyWVgzaUJSUGtT
        MWhGSkN3KzlWM1dPaHJIVDdPMDFmNG8KLS0tIEZ1VXZML2NqaUFJaGp3Ymg2WU5J
        S0hGM0NNT1lIeFZGMFRrdXpqR3VMOEUKXL9AdQ6Mif9oUlpdgQ5vGTaTL75syJXv
        15gPQmOBId2tX5HL79uRr7/eju7j/J3D4o8w3LvlFhEYFrJA6U+E8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRHhrdHJjcDRmOUppUGh5
        Mi9UOWhkeE1mZlVmaEVQcVFncmZ0ZCtwNW5BClQwREw2aHprbkVOeEo0a3c1S1pR
        SmxZUFRvR1pINmlhZllZLzZONC9YcmsKLS0tIHQ0YXZHbEpoTHJmUzduMXpOVVVs
        OUlyNkg3QTRVR25JR2JzMU0zR3puWVEKFU0fxlBbgbU9Xey0JEpb6/qznkDR2yPa
        yK3d2W/Q60MFiQ7LxRgRtiifyvqxLj9NOUIRAExMmRfZodeB56TNlw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:RPQa8bUqh9TT3j6XZIZzwnnBu+yTSpg2+XQjePSlG4mtq3utQfBG6PUa3ph5c1gEADtyXVawmMd8FwSh8gnjCL7uu7Jb49Yp+ey7ZkPnbDJ++G5jsCqjgpLXllMy1mk0uSgr+75XLcl8NaEsUYyqeVDJnw04vj3wm/Lsa4FuZag=,iv:rEPuwVFwVtPCltXJ2oosnMcf40w6dCAHl4vcGFpR+Aw=,tag:KHkYcVBqILpvC/Et9yxzQg==,type:str]
  version: 3.13.1
