apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: system
type: Opaque
data:
  api-key: ENC[AES256_GCM,data:IBN+ucgV0boUk1/q6IaMd1LJHs0dE45OXHqDvCAZiVckVmbKM9bPNB+gdOnLoNzu4PBYNIJW3bw=,iv:Q8XdEomtzB1iXw6l8nLX+9INMWQxVsK2qGBjdGT6j/w=,tag:xQhOJQr+uJK9RxfVzKlGJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRkpOa2pNV3UvT3QrZ1F0
        THlLbmM3OHprR1BmR2pkV05MVWM5SktETEJzCndEei9uWEpLRzZGQ2hQUGJod25k
        UGtNV3F5WWNTdHVFUzdoQ25PYUthdVkKLS0tIFVaMlVCaCtDTjUvV2taUWR5NzB2
        OXMrcU1XdDExamdNTlp5MzFYQmh2MlUKQ/TGq6EMqe1t0MQp1ZKLUkuP6DBp2Wqy
        78g22Fd9J6TNNq9Mt2O5qHt09C+og7aO/6eb9KZvVFiU/bWu6bOeeg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaFZnWDRyYUtxRHZxeDZK
        MGorMVY3dVlVQVRXdEQ0YzMzK3BQTEdDY0ZnCmNUd0xTekhkKzI2YTg4N2JlOCtt
        Zyt3bDc4WG9DL0Y4My9DMFVxSHFXSDgKLS0tIHpaZ3hoUGZNWnEvZnB0eVFOZ2xT
        amZXUDNVM01FZjgwZCtrYnFZUktKbTAKuaDNDhHxqiDElWBgpAVVARfFxrQj4M3z
        9ihDLpPd8228NjmemtQUil3F+vabL2SIo8YDOw1ozfOXG46kDwLykA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS0F3cW4zMEo5Y1g2Mlky
        QVNUSmQyRFVNVzNENjlxVG85OW10WWVnK1FNCllMYjgwYW90T3pqZUJHOGJnVEFF
        a1dOajNMNURiT00rUG5seE9UaUZDUGMKLS0tIHF4ZVFsZlo3OVEzbkg0d2ZTd1U4
        blV5WTRObXIwUm96blZMNit2VGk5ZkkKGLqSDjR/o3osTTuIzLX/a4wEgbJrUETi
        1hYBHSd6Tb/zyv9yZImXI/Z9Ims2VomSIebv+VuH0SRfHhVjYZzQtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:4nmP9dLjEw0Alii1nE40y9J5ngaXTX+5FbvmET/NlQ0aVY2i1Sic2CgFlJFbAWwclYkPELQO7uomeY4+BCs4ZX25qfi9XpfsZj1gRekwL+I81XtG3JEwgu9wfwzaGaENN19a140quKXVWMjkmbwtrfyJ9Wv7pdcK784cDgG9KOg=,iv:bAMlMuee3rJjoPXjY+FG0C3fKEK0bQJT9bQEAnJPdtg=,tag:BFa97ceYNjKzI2jd3TDesw==,type:str]
  version: 3.13.1
