apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: system
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:DqjPRJU/bvqBGVVu/HOcUMq+0uL1gGt97IY/NmwDofTpQNHqLbnwXQ==,iv:nr1XeehrjVSVIeYuOVK1KCjToJKoEoHbNu6VpzZOIBw=,tag:Sjsn4yYE86KMGwq+9EN/tg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdkhHOGhEb0Qxbi9vOVpj
        c1QxRldFdWo4L25QTDQyL1NydUFpbGgxNkRRCnhWQ0hzMUpUb2UwbnVFN1BjSFpI
        cThraHEwWVIzRHV0M3hoNThJRmVaR00KLS0tIHczVndlTkNsNkxoMjFUTXJhY1Qr
        YlZPR1UxQkhKME5QUmhvTHVFaURaTVkKkO4neHYLoBUwClaDCFigyCoz5pM+hz8q
        JgUFk8UnNcV2o45doO4saeZd0ztephxEiAMML4KplKFlD1XowUGyxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVFJkalMvandrSURQbVd0
        ZlF4NUk0VEVxZDdvN1NIT3RuNXZVRXREOTBVCkRLd29pcnhCbGRNc2pSNDBCbm5D
        L3RHWmJhWGFnckRoUkxJN3pRY0IvL2MKLS0tIGlKVGVTWWQrdmcwQVlUeGxvbndm
        ZE5nb2dFU3ordjlDNjRpR2FvT21KUkUKcOWkQOAC8wsbStkAE60dpUpMqssdfepJ
        VKYvjK1P0gAwME6FrjIDJv28H1KmE1FdVqtF6t6JyVZDoc2eZz3C/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNDk4ZUZFTW9odDF4dU1l
        QXhDTlB3dDdWeVFvNUZsVnY2K2lmZWN0MkFVCkwzQ3VPMGxMVlVreklNV3U4L1lk
        L2t3R0FvMTlocWdRQ1VnbUZvMi9BRFUKLS0tICtZMm9tN2RpNWQrbmoyNlpBMmtQ
        V2dXVmg1YVkxVFJXRzl2SmlMWmg4UmcKJwg4lL2xhjcnTn7QCgvVvTr2/3uDsTXf
        GgRNqP8oEV/ShD4P1I4XOHpKCKlOv3ePcyc2J8QOGYBNVI/khMCMjg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:PXY++va6lRo6goYqjBajdNPt4geKV0QXWZpBubkRuVY7q0h051n5FUMdW1ymJn4rEYaNCLVrXXq1gPmbpcNFHMCyQ6vTYKtX8ZHhylZNqrYhej022uaTI+AJ0oVDppsj3wI1p+Y42mnfND5blzlarMWwp0gr7jLQR87a8+1Onf0=,iv:f+zhePQlC8Pi43oKiWHPKPMfDQH+EGjOBicFbXeqfEA=,tag:LWRjFtHHDA78bP61CbUfmw==,type:str]
  version: 3.13.1
