apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
- name: mongodb-community-operator-values
  namespace: storage
  files:
  - values.yaml=mongodb-community-operator-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
