image:
  registry: harbor.stevevaradi.me/stevevaradi
  pullSecrets:
  - registry-pass
  tag: 0.1.1
daemonset:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - arm64
            - arm
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - macm1
