
deploymentMode: SingleBinary

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 3

  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: pvc

  frontend:
    max_outstanding_per_tenant: 4096

  limits_config:
    allow_structured_metadata: true
    max_query_parallelism: 32
    max_query_series: 100000
    retention_period: 744h

  query_scheduler:
    max_outstanding_requests_per_tenant: 4096

  schemaConfig:
    configs:
    - from: "2024-04-10"
      index:
        period: 24h      
        prefix: loki_index_
      object_store: pvc
      schema: v13
      store: tsdb

  storage:
    type: pvc

    pvc:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Gi
      storageClassName: nfs-csi

gateway:
  replicas: 1
  
  resources:
    requests:
      cpu: 100m
      memory: 64Mi

singleBinary:
  replicas: 3
  
  persistence:
    size: 8Gi
    storageClass: nfs-csi

  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

chunksCache:
  enabled: false

resultsCache:
  enabled: false

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

