
grafana:
  enabled: true
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/whitelist-source-range: >-
        192.168.0.1/24,
        10.192.1.1/24
    hosts:
      - grafana.stevevaradi.me
    tls: 
      - secretName: grafana-tls
        hosts:
          - grafana.stevevaradi.me


kubelet:
  serviceMonitor:
    cAdvisorRelabelings:
      - action: replace
        replacement: melodic-sky
        targetLabel: cluster
      - targetLabel: metrics_path
        sourceLabels:
          - "__metrics_path__"
      - targetLabel: "instance"
        sourceLabels:
          - "node"

    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance

defaultRules:
  additionalRuleLabels:
    cluster: melodic-sky

"kube-state-metrics":
  prometheus:
    monitor:
      relabelings:
        - action: replace
          replacement: melodic-sky
          targetLabel: cluster
        - targetLabel: "instance"
          sourceLabels:
            - "__meta_kubernetes_pod_node_name"

"prometheus-node-exporter":
  prometheus:
    monitor:
      relabelings:
        - action: replace
          replacement: melodic-sky
          targetLabel: cluster
        - targetLabel: "instance"
          sourceLabels:
            - "__meta_kubernetes_pod_node_name"

nodeExporter:
  serviceMonitor:
    relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node

prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/whitelist-source-range: >-
        192.168.0.1/24,
        10.192.1.1/24
    hosts:
      - prometheus.stevevaradi.me
    paths:
      - /
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.stevevaradi.me

  monitor:
    relabelings:
      - action: replace
        replacement: melodic-sky
        targetLabel: cluster

  prometheusSpec:
    podMonitorSelector:
      matchLabels: null

    serviceMonitorSelector:
      matchLabels: null

  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: nfs-csi
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
    remoteWriteInterval: 30m
    retentionSize: 8Gi

    localStorage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

