apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: monitoring
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:oRwcjoBmTjI/vpt+iDTpxceHhORgYRpEAHjNUnyPqeRM02M4SiJFsuxEFiq0SE5BSRw00nhlLUFOF2smPJbfmFfv2gDcUyhX7Wj6sohGjezwNSeebiM7geddamTvQK6O5uh6WPcezKAsBDMPSZCa7mAcfy26fV4U6jIc4DzLI4OAfNcY/NWHTJ6+uAMktZLlssUvdtmTtfMnqLoxT5UbdEeorg9ZaPSxpReWKtnoufK8VLAK,iv:zyBHUay6eyo5I23FvwgNZwM+eFlF/oVZGdLXSC2iMhk=,tag:GTxpJDjaO0zZEVRi89yXEQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxREN4WGJoQnkrcmZodHdW
        QjNBMHhnSmt6bjloTy9PM3JocW5SMWJIR0VRCjhqVHJVRWJrOHVPSTQ2cGZuUllU
        Tjh4M1FLbTFqUWJ5MXBwNlIzQkUxMlkKLS0tIGxidnpyLzNHdVNhMzNsa3J3UGFQ
        RkxoN1VZVWdYdUJSeEJ1SnpDWjV2Ym8K3lxmzlKGLHYP5yWarIQoZ3YFjrR0sFGO
        eN4Rth1Zm3CjKBiyeg5KA/iKElVLd6zt6T0JupjsY6SuN26/mZuswA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK2lZdFFnQkhGbFJmU1pB
        dENLbi9LSENZaUhhNEZTSFNianZaT3BvWGdjCkp0S1pJSlNwYUtUR0kyR3MvWTN1
        NUVKVVB5cUZxdkNKMng1dDE0c2xjT3cKLS0tIFp1MmZYUDRqZ0F6ZkhBOFdyUGEx
        UDhBZFVoaGh6TUFFNWNvRWswSUlDdUEKsjzicerQureL6AGu2IGAsoQNrQpPmG9j
        UUK6lZxQ+pfiZcjokXL+zxFW73HJRwd4d7NBMTXInYBhW399itsthg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZjg3WGpqK2UxaFB3dlJ0
        ZnlSLzVnWUp5am5GOGp1c2YzdXZUN251cEJFCkdweVR4a0RUbUk1TTl0Wm9kQ0J6
        d2tZVmJ5c2tKT2g3azNNMVNVNVA0eEkKLS0tIE1RT1lQcVYyelVRSkRqMy9yL0Vu
        dDBKS1JqRld1aS9WSmM5anpCUGRwVkEKqEa6J7uPA8RDE320uTX3pePGR/OFslbH
        EOQuNZqzjey8mj1ixoYTOsACaVU5ZhcXCRtowdmUOF1naWbTXmvC+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:zgSBXyvQaX8pnzbKbL6Tl6duX2sTpkJjIIn/KJmiN4JKioM55fFTFzXcA67EheUpXoZgtXqptBHdhRi8Sqg16V2FWC6r/KnZ0jU1GNg7S9g2VmWmekSXRLwMvHxAuY4mlxQ0qcWlepLS59Y3dmvLVpol58DDP+ZWPg733+rP9dg=,iv:JUTZqDoBBXictiUjsQn5VbEv/xPsAqBeVDRdM6Xjz00=,tag:/ILpAjrM8fd1xSUw6eGCaQ==,type:str]
  version: 3.13.1
