apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: monitoring
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:4mGfx4PtqHbaMX6msEOUO48LHbFxgDgO1YMofjmCd9F8NetWhx16jBWRgGvp9n2BXq3DlrHPwWJoWfWlKw4vdNtWLR8i9mf3qoaFjNSDviFTiBXaX8ValOgPHonhX63n/3FjQjqoAVB9/GTMLIOMRKPNNrcmYidxHqFmEKrhkKMRy4jh2A==,iv:kJohdRGiDofBLuscx1FKlOoplc/x2Jj2o4KGtB+h6DM=,tag:oev26iSWbUpy/W+79VQ/gQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYkJBOVY0emw2Wng5VXIz
        R2FTZkw5ZjFIVVdjQmN4VVJaRHhwcEFKTWdJCnFRZkQ2N3pHaWprQjJHN3ZtdFZN
        aDl0WFM4MVpYNU1UR3BRU1NUUUhvVVkKLS0tIFJjUTlMbjAzclVmL2l5TUpOeGRT
        aWFndlBYN1dWQUd1YVhaMmZ6Y1FlTG8KaQS6LExh9fZVSE9wZiveyiitAbpsmb/a
        2EEXaPPfQfPBMVmi38O/aZ39SZEeoS7RXB4jZ52tTcxkmTaXKkzJwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSlFnUURVeDdtODdOemR4
        Nm9XQkhXNjVlTWdFQ2hrTWI2QnRLNWZkc0M4ClBUOHBkaGJXdXZHOEU4ZUQ0ZW9y
        dTBWRlN6ZkwrbXptdE5xM3F0NXNBc1UKLS0tIGd6MWRHVURlMWJlZEkreXZNM2d3
        T2dDWXNCZTVMNVdod3VyNlVnbW5raFUKh/havfnCCh08yeaoeJmGJwz2dLaFnh0Y
        oGtOfPUm0Wht3glTv6H54yRvHq18lMVJbEnqv7YAaFkIRFa0G0LPEg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSlNqK2hHb0k5T21qcWVZ
        REZwZmhRMUszUlJRak02YkVpb1BRZmIxSGw4ClVsWU1CcjZTVGM3NGlqeWdXbW1N
        WGQvQzZ4ZnZaSUJ5dUVvZnh0U045NTAKLS0tIHptVUJaYnV3NlVBS1lIUnlwazVa
        bmQ5MHM4K0V4UzYwRDNNRFUxQlFaVDQKitR7wyQNKbsehRnKhisUg8+DqNlws5O9
        B09JOwx32WR/BL4dfCtRtGJaaI6rSLd3I6bQ6Y8OesCSsd7Lxkbq4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:13Z"
  mac: ENC[AES256_GCM,data:W2I0b6K6dbdFTq7vnjswObBzAYCanb3Akpu/jkh6SInQp+EvuYy77/FiUX8Zr0weoVD8SZsym12/FI8hxhEzK5uleqKLGw88rHa4F6u4paUY3x2ZOEanEBbCz5GspU4CX47aFjqNs22qc6Gng3lcG1S8GSevCLSmKeVAm5125FI=,iv:GTiwEqA6Rq0x5DGPTdWLu0rciAZVLr7XOP9N8BCa/PE=,tag:BBbROJ5bRB3p3ZumPdw3Cg==,type:str]
  version: 3.13.1
