apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: monitoring
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:rKPRvCGzr8pQWCSFaGksC9Nl1LZ1ofQQpF4/qLDNOhB/GC72A0MESrPclFtJb1JaunDxaPiR85s6VSan0nPMJQSXo/FXCe1ATHRd+2zk+FAZxyP17NSQ3hJ422lTnehrOkKWLoAdG4llkglTJcXn1o0YNK8VBP/Fw27a7frwyfhqiIkXUuSM681Em2zm83aE5f2kib+X3UEBNo/P/BGOUtXnmmHIXLow2xzrzUHYrFSDEPfz,iv:VHntqaaKKOzR1zzkTSnDOi36q3p6XP8Vv6gRGIQbTYo=,tag:fWrGOYRBjEhgOCHdZUSWyA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YTV0eHdHUHBIdHp5cGsz
        Y1FOUnR3R0ZwY29zdW9EdjAwUlVYNzFUNERjCm5BbTlDTXdYbFZvRjMrUEJ0QWhp
        aEI3TVBBdzBYZVJoT3ZNcGowbHpRd0UKLS0tIDdxQ3QvbjZQc243SUg5bTVwSU5i
        cXBZQW1HK25UV1hraW9idzEwUlBUamMKSLQEVML2TROP/MBZdOJIPM4e1FJLvVda
        3czu0QJW/rmjqWp3ZLAeDhh446UqNtQqQqYBRXXUWZoOIAwi2djAYQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RER6ZzhPek5sQi9MQmpE
        dko3SW9zdlRTSWI3UDhmemV5Y2lsZngzekRRClpFVFNkTytjVEYvNk9PcDFmTnJ2
        bHRLcHBNdjF0ME1xTmZuNFkyaEpoMXMKLS0tIGpYanZPZVNGWUgxQ0k4dTVrNnlM
        OTJjUTR3M2hyVFJkU3NmR3VteFE5ZUkK0Wmg8OfUMZcVL1L0Me66VsEm8G0yJofz
        /OU+eWRVdz2OEfvutxWJq0awFwTV1l9IV7Us2WBKkIznhYlbiq7jAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUGFCeHE0VHFoR0ZYSzVG
        V3Q3NFFFZTA0c2tNMG1yQW9ISjNhcTYrNHdrCkFSRmZXSXJWaSt2ZTZFL1A1SXl5
        bGRsZmdNNUp2Z05Xcko1bHdiMU5Mc00KLS0tIFY1MEd1MW9IMkxnMTl2ZFBLYm1q
        MWdyLzdDSllCdmIxWTJCMnltSWF4YTgK/rk0cqfmUlzGkAzkOdpfNwFpPXL4Wh66
        mSm98FLUWPWc/NH+IIQR4XQiNQtOVMLMOBh5JPFDwlNB4tlt+GiGfg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMitpalF4WkFpMHlqemR6
        WUJxeWZ6OFdzZ0RCdjlZdDJmNXQ0UzBCNGxvCk5sYnNlN1UvbmtwckRTUjBYdXJi
        Um5MZ1N6RTJBaEQ4R0huZmpoMDE1Q0kKLS0tIDNJTytGbXV1NGdteTc2TnJHWEZp
        REhRdURQVi9WQ0pVc3kvTmVpRGNNQ2MKG2hKrplUGQ26BhwMvhbfCM0CRVmjlFCg
        xMe+T2BSSVxiZNZjWkgBIRfsI8pLfOn7hZrL09WWYzPUOqC2yYjxmw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa3Z4ditlZm5IUnJzWDBw
        UHhtZzcrNnR2Q3orZG5abjIrVHRVYi82M2pvCkxLYUsrbVhKZlNvSi94a0M1OU9Y
        amlLbFJ5dzhrU2VSd2habnkrNFhkSTQKLS0tIGN4anBWQThySlVNSnBCYTlhRFNa
        V2ZYTGNiRVg3V2dmNDdHa2NEdU9xOTAKB/sOwv8U27K9GazM1eOz+nItzRKn60Zq
        M8DHNGt3s6GW0k8u3PCHipeBapUB76TFNll4pr59fBk1chcrpFjtKw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MUU3SjUyUmN3T01GcjdL
        b09oZ0lEUGlMU0NmRW43MUtRMXdzOGltc3hzCmRFQkR3ZFhtL0JlQ0hZSHgrZ0RV
        MEtDY3JZeDJIMTZrNXdEdFAwQ2U5T1EKLS0tIElPUDM0YWdxL2trMkcyZTRiUGxS
        Z3FwRnM0RnhPVjZYZFR0OG9Oam1HcDAKDE8ln+/npG6XRF0IRuztg1wmdO7Av95L
        mj6f0ZU0TFHmc09G9o4Rey4i5S/rKhefE3BSnwyCFWy1B+TSVDJ7uw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV2JIMWdqMUw5Y0wxYTNn
        cHVFUktXVXdiUTFOOXVLZWRydzBMOUNlVmpRCjljUXJHamhqdVd4S01YTk1WeE1o
        L1hFbUtEakpETmNPZXhjTTRJTkdvaW8KLS0tIHJ2Q2xocFpXcGV5ZWlmOFJobENM
        V3dQcUt3MlNuVVpQaCtzdGYvOFJZRGcKKig3MetOXaR+gXmtwRhoWQa+iRnFjg8f
        vw+8rtCVfdpT21EpIDRWwXtibMn++Cmrh69+YqCDah8pds3e9fcBBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRGRHbXNwVWJMc1Y2T0tv
        YzlMeW9ySlovS3kybDFyT1FGbWt3V3lhNUUwCi9JNUhONXR3UEIydDFPL0t4MzJY
        YnM2SmZjQ0ptaDJVdHIvLzJzR204QmMKLS0tIHYyQmJLR2NMWFdiN2Zlam9XY0pR
        UTNmRDhsb0NxcmY0MGRzTjI5K0JWeW8K/hMXNNNwuWOzIgp0TCkVnAC6OnxgX/wS
        ltseRlNE2O0apeLJjLIzJBLlyQ7Ez/GaoTtVW+D8LeczgxW2b6XoUw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVENPRlY3dTN3V1k2Ym5h
        Z0FWclQ0ZXdmTVBlOWFLTy9DMTdVeGVHbTFNCk13SGk5dnBFa1kvMEJxNFBDRzFU
        VjNOSTUyL0VER0dacm1ZdXVmc0FLSlEKLS0tIDU5bUpsSTArZEpQVTQ4VlRqMk5U
        VHJSTnlVVjhxTDFwZ0FNMDFqUlFucVUKhJ6pQlLdC9snNgBvK1P9QE9MIg8mlNqP
        CP62DWAfuBEdXKfazZN2NmjaD3dGdr1bGgENvFOlJj0oL10ZZIgE0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOFhsK0hXK1pGV1dLUzVH
        K3NITTB3YmdZTVNWY0JiS2JhSFZ6Qkd5dnlBCk9XemJ1SDA1SklPVUxPWVlYOEdN
        SFhjY0xPRTUvQnpieUVzclp5VnNNUGsKLS0tIFdkVWUrbThHWGU0TWdKM0c2T2lj
        NHJBd3F4ZjN1b0NMZlVnRStLempNWW8K2xkhaEOGk0fAC94UrjAxivzRvmr0VmRw
        zhz/tuTPQpTAxPePGVV0omngpXtgkBxqtRKyKkfB9gx9KjGP3W3Jiw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:77dY7F1IBGWQWB34KOMCD9enGCqgtzKEEhI76acbBWnV54o2+u0rMIoV4rjfGUmP5+3aARBIyMuB1M+vBvh9tz+Zsi1LD512xY2AXyC8BIasaXWvrQctENtPtj+RUvPVkWTdl2fY0zw18pf+4kSVVlX8mfWY0s13MALji1JaiQI=,iv:i2qHOByF9Q8meM/WXcwD092UdjmYM0LUNXMLjxffp+k=,tag:2BUUrcuDWGEXoaS2sdQXJw==,type:str]
  version: 3.13.1
