apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "pi5-monitor.fullname" . }}
  labels:
    {{- include "pi5-monitor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pi5-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pi5-monitor.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.daemonset.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.daemonset.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.daemonset.affinity | nindent 8 }}
      containers:
        - name: pi5-monitor
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9101
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
