{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pi5-monitor.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "pi5-monitor.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.prometheus.scrapeInterval }}
      metricRelabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
{{- end }}

