apiVersion: v1
kind: Secret
metadata:
  name: planka-dburi
  namespace: planka
type: Opaque
data:
  uri: ENC[AES256_GCM,data:40QEU7K2nTHnwykyfRojg+8B+RHdBu2ld0qs29EJCISStBOClNzztvKpG7F9YPBt/5zPhjCAh3t8DCAYDYs6VOpWVUNtu/Yv3hPZfKOpwRWavUgf/n277YihJ6MqsohUCxhexn/BY5n642oTWSM5VNhhY3LHDiNB,iv:EZpFtzHxpkZ1OL46v3i3gKQi10MOtMcIvBMOhk6Ah4M=,tag:jtuFhx1SrKHH//1HzrdxJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSlZaY3BLUUtJUjhDTy8v
        aFhtSTd0VXVVcHNGUDJKN01zUzZOWEE4TDJjCkVYQ2tkZ08wL0d3MW11emZsOHd3
        ZFRwenQxeHFtMk03VFkyRklxS3lGQ0kKLS0tIHpLRlp4QnZvSE54bG5KaDJJWXRl
        eGJuUkQvZDVSUDlsRFB0ZFoxNUFoaUUKyuWmlMxYFbO6SMLlgiUaEw1iNfDbBcGk
        zvLvTrOxGDJ2B9nMm5S0Ke2govIJS3sJL2QHoLeGwDtRvJzggwkiiw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMmVOc0JHWm9NR1BBY2p4
        SHIxRnZYb2VZaXRqb0owM2k5ajRZYkVIUVRzCkg4R3VETno0cTZrWXFOajc2WFdr
        NWVDTEE3ZW1Majdnbk5KdUZvNUwwOGsKLS0tIHdxd1VBWjRGcXBySlJIVXdzL2ho
        TWFnYVg1eWE3cHd1VGUvUk9hZFRLYlEK57ereOG7wFpjS3rLSBBQS6EFcpYXRHfD
        /swwRItsj6Y0FDuqMuH+dNNUEIhqBWaX/73XaYLd1Munm7Eono2+Fg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVGdhU2cvU1pYZEZCSzQx
        NFdvZ0V3VEUyUTUwL1VaZ1g1YVB4QnNncDBZClNUVUdFTDdWbHBxU3NTOWFGUTRu
        VVcxTWJmZ1NQTmtFWlc5cGlXSzREMGMKLS0tIGt4aWRwMGo2MXhWSFpkSmNQMEpF
        Zyt0QW05Z1ZIRkMwMzEzRFk5RTFKMkkKe+7NMdSZAfhzZk35DantyKPeQB/goe57
        wc1XRJPq2T/FYlb4K6B4fRJHuHuFAAHq1C4gP0j9vj0XvfWvF5w2Zw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:jbSmb1s+PQTj7V9yrY+zgG4JIERlNzVV4me4PXqAZ1rhmOmZounBVrbqOLrcq5i/6ux5CMEFieoZABMYkooss7ErvaSiIdnt4nZFarLKDL0PA8dYvugWMOEuXHFg5wxbsD/mS1T/X/rzAJjolNlxkxiEDf5TByBPHYb1zXiMmqM=,iv:xlyZZVUu0TCz0yUauMqe2Misv2ehPZf1E/8zDFTGf8w=,tag:UtWYKQI5xiZBmkB9WFCj+A==,type:str]
  version: 3.13.1
