apiVersion: v1
kind: Secret
metadata:
  name: planka-admin
  namespace: planka
type: Opaque
data:
  password: ENC[AES256_GCM,data:YTCa4P5jhquaPhxLVzYJ3i/BVIM=,iv:wbe+CTET5drpqs4sblcsvYP6wWGVm+W/h3Z7chWq89c=,tag:0jCKHe1cqpdoxx5PcTl24A==,type:str]
  username: ENC[AES256_GCM,data:xzhYqqImh4g=,iv:qZdep6sjGYd+9mQ6kFSnCXbgzgoJouK/A3CmQ+kxba8=,tag:GVTLO1ZQXkTunp2RfPjWUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS21pWUZCdmdXWFd1YUlY
        dUF6Tm1NTFFPM1RZaUJhZGN6NmxLdllUanpJCitPTmJVSTljYXVMbXZHVFBVVXN6
        MEpSSlJraFFEbVRTWmJ4bDNRWW1JT3MKLS0tIDB4RFZEMTllN3ZSQlNSWVRVVmJy
        VW1qMWV0UGt3dlZMbTF1SEQrb0RPNWMKwnN1E/0WD2XbxnkInHNFY3Nv1/EgJeA/
        uNf7RuuzepyRoYrzfhoptrD4fg0pnjnO+DmIJY119rn/c2gEo21/Fg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWkNobzFWWGUxTUg5UWVP
        bXUyZGpNNVVWUDZGSE1iSVRFWDlvbXQ5U2c0CmVOa0lPSHpoZGdXcW5VdUp5K2Vs
        UTFXWkk2VEIrT3MvbUlCQVdaYmxOUXMKLS0tIEprNk9vdDI5bS9BbjVoMmdmS0NC
        R1ovd1Bwd055RExLZktKZDlSQmhtYkUKwsT8UY6IJYgP23AUoF31sjt5VfxLwqS2
        oLPz+STphNHhWtn/K6bkAHN2FeFvFjWIyxSbXXI1ZQ0W7dtyRNBfBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUkNkbWk1Qm0yUW1TWnhv
        Z1E2ZGYzSjU3VmdvZjVOekNuMHdRUG9wKzIwCis1amx3eHY1QytOZmFUZUpBcFdC
        RlIyckxVSVVPYjEyQ05HOFJrRURUMnMKLS0tIFZPbmlJUk0rTEw0cjI2Y2Vyam5H
        VHlCZDdXc05xYXlCMHovTUNncUx0WDAKyVEw16FUesknVswnjHQ5LiBmEIrH4x8f
        rJAcru2ATea4iZnaTBv9Yxa5LJDB6Y6SLCHqcsokYkYkOxwmQkcZHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:DPpRQcXG836Jw4OO/qoV6J6hyS34qyBI2z789NzQbUCAFLYY9fwJlVK+22b77hYeYcDM+8JCv+1bmPsH/XSX2Kp28tTrWdWqhTJ+JIm/7yHWAheqSsLWzfJldm6YDYk3Hh03OiLr3NsyggDwFESPRf3vSZKffT/wP89lU9isZMQ=,iv:5Ku9x/kA6EAQqyiDYZIWFPODicyGDrdo+tAUHzHlAG4=,tag:9bVom8BOq2WI2AarSJiHRg==,type:str]
  version: 3.13.1
