apiVersion: v1
kind: Secret
metadata:
  name: planka-dburi
  namespace: planka
type: Opaque
stringData:
  uri: ENC[AES256_GCM,data:FvIgxFY0VjxvFpCTMyH7nJEpji4dV6uAStojfWNgz4TRfGwVriNwiFcEJYLlYxxc83rbZv0pjQeSvGnEDAkDD5Y/G/dtcSgn/HXZj5jMe5UwqLfO+LfHqIcTnbYo,iv:T7XoFTWRmZXDVXNfCS4jBIVhEEguJLLsl2+zu624odo=,tag:M9+JevSxwXc5xHRNB8dwUQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTGxPVFdVWjhLeDQzaDl3
        Mkh3V2dyVmFsMFhDQ1MrNzVNN01oS3ZnaEcwCk1aNDhxR2lNNHpGV21PT2UzL2dn
        UVVScXZ4blc3cnVFWWZxMEFwTjk2dEkKLS0tIDF1RjNNWmhCNXRTS2haa25ZbFpy
        d2VtUzhNOUgrWWgzYUtFRjlSdUVOTFEKRMuS0m8gLhUpi9Mm+X0iTFHVNV5QmsqE
        ++IzAfEfJluazqdAqdGyL9Ymvv5qICnNGRWvERytIeoqmhZsC5Q/aQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT2xKbDkvMHR3dGR0RXRi
        cjJZTzRaMDQrOXMxTFBuUVZJSklteEZRUEVrCk1sNGtLbXhnaitLSWhoNFJPVFVt
        cHg1eEZjYVFKS1FTbE9ybis1RjdlekkKLS0tIFgrcjRDV2NVamUyRWcwNGI4WDZM
        RGVPUXFyd2JTcHJldW1iN2krdEU0bU0KXFaGNKAlfI+TvSolktcksavvvluh4b2X
        zVv7DSovAdYWUTpLQNxi5R3DlwUZw2Nf51Oi6no4xuOtMXOwuPArbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MDFDdDRjdlpRSEI4RnBQ
        eGt6M3h6dy9EeVZuajFiNzZtQS9zNDRBSUZZCjBTR3cyYml0QUg3VTlPbFlualdw
        aGFZc1VDaUFVVnh5MlJjSFIrTDBvalEKLS0tIHJTNmxDT0F0eXJCNEc3cUFYb3pE
        Mm1oaFFqdU1sQmJmT0tUSGFTQkhVckkKZbPj85iodvRxudQKHPjsIbtnFd/glQ+O
        xWHA/J1zJKpcoC53NKyqY1FB1I7i2YM78z2wuWBL/w45Fa/T1Y1hdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T16:26:52Z"
  mac: ENC[AES256_GCM,data:tGGQzg4rKfV/7H1r1BtH/BX8kLb55UtVPIouZLW6doiVhbL5q6yt+YZKE72sQ3LHEisX6nUXk/xRWrL6FMNUoWUFqHBgfeqFTF9Ha9T2PZ7IBLS6obrN29HIT53bT/fziLgLk57yWfbhuBIjx/0KEUcZd6Dyj3CaMhKj9UMTbII=,iv:VzXjGcVyN9ieJ5zj8up0Kv3BBp1QbxlAhgn3ZC4WKnI=,tag:Ql8nJ3/0wcgO38ww3UuQBw==,type:str]
  version: 3.13.1
