apiVersion: v1
kind: Secret
metadata:
  name: planka-admin
  namespace: planka
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:4CcfbsA3RnTSpF2WcDs=,iv:pC9M6mISjFK6x3G5NU7XuHNoCmBpt1iyzOSfby4ISvM=,tag:NYivUOcJRzyoUCggM59o4w==,type:str]
  username: ENC[AES256_GCM,data:vcZxh129,iv:jRdKZ0YGG0L6PxA5m9zWEhLVLFuzHFE8J5ZY6h9PqrI=,tag:AgS1n9KlI/z8pw7Sansc/Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU1pkQ1g3K3RKL0NJVGZh
        Z0JQZVIxWkN5aU1yWDBKa0ViR3dSdlA2UEZ3ClZQUU9qTmd5b0dVVlc4M0pBMmtV
        VVBZRUc1bVRjS3p0TTJ6eEk4N3ljUzgKLS0tIER4VUhocXpDVWNCeTNTVVU5K2ph
        UUxEZ3NmY0xEUFlPY1U4RHh6NlMwV2MKygb25RhaHF0fM+UD0YyDJYSrzI7/9mQe
        h6JGbWciX9PsAA9DJT3x6R/EhfTFdTfgwTVNpgJR4bjPgYMKq1Q++w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJamU1cU9WRHRMTTFBbE0w
        TThoZmtxUmcrdXJoUlJOTVpVVjFMem9yd1FNCjRQSTMzb0hVTmorUHcyaHFLNEdP
        ZkhIZFpIalBwb20xeWRIdjlSckFta2cKLS0tIGhLcG5UQTd0UG9jMkU3dzZucUFq
        Y1IycW1nU09CVnJySkI0KzdsaHg1TmsKbIwdNRFJ1GYhoKSIrsJmmgAHw5o8SloW
        jgaWC1A4PyqfVm4wF4uGJ0DTQKyTud5hbSEQ7q7q3S4KvffFclTqug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NlR3Sm1WdUxyS0lnRkVP
        SnVDb3FpMFlHSklhOGlZTnQvVHliUzlPK0EwCjZKV1laSVpzTVBBeDlXR1AvZEhZ
        aFBaUVlqdmVGT2pJVzZscWtnTktYN1kKLS0tIFRjY0hzQVkweFN4UXgxN29STU5D
        UlFyWU56ZXh0ZGY5L3kvK0Q5OXp5SzAKu7CTo4s7pIcmBB3WVfeFsNCOlWd6BWqo
        UjhJCkB4F7ITWvXfCJRMczB1to3DOxB7HEtftruccmN2TzHPB8cLTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:4bUi94VO63vW0DLS4PVeKs3C12cpkWU7brUD1x8xVLDijEwGKBFqrntSeoYRadXwrldAdgm6diB5HRG+qWTX2MUKdksYaLusMd67CR+e7OZS6qBpUuoi8/QwViMl5+sg5bkFrHg33y229XW6+qF70qhG9MfoPm3oW0IZ3fOh5/U=,iv:ypwzx8aR0rNzppz9nBWIzvHeo1l9dNf55MUTpiQXLFg=,tag:xwC5R6RoOGlGlVBp3g0Dsw==,type:str]
  version: 3.13.1
