apiVersion: v1
kind: Secret
metadata:
  name: planka-appkey
  namespace: planka
type: Opaque
data:
  key: ENC[AES256_GCM,data:P7gjoK29sFY8jC3faIMmCqJumBuhHM5EH5SO2H3gAJAA70Uct8R3iQ+wlWWMT/NkC11Q8YGH/1v7+vFjhBs4Fq1sEtscYU4Utjk68M8Zlag=,iv:oMIII0seFsW9yOxwoY+agZVY361OhPF8AmmVUAEpplw=,tag:VaTLRSE+8TwEmZ412WRctw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5b0gzVTM5N0NCeDYzZDhs
        TXNWOUV3Z3lLaEVXdHlzY1BBRG1FVTE4RUF3CmU0TlRpcFMrMGF0VFZGNFZMdTRa
        RmtWeEN0blM4cDkxTURxN1VBekcxTEEKLS0tIERhT094ZnB1QjVXLzdXOUFQWU5K
        dFF6ck90MkZXbUtpeTFnK3FFN0pEa2MKPOu0sxlQOXE8jjwx+arF7MFK/kMwewyZ
        9abX9nydsavCbwX4+6Sn9IETHbeZCmSjQ0Zoh7VLwUR4dGrMdkUpKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWnI2YzBHNmMyWXppWGdO
        d3ZEOE0xcmtneHVDbTFwYkNFektMeG5SMlVJCjAzQTBhcUM0emlIMUM3ZXpodzMz
        MXZLRW11TldodC84RVNiTWk2dkFUbm8KLS0tIHhtbTNVcGxaMmZYY29kSUFNUFJ1
        MHA4NU1KVGRCS3Q0eHRBS0MvejNUR3MKywm21hFj5sLFosRO9lSwOg0H2Lg4Mrsj
        bK88yc1L2SZbZEUcTqi5rRwb7oKFHK5UGP95VIfR61ALDx/hTkjmew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUmExczlwREdSci9Oc2dS
        allZWkRKKzdPOEhFWXQzekFLNjB4OGtCWFdJCnIvVE5QaTlYcEpzdGpvZjJPZGFq
        ejFSdjlkdERHU3Rwd05RYnJDQ3dRaEEKLS0tIHJjT2dLYTFmSDRLT1RQK2xPajFG
        K3hXWStBUGZIVTBhMnB6cDN2YmNiZWMKXFz4XtY0KvHDSXcKvu+Nqsb+l1iNMbvr
        XzGhoozoSmwGVhXeM83mxkUuAXORUF4TKHRI7xqMp6H/rUR+PjtZkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:ppHFvs9fXOWoF+KK5Zqz5mph2uWKwcaljU75bdoFi6NlxG6xVcLbjFgBVZoXP+t47nOeo+GmmVDQaZUpOBAHLmMQOxpBrxLv18mCsf/xISUz+VGQo4UpYw59IWwaJh6Z+2bEYfWzVEH9Ydy8J1soRHtHCNdfW5TrpOPgvb0Ncx8=,iv:GyTiDSivjcUYiyr4KrHd5oVw9Evk5QmMUj5mWVFcm9g=,tag:g4PUH1AT9CYmTJ8jvdLV0A==,type:str]
  version: 3.13.1
