apiVersion: v1
kind: Secret
metadata:
  name: planka-appkey
  namespace: planka
type: Opaque
stringData:
  key: ENC[AES256_GCM,data:uZlW1eZMXsM8gMVS5/3xLr8yMQjypwcqRJn7OQfpYt/1aJPF1CdWvnX67ksSASyL7vzZuQDr4KRzAevK,iv:vvxyxQU4jm4VsxcdZy4ffhJMgftJh7zGYaB0ar9zLxs=,tag:+eZ6CdrqikZtoZf3V3jPYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6anVmTFU2Z0Y5eWpIZGdo
        cDVjS25BOS91bFJzY01yZEF1VXFxaHl1a0Y4CndGZzBxUDdiRlFSRmRqKzRVbUIy
        VityV1NiVHFPVC9MVUZOdGVKV2RURDAKLS0tIHpIakxGclVlVlpqVDR3N2FpWXJM
        OVFGTEc1NFZlWUtzbm5Zb3RQMU1vdlkKx79CwWQjflwhKWGIXtv3w1sQ5uEA4Ics
        6lRBtYqGbE98i+1dF5ocKYPyitj409V+vzl0qIq+v07lIsDoH9Focw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTkp0KzlRWi9QRGxWTUFj
        MkppdlhuS0JLL3k5cVZ4WHVzMi84SzV2YXhrCmphWU9LSDJsSVZndjlqeitaYnFj
        UmQxYnBiRUdLbjJRZXgyajJUdExNajAKLS0tIHNidTZaZHczcGhrVG5rSExIMDR0
        MXcwV05YU0RFWGxzbVVoUUZVN053ajQKghdnu94H+zLf1yAnnpAoogl3CfneHCvu
        FRMKNfiQW9DOswcyhZ+kac7qeK5GOBnXKw9pkm9GrBS9DX6/vn4VEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaW5SK0MwZWptY1lHSVpz
        RTd1bXBlUlY5OHZQYTF6dittTG5Zc2ZIS0gwCjhKa20rWm5GZncwVVcvS3d1MUU1
        c3pad3FTNGJDYTFBZldGcFhUSmRGSkkKLS0tIFQ0TTJRVEdxSFd6SmNVcWI2K00x
        MTNldmxyaHdYZ3VnSnAzRW85M2FFMjQK5ddl6d/SP3QLyuVHGZuKjb2ZHv6F+far
        o5s0BMfl3UyOsZVLbRD1cU3ey8TBMWStQL3O0fs2ANycoMQljdrBkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:4tMVEffznfv1Y4pE+HwiFp06wey2dFeEgp16aM70hCIdn5f1EI85/HymKph7QM9MEn2wn5HTztGdiIxsV1lva6v2Kux8QrEmdPwZQUG/9U08w9lkfkb8Fs1yhk1EDqYkukv+kactYk3gjN2OSDjc/9DZYUOFPPeHZzzjTtcBM8A=,iv:aaigdJadsLGqMCCYcV3EMm285qNMrs+ubWs4llJzl5Q=,tag:dyvbqbblUapREanZVb1cSA==,type:str]
  version: 3.13.1
