apiVersion: v1
kind: Secret
metadata:
  name: planka-password
  namespace: planka
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  password: ENC[AES256_GCM,data:Fa+iwNR3952JyZPYNvFfUP/jDyhhz+QkaQVR22rzeV0=,iv:E7qo2H54tihhf/+PlU38u49uDDVkD7K9Jl9JUdkq2qU=,tag:c0ivfme6spZhs8BC7lQlCA==,type:str]
  username: ENC[AES256_GCM,data:XFWhCNF5EW4=,iv:EYWExgrFVu2Qu/oL02BjeuGCZ7sVzv33DoHMh94oeNQ=,tag:soHFvR3cjkN2eOqVenpTsg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNakt3ZDc1eFF2VkFpQVQy
        RTRNSjRYTENWSDJuRmJGSzU1aXZkekRyMVRrCjdrQ25BeCtuemVtR1V0L1VNcTNG
        VmlwcHpnS2FYUXg2ZW5iVTFSQ3Z2ZlEKLS0tIEp1WVgwbW8xNFZUQitTT1d6WjRw
        Yi92cU02UWtQQkFBUGRQWWtSbVkweG8Kkhu0qIHprBwwesHH6THZjxVwflIYDfy6
        67FAQHFvz+uVaLHnAZCZaIXX9PhVvkocWpSHtQaEXxhaDJF83Ls/UA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU08yZ2hoZTFlbzhJUlND
        L3l5SmFCck9VWk4rL0laZWREMHVLck1UakNRClNUcEFXbmlJdmtIelJQWmEvY3hZ
        RSt0Z2xWck9GMk40ZE1FL0x4M2dqaVkKLS0tIG9DZHZRU2YvWUdScHRTNDQ4V1Rx
        bUFVdEdyQUJBK01uOUxvTXpFZjh0MlkKaufM8qq4ke52ftAuBZl/U30+9IvPBezz
        LxLllb77qXbgcfD6HQv3SdMvE6UfU5JDoGArMEvbi6XBWNQsxdbFFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRXI4MmNNeTRpS3VOeWdZ
        U3BxTlY1TVhBRWlmekx0NWRqRmlMRlN0dlVzCkV5bEZxekJSRjhkZXFSVzJBNEtR
        M0xDN3pLTGxFbVJvN1pyRkdFTFQwNGMKLS0tIEZVZG1neGxpdityRklQVC9NUWVF
        NVExQnpnWTB0cnZBaHI3NFVCWDI2dUEKio9396Wg5I1lCA5juMgo+omxX6MCNnqn
        VtXQRTAzgICP0erQhQEnxb2+L6coKKccCEK6/Uyt16V7VHg34Vktlg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:8rc1LVBxA3v9REfglqwhqIYJbdUAuGyVT9rl0FctJEZYG4ZF1SjBv6LeXLO+G5hLudJyAMu3UidjAwgaWkeIZhPTg/lbo5HXz25r+XKb6NBKHitv5UyVBlC9EGU4mVkG056owoh054YCmHlIt7QTe4X+JSHKLGlSc4qvi1TRcSc=,iv:s5V58kYYMvThpa8ID9vm78FYHvVdZiePDbaGSpOUFEI=,tag:v3KjTtjLQCh0KHQSsWXIjQ==,type:str]
  version: 3.13.1
