apiVersion: v1
kind: Secret
metadata:
  name: planka-appkey
  namespace: planka
type: Opaque
data:
  key: ENC[AES256_GCM,data:CzZOR6jRJekb7JBMkTkzBo2tR1FnaALBK0uxcFpiKU2cTFFU5pRZaOjSsJFuRhc42B4C2VLhz1N4zj4FDEisjSZxbgE2I6lQVCZurwrNxIc=,iv:6UZ49ue5v8SLACTFz5tQ8nFckcNx4ZWpVBmU+CBg9EI=,tag:xW2TZknnUV8FMWABbBrNhw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZkgxNGFKdlR2YUdRem9N
        Mld5RjZ2ODZrSlltNEtKSjJ3VnZHYjdkVUVVCkswVHVrZTlYbndtU05sQWp0T2pI
        SFBxZ2sxRExKVEZ5d1NSTzg5Nm11UUUKLS0tIEIzTHgwanhqazVxMWJLaWp5Zjc5
        ZVFxaU9pYjBQc2Iwcm13WkY4dlhEazgKhr4MQw/+CwJBXUUxk7W+2FDSwOgs7aG1
        kekfe9K0/74EdTuWg1wDQrekZ1rOHPSp4gFCgtM/AxrDTqq30vhDjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5a3lYTS9GMWNiVWJEcStj
        cmhWUHBSajY2bjQ5dGpweHIyYlh0WU45MjFrCmk0L0lWRERvSTZIYzlUS3VBUkhK
        SkVFSEhsNmxIalJLbTI2Y0pQdDZ3N1kKLS0tIGdLNXpaRFd4WTF6Uzd4Z2xTOXZJ
        bWxuM25FWVpsSWFxYVJsY0VHbTVHUUkK7AOWNLhFHAfomc0lRC3y2SpYFTg4ZCTM
        CLHcya3vZsIig/NCdGkDgJD0WGe+OBJ0aXQt4qK1HVI8QwxD2NVqpg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNTdKbFBLaWZBcE1CMUh3
        ZzNjYU54M2t4dHB2dnJKakhGdnlTaFB5aFVZCi8relo4L3Q1U2J5MzYzUXVmWjJZ
        ZGNYYnFoVlJNeGZVUzJGMktob0c0U1EKLS0tIFVyb2x2ZjhoUGVySXk2OGloeEhJ
        SlNnenJrS2JRTUk5dmNSRkl2bHF4WEEK/+9y2QI8TyBW/p+H2vlieHRP0WwGHg4Q
        dDeL4OWfxSBSRh/WPinrecMjWeejjePwZhxuNwgiezpaWgwqfCkdxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNkxjeUNTbXZtTzJkNEtN
        VmF1TFc1TGtHaGIxZm10czd1K3B0bkhzVUVnCkdwUWxFNWtLUVJHZVBBdFVlSFN1
        VUVDOWVCdWErZSt0ZjBsRmRhZWpqYk0KLS0tIEZNYXRtRHhHcjdXbmIwalZHTWZq
        Uno1SUEwREVmWktia2NyWUtIb2s3TjgKvCkNFE+6I/1cfthQEEPuKFAmoRgPcA6W
        S03mFSt6urGQEJnzx7NIoAXGnFzg+NX6Vrur0zN+8CF2BSO9E91Q5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLU3N4eU1rRkxnU0RsV0xF
        cy95U09KUHN5MWhFbTBydlFuRi9sbUdhL2tNCmUzOTNZRDU3UmhjRHdSTVlOTFVl
        eUdid2dPNm91K1hpd0g3ajZVRmRXcE0KLS0tIFJaK2czakZoWE5LSXpuNTBIejY1
        ckdOTzFiVjgvQ212QXkyb1VMTGNWa3MKhLrBp4jIMkGkxhqsljKYJ9P+Np0HWDDo
        HgOpIn5KuTiFrqsEF2aw5htJfDFg+yQ0C/uTygObpTYcRuMCHBdHsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUmUzSUFva2h1aHZ4SHpv
        SW92MmlJeGg4UTlOS0pIM0tiZHY1YW9KR2pvClQ3aFZCM3RlSDhVUzdGVjAxN1Zm
        N0F0SlY3d04wdUprOEtjalNBblhuZUkKLS0tIEFySjZSTTgyZHNmeGYzWWtGbTNN
        OGk2MkRtRElNdElVUERtOGZ3NVNtbHMK5LF2wWjCw59JssGDU7cqBeMA0osR1fc4
        cLvQfV9HvFgBKxwWohm++CnzXRzKeuH+9LtczkkdSY9uXhszJihy5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvazVZcVlXbnNmV1lnM1hy
        dmgzTmpaVWdYWWR2d1Q5MzN2M1VuTXVDSEc0CndEbE13TFU2K1U2TFZ1SklNUlla
        ZkErQzMwZTB5RnljUFlCdUFpRTRLbTQKLS0tIHRwT211Z0w0V3ozSFJ5cW9UZTBP
        ek80b2xQcU8wd0tyUmlKU2I2SmJuUVEKwkm+w3hSQ+QQ7fL15nubcJcprivsuAE/
        PuRblxuekGd6YyFdiNXpVG1boVJPm41+n2EBT4vptkJJIheYOhHr7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZGpwRm1kOHdLeE9vRStV
        ZWhCanJoT09wWkpGbVg2dDlMQVJzZDdwYXhnCk5mT01mRnFsQllVWUtTTEllbFNt
        YkZTbFVxQkRrZVhpbVpJQTJ5WnozaWcKLS0tICsyUUpCSTIvS1pBSFJiSHpWWmZS
        TlZzNUxUYmRYVURMNS9YTi9tZjN0MnMKC9qlCVx8kjDNP4z4JPqd6YBmoxtEJVic
        HR3YKdRpzHmXko3IBA7Jb9sfBIAhbRZCq0ejaYNKX9XOQfX0aN/qOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTm4xbnlucmlmN1VpVnVZ
        ZnVPL0dFYjZxbFM5aFkxZzdwbUM3RDE3RTNrCndJTDcyMThhNDBjMHplY1ptUk1C
        R3lOZDZvcUtndldWN0E5elREL2k4ZEEKLS0tIDZWRVlmWlM5Yi9YeTF1aWdNSVVi
        SURjaGNFL2RuTzhmTG13a2cyYjZiVmMK7KZP210nR7z2tHBC0svbmeXX8qFe+TAy
        /rKT0Nv4C4QU03W5atseKuDH0U1BI/K3YTJexaenEZ/SQAwoACz9Ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTEFqVEFKZ0V5SzBGaW80
        ZUFMVFNaWkZTTUZuM2VQU2ZZRHRCazQraFNJClliZFUxNlV4UEEvbVlTQ2J1YWFn
        WFY0SkdCTmFNaWFtL254Z2xsRWpjcE0KLS0tIEUxbjdWUU9vU3ovK0g1WWRjREdW
        RDNUdGxSMEp3dkp2c29WYUhvNGZUQTQKsCHOIy4695O8uy/stjT6NXhNH7wabWB0
        CH1LtkHNWVyhVDI+yEbFhAkkJCTqouiivfKBrZTHJedajs9lwlJp2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:bY+3++920DVR5JjHQJwMQ+d4sEkdysbjByP/WCEUfYUeGUgIZlP9c+/8nsCfwM7qsBx8EwrACGQ+CPEAI5e2T85zBZOyH5mGSrH5dofF8Uu200BxKJLXVIdRxg6SNod46H4a+lb/D6CRuOWm47k9IefDhzCHWNN/j+X4yBn4PKM=,iv:8VztMqRAWd9pDYUiUmTProQ6QOHKyETcCJ/HR/H0PEQ=,tag:+iKDHQ1turgb505phig/Yg==,type:str]
  version: 3.13.1
