apiVersion: v1
kind: Secret
metadata:
  name: planka-admin
  namespace: planka
type: Opaque
data:
  password: ENC[AES256_GCM,data:asYVMHt0Ekqcl23AuvAz/w5N/dE=,iv:5GeELvGC8ra5xGece1J2GXe/SFECc/FO44JZSSRgyA8=,tag:6uuuuqhH4TXCjqKNqIrcYg==,type:str]
  username: ENC[AES256_GCM,data:vY1IOLZeJKY=,iv:hLjMrUtAlpN8fipGQx4KqNiksPiNh7qWQEU3wOqcf0Q=,tag:NUkX7sB5nvNFMGRn6d8YBQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbjArTDN1UDlIMlhGUkVO
        RU9WOHVVQ2NrRis5TjRVNzNXRnVnRUVqaXhFClNYdytZK1lPbTJlWVlKa2g1d3Jp
        OVRPdXVGcVhySi9XQ2pDNnNRVVE3RWsKLS0tIEJ6N3RjMEtyK29TUWRZZ2ZpK0Fz
        QkFhaGlYMDJCNnd2RkU0Sld2WWFyemMKpLZfke5e+4XeW2ONcAVMcqMjWEm+lrwH
        qLeP3zfVIaYo3toVJWKTBPsdbbK4JlFBneS3/fbDpDysvHKqwTjUjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VTZZNnpYWG42bXQwYWh3
        bzI0WkVDalh3WlZaRmNrVkVScmV6elp0VFNRCkl0SHhrVTJrUDZ0RTU5V3ViSjR2
        YkpWUG5nZGJsQ01waDdMNUJYaXhwSFEKLS0tIHd2NDI2WlpTSFZnNnF4Zk50eWJQ
        RGZqOGhXSFp5cEVqYTd4MXlWNUIrY1EK3UAch9Pi/PJo2L1rzqVw4J5lrWprcCOX
        poJitf3fESUylltqS81pr6EUoH6RElyd/5hKDxgXUqhx59E15hdI/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUGtrRTB0VkZ6Q0dPVm1C
        bEYvMWY5d3FCV0ZCWkgvVm4wVHNwaWN4TW1vCnBneGV0djRxVFVLU0h4c1JOaWFi
        ZmZYdEVRd3hhWUdvTm9UakROdjVqWkkKLS0tIDZrTU1VOFZyTTZITFFPREQ2Y2pz
        aFFiYTNocWlTdEpvYmVSOGFlNm52d3cKkDOB3jPKavp0ejRRo8G76SjqqO1SJRfm
        8SIIWK5IKd+fo56A6yFaQ+D5awxMyaYx1hGSHiI7up51B4rj4+V05A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYmNScUpMZWNyUzBDdkpS
        RGVuZytmN2kzdU96cE43a2tySGNGUm9Rd1JZCmwveGJmYzN0clB2dzNhaDlQTVQr
        K29xMWhYZ2cyb1NVTThkVVkwYlQwd2MKLS0tIDZ1aFpaeU1BMkRaRG9YZ2FaVDBx
        ZVd3OHVleXcxK1dCN0lYcHhHSHhBbTQKVxQP6jbi+3cZz48H8jTbVFcbBifef79T
        19lXiUWURYQoyl4NkomyBsVVKkkVvXF20mgWzr5e2ewo6dnaju/HFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbzZCYlh4V0tUQ1ZDcGVu
        S0lvV256UlYyRmROVk4vM3I4eG9oWGN0OHdJCnNiWXlIWVJPUUhHM3BpQlB5MmQr
        YTVqNXVPWjhEYkRiS3Y0Y25WenRuVXMKLS0tIDQveVFTVWtFVHJLV2JBcXFTZmg1
        Tkp0bHBXZ1NqLzB5SHlNcE9hNFRscEUKVhsyrqJ2RsZ8hv0Wqd5GWKo+UUs1CGZp
        wBnyHt/C1MeRSOGfM9YuEn8u6BZMUh8EEXITMr1l8IeEqyBusKTZ/w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTEVVQ0RJOVJuWVBFaVpO
        d2FSOGZEd1lYTFNXMlZ6UjA0UTJ0T3BIQldJCnJiU0JRVHpsUjV3RndvUmZyc0d6
        bFNvVERtWW9oaWo1QitHazJiaFRtQjAKLS0tIGRkYjk5QUZtSURncnliQ3ZtVDAr
        a2ZmV05TQmFlOWozYS93a3R2eTMwVW8KsncAz9ulbfXlViVPXxJDJX6KN8EIclrD
        q6282T71gb3T9xGPP75OewPGMuXOqNxfCvUFev+XXwWseWHJ+nqVjg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS1NVa25Rd0NFSG9uYkZ3
        VTNPSmtJYVczNjh4bkZGZyt3MjF5MXNQTTFJCkNLZ3c1Vjk5MHBORGRCSU1DVktq
        NXlxZTBuVDlaSlRQWlV3cFljZTZZTFUKLS0tIEZudGdUdzBudk91VnpadXJCeU42
        c096NkJqejVHZThnMklDSVBFaUllN2MK7nao8MrqTU3zY8BKkcw8HWE1CdYsArg1
        dE13CqzfWlXGx2qx0jwXSB7oCeK9jf2CaVotVNy8HPbUJpTsbehr2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzF4S2hJbnRETkZ5TlM5
        eEhrMUI2WDRRbEJRY21XcVprNUR1Yit5U0VFCi9NU1RLcUNpMEJkNUdzN25RcmNR
        ekhqWm12Z2o3eXZ5UzhYcVBlL0NaVWcKLS0tIEd4b3JDY0xPSjRxMXNEY1ZIWnVu
        S3I4WnQwdGorOU52S0xibFR0cVlDYTgKeudk8sd0Vt9T8PqFJvmhfY189VnLjqI7
        8jmNajH1ZPzvQviF8IdFdyYox7xZ+jrF5v82mj4eHT4c5wkFVRF86A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMlN5QTN1ZUlxa3laSFND
        bXZhYUEwQnZDY1diRUgxQnBueFVFUUZINVFJCk83Y2ZLbjBER1pHcS9SRExLdVFZ
        NXFmaWlEZlc0UmVHd2NsOHJZNHlEUzAKLS0tIDFzRXhHODVWbkJsaXdBVFRnQS9U
        WlVobDFIM29YaHBUTS8vUEJ4U0tRQVkK11Xo5597uezGZfuaUG3ztFhtPSVabTAd
        HJg/dvzXMLZqbT+3X3+4DYoJYEmhSL4JsMgv8gWv8lz8mjOxQJZvpw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNWFaK09ZbTM4SlRYVENq
        OElBLzVhYXFKWTBhb2VVK1BrOURWUndBNWhjCmRCNTlnL1JNMGVDTUtxWXh3a0Ja
        R3ovOXkrVUgwQzJPS1NORUJhVEg4bVkKLS0tIFZSWVBodnNCVTZ2cFQ3ci9KNTVz
        NWVRNHQrMExWckpLNzB3RlhoRDhtOTQKpJTfGjl36tpzfQUsKJtv+dCjXYzKumSc
        d20qLkq5On/i8fM07WAYZbkcPqFLDoUG9j5T79CEKlPUqnHGUyuWuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:kES4szRilPCEbRqNcbr6XJUAXyO5WBCgVKP8qRx+Qvbz3MMcTKJrcV5+3iGwgMrY0FbJ+Yi/6emge/8wWDqShNpLxTwFe5/fOgnoCD46eUJlV+s2bAyA0ecD/stAP23Uea1+3GPCSqIASAfTt5+BtDDNurUKQgrrYkYaNY1g6+o=,iv:NYt/DkG3Y6pdmjVPuqQLz8nY42oyc76xzkf8Zvp2Ivs=,tag:Vmv4093DMMLr5IEf3TR0RA==,type:str]
  version: 3.13.1
