apiVersion: v1
kind: Secret
metadata:
  name: planka-password
  namespace: planka
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  password: ENC[AES256_GCM,data:DBV5j7xzkJxFWIU6LJwQyJ3/DOveflo7,iv:0iSqDYCEZnE38DWswSsIHAiG7IzvEJ4FJsnB1Z2x9Ss=,tag:/MfRcQBekVKFaqORm7fWUA==,type:str]
  username: ENC[AES256_GCM,data:iy6SbzhN,iv:h/0QXKfO8FfKKPkD5t6ZFO/dJqJ6bBm4m5wteG9yQIg=,tag:QJma6Zqkik04MhVh3Bqvtg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwek9tRUtJaVVzeW9Qb1JB
        dWI1dVY0aUdDa0N1MnVQNGI3RDZ2ZWgzNGg4ClpyblNTSnpjM1FzTUx6Snh3aGdD
        VmdBQXV2ZmVXdlYrdUxrdTVHQkMwZEkKLS0tIEtQSXQ2QWdYNllwZ0dSK3FiaHIr
        OXFGT3UreWM3cHhDOU5ucHVkdXpJSGsKLsRgmX1dAKLnqMAjvYfrdeGSCpRjdU0U
        2/hEPoLcSVCG9Eby2MzT8+vLQf+z90S07gEEnfDX5C4MQrJeqA8xmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbU11ZGttQm1XV1NVUCsx
        QjVsbHhKWDB2c3h4bHlWdFViaG16VDY3WkEwCjhJMjZHVit1eUgxQnRqdW4ydy9V
        T3NwbjFhcStpMVQyZ1owOCtud0Q5RkkKLS0tIHR3VkszczkzcjhYRFZIaGR5QW5U
        L2UyTkszaGluK004R3M5NXcwOVdBMlEKtaPrExRmNOb0KNR7iCWmej4kts7R6/GR
        AGcXRKr6Rp7OvO4iIVRQmJ7GcXxSWnZZSupj4UXqcJRsuKfLAcC3ag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d0VEUjVJODFOZ0JBcExV
        MDZSTTJHa1dqRTZFNVBnM2FRZW1wVDNxSVNVCjd0ZWxOdmsxendNQkt0dHZGVDdE
        aHVVdjRBVjd6SVl4ckRSZlVkWGRKSjAKLS0tIGludmRlZEEwSTR0RFNRM2FWei84
        WG5lcmZUZE51UG53Y1hnb05UcDYzNTQK0WAWvLuNx28hEnX/6Rb3VNdikKZJeHwI
        PMDl5N8tU8xT0UZ98LwSw7egzzcDI7zHFv3ycFdLzlq07tRG4IYFqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:Vuv+5f4myJeUnpf0ElxI6TTlrQ2WZebeWKvjD+LjKm3qtiNxsWjmYJ+CRXW0J/f6kmWcr9CnO6MPvgt51QyVC7P9YMvLIkaJJ+cmGAFc1KEoTbmQEe6CqT7sawPmWYYefK/J/Y/jD8U0vmm67YNs2S+49HI7mFh+BlwblVUiNxE=,iv:C/3XUWxLVVZuMmfkLDeOefQpPlKEZVZAY9QR7zp8URw=,tag:jFcletexMGwzGGq/di/6VQ==,type:str]
  version: 3.13.1
