apiVersion: v1
kind: Secret
metadata:
  name: planka-dburi
  namespace: planka
type: Opaque
data:
  uri: ENC[AES256_GCM,data:CObHikRRrzC/j9kticpdH86OP8y1b6DewPHMFdVbAwFoIDP7PK+p8mE46mvFloo2jFgaqZF1B11IkMe5iE/EQgWOZr0lbU8TzF0w1Nor0YXSLcdmM0+kYoA4z7p/ngDJqqfX2MiVKrSeTdEmHFiXrZ0P/RS6v9z3,iv:Dnr83VhtmK+bjUrjm6SrYE86lfwWt07wcoH78JKX950=,tag:Ry7MVQJOJp008KdGnTVEKg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cG54VkNnenZBSlN5a1Zm
        T2xCU1R4ZTZ2Z09KcXNNZ2ZtdW8rNTArU1MwCkRwenhLdngxNldadmx3amhJRzRy
        eXdUa2ozTzI0d1Y4MzB3QW1zcmRJOWcKLS0tIG1kV0NNRFBicmhrT0tCYllHemtU
        SmFkcWR1MERLV3AxczdKZ0ZpQW5MR1UK3/C6KXg3BiN9TAhJ/WAz78mJiJZZjY9A
        q4eu6mNq8ZLDk0zGY2vfQp3nKUent4jwjHxkLOJgNon5OrL7hy588Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUno3dWIrQjNYNVdpVjZa
        QkhNM01zOHZGWlBIeTBNR1Q1U3FEcFIwdlVVCnNyVktVK1Rpb3pWbGYzcFdvODF2
        djhNY3dTQlFLRHhvRUJmRUx2SUpQTXMKLS0tIHJ5eGpXT3JmYmRKanN1WlVzVEtW
        YkFFNUk4U3BwNUF6ZzNDS0Q3UTYwOVkKZTxfUURgDTQpHM1MFcnrBV+wp/BmUk6h
        hQeVAABuXOz5367sYj2+3+/q14TE6ggpS/mFzN6n0G3G8GxszoLRbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc09OVnpCYWlDVlc0bE10
        ZDhXc3J6MWtWWVk0elZZQ2VOTytaMVBlSlQwCjNTV2F0RmdIQ0dLTnBXY1hEV0d2
        U0FhWExKb3RKSmllRlZ3RnJURWRjTEkKLS0tIHN1K25LTWN3TXBodzJKeXRxUGFx
        cWFudFpRMkVoQ2dXZ1g0dU9Hb0JoN0UKnSo0jk4yBVM+okq/QjZvxXnxqNJt3bHM
        7HPYcBm0Q6ddlZC3s8FvSP9eur6oo6aIYZQTUcGrGtUAFZ/uni1oPw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeml2b0VrcjVEWFJGMmg3
        enBoalBiVWF5WkszWlBvdXJQakxOV3hYSVZZCmRERVNqM1JWVkxIa3BLem1SQ2hJ
        cWh3aytTNlBMZ01mTWNUTGZZN1UrTkkKLS0tIGVPaGhMMXBVdjE5SUxsSm9WODRy
        bnFGVlQ2eWEreEk3c3dOUzJaVjBCNXMK5gu8Z3cJ+shSlcdzzR1KEaBCtyoR8PGg
        kvw7weAtFlBe5ztZVsudKKHH0jbr/ita1hKHWe1/rNCew6z8YRykSA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBULzM3UFBMcTBIaEhzTDZ3
        d0RoM29TU2dBL2lEWXFzamJoT1hKL2w0bmwwCk5PMWZoQi9jUWRBak0zeHRUN0J5
        M0dCZVJjZWdnQ09OVkRhZHNEUEFsYU0KLS0tIFV4TG5jVitKMFpYUmJyRXV5dk1U
        VWRzU1dMRTllUUxmbTJTRXgveHVwQW8KyBVpUfmO/N9MTfnKim0s8majCzpncegX
        pnj2pF5niRU85xb3IGAXZw3HQ+vEQAYzkoSX6LvZMmXC+ou2KhgF4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOUQ5djl2MXlGRUcvZUt6
        NTdCcmNxQnMwbTlOWVd1cnViMGx4RW41OWpZCm54S1NYNnpiakNINkM4dWxNQ0pW
        ZWJIUnFXRmdyWG8yZFpmUjVodG1FZHMKLS0tIE15OGlKZ1h6WUluVEN2M3F4RHpM
        dGkwSkFiQW94NHpodm5OSldKWldjR2cKcOgi8IFVdYV+XMPXyFdFWDwy70CfdjUN
        Bv4FitXI6HW+GkP1W2aFsvJbQczA0PG+9Kmk5wjSAQLQWdvt1nJN1A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q0oxWUZyZXJLUW1lVTR4
        dHg3SUNWT0VYeXFDbFZ1WStZcUsvRDVxV0NzCkFhQ0I2Mm51SElvVXJVUVh3T3dO
        UWdqMmNJUXFpZ2dTb0lYTGRkNkE2cDQKLS0tIGZKbC9iUCtQVmRsRjd6ZitpNEJK
        dVYxdFhXWGo4UDdBaGhCbElpdmR4bVkKIU7gMsEvo3FMN5Q0WIx1O+9XjWj6KQmR
        +D9YMNXFztl+Q8rl0g1HdTLMfKYfmKGBk13hwMan1KmEpDRfC9eVsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dHhUUVJCaVdrZmJZemFV
        dkUrUHNRRTVqNVkySkJWaTRUdjFaSGNibWwwCm5pWnVwcmF5UzBxSFN6SWRtZGls
        WUZwWkphVkQrT1l1YjZQUWVsMXl2SkUKLS0tIFZ4RVJhcXRnaGQ2ZUFJNVNUY2Jw
        a2ZVMk9Ba21UZnErUEw3Y000bDVoRmMKGS8UKYNOKpYfRxHSsY7oeB55PMhdRw9h
        MJMepGhU/6ohPmv5AyllrFhHuPzwv1rF+fTKr461pBv/6bHkCpLVfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc0gwWWdFNEQ1blYwTEUw
        Y1dWZXltZElTSnhHME5uR2xvQm1PVVFDLzBJCkxhRk9ucDQxQ3dWVTUwTC9lSlh3
        WjlFUm4rbHlhWlpTTzNGS2V5YlNmWW8KLS0tIHcvcUlaRHV1ZmhIcWY2T3VQcStq
        eCtxUHFRNTNCcW9MTC9SY0I1L1JNN1UK2TNb+br+vxDoaT2XLb9TY9yWRgPu7M/h
        8ELggrqxBFC7dbNgeQwP+DD/qLbS/hiZwi8Dc2HpPogPc0yxYDsOoA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bndDZEpYUUdnL0tZTng0
        bjBEZ1BUT3lYM2g5bzNwQTJiWWQ5Mzg5M1hNCkNCZDA3OHhQSWxaMllsRE01Y0dr
        eURrelVBcEdOdE1rNW85dkkrNWFPRlkKLS0tIEIwVlVoK0RCZnJJeDE0UGEvNGsv
        SmNUSmc0U2ZoUE1veTFGVko5QjVZb1kKwhQHmycZYGgALn6c/M6g/oo4bhFwCIjP
        o6LNSaJ3IV7gJnFfVrWRjJQNRlwDDvD8y7JIRdl1mNakaFUfJT0liw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:OabL7KbH6M4YIudq4NPe/LmlE4qjqrGcO+J2Y3mlVxqJW1PQCON+eq9MwDf/KWxE9x+8cJXl6huaoUZgjgM2N9V5u88wnRyr6Wu3VJWOiwFrZesmiBrFBBsq9zbb9+PWpaeK8tZyLeuZ/L9D1XDZgoDYSgtSbM0w4gmak5KeWoE=,iv:tBt2vB0ZwX0qc/yeW3spCykM/9T8dPHGr/vkNykqNXk=,tag:dLLfT20PAlMs09xTR3y8Aw==,type:str]
  version: 3.13.1
