---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: media
spec:
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: immich
      # renovate: datasource=helm depName=immich registryUrl=https://immich-app.github.io/immich-charts
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: immich-values
  - kind: Secret
    name: postgres-immich
    valuesKey: password
    targetPath: controllers.main.containers.main.env.DB_PASSWORD
  - kind: Secret
    name: immich-redis-auth
    valuesKey: password
    targetPath: controllers.main.containers.main.env.REDIS_PASSWORD
