apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yaml
- postgres-immich-secret.enc.yaml
- pvc.yaml
configMapGenerator:
- name: immich-values
  namespace: media
  files:
  - values.yaml=immich-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
