apiVersion: v1
kind: Secret
metadata:
  name: postgres-immich
  namespace: media
  labels:
    cnpg.io/reload: "true"
type: Opaque
data:
  password: ENC[AES256_GCM,data:QF6eUkgJav8frmIbptiUFx2cJ+8KjIcs,iv:3kZJr0gjyykfjH/5Rqk8imMxXMvqlQcioL1OcGwP4YQ=,tag:DHI5NajvW+x0Dh5725JxWQ==,type:str]
  username: ENC[AES256_GCM,data:hm7pWfCUsxM=,iv:Qato1s7TP6KskSSFpRts+ypY0uN+tuBY0T5dIQP31xc=,tag:rtOGh6NvHNq2I4/x7LdDZg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TzRHTGN0aHdjVDRFVHRa
        cStYODNzYURFV0ZZQlVGRGIzZ0lYT3RDZ0RRClBRaGJVeEUzaGF1RkExS1pOajdl
        T3M3aEFKbzhoVE5iNHBEM1BXQ1VSWDAKLS0tIEZ6aFFrelFKYUxXNG1yU1YyNTZL
        ckl5SzFQNSthYm9sVXZWc3JwSUlSQ2MK8D9sqzqkUDchuAvSlt2E+nKpjbl9a6wM
        7tdxEuzAeDQugMcZw0X7PPWd4Pf6eSKHgwElEp6hJtIos43niVv8uw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRnBINXpRcFl0QW1oaE1Y
        b010WktuTTZaT0N3NGw4NGpWOWZJcGxKOTFFCjlJMTNMM0RaNVVqaWtIdGFCZU40
        MGlyL3dWdFgyaXA4aHovdWVqQjVoT3cKLS0tIHVjMnBmNXdrSXR5M2h3NWJTRFBN
        T3lkeUpGRGtKQ2VlRElyYndleGZXVU0K1aCR55vjVGGSxazfPWBYgH+iREF2vHdv
        sduPmnqqSwjq70bAPFFxTTN7ZKpEvNyCbZ+uRjmuBxo2FikVzotjxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQ1ZkdDNLMmp0VngvWTFw
        TW1NbER1YWtsYXR1Ti9yQ3VzL3QweDZ6bHo4ClNYdk83andGUE1oN2M4ZzIvanNH
        L01Hc3FqL0g3RzBtVVJoZzRYcGZIcjAKLS0tIGh2YW53V3B5TjF0dE5ack5tOCta
        TGptMVhRYXRWK0wvemhzZVZJWkZ1N1EK/P0J/1qhZrcF+KXp8G5UEUoQTz9vJlPh
        rAmey50ZqWAT4Ei9ZF+jH2aAanuJhiO3TimbgaAKs395ryg39xliwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:hry1uILDnjcTlxG/WlcOspnPYWa0QGSmZUVFt6LOydpvqiUPe7UyyUEK/0odiEIcs2I7DMpvrWfaWc0Frjra1J4GCFdFssfsWYL6eE/DP8pbzX3WOaiwktSj6QKSbuaJ71aFLZ/n9f0CoIOAc7z//pvI1nB+kxq/XynNZVRW+Ks=,iv:kqDIkIyjykzvRSBdBDyPhEPuKdVYKjBlXPpCWlv+Oxk=,tag:ICE4ZXOaAL3ejd0Fz92RTQ==,type:str]
  version: 3.13.1
