apiVersion: v1
kind: Secret
metadata:
  name: postgres-immich
  namespace: media
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:XeeBkPrS3KXCrJBKsbO4vw==,iv:rSQXQninPBbingK9GsrsEvy8GNplhhzHf0mOlPaMG7E=,tag:iyo5dJ97FBQIWqkbk8m1Ew==,type:str]
  username: ENC[AES256_GCM,data:Jm7wWu9d,iv:NovwU/EyF7M0291larGUSKA/dSgwyyQUgs/hQqFFYJI=,tag:AywweblMr/E7iYYCguNx/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bHg3aWQ5a0pCbExVaUc2
        TDFrei81dGF0b29oVkM1cUVKbzU1UVZVb2s4CmhoZTJ5RHpka1RwcEpSUnhDR2Nu
        SjVZV1VRVEsxcDc4UDlaY1RmV3RPZ2sKLS0tIEsvYTlLa25jZmZ5eDNsaFkxNWJl
        clJiYllUNnRvbGUxc2g1R01FNVR5a2cK2V71/FJfNWgZ7y+DGjKTbK+OVez6vvVV
        7pa6UYy72XfJtH/xo6xhwsk1yNh6j/hTasq3slDRrDsyi5ejVTTeVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaREJuazZXdTk1cFovN3JV
        TjI1Y1NiTUc5cGYzM2ZiMmZEaVU0NitnRkZJCnJrR05rTVlHSzJoclNCN2pSeXhW
        YnZ1NTVSdVlTYmNIVENGU1kza2VtVk0KLS0tIHVLeGRKakZteHl3VVB0ZGFSeitC
        VE1LUk5vMGdDd3ltS0pkbkJnM3dFMmMKcx4VL0RSMJiu9JaraikHmkQk2DQeqvpT
        DhjUKK6B+lHgzI7kDbjTSen6rWkHfRPpV9oB+1b4XEKIvoZejRaVYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOE5vRk5YVnBsSXNXTnYw
        bk4rRVRMbkt2U3pwWTZhd3Q2Z2ppeVhiSXkwCnJPRDNRVkRaR1VobXYrZk1aT3lm
        RjlLZ0tULzJESWtmV0pmaytYWUJqdjgKLS0tIDA5WmtjekFDbTkxVjd2MkZZTFRj
        QXowclpmVWRHOWZlazhrNFd2Q3hhcVUKeky1jVfpB+Sa5mB9csKYpZjyrgYlrJX6
        xtjBMsurF0K1by+we9dw6ZuHKsExFF9QWydcLLXWiyxmB+XoiHe+nQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:B50nw5sbZItrtxDgTDfoPeKO7Y2ElLQNIFwizQf2kDqXOgwdDVAOUlFrLMm/E7NMHwWU7eHwA5Rtv1h/DFyh8dcO3TRiJEkgRRewpGjCIydtu3eFgykqXqnPxly/OUV6VIPNgf/ZUkn6c+Ba3ovwQeCbJUgIRKoPj/236+DZUN8=,iv:5ud+/FKMipZ5LlPtSMKsW00VwhWRSIuGLi+c2R757Bw=,tag:mYAxsqsysNMMjMo3GHNQ+g==,type:str]
  version: 3.13.1
