grafana:
  enabled: false
  ingress:
    enabled: false
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.1/24, 10.192.1.1/24
    hosts:
      - grafana.stevevaradi.me
    paths:
      - /
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.stevevaradi.me
kubelet:
  serviceMonitor:
    relabelings: &kubelet-relabelings
      - &cluster-label
        action: replace
        replacement: melodic-sky
        targetLabel: cluster
      - targetLabel: metrics_path
        sourceLabels:
          - __metrics_path__
    probesRelabelings: *kubelet-relabelings
    resourceRelabelings: *kubelet-relabelings
    cAdvisorRelabelings:
      - *cluster-label
      - targetLabel: metrics_path
        sourceLabels:
          - __metrics_path__
      - targetLabel: instance
        sourceLabels:
          - node
    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance
defaultRules:
  additionalRuleLabels:
    cluster: melodic-sky
kube-state-metrics:
  prometheus:
    monitor:
      relabelings:
        - action: replace
          replacement: melodic-sky
          targetLabel: cluster
        - targetLabel: instance
          sourceLabels:
            - __meta_kubernetes_pod_node_name
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      memory: 256Mi
prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
        - action: replace
          replacement: melodic-sky
          targetLabel: cluster
        - targetLabel: instance
          sourceLabels:
            - __meta_kubernetes_pod_node_name
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
kubeApiServer:
  serviceMonitor:
    relabelings:
      - *cluster-label
coreDns:
  serviceMonitor:
    relabelings:
      - *cluster-label
kubeControllerManager:
  serviceMonitor:
    relabelings:
      - *cluster-label
kubeScheduler:
  serviceMonitor:
    relabelings:
      - *cluster-label
kubeEtcd:
  serviceMonitor:
    relabelings:
      - *cluster-label
kubeProxy:
  enabled: false
alertmanager:
  serviceMonitor:
    relabelings:
      - *cluster-label
  alertmanagerSpec:
    resources:
      requests:
        cpu: 10m
        memory: 48Mi
      limits:
        memory: 256Mi
prometheusOperator:
  serviceMonitor:
    relabelings:
      - *cluster-label
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi
  prometheusConfigReloader:
    resources:
      requests:
        cpu: 10m
        memory: 48Mi
      limits:
        memory: 64Mi
prometheus:
  serviceMonitor:
    relabelings:
      - *cluster-label
  prometheusSpec:
    podMonitorSelector: {}
    serviceMonitorSelector: {}
    additionalScrapeConfigs:
      - job_name: scaphandre
        scrape_interval: 30s
        fallback_scrape_protocol: PrometheusText0.0.4
        metrics_path: /metrics
        static_configs:
          - targets:
              - 192.168.0.151:8181
        relabel_configs:
          - source_labels:
              - __address__
            regex: 192.168.0.151:8181
            action: replace
            target_label: node
            replacement: nas
          - source_labels:
              - __address__
            regex: 192.168.0.109:8181
            action: replace
            target_label: node
            replacement: homepc
    retentionSize: 8GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: iscsi-csi
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        cpu: 65m
        memory: 1600Mi
      limits:
        memory: 3Gi
crds:
  upgradeJob:
    enabled: false
    forceConflicts: true
  enabled: true
