apiVersion: v1
kind: ConfigMap
metadata:
  name: copyparty-config
  namespace: copyparty
data:
  copyparty.conf: ENC[AES256_GCM,data:ixPSkx5xbPwR8R6rUzHv+3AkpaaVsgDxilI/wU4tQ1m/tipdiSagyxJg1eIMiGRjJn3UcrBeXitOBHQpBnilfz52COBwAeKa3WWnEQ7dBCVF+C82hLfh/Jp756HhA6v7eQ36oCwDGPb/Um+jgB5Aqcp9IGWWF4KTXvVyOWLHjRIzUbKPRYd93N3CiNdKb+/wGXCFFXRF2lugB9cT73boU844YzhRUaorZw/cwKGMlXaEbl8bDVwyavyuoz9S4HyORKpwDuwiFr7fFynsONep8wUZd7bZ/BV5ZfJqePMghkbsm96eA0qwDEBxqwnFLtAoCJDPK9cPW9d399rHy37LU4y6DoBn2d5XWzUJXxmDRX1/j0KmudGio9iz3ZlbnAdUM5UbMCA71UV68kSMT14BShZ1cOSYcg==,iv:IvGRd1NYXSuabkodBV59ouLJ4JGFTUBZtc2FFu+hUWg=,tag:oUtTHz2y2wFgALX/yFn8Vg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY1g5RW5YbUFuUkpySVBv
        dmhHTTl0d04yZ1J3b1lEeHJTWnBYdEo5S0JvCnBGaFhOV2VGM09FWGlyajRtTGRw
        aFA3WUU1UXZsREpJRVlTbm9vTTgzRTgKLS0tIG9PNXZvdkxhU0ZRdHR3UXRzRmN2
        eVB5bURUdWppYno1eDQ5NjUwbmJZdUkKDzRNReJxxHWAZJQ13T+sJsUHBhePu6XX
        CP2VsEvaqcTifFT6b2DwjUSeDFeGQBp3e8SGOHWHD1R3+3AQ6Ik0VA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSHFOVktoR1l6QkF6aWdq
        dGpma2NPYWgySTl2Q3hpVWFEYTliVWN0L200ClNmSjRBaHhzRDdBNEtSUUlPa3Iw
        TEdhUEJWb3REVVZ0cVducEdrM25VU0UKLS0tIEJLSzBXMmw5SXNXa3RJTmhMZ3Jh
        VmMrM1V2VXQ2K3VvS3o0dmJ6TG9WRzgKu3MFC6rEFNUof2ptKUdMY5MmsB8Ylm5B
        ZLSrr5rQSMj2qUl5v7607VcuvA7QIVHBOUQ2jPhgVtmu6YOo1F7KWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSm1td0RnZDBRZ3ZHMm1K
        S0JPeElBUk5JdFhiTFRwTFJ2UkwwdXpKN1dZCkJwUHZTMmNuL3VGNkZmcDJRa2F4
        SnU5N285QkpOWjhyMUlSQ3NneVRzRmcKLS0tIG9qTUxHVkhMTWtacm1GKzdSSVZp
        RlQwaWZ0R3lzUmdHWUVxdlExY050aE0KltXIqjQXFdxv6mTsPDTZLzLwQInOzbs6
        7a4jC+vzk+6usZmJQ7sy0mXjinAqCo9hji4j3PbCy1+0M//uYpv5MA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVGVSeDNoUzkyUXJrYm5k
        azhKREU1L0dkbGNXdGhmMzFZTlNpaldtSlNjCmUycCtWbzdmbDVDaFN0QlJjSmps
        ZzZoQ0hYQkNNTWkvU0dSeU1NR1RmZTgKLS0tIFpHKzl5U1lDYVpaWmhTZEwxeS9w
        ZFNCWkl2VUxZeDh0RjcwWVQ2RXR2RzQKID6YOsRpX95/D8oIzRM+pah9GP0+adIV
        qhY8nH8fsc2Zr2i+yF1D53Wja3ReYl2bDbyVCvq3jAgFwynlIzeWCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc0Z1RFlIY2VxZk1yd0FO
        dElIemFVUzQzRXE1RmMyaEhsa1FIci8zV1NJCktodmF5NXJSdDNQcHkreDUxdkpF
        Nk5PV2NmQlNsZHpUOVdJaW5KWlBLTW8KLS0tIG9meHVidHZwS2hxYlJNUUs0MTRG
        cjJBKzVBcWZGZDkyYnRzMlhwemN3LzAKjYORTu5wMxks+AxeJjgroZMi4yn+uFDN
        qYWZ7NjJ1SIW6tozUvubalymtLiWasqhKc/CaSZ6nSzdG4PQ9ERM/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYkg5a0RUQmR2bXZBOEZ0
        bWpkWlpMeS9mZlJCUVdGU0hkN0ZJNC9RcWpNClpKejdydDhwYkI1NDJTS3AyMWdZ
        bW1VQktER1hjWlFCU00rMEl3VHpuWTAKLS0tIGhFZ0pZWG10ZUlMU09tWGpJTS82
        eW9FcThoNC8xaUt2c3hFdjRXVkpiNW8KmNV7c1bYgIDyKJ7UFm+BtYnvJgvQLyN1
        zsdPrIc6iI4rW8ZF6SGR6tCJnNN/c13vto+k8aYgJ2jFOOAsZ2PT3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVmRLbk1LOW85NHU1NFRw
        Q2dTdDlMNkgwRjA1czkxdWJPc3doYlNya2pBClFockdPOEpjc0NPOWJBRHhHdU5K
        TjBRbmRuM1BOSmZ5TkhTY00zdUgrY00KLS0tIG9JUjRxTCtwWDE4YkxocGN6OUpR
        NFllUE8rSTYwOEU2YmcyUmhXS2psV1EKMrPOOxMsGnCnrb4VU5SxyMvLbxlnJ+ye
        GKqEUs129x50Y/n3rLEiKYztjVNOkRYLgf/BmGk8QQQGAj0rUtYTwQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRFN3WXhCaFdTd2lKd3BY
        K3p1YkY1bGRIOXRuNzRtUGpGSFNaczNYd1VRCjZVWEV4dDkrWGJYRVhXRENYRndK
        eDdXSVdNSVFhNnIvQ3laWTRiOEJkV3MKLS0tIGJHN0l2WUJwR3NRTzNxK00wUnlM
        dHd2VlJVblJnVTJWUVFBUlRwVHh5MjgKRilwwx/sZMKU/mYkym3NyD2y2AcKuwIH
        I8LOacS8QrEUvSM4Z6LeSVZWEB4nz6YPM09EI1iZRRMaZFufG2n8Jg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb0NPV283b01uVkVIS01U
        Tmd3RDRLVnNXUG5yVEhyOGNVa1RTelFHTVNvCmJWK2prSzVHVjJETHJQNHNxamFV
        Yk5EQlBFSW16dG8vWldyUDRNSEN5NmMKLS0tIGNUOEV1bEkwMDNaeHI5eHdXR05V
        eHdYUGc4MEhMYkE4SEVjRDZZWXJzOVEKMcKb9MfJuOYlP8Eo6ZdoXpbVnikEsbjT
        ZiFwt2GtGr7HXF12Uv6QFOZOButHCol/t3UTs2KtcEqp3wbO0CYdVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVFBhSmhyTEdBTUUzSWN1
        eWE2R0FZdnpCVUhxK004eXpJWGV5VUhpa0FBCkhEdEE2YndId3dMZk81a20zMU1j
        VXVaMjJ5Vkl4Ryt1MC9vYmlGZXdPbDQKLS0tIEVEeGZmMy9zM3dBV2hyM3FyNGJw
        ZkREcUd3NS9MaE5zYzlmTGVSU3l1azAKO7Gf3J46KfYchoEMtVKNvTjUCwMTUz4y
        2hJBUC797+P9HXhMu1qK9s2YRxgh/oBA6L+sMTEOC+UmCQfJ9tnXWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:ISbCiLTVO/uZnwWauuLAL1dwIxkC2Ld65yJ9UFcVBtH4AtG5mUGpeHRolAiZI6BiCqBUJYI7Z6pztzyhykjwYZyzoM0RechKWPuUOdu7bXMtOZKND2Y8juretMa1aGeyPXZbCEy3vSM1n94GcEgEgbWpwWm83AJo6S+sHLtZDaw=,iv:veMzpYvGweJySA0+voZIr37ySkGEwvvvrZaPnjGdICU=,tag:zlnUsxCFJ4vDG7Yd32N9+A==,type:str]
  version: 3.13.1
