apiVersion: v1
kind: ConfigMap
metadata:
  name: copyparty-config
  namespace: copyparty
data:
  copyparty.conf: ENC[AES256_GCM,data:X8kSdgjbux9Wp1sj3IDB77xoROD+n25Oy1f7yaAng9I+tsgQK+nRO4AKQ/ZAZy6tKh7PplbNVsMtSI1HsvjNS3GFNxEKKPx9fn/Jsn0ARGUarhhT2Sd+mfO8U++H3Gb52DkZo5lWGb49cYJUwyoqd6eR8Ambpvg8j9FZC7D/FfG/PsYaEq5EJPc8Ccq2AYvahk7+rIvOXlBGKgX/mua9NO9am+fPPjVy4Vj7GYTcaK6H7Xs8sGV1EFzOe8keyAJJAMv+PWPC4DaVmS4WCS3vEIrBFFZzcAW84qgC17WJyOkwHxJcCtRMyx+99hC4Lj5/cW3ZUDYBGHe0Eqar8Kpm0rq1eNAo9fHRQRjeVxyzoR1fBH1/LcBs2ZGfcYMwOX+/TluhkqPxQ2Qz8Aj7Q9J22148f9k+2w==,iv:Dv3Yd+GsCge4zIyChunsZP8Zga1JvEjdYChLH0/Xn5I=,tag:N4+f9iQp4tJZQQ4QVC0fCA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c0Y4c2drNnExalhDTitx
        S3V4WW9XaGp4TXZJeVJPYUp5cW03aDhucFVZClc2bThDckpxTDJGK3F4NVlHd3h4
        RlIxVlRDaHJmZzQ4b2lXbXdRNlFtdEUKLS0tIFNsd01vMmtxM1gwbWxBN0hza0xP
        Y1B1Qk43U2xZa1AvVDNla3poeWwwdmcKCnnJZSe4v1HdzItmJBtRmurFgjdNzHs6
        9TIowZwqyVpCrNQzE3B4QkaKOQEJWKZsjEfFgLNGFHODzJ2hxMrLSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbDZ3ZDRnOUN5aDVML1FN
        V3djYUtPTmJNUndKYjFQSVBaQ05malJqR0g0Clkzd0I0NTFoNzk3cVVML1dTeHFw
        WjdqVU9ESTBXZ211dURTdlMxQzhPa1kKLS0tIFN5UGlCNEhSS3pBRDhYM1hnY1V0
        MERSdFVCcm9WRTQ1aVNieEwxSzNNdlEKclr+VW3/u84xJY129iUHbqZvSjQxrIzT
        eWFPnjnPyN8RNgooTOx7DQiRx1FThwewzpCuHUGqfn55mABckg422g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWHB2L01URFNBaEVzWWkr
        dXlwQi9EVDRKM2tWNXVoa3ZHbVBXLzRyRVhJClBCaHIyOGk0TSt5d2tCLzlPNXF5
        OGtUWEo5K3M3NlBndWFFN2YxWjVrancKLS0tIEFTd2JZN2MraUNQbDN2SS94RGxT
        c2dCMmpTWDFDTkdiM2IzdU9JZUVUaVUKmN+Zi/m5jnAUnIFiAej/3bkFEVgaO/M6
        45GyBXzcphFxCAw7O3ezsJ0zDvu2XWfmyvG4eg6r9jq7EEJa3aWOOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:QlKu03wm5ULUJVMKnz+VanGjhpgtS3QUp/0AHdZgf06thE4ys9xfov3zm4aSMeQfwrL7THsEpiAGxCa1y+30KcPmVoI8H5S8fZetzHverr41iV3+9MTWO5riPDcoCSR835aqq4Uzo7I38y1ni1N3UgTuvlf+DB2D3o45nZenbco=,iv:V+VueK+iKOBn+grE9ioktdA1Mgjv4AysPCpE3HxUK7c=,tag:99l+jS/5o6cha9FVMyT9WQ==,type:str]
  version: 3.13.1
