apiVersion: v1
kind: Secret
metadata:
  name: lastfm-secret
  namespace: media
stringData:
  ND_LASTFM_APIKEY: ENC[AES256_GCM,data:BkUvHBmpaXe44QurRzbNpJhqt4Zr3EDFIid7BITOwCY=,iv:HwwCnwTxDaxPh/yt0oWJyOYG61PMJozM/3yH5pEAoh4=,tag:ZDRDi8j1zOfWgILkgnSCYA==,type:str]
  ND_LASTFM_SECRET: ENC[AES256_GCM,data:VT6SSFq6fQQZEW0O/WVMIYie/288Qij7F2ur3apvrjo=,iv:YiGBu6xrpY6TqvQJwWe1cFiMvfCpj1se42eY5QkJk1Q=,tag:rzZRZB4HW71bp9LPEKW0SA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdndEWDJyWHdHY1ZGOFRQ
        Um9xRDZMbVdHb3FKZFcvcGJPWjdXVk9rOFdnCjZFYThJRmdoMVRXZTRuY2p5dFky
        d0J5R1VqMVhrOHd3ZldYeU53WUhUZjgKLS0tIHE5My9wRXdwb1RmRUdrMmtJSnRP
        bnpKcXlTVXVKR2ZoZVBRNHhjWVQvT2cKaZB2XBF9zwD04X5ekmQ+6daZuRsS4GIy
        Occ9+GuDfIqo+wsC6OHBJ/hu9ULIhv/GzDrTSwzriJY2QMfmVllLOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R2JsNjdGQmJNUEdJTjd4
        dUxzRUkvaXRzTlMvYXlLNllMT0NENUlTRWpZClN1TXluRXVDNkI4Y3JDbTVzbEwv
        YXQ4ckFMRmNMMnlvVTRaaWdlcGRZaVkKLS0tIExIL1A2UWt3ck1vUGlxTVZMQ01v
        TkkwT2NYVGhPT01vYUoxaFU3Wm1GYTQKX5YwjM8jYlJ/TdpulHJs3WoytlwFvs37
        Aj7Ae62FbGOGEa+A+ofb0NspSkTJ5QgXGcDOUFD0X/83RI1vuOp3eA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWi9CWVZjZXB4R3hzcSts
        VGNPaFhzVXYrdG81b0pNUTFXOW53QjhGK21vCjNTZlpOemJpelRUQWhpcklpYis3
        UW9CNWVIMi9ObmMydStFWDBmUW00OTQKLS0tIDJhQ00wZlc3aXRjbWJOZzQxWU45
        eUMzVzRBUFVRWkRzanZ0WjlhaktMTk0KF61+MNFKNdU59vB+UHgqmwhfPxfqnkoH
        LhESuAcXNAhkm9RiuFN/5q49PdjCYaJrmj+8Z5rRo2SRnkaOlmiiiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T14:30:55Z"
  mac: ENC[AES256_GCM,data:HG1q131UpMNZ9WqGa7F4Rle5ue3XokO4nmqHE5PLDoIcQ+eMNm6j4e2BFWjiUdsL59EqmiJOOpVfo1e/PCxlkHNVqBb69lVzwvOsXTH1qsjxd1DME7TkyOZOR8Fa3BBjgHxCSTrcs0EiBlZKkh+P8hjsz3X9J8jXWKD8E1am0z8=,iv:qldLyTj42oJC3dPw9T5agVb1Hf78XeK+GdOl4CpgQRo=,tag:pWBTyBpIXh2muNNNlHGqLA==,type:str]
  version: 3.13.3
