---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  timeout: 10m
  install:
    crds: Create
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: kyverno
      # renovate: datasource=helm depName=kyverno registryUrl=https://kyverno.github.io/kyverno/
      version: 3.8.x
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: kyverno-values
