apiVersion: v1
kind: Secret
metadata:
  name: ddns-dabitches-secret
  namespace: network
type: Opaque
stringData:
  AUTH_KEY: ENC[AES256_GCM,data:dKcSayH42Ey9GUpAGUmDE76dsLOWJnqxUC+88roBjYsLQ8jNKdaTDQ==,iv:a9DTcnq7moOMqk1j7Z1yY+XxWYW0kqhNP1KsqDPf104=,tag:OoW5qNN8LnOvK3yUtslgBA==,type:str]
  NAME: ENC[AES256_GCM,data:84v/2ohy2fSX3eKjlA==,iv:nGTU+4OFpuYc3xALI+190vKBxU2fUUa/HfL34bOF7xI=,tag:ualOUtYT7A4c5gbSMPOLag==,type:str]
  RECORD_ID: ENC[AES256_GCM,data:M3o/A8qqh6soFMmTG/cgcJCUDW03fWxhgkyEgCFosx4=,iv:bhcVRrWm+Xxt3jeHGuRqTtuSG3SHQa8Ox5p3PBNuTp8=,tag:HtvAxlcGuCGqcKifBerTlg==,type:str]
  ZONE_ID: ENC[AES256_GCM,data:kZ/xAivuTOE5vNAUSs29Nbwhuv6Tu6ij1FbVv2BqkD0=,iv:PgqU02mJ/m5p5N0/oeNWzRqAJqkKqaG5W62R562AKxs=,tag:wvsiFLIn2VXvKrQkaar7lA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbHJIcDhES2FjeTF6MzZK
        TGVScmU1YWhwc0oweUhFckI5ai9WbzZuOVNzCkw1RTNMalB6TUh3WHZ6SklwSi83
        eUlPT0FLUVcyRVZkNWMweHd3U2JFR0EKLS0tICtmZjVMdFhBMWxpT08wcHJyVTlL
        SGhYNEp1a0NiT05WYXpaUU11eUtyTzgKmWb8LB9tn6OXvbYfiw9prMGVeB4iuKrO
        v7ai4twNvUa1vKARr6YO3e+A10IcLW/2QQoBWF6+X4ZltexG4h1lTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaVUxTUJXNFp0YUJDZUxR
        TTFlNjNvR3gxNVBNUGpzcGxENytJa1Zub0ZnCjlxZXUrYTRobzJ6NkVCTXhsRXcv
        NURoSkJWaDViWUdOZTdpWEJFblNYeXcKLS0tIFhTOUh1QjBwWlVnWXRwcDFHZ2NP
        OGZISXJ6a1BDdEt4QnZPcGgwR1Z4bXcKMPSyP6NtOoZuGRrm/JK6akuneW95fOtN
        qImkND/as+7RCukTF9K+RXh97Qi25cH/QwR/oqrC7JvfBcoSwAVBpw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbUtIZDhJZ2kybDhTekpj
        SU1rOXgreE9lb3JrRUxnMEhXQWc2RzRKSTBNCmtPd0FMZXdhelp4Sm04TzY2ZVMx
        L1JUSDA5ZEJFcUgyOVBTbmVkYVlRYm8KLS0tIG0wZUErM0htcVpoSWlDTUZFVmxv
        K0VpSVhMTk0rZ21yTkU5M0dRWEVtU1UKcWEbGeKlHFs9TYjMkLCYrWTcnXP3aXUp
        4odu8t9wOKB77Os++7WYuS2vVXAapESG8DI2vtRIxz7kGfmFhyLnwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:q4RQC81g0MNuQ2E31yFxDGGNz1H4w07jH/nev0hcD2G2cIzUVDSKoZiWs6U3W/77Jr2F7ppHpui7OU+cJPUCw9BmVYcX0hZeQnXfDNTWxRk9+uP+fNabWcSasxRKY9e8ZaEFWoqjPv5RNDC4MSzDzFif3rgCE8byBLBucz0v5do=,iv:zwz08Msxwg/iBZiM29F16ozB6Mh/JQK8WgM6fVXCxZo=,tag:t9fqy6T4HusU2iysp2Qxbw==,type:str]
  version: 3.13.1
