apiVersion: v1
kind: Secret
metadata:
  name: ddns-dabitches-secret
  namespace: network
type: Opaque
data:
  AUTH_KEY: ENC[AES256_GCM,data:NSMjI8fLEhK+OC6h/2tH3PGGijioghM7oDL1VGFxRTymzmSs3PWfJEQUyzMKLBcOncIzMSGU5qA=,iv:arg8Er1sQGl1uGw0wi8R1NPxv9C6STllWq6Gt/xhnOo=,tag:srTl7dhgwYQgCT6fdG2kHg==,type:str]
  NAME: ENC[AES256_GCM,data:HBYTwXwnGwemXK3JH2TjQvdZ27g=,iv:fHnPzYNp4EOhrOq5Kkj2MHqDwevSDnnCBRjGd9iTuYU=,tag:ejqinuQ/YYgRFSAZrk4BpA==,type:str]
  RECORD_ID: ENC[AES256_GCM,data:SfduS+DhWBC+He3pFSb1p32nr60x/c9kJxxMYUbGgaW+D64uYg8WuD3+3xc=,iv:OfTVIzGVzJHmFYtKRL3vHwSEf1aT6H086PLuFQBqnWE=,tag:80JzVwGnoUAtDEspc0xjHg==,type:str]
  ZONE_ID: ENC[AES256_GCM,data:ryp7kBjWxzugZhLvy59+U9Mist8vxjFuypdZI73Sq1P58XiVT+S+J6EkuFk=,iv:5Gqwjtz8SZePGtlAL8d51wyJKZgtKrfmNWePuiRg+Dk=,tag:RW4cmqgTiy+8IvfBmMC+0Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL1c1SDVaeFVuS0VIK2tz
        djg5TTdvUHV5V0RON1RmS0drWHhIKzVGUkV3ClJsNGZBcmJodVhOYTFhYkpnczAr
        MWx4SG1jdGFKWWljcVJMZDZBZ3NNR1kKLS0tIGtBZkY5ZmR6RnNCU3JvY0FML3ZT
        REtrL0MvZWt4eE5mUGhYZXFFK2F6NUkKmqOZtx4TY9h80CIfqj9OhT7B62Q/tIbl
        iZZgo5keiB9w9Kmq4MV+oQSQPBLuVn7OeImU9beL3ukASDC94kstfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VWtvMmVqb1Y2cnpwbjJa
        Ni9GL2NGai9RQXF2OGcwZEM3RDZoQWlQOUVZClZDYzBzOVFCODlTZnZ3U3hiNWFW
        SHdJSEtxQnpaSUFnSHZMVythbDhSYWsKLS0tIFVOenE3aHhhVHBjQ21ncDZHTEJj
        NzNQOURVakZpajA1NEVqSEtiUWhyOW8Kgs7ooPiRf6W+nFNO5i19jXWBqVVVLacF
        9hMCZmc8FaPe7MkVSacC2tzohDFaXGQrOpqOEuZpfqDEKvTmmQysEw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VnU0aG4ybnNYNGpCRHRY
        V2kwb01IaVNYcWpvTUFUZmNwSzRGQyt1eHhJClVaakJaVmlsd3Nva1FvdUcrWlk0
        Z3JHWnZkTFg3WmlKakpPdkdOaU9qVUUKLS0tIE10c2xFemVUY3ZCLzM2TlRvVmJT
        UHRiem1BODEvdkhNOWZUMmZlTmYveTgKSJV9Nc3A7EJodgtuI51/P8M/5KhFC8Sm
        oTPDHrRGFl4BX7mgJK7tE4fEcWUVXwZNz5JoYBlw8uNHWS4NmJx6nw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bTlOS2tUVEZOdTJodEhl
        eFJQaTArR0U1aTNNVlZmYXRHb3hTT0dmcHlNCnJUdFNhcEZ2WWd5QTFLNk5reHht
        OXpSV1VNTVkxM2oxNDViL3JRWDhYUVUKLS0tIFJ6b3B6NzcweElGT3B2a1VZWEI0
        aER0NlE5Zi9MVmJKNGx6YnBJWGwxTkEKi/JghmHI9Rpc1TKDWyxorc5sWp+bnpbX
        xv8b3Zn+IHNmaGavQ8j76iBdhLNiuNBti7R39qT/+U5CbdB/l01f1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVEtpZ25hMW5VUTg1a1d4
        MVBpRDB6NVFBR2JDWDR1Umk0bTJBejYwNWpnCkFOZmtSR0pZOXVXMTl0dGdzU0o0
        UUhmOGg1bDJoUjhUQVFkQUpDYzhaUkUKLS0tIFpZeVR0cXJMZnJhdVpHQzl0MGJJ
        QzNLL3hRTW02QlZRS1pYMWFZMmR3VzgKOeJZMrCvoTX2x5THP6ZPzJh93kFCYynS
        rWBe3Omty9LiuDs3PHg1+VVTtLBnTcm+ohf7x0RxP63R/jQ4p0cxmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWGhGVWwzT3N4SjB6WXBy
        TlZhTVgrdEdJRTZUdEp1WGxDVm9rWHlJMFZVClBCSDFBcEphNW9uQjU5dzAxdHNj
        anVjaHhxZWswYlY3QndKQ1BZQ0ZQaG8KLS0tIEFTbFR1YWhwWXNwWlptZ1RMZDVo
        WkJpOHZZVkcxOEM4akxGL0FoMmJUVVUKX1QwC5bdE7Q1q+Xy3hBwU5dZOJqveAIc
        Zi777UdphYyRGZULdqugHc28urCfFzh5cWiGhEV2GvVJN8oRb657hw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSzBPL1NYdG1hOGIzUGpH
        NWFQSXJ1WlhXU0VTUHZYTWpyTDhOZXYrR3hzCnNqcmxJbm5EYll4Wm9aczQwd1NM
        YytEWkd3cDkwejVLMkJSbWx4bCtUTzgKLS0tIHh2RGNYb1V5R1pRVmlTNmtNTGE0
        eVlkZUd1Rk5kd0NOWDcwYWhTZGYxaG8KupGrBlyh4iGCqvhQ+XLpcU6NsVKMf3ac
        rIoKsAgvOoBFSUyb2pFLm2xYjEMgMdWAnaZI+FcHbsjwLpu/dvyYwQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdXBCOHM5TkExZE1jMDFV
        TStubmg1bGJkRzI4QWgyQXg3Snh6MHdIRURvCndQUCtncFRpbjVFTnhEZTlOaW04
        dEJXd0hud2wzWXB3eWFRaXhWaEJrNXMKLS0tIEczcE80MEFlUElEZ3lTL0VYTU5X
        M2dSMDZ5VGxxZlFpNlppNGdtNGsrb1EKxOaWRyZEjwQ/v2H3F7tRxcylWgcI4NGK
        H3Mx9So1gR3wUf+XqtuZBPWfiUJfoc9PQ/QXsXK36zupbIYEaiGFVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbFY3OUpOeEx4ODV2ajFH
        Uk5rSU1Fb1Q4QnZ1NTBrSjRWNDFNRFd6blJrCnIwTXVzSjd6eVdBTzNaUktCTzBj
        aHUrNnhLT1NhU0dja0o1SnVMRHltWTAKLS0tIGk4K2c1VThJU0JraGM1VVBnOEc4
        WllmakxpWU1XODBJQlB6aVBSNjcrT0UKMQX7c116YlRJwLX/Niag81Fu3JJXLKVo
        9sO3qqPBxY2YC46xWsCQuCze1Xxw9fOPytJ4BVkD6w7lTks4PNelqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWW1TU2ZXNWdUNkJlelFU
        ZjF4cjVUK2YreFIwa3ZRQkNzWnp3aHlHRWhVClQvb25COUtRTmU3Q0JMVE1pRFNS
        WVhwYmZEVldOMnNWQktSeEpaalNDUGMKLS0tIDFVd082Q0tlT3VlVHRPZThGN1Y5
        Zk54dHljazRsUTdJV1hqK2JJL1FLa2cKsniXmhO9hfBqxW7L29hqsZNVgJfqtnnR
        hFJw4SLDFoRdy9UDd2aAknCMyPulLEn5CBYbplYncl3VoeXBusxeWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:Y0zt8fNu/z0V9M7qBDlcJreaRxnfq2ltdt9jHFvuot4bJjISBvUivcV3WZgRqICtfvqlbmRi0an02oqmxkjWcGkvC3TViGThSyivaxpuLTFTyKSqGKsULCnhAgpI8wEzp6WUlMrneJnILVb6L+rPJhgFX5/Wnazuc4BCOekegBk=,iv:pYsqX8iLhvAoFo9CNoOzy0dqCa2F4EjeSVf4jMRIbw4=,tag:PoPmJm6YA7Xisk/qKTYlCQ==,type:str]
  version: 3.13.1
