apiVersion: v1
kind: Secret
metadata:
  name: ddns-dabitches-secret
  namespace: network
type: Opaque
data:
  AUTH_KEY: ENC[AES256_GCM,data:Urr1rP3Z8nValQayfAWfKfOV9YDQphT3YfsFaLAGt/DJ3pZb79wpYEDP9lQH4G5GniP03cDXkMg=,iv:l/Jl4qeSGUtOf5VmBh3iEJNJAbSvi47hDTVvcXQCXJc=,tag:OSjOpkxfX33cKGOXEotszA==,type:str]
  NAME: ENC[AES256_GCM,data:Vr6AwCLuZm3I28QYwBgV2n6KNmw=,iv:SLo87q5pBN/6fxATDoUgqFo2iQTzKBMwc93mSBQeeFg=,tag:XWjvsIZTiMCc6TpFDpYcbQ==,type:str]
  RECORD_ID: ENC[AES256_GCM,data:xQ8Mfj3+3AN+0DJaymfNF4UKejX0NocqRMSKhcUxbDMQy2e9Jl0a5iB1FgI=,iv:vEBJekTSa0Z70yY9eImZaKXwfb7mNBKxbKjl4/ETCcM=,tag:5uG20m2QhVVJ/LUbVIb/PQ==,type:str]
  ZONE_ID: ENC[AES256_GCM,data:TzV48yTwiNvBCAxqio/1L1hYKBGo7OPCV5O0clvHm1/41vtInZSIDuCKV1E=,iv:kT6hxwZWQ1c3i+gCBWULDGBy7fGKm81badqAb5sQrAg=,tag:dZsbCZ1iYuoR3PdnCsOOYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVUQ1cUtpREdlR2l4aTlq
        SWI2VER6NWRTYytZT05QeGVMd0FNS01vREcwCjdrYnBLTTRVY0xyNVJtaTd6MnRx
        MDRwSU03ZkZjKzFiRWtoWENvLy9IL2cKLS0tIGNNRzBKbzNpdGMzbm42c3l5RHkv
        dDltT1hmN2RZeFpJZ2Z0UnBhZ1QzUmcKOUeWBCV2qG19spsyhxujAHt4IXP07Yjx
        Nc9wxYoky7YujtphfysVOi0KmHe1D3ONKUXkmUPYQ969mOccjffWrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZEdCV0tHNjJBcXRaMzJq
        YWliYVRoR2JnZ2Q3NDVoU2sxdmdOQWRzMHl3ClVtK3lHYk1jU0NPNXFCZVJ4TmFl
        SWFMRWFodlJrQjdGMGY3WGQrMzd4cDgKLS0tIHF4WldlWWYxYzcyazliOVdEMCt0
        cjFNOFZCWHZDdnNLTThRenhSK3ZHMEkKwejroGxpryHMysyFh0ZUmnNVSjNxQly2
        6qqsz+3wX4jbdh4KWo+B604BNmj18x2c3EA/R4r39hXIueAZsEXnLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc3hBY3M2QndYQkV4b0NH
        S3FKMTJEOUFTVkdZdEl1REVEblQ4Zm1WdTNJClRvZDZJYVZUbVRNMGtJeVlLeUpI
        YmsrbHhuL1NHYVdTYlgwU1JwRGlTdDQKLS0tIDdTR2Y4Y2JYYndDRit0cTZoalJG
        QjFGNmlhYTJqYWhLRk5ZYXFPL0l1NVkK1AWpLHyVEubHj2u19/t+6VynoPSTioIQ
        1cWachjxopaBRBtV1Qp+BHwLP5E9NrIMFdA6insMqW5Anw9nsFiXaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:HC/SoyL7Sl4XYOWceSgAXSaFxDCWhGZflkC8PgZQBvuOFviFVN/f4UGFqrGt4z/DHpfxd/jSU8NgjSv1wNvt/yR9FWvM1tsxRluIgo+13JyIfpZKacX/m8vq994ZJ71gxm1XhIj4R050+9i8/3+d9UsfaVJtXgpWqsY6zF6aQpM=,iv:Ihl6uy3CHvCljU3iyV6d2jUBmcmmINDnXZ60N2WiOIY=,tag:U3Dh72V8bTClWmdmklaeTQ==,type:str]
  version: 3.13.1
