apiVersion: v1
kind: Secret
metadata:
  name: ddns-secret
  namespace: network
type: Opaque
data:
  AUTH_KEY: ENC[AES256_GCM,data:58p4eHbbXPry9kPSXRacpQqQd3yhd7cP0aEzyoDDWtVeoJrc5dC1SFUY91bxXlI4KC7Zogv6kPQ=,iv:zTh41xyOvcdOS0HmoV1/zVEK8n3mtyky8tMABv7h9RE=,tag:g0+fWUqwb5psBJi67AamOA==,type:str]
  NAME: ENC[AES256_GCM,data:7q6iYnOTuLRKqUZC6/5dA1hQugc=,iv:NEiYqMMUHQ4VXkSo2MFG6EpgNDZsmpoUJsMoWA5V5eI=,tag:pRsAYqEz6/Uzsip5suntNw==,type:str]
  RECORD_ID: ENC[AES256_GCM,data:wvPZCDdn9VqBwcBbSA9etlPyXZCX01taa3lO4G4QohzdejcuSJHWYE/WX9s=,iv:OlcxDVUfox8xA5xnvpAd6NIyZJWvI3n4TYPqBwlWx24=,tag:ud8ConUAmuYqO+APC+PpjA==,type:str]
  ZONE_ID: ENC[AES256_GCM,data:Diid9aLVwF+U1tyooTGBwPcixURat23tdZuuOAIfgOIWihERJY9JL7NGQsc=,iv:33tb6rr7P8AuJcbxLL8ymqNmjo7XjeeX4MPfOHivU+0=,tag:tpDIgCWkhPfhMww48yg25w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRjgrSjNFK2ZPMDcvdlFP
        Mlk4T3V6Mk4ybGROeVFjV0F6ZXpYc0xscXdrClE2RlVFZHZvQjluMUVZb213Mi95
        RFpPbDFhd3kxcmdHZW01SU1nSEdPaFEKLS0tIGJvK1FDNW5peU1pWkwxUFFPMElG
        L1RxZm1DRnFrME5ySW03RXFiVXRmd0kKLtC7j251bfOwAl1JRZqiuexuCcY6SjVw
        d4eEm7B378CQyKpAw4Jl0w0ZfXom4KzVCtYqK9i5QKvZnW7PEyLC2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc0VObFNLdjBBQ3RmWGg5
        NXVEMVpCU2NWaS91Q3JVNUZyWjl4Vng0Zmc0CkFaVjZKWnJuSllkdFAwTU1mZU53
        dVhSUEt2Q1pwUDZxeTlqbDZTZG0ybVkKLS0tIE1aYzZUY0hyUHRHeHUrdnkybFZu
        QzROMnk4ZDBIYld5MmJXQzZrQjgzU1EKVbsBRf+isObDhOL0LJqt5nNi6huwdwWQ
        gGMHflhss/jDasMp1RyiuYEz8RgbAeKHNQft6xsksmzu3rEHBjOl6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMFRkdG03TTVrVUFkbDhF
        VUh4VE1Ea1BHMUJub1ZCZ2kyekNtM3YvaXdRCkNtOFc3YVQ5c3JaazZ6Z0FCZkln
        aHhFWWFQYkp6dURMOUEvNmhicE5abHMKLS0tIEtSR2RUdjh2UjBTV21tR0FidnFp
        N1IvWmR0VGpwZDIxZFJuakRjWDVreW8KUMZbRbjYNsHf2uH3atEspOWfIBSQnFwO
        jxCQMjqTDCSOlHnRABSix5Fv67C82IZs7QSRVXBdrQbtnns8AkvmUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:8nXp1RO/vbndxTt4gjDeZoUEtnuhXcAAYDX2vlOEpvq6Eq7WKMOlq4ooByvxSNekeUQLLoibZ3tb9FthKR0UfFCpLWHo6ySVic2UY/v1HxsaAHG05Bhb1cv9oSpIsvOQOpXcE2sbgatzoSS5bzzKfP6sJBKcDOszeWPWn3JBJas=,iv:1/FkcKTDR57YqKm87Fffs8utrYsV1xkJBR8b4O25Q9Q=,tag:PKlOWT+/TRLUVD3FmtZQPw==,type:str]
  version: 3.13.1
