apiVersion: v1
kind: Secret
metadata:
  name: ddns-secret
  namespace: network
type: Opaque
stringData:
  AUTH_KEY: ENC[AES256_GCM,data:S2aQ0j+BrFiEMBQJ8dJox2zGsrOFmrU1YAJzBM/K0LPsflXcGdXfKQ==,iv:KhdRVazSWWDh1mTNi5b9Pw7B92Cm0+eZW1tdTLhWXUE=,tag:ToiD69u6GKVygUmRSPgu4g==,type:str]
  NAME: ENC[AES256_GCM,data:P70KSzZObKP54Ywabm0=,iv:YQt1/GrOG3yVUwRO/79vHlC0H+9Mcwk7dtAtbzHphlk=,tag:0dip9Uq3+WzYIMc3/G7XRg==,type:str]
  RECORD_ID: ENC[AES256_GCM,data:H8BiBGTJ+uqzifbnRLQ6y5kUSOMl773wFkeep9/ouHs=,iv:8dhWU43ZlmmyZwiFSov83OIFhIUGuphIfqHTRsFmWsA=,tag:0NPByedHMytOKWPlhyKEhw==,type:str]
  ZONE_ID: ENC[AES256_GCM,data:iuLlKqHvnX9/u6JPd4XO8l2TUxfK+CBy37TpgBQ+zwI=,iv:V9z01fUnCdOelurn74jSbn8L3c1UMl0eO5xNUuCzwIY=,tag:oGZMWv8q77K2Eue45VruwQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOXI3OFZ6RStHZVNuZXZD
        RWRiQ0N4blQxaXRaMVVaNWJvLzRocjdHY3hBCnVCQ2lVZ0ErTmI3eTQxQWFnS1pz
        a0dONE1qT25sV3Y4MFoxemk1bWp3OUEKLS0tIDdZK3NrRWZmMmhsYndGckhXaC9y
        aExSbzBOc2VsUXB0OW9PL0djaEdzSVEKsShaV/0GzpbcLsXTX1qCPCjqNswFnIKf
        Vh4LVufQST58FvOvD7oh3qWlV4R1oefP+337ydRSSZ0Q9s4r6hRMuw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZHhqQXZIQ0V6aXJaR1dD
        M2VhY0QyaHRqdTY2YWN3eWtobHd2TmJFY2g4CnQzQXQ1RW5rYUFKYXlnalVGRFZ2
        RW4zbmh6ZXhrYVNkOEFWZ0JyTkt5cXcKLS0tIGdtWnErWXVpdjE5cGVKbzg3NlRI
        aU00eWt5eCttbGlEYitPRWJmVmZlTWcKoreYTZXltLLodhh/XKQabTMWkr/yAWls
        /cFiz+dz58HsCj1mdm8cOLveWqg13Q78nRmUFMHmrdIjuo0/eeIdyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVVgwZEVkRDEwdmtVZ1Vo
        NU0wa1BQUUxaRklvMnVTZjdvc29FUkgrWlhnCnByWTB3cDMxNVNCUmxVdEI2Ulpq
        a3lXV0lJS2Z4aC9SMEZQNVJHTjJFalkKLS0tIFNUSUdpd0o2bG1kazJVeGNZdkVZ
        R0Z4RWlyQzBuZlByU3YvMVB4RTBIU1kKooU9dNPxuJLN1L0Oyh083HzPDZqdJJR+
        RaLMpSRhTLJFnPpiYEwH/t+xx01yd34M8MgcHx7JG4yzLgXY+zvwqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:1eBQSTELXu1N39aXqUuXsOp57xwOYj54i6MnTtqVjdC1llIvDT7RkmSsyeiPy0X7v/QI1SdmEmzBS7AZ4lNx8SXrYb15lOQrfXibSPLIN5yTrF5/kXhsJ8ajiGesF9leBZhP2dE1Qpo8Dvq3kh1BIODhtAtX/LMtlN0dKUCIucc=,iv:yROMx26DO0HhGRmtA4pNRfeo/7l9+JHpSI8zW370SQ0=,tag:I5O8m1FGZU/FOn1TCg2dIQ==,type:str]
  version: 3.13.1
