apiVersion: v1
kind: Secret
metadata:
  name: ddns-secret
  namespace: network
type: Opaque
data:
  AUTH_KEY: ENC[AES256_GCM,data:NPRo+R19C7m+u4k+HGhSLvJLqq/hgxY6IuQaaNPtGsGTwwsrhodqxO2sBHGW8R46tDhtPSw8pXs=,iv:ZBZv4wPbAsTgNYZHPp0Ami7cxgD1ZXjbSKvbb/MoxhE=,tag:5IHDiZbcQh9DgQRw2xJGRQ==,type:str]
  NAME: ENC[AES256_GCM,data:sJG9uWB1aC6lo5HMn8wTY3rILn4=,iv:ZMiPiksdxy1Fp+aqCeGBbaqPePlE4WVmoHwFVujYv/Y=,tag:g2nKTCI9TeRNHeX0spwZpA==,type:str]
  RECORD_ID: ENC[AES256_GCM,data:EKgrPSaBLvoWTdaOnqvSxjifW5Y2EX8Igghlohg/Aw0vCxV1/V+am3EYUZ0=,iv:5VTQnVCUKNdr0r77wQdK53nQWGSn/xd5bVKVT3tK7to=,tag:ArF7N+eLchvQGfk1i98Bxg==,type:str]
  ZONE_ID: ENC[AES256_GCM,data:vWROsQssgiD4lT64PVZJuO4b1ymAn8jiHdmRYLy/e+gwmpN8qu+DUlOBFFc=,iv:XWSK7n1QxrNdxBpD/noiIVO+zTATwZnnG1CH27fUuZE=,tag:SV8HwBL7dHsUdXzWillYVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZnpIL1NkMHBTQ0lWeW9B
        bFNwcnVNWElVQldqNnJwV1dockVOQXVwVlg4CmU2M21mK1ZhVlF0MllPQ0xtSC9j
        UlZ2U1NuYlUzTElhek4wTjNhaEVGWEUKLS0tIHdKLzZSeFg5akhiYXRqVG96bFVT
        eDNyZ2oydnJRL2VYZkp0QURFNzNKZGMKSACoc5rI/ANTrkbAbYVKtH5AgtVsiDRN
        bRQw3I+F+NNkTKWLvnFTUB5T6giGjJXw0wq+3xzdYXHGB7GqBqu7mQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL3dmaU5ZU2Y0MW9rTWJr
        VnpFT2UyaTlHSlh1UmVJZVY4cGVxTjZZa3dJCnZnZHpyL2p4eG9CRElScnlNQ1Jy
        OWYwZzQ0NHJ3dEpQTVBmSUgrTmxyb0EKLS0tIGRKdldhVTRmM3pRVWFBL2w1Y1dS
        TnZvL0Z6L2dQcGlGL2tMU0lwU0dQNW8KhzwAZu+MwoOvr8IPMtRe5Tuc7GAmukda
        /D33UvSwFvLFKjixsRjz5kh4adpWSRbK5AldkXJXAXSR5D7khs8WFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMEhWamVDd0RZQUMxbWwy
        cEt3ZkhhZVpnR0xwajYxWmllSll1aDB3ZFdvCjBUWGYvSitkS1hJYkl3cDNCYTR5
        UUVMN0VuR2k3NWJFZXd3VWhhSytDREEKLS0tIGlNTUZYMnNzYlIzU3JqUjhpSU9K
        aHV6MnNEOVJNWG1mK20rTXA4ZU1sNDQKKuEXlBxzHEA+dtl1bXbCzcyE+M0xrZzK
        mCCzlLxPYQsOhwV4rZsdldakhuJJYTbIQ7b4HZaE/uDKMnaEWFJ5PA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbjFtRXNXWDE5TkVNSFc1
        WUFHdThjVTUrMSs5djlRSXFMdXBNUndhZ0hFCmdjbG5SZWJyOW5CSzdJQmpFMGpj
        ckJKT0tSZytGSE1kMjJ3d0JDWWpDa0UKLS0tIFJqN2JLTVpmODV5STY1Zkc3V2lW
        K3ZnRGVMYkRLLzVWK2tGK2JMbVF5QmsK3pqpxtuhUgCDlAccByzvEHAf3R/X6lGu
        psCiSPnL5OlRhtolYtK1JVec0r/WOZK7gp8I2+YX/6whFaLdi3p0NQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5emV3MmQvb1MwR0F4TUlH
        elRHVGJQU2pxMjBidnJHY1IzdnlMaVE2MDJnCjYrVllLY1NOQzFpTkZocE0vQjQz
        YlppaFE5ZU5zUTdMejAzcmdNcUxjUVkKLS0tIDBMTlJ2eWhmMzZpRWpJcSthU1ZJ
        WmxQa0JWOW12VnNHazc5dG5VWC9ybEUKR6nZFLQ6VtWWyzmAa+HJzjg58bExTFfq
        Y4nIl++I0+fWxyAc/Dj5PPNa9EB4KonCGQask9DhxEKe/VvLZVYevg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S0dRY1Yrbk1PRnhNcHBo
        OHhKYi9aMGYvbEswT3hFelhYQ0h1WHl0Q25RCktaQWt6Y3RyR2sySmZ0NFhXSHhW
        dGowcDBEOW9uUlo5NGRJUGx5Q2VOTUUKLS0tIFY0SjRhYU5vK3F2Mmc4Wi9RVDg5
        ckRtYWlYUFRwNWxsWXpVYjJ4Qnd1MFEKcf6F5Z+JXV2hJcW3obFn/eiXA4SsLFwd
        f0BEw/HJBK1wUrRV+feVMBj3Rik12FTpBSVxdsE1ObuiYX9CAtyTNA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV3loeVlmeDBwWFFHMnZm
        amRPYWVrOUZLc3ZwSkdHWWZKQ095VXpncTFZCllLKzhNaWlBVDEzMnNjYjJtVlJ5
        c2VyS0NFeWxmemhTaC9TMW5UUTVhOTQKLS0tIDBYakd3MVhqdFFwbWtkM1JzR2RK
        RERlUHQraENwMlJrRlN0aE9RV25pNzQKPKDvxfl4JLDE4Hu9KydakmU8LcfrXPR5
        mlVgJ6HWDy82GrzhiBU6E1wXX2OM8kwK8n4dFBvlIOk+bVQi0JJ44A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bXJYSGxGcXhaTzNPWnlH
        U1RrWUJ6QmREWjJNZTZoNHlSK3JwU2NiWEZBCmRCTlA2Ujl6S2M3b25ZMVZwbzVO
        cTBjQm1NdE1OV1lJbjc5dEh0bytjMncKLS0tIFd6ZUJHM2JHelYvR21DZXZRakRj
        eVB5VFlUWUhpcHVTejZGTUp1TFhOUEEKAVmizY2aP7mfcAng5d9QjBZYKJem6fja
        8c6Jz/W3Iulqvr2VIG+jUoZIIIFufMncb7VBPnYV5rauh4oeNwM5yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMEV5c1FEZURWdGJHb3dp
        ZVFCd3B4SnZiSEhJYzd3TUdWdUFMd0creGtvCkFOTlg1WTBmVjZTWGhpekphTEIv
        aTdnUVBiYzMvZjBKRGtqZUI1L2s4WFkKLS0tIEJYUnlOWGQ5WVNqdmg4OHVzTktC
        cUhrN0RZZFFobElQZDRsVTNuK3dVbjQKzSw8ErgzUJPKyKEavs/Ye4gUWaR3sNY9
        gwMB4wYG6KcsXy52YIcQr6ejZz2ADPnh0o4E/ztOOHc56IUqYgBaug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSLzBzNGhVRk16R1VkaC9y
        K29OekhmNUlqcGlZSlYwL09lOFVrYWZ0RmtRCmE0cnlIODB4cmZ5TSttelhPMTZs
        WGFDODdoUEtrQmZQY2hnVkFRNFJvZUkKLS0tIHlJdGN2WU5ya2tVMHBRL25DekFx
        cXFhN3N4a0VUS0tEcVlwclRwWlhIbW8KR4TSa1iCrDZClRkVXFOVnCYmYc0Dq3AK
        zu+8XBFjCa1qiYo6VANmOfxU36qoTQ2cSRSQXT+cM2UFtPkefExD8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:HrIxlD6zklIZ/j7hvCENycU7hb+0M4Hyn36wyVHZnR5Lz3JPwMLw+YBPLtUzb7A5nGSaKluC5Edf70zHXdSdmMoZJCpcQTFoZuXlktVYxyaB6w7XOehVjLO0nBVqPYSisDf6TKVx7slfQhpYvpbVFV31kWA4APJqPwcus29pvZY=,iv:mKcrRtg7uN6tVPQgAW2lvH5mQJIzhUNMLIdjvDbZnxk=,tag:Tsqb9aEDiYNKIbhLSipOfA==,type:str]
  version: 3.13.1
