image: { repository: harbor.stevevaradi.me/quay/cilium/cilium }
certgen: { image: { repository: harbor.stevevaradi.me/quay/cilium/certgen } }
envoy: { image: { repository: harbor.stevevaradi.me/quay/cilium/cilium-envoy } }
nodeinit:
  { image: { repository: harbor.stevevaradi.me/quay/cilium/startup-script } }
preflight: { image: { repository: harbor.stevevaradi.me/quay/cilium/cilium } }
clustermesh:
  apiserver:
    {
      image:
        { repository: harbor.stevevaradi.me/quay/cilium/clustermesh-apiserver },
    }
authentication:
  mutual:
    spire:
      install:
        initImage: { repository: harbor.stevevaradi.me/hub/library/busybox }
        agent:
          {
            image:
              { repository: harbor.stevevaradi.me/ghcr/spiffe/spire-agent },
          }
        server:
          {
            image:
              { repository: harbor.stevevaradi.me/ghcr/spiffe/spire-server },
          }

imagePullSecrets:
  - name: registry-pass

hubble:
  tls:
    enabled: true
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: 365
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: ca-issuer
  relay:
    image: { repository: harbor.stevevaradi.me/quay/cilium/hubble-relay }
    enabled: true
    pprof:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    backend:
      {
        image:
          { repository: harbor.stevevaradi.me/quay/cilium/hubble-ui-backend },
      }
    frontend:
      { image: { repository: harbor.stevevaradi.me/quay/cilium/hubble-ui } }
  metrics:
    dashboards:
      enabled: true
      namespace: monitoring
    enabled:
      - "dns:query;ignoreAAAA"
      - "drop"
      - "tcp"
      - "flow"
      - "icmp"
      - "http"
      - "policy"

serviceMonitor:
  enabled: true

ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16

routingMode: tunnel
tunnelProtocol: vxlan

k8sServiceHost: 192.168.0.151
k8sServicePort: 6443

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  image: { repository: harbor.stevevaradi.me/quay/cilium/operator }
  replicas: 1
  pprof:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
    namespace: monitoring

logOptions:
  format: json

logSystemLoad: true

bpf:
  masquerade: true
  mapDynamicSizeRatio: 0.0025
  events:
    policyVerdict:
      enabled: true

l2announcements:
  enabled: true
  leaseDuration: 3s
  renewDeadline: 1s
  retryPeriod: 200ms

k8sClientRateLimit:
  qps: 30
  burst: 60

kubeProxyReplacement: true
