hubble:
  relay:
    enabled: true
    pprof:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
  metrics:
    dashboards:
      enabled: true
      namespace: monitoring
    enabled:
      - "dns:query;ignoreAAAA"
      - "drop"
      - "tcp"
      - "flow"
      - "icmp"
      - "http"
      - "policy"
serviceMonitor:
  enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16

routingMode: tunnel
tunnelProtocol: vxlan

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  replicas: 1
  pprof:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
    namespace: monitoring

logOptions:
  format: json

logSystemLoad: true

bpf:
  mapDynamicSizeRatio: 0.0025
  events:
    policyVerdict:
      enabled: true
