controller:
  kind: DaemonSet

  config:
    enable-real-ip: "true"
    use-proxy-protocol: "true"
    # If HAProxy is on a single server at 192.168.0.200: "192.168.0.200/32"
    # If HAProxy instances are in the 192.168.0.0/24 subnet: "192.168.0.0/24"
    # If multiple specific IPs: "192.168.0.200/32,192.168.0.201/32"
    proxy-real-ip-cidr: "192.168.0.151/32" # <--- THIS IS CRITICAL!

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: ingress-nginx
                app.kubernetem.io/instance: waxen-chinchilla

  ingressClassResource:
    default: true

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

  resources:
    requests:
      cpu: 50m
      memory: 128Mi

  service:
    type: NodePort
    externalTrafficPolicy: Local
    nodePorts:
      http: "30080"
      https: "30443"
      tcp:
        5432: 30432

  watchIngressWithoutClass: true

tcp:
  "5432": "apps/postgres-postgresql"
