controller:
  replicaCount: 3

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: ingress-nginx
                app.kubernetem.io/instance: waxen-chinchilla

  ingressClassResource:
    default: true

  # metrics:
  #   enabled: true
  #   service:
  #     annotations:
  #       prometheus.io/scrape: "true"
  #       prometheus.io/port: "10254"

  resources:
    requests:
      cpu: 50m
      memory: 128Mi

  service:
    externalTrafficPolicy: Local
    externalIps: 
      - 192.168.0.143
    annotations:
      external-dns.alpha.kubernetes.io/hostname: stevevaradi.me
    
  watchIngressWithoutClass: true
