apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syncthing.fullname" . }}-init
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
data:
  configure.sh: |
    #!/bin/sh
    set -euo pipefail
    apk add --no-cache xmlstarlet >/dev/null 2>&1 || true

    CONF="${CONF_DIR:-/var/syncthing}/config.xml"
    [ -f "$CONF" ] || { echo "config.xml not found at $CONF"; exit 0; }

    # GUI address & TLS
    xml ed -L \
      -u '/configuration/gui/address' -v "${GUI_ADDRESS:-0.0.0.0:8384}" \
      "$CONF"
    if [ "${GUI_TLS:-false}" = "true" ]; then
      xml ed -L -u '/configuration/gui/@tls' -v "true" "$CONF"
    else
      xml ed -L -u '/configuration/gui/@tls' -v "false" "$CONF"
    fi

    # Options toggles
    xml ed -L \
      -u '/configuration/options/globalAnnounceEnabled' -v "${GLOBAL_ANNOUNCE:-false}" \
      -u '/configuration/options/localAnnounceEnabled'  -v "${LOCAL_ANNOUNCE:-true}" \
      -u '/configuration/options/stunKeepaliveStartS'   -v "${STUN_KEEPALIVE_STARTS:-0}" \
      "$CONF"

    # Replace listenAddress entries with chart-provided list
    xml ed -L -d '/configuration/options/listenAddress' "$CONF"
{{- range $addr := .Values.syncthing.config.options.listenAddresses }}
    xml ed -L -s '/configuration/options' -t elem -n listenAddress -v '{{ $addr }}' "$CONF"
{{- end }}

    # Optional alwaysLocalNets
{{- if .Values.syncthing.config.options.alwaysLocalNets }}
    xml ed -L -d '/configuration/options/alwaysLocalNet' "$CONF"
{{- range $cidr := .Values.syncthing.config.options.alwaysLocalNets }}
    xml ed -L -s '/configuration/options' -t elem -n alwaysLocalNet -v '{{ $cidr }}' "$CONF"
{{- end }}
{{- end }}

    echo "Syncthing config tweaked."

