apiVersion: v1
kind: Secret
metadata:
  name: obico-smtp
  namespace: home
type: Opaque
stringData:
  EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:SCzVTdChbwtGkR/Rz6k3OzgK8Q==,iv:GwGHcbbbwGl2jC86G3YKNu3D6Eiv2DampwhLKD+DBx8=,tag:XK1yAGDso0aM0kcL7zSbmQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSnU2V2ozdDJSZzdSK1M2
        ZnRSUlZ6SnBjSjQ1UDBrYnFIRVJkMGtsQzI4CjRiWVFENWNTTmRhVXd1cHQ3WHV6
        Q245OHBid29EelRBL2cvNlRVejZrdWsKLS0tIERMeEJqbVZCaUNucXl4VnZKLytN
        SFM0M0d2SytxYW8wUi9BdmNKMjFXa0EKNMXL4fy7V2G5HcOsEsdDanPotdlZJqUM
        tisO50aHR38TvOWB63pbXZK/yu6oc3HPN9/6HxosoOMezM/5UHV4vg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWHQ3QnZ3Vi8wWE55cGs5
        QnBRdnJlZHBZVkM1U2NXUVNCcGJROGx6cDJzCitmS0ZjL3RmeUttSGlvNXNXbGNT
        V2h6MHNvNzBvRnREWnpLRDVHUTF4a1UKLS0tIGhOVFhicjdFN3dwK2VXN1VlaFpk
        WlNoSGI0YTRuUE85clUzdFNrMm0xZ3cKUf3Aet83WVfsFfbMuAPeCQk1x48M128M
        LLmC0xaed6+4kiBIfskUoKcdqvNQZ++mq6vGRxgUXanYAFZd/RfSHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWnQwNi9RMExSSk54Umgv
        TDBGSnBXSit6aFdyREVMQ3Rld1FXQ20rQTJRCmtLYVVnQnc0dzc2aWU3Qkk2OTQy
        cHZscjByOVdDZnp0MU9URXlEVkhyejAKLS0tIEVSamVaT2lYYzJCZzZpdk1Dd2ph
        aXY4cGZiTFpvaXZQODA1MzFrNWcxVmMKlCQ9clFRPpKV9oPYMX4B4kwqt7lOFeBe
        isYJJIYEADuAexIBchUxhK4hEUaQ482Pe6rDWxia72yKTP5gmvj7Qw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZTVUL1daZzdNSFVKcWE5
        Y05DV1Fkdlg2UzhlekJhWTNzNFhiVjFnNldvCmhQOTAxOEYvWnJVTWVZZ3JmY000
        UnU1dGwzS2NLMGhvZTRLcGtmRWZXd1EKLS0tIFJ5MFJFVnJMeE1WeWZoT0NtSGdq
        YjBWWEN3b09WeUxKLzZSYnViTTNyY0UKT22NYuIrVM9EwRuahzecTXVOvhhayGwH
        dq4iXU3zaq5yfVUdfo6j6CjwHx4ar8DApD0E4q7unIvQhjfzGowV4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMC9jeWl2UmRrSGkwYy9B
        M3U3N21WWHNmWWNxOHdrMVRnSzV0Z3AwTWdjCmRwbW52NGdjMWlKcUc4L1B4clBK
        WmxHSWdXMm4rRmVJako1QSt5NVgvZTAKLS0tIC8vaVZtYUVZcW5oa2hLbnhEbzIr
        UTFrNzdrWVZzSWNWZ25XQW5XRWczYWMKK8S8PiguBIttslHiXMueyilSqfvo1Z1b
        ElEHrrvsMbQmAvNWZwcnhUCndeIMgKrwidw4aF7eb+EvjeYzQR9w8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ektIMWwyOE80QXNJV3Fi
        T3NQbWJpRDJLT253a2duTmJZTzhTaGhCTVc4CklNY3hETEd6Nk1ub21jbUJLcHFx
        YWFpUUxUWDROckpiaGM2aU9qYWVJZjQKLS0tIDVCaEt4Ulg1VUxWWDFBd2N0dXJO
        TC9pcGMzTlhMeU9SU1hQUVVSSkw4SHcKo8pfPIfKTFp0E2dyrDaaICBg+MfKTLu2
        Zl5w6Q5nSLaA7Ose0PYYU/7EOongWMdmFvvz/7cEydorWf0tCuJ64w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbGYrUTByY0xUU0laekFB
        UGJiV0NQVzAzRVFIVWFIMDFEVjZmVElNdlRNClpqRzhzQTdZbmEzTER3MzdlaWhG
        T1RsQmo3N0RhVXljUy9TYXlTTmwrZDgKLS0tIHRoNlhjYXY3WjNQWTZRSzdzbC8x
        MmRHQWJWeFhlbmVHZ0tCd2pLem04U1EKXL0bANyLAQol+NJpu3mwJP2vU23l10nl
        KEaNJISRMp9+D3CM0XiPu275RQxp0LQwdyhkyU3oC6hrwRE+M/IIEw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRndYcGo1d21NT0dNeDQw
        UXVBSFRWWHlaS0piUW5RdmE1TjFpUlc5RG1nClh2YWVoY1dBRWViV1lrbXJlMnZu
        TWQ4OFBHS3cvU2NCV1h5ZFdIblE5MVkKLS0tIHp3UXYxWlVqODI3TDFhN0V4OFlT
        UTE5Ry9TTE9IamNqQUZIK0orZ2NmdnMK4d9MDlwBP5HCrJVzSmVS2Gac7ltvAQ7u
        yBw9q45zfCie1WKnnKyeACHOv3XyTwjlzZkVDy/0H1CQo6SZGkZNPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlajArVURHWG9FV1Qxdklq
        d1l4UEFGNFlQTGtNNkI4NnFJNDRNSTd5NTNjCjg1MUtuYTZ3djFXL0YrVkZJT3dr
        MzdKbUloOWhlL3ZucFk2QjFNd2EvS1EKLS0tICtLaXk3SHJaOW1CaVZ2NFB2SVpk
        V0J3V1FEeUtiM3U2eUFxVGF3Z1Jwa1UKlqrVnxskOxVRVGBgkIwm313P86XxehMf
        GsTpx8rtCW8WMrM4cr8bfIVal3y9r+BuGUiYS0K+ePQ0hd9AGuzN5Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYblZkVnA1VnFBQ3cwWFpk
        RDJHUUJXL3p6M3QwSTQ0aFBld0c3N2pmZkFJCjVXVHk2dmVHZ3pUSEpROW9TYmpD
        YTU2WHhnb1ZKTTlJd2ZGcGtZMjdUMjgKLS0tIGNqSVVSSlpKQmU3NlVUdkk5SEVX
        ZVA5ZFdvSlQxT0U0cnhzb0xDVGxYVlkKss9PmdVD0qT0z0dhjxlrk246Bie3hrJ7
        LUiVqehXISRwK0/mQijP1WHgTJ4sU2iftU/OqSHnnl7jNzL/LclPLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:Afe07rseQFGyJLpGyzi2aa0QUuXGumpglyW9XOaD8fp4YvGFK7bhU3ysKwHfgwMsiuS3KRBURn1W81546w4bB5GyNwpdZIXIRN/eMruFs+YPN4rm1Xne3SPSULKS2NMoTHEu4E2c/414aZxIB0b/5Yrbgo71nSGcLczuzk+xLL4=,iv:ukcF+s3obkVzy+W82nvO8Um454D3Aslo2qhRLdV8BrM=,tag:4XxM4iJPqOjqifRh57xnPA==,type:str]
  version: 3.13.1
