apiVersion: v1
kind: Secret
metadata:
  name: obico-smtp
  namespace: home
type: Opaque
stringData:
  EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:2cSz5QmhIvz0JCv6YIg2eYfuOA==,iv:o9yI2UkCoKqfRFJ5vL++vtimnyobDG+R/iSeYwHVgQw=,tag:Nh2CrGIxY2smeAVww6R2xA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUY3dzNG8ya1hRaW1KMEZ6
        V051ZUFGT1Yxc21wLy95RHZ6NE83VVdiQW1rCmtDV2w0YVJTaHQ3aVJKbnkzaWpu
        bzZ6MWFHdVA5SU9rRmhyOWtzTEU3dnMKLS0tIGNKakw3dUNJa1VpaGJEZUJkZlk4
        QklOYTZ2RlJLNnp5N3RXL3Y1ei9TbUEKSkByOrlrK1xZkQHIqZH8ejh7yorxMo4s
        t01kPP1sJP0kPXtSWNpo4XSNsBCVapuKzaCpv6VTTVhas6CWA0fbTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZXQ2QXRWaHF2Wk1taXh4
        TzFwOWIvZFVKWjVRQkp0cjJZZ2gwY00xeFJ3ClZZZ01qejhNWVlXVjFvbmZpdWRS
        SGRUNkRibzJsVXdXTU9wVWNQZFpQaUUKLS0tIFByMGkzTGN6bUhJQ1dibFFGWCt2
        WHVrdmNROWFxUnJHYVpMNmRpR1EwU3cK+9SgySV2PGSCPRXY6K5qYtp5VLrQkDxL
        YZu7uMqb3gEPWoMnAEOHcfLNatb4zN0rBhSOLE0UQo89eMZ4MWcnGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSXpFWUlBck1yeW5XWW9X
        NUxKRForRXZCNnowWVl3TlJGQzFVMVBtWXhNCkRMeG03K0xiV1lQWnZGVjJHWTM3
        RWJDQmJXOE9wTVNhZUN1QWJBVnJHbkEKLS0tIEZhVjJRZEtnRDRBUkVQUUF0Nmw4
        Tk9uMFFZTE0yQys5NGpmUzlDZC94R0UKGHgFlQUt6Ggr82YF43pZn6G0C11uB9Ju
        Sg/u2ylEkk4oesuidOQJbKB+1vM9TaB50XprdeWkEnZA+oND/fWg1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:2gVy9QLl2ZvOCBbeHJ26xL82rMago9UT/fD0ohZtc5Ji61rFEYd8qTRiKiUk5kQardfH7W6u4/Om0o3OIqmua9/9rcK7WzTSulwbHzshGLf7OKJhGDZJ0HgyMFPlZ6JP5LJH0kA6yChPFTzU6I41RlZB8jagjEjL7/l8D6zF+hc=,iv:WI9IKk094/n1BJHt2Z83OlOKpTGvURFxGBk+KK0X6V0=,tag:R9Z14Y5klRG+DGUEat7MaQ==,type:str]
  version: 3.13.1
