apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
    app.kubernetes.io/instance: mealie
data:
  ALLOW_SIGNUP: "false"
  BASE_URL: "https://mealie.stevevaradi.me"
  DB_ENGINE: "postgres"
  PGID: "1000"
  POSTGRES_DB: "mealie"
  POSTGRES_PORT: "5432"
  POSTGRES_SERVER: "pg-cnpg-rw.storage.svc.cluster.local"
  POSTGRES_USER: "mealie"
  PUID: "1000"
  TZ: "Europe/Amsterdam"
