apiVersion: v1
kind: Secret
metadata:
  name: mealie-postgres
  namespace: mealie
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:hORSMagMcxiV26B0yKO78w==,iv:aMz2GqBcLgIOWC/VJo/N7SR8ZW170w2vlYHSWlTd66s=,tag:r7zVDlJqbSVMFLM8XCh8nA==,type:str]
  password: ENC[AES256_GCM,data:gd+ILUt8+q39gt5ia811DQ==,iv:MbV5DD1nH7kDxHNqvBcI4XQ20E5/k3KbffOpaKRoVG8=,tag:/KOeSLxW6Iq8oZNgt+CibQ==,type:str]
  username: ENC[AES256_GCM,data:b97ZtHyS,iv:7VsD8JHDSpGvGj0Z2sL0GDCvdS+qm3tr+hqbMv9UaRo=,tag:bVnC7J/DxizG0FM6UYI1Gw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMlFWVlFPYnBINkpDS3B0
        Q0txSU9yZDBNSlFBUStSY3ppM3R3ZXE2Z2lRCk5GZU1NaGx2bCtNTGNjdEJzZGVO
        UkhRb0xrVzJITnRlOGhueDhXeGhDL1EKLS0tIENabWRUZHg0NHFtV3F5VEZTd0Iv
        bG5jTXBaZkkvVE9aazdCWVhiSnora1kKpbAv1bFVvKCWc37812S7nCr6DQMEP9Hr
        neIZsrbqFh7sWr1dUE5KcEtt9qWqfnSO5dgMxKG7T49ILcrilwZFCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSEZMYkF1ek5INWZnemhm
        TmhYaDRVU25LRDNneVhwZ2JIcWNRazlYSjM4CjQyaTJBU3o1UDJOZDBIaE04S2lW
        d2ZValdUZyt5ZEh5V1VjOHJRL1A3dHMKLS0tIDd2czdxRzF3V0w0MW9kN3JLVTBK
        RTkycS9qV3BxT1Avb0RaOWhvQ1d3T1UKZ6Rp68ncubxkX+9ht5AChMZggzkRBwH1
        r4sMToWxDA+51lNb/1XE20aQzwBJx3qNCXtzdH9M0+pNNGY7xAQ/PQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRWlqWG1ybDFpWDU4TStp
        M01hUmptUzVVdmVGNmFhME4wcFpOVFI1NnkwCi9FTGtDS2lJZjkvS1o2M1BKcmlW
        VTN2SUV2M0ZJODBFckIvVHE0U2JCUk0KLS0tIERYRGhndXlzY0Q2aTlBeE1OMTNh
        UHltZnJsandpMXExa29LTFptdEloMXMKlQ5E/dcg9gGYUV849tzylDnNTS+jjiMi
        i7F5MonAN7FYyz9PRCl+P8Hx0nCV4DQXoP8++/g2SCg40M7xB0o7Mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:qvbRZR13+w8vFCqFDDPMAyamQfdLi5u6+Tf0VIH+bwBa6Ac0+8+ZFu3a4g2G4U4ro10xCIS5Yfc0N3eseQqBlTVRyEWhWmaeHSSvTqj2d5daBaTCQsm6lhm21tGQB3Jkhe4tJ4tqTNPqkULo/Qb/Yloga8BgLXqFQvYluZmnsH0=,iv:VJxD20y/zd3iu3GtzyRfu6CHgzXHh2xtBgaVZwg8jSk=,tag:MxWLZU7zJhYjIpJOSm0Sww==,type:str]
  version: 3.13.1
