apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-mealie-mealie-data
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
    app.kubernetes.io/instance: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
