mealie:
  repository:
    image: ghcr.io/mealie-recipes/mealie
    tag: '{{ .Chart.AppVersion }}'
  db:
    existingSecret:
      enabled: true
      name: mealie-postgres
  env:
    ALLOW_SIGNUP: 'false'
    BASE_URL: https://mealie.stevevaradi.me
    DB_ENGINE: postgres
    PGID: '1000'
    POSTGRES_DB: mealie
    POSTGRES_PORT: '5432'
    POSTGRES_SERVER: pg-cnpg-rw.storage.svc.cluster.local
    POSTGRES_USER: mealie
    PUID: '1000'
    TZ: Europe/Amsterdam
  persistence:
    mealie_data:
      storageClass: nfs-csi
      size: 5Gi
      accessMode:
      - ReadWriteOnce
      enabled: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.1/24, 10.192.1.1/24
    host: mealie.stevevaradi.me
    path: /
    enabled: true
    tls:
      enabled: true
  replicas: 1
  nodeSelector: {}
  resources: {}
  imagePullPolicy: IfNotPresent
  serviceAccount: ''
pullSecrets: []
