apiVersion: v1
kind: Secret
metadata:
  name: mealie-postgres
  namespace: mealie
type: Opaque
data:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:OO69RzUsUVu+RFjybyMjnxfUF8denS5w,iv:PZFTvl2feubrBL8peycYKouFQP/LoZ8wHK1kItsc0pw=,tag:w9p7uNuoMCQtXBo8IsHocg==,type:str]
  password: ENC[AES256_GCM,data:Hd7ZCwhBqT8Bo8dxn7N5tJdWihyW5l7k,iv:g9VgONo/Wcz6K0XQRGvaON3coCsE0L+0hzk9Eo3Rm3Q=,tag:Y3DyLaKG/Sk2AA4mqining==,type:str]
  username: ENC[AES256_GCM,data:lOWUYHugw+A=,iv:8Ycg+IlhCzjENNPgNGHvsZcsMfAwS2HHi0yY5gbDfy0=,tag:8MvNBpTi68/WZXpK25nyzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UzRMNXFBMlc5dVZlcXVI
        Wk42NFNnbWExNnY3OVd2QWZ0N0FadDlkVTJBCmtMVTRiaGNORGE2L0l1NHdHVmtv
        TEY2Yi90S25CdmtobDRLNm9QMXlxV2cKLS0tIHpOdEorNXU3dUwyU25VMnFFQnZi
        TlFxbFFFWWxaSWQxWlhjK2hXTHhqNm8KvDeujB5ura9P9OUqE3dlVLkCJxwjEgTs
        /Ql58Hur1M0MC7tJO/KYkpu76PsjDF+IBWWE5+CWHKn4aJMORzrxWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZDdoZG5Ndi95SklySmRs
        S2lEMmF4T25PZFhjSVhib21JWE5kTDBMTUI0CnJ2L2lMODk5UU0wM1F1QkZiQUl2
        dW9hRnFJOXIzN2hpSVdpUFRnWE5iUncKLS0tIDBYZUMxcEcwK044MzRVNEFWMysx
        ZU9DMEVWUk5XaEdCMFU5K3JxakszRkUK5t7tSQLIWCwV7tLeHgrPT3iMzTjhjD+B
        C0EpfxB8BQwIR7Wh9jjB5QoTwVTgOCqb//gfo6796qf8DQpN70HWHw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWDliZ0w5TlVDdGRSdEs0
        eVQvdDBZSlUxNVZoeC9raXVsdm94Q2ZUTjBZCnZFc3gxVEZLUFdKbjhLdWEzd2NO
        cHViK2dPUnBZbUZWc2thMmtYVUkzL0EKLS0tIEhPYnJWdFZiVW9lQjZCR0REY3hP
        TDhQK2V5Y1lWVnJvN3ljWTFUNWtjbFUKKDVPsSxczbprxDYRBZlRvZqNHB3gwSNU
        nLTyVPx69fw4puTaUnscxnOVEBNggOiOHam7BxOaB7tUpgbEA+jmdA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:KlpEY6G4Cgm1U05w3ObsYWOuwYEodsInhZf84ncYdkwri+fcaK5WHG63ZTqmyl88Gp8aOJ/82WldhUdBRmsgCmf9sKPZ3uVaVtbBVoSgGhoUsH+xjHFb/7lkPHck6UT/sL7OBe7IYVZ5Yfu9Yuj/RdaZpgCQz7v+vsUrdITyhRg=,iv:AGQ2f3CzwJGcn0YBOsAWHYW6cWBfSYixAhjdi/7+u1Q=,tag:RkY0SIkDIgbI+WQQsftJfQ==,type:str]
  version: 3.13.1
