apiVersion: v1
kind: Secret
metadata:
  name: mealie-postgres
  namespace: mealie
type: Opaque
data:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:rK5dnVFQq4J8L4qGB/Uf/nGn/BZdXbcN,iv:5LJPbHi6o593AzH3ifW/rLRHGnAtlwQNBIzcnOcSVlQ=,tag:YnGx3DupnR15Nja0C+lzkw==,type:str]
  password: ENC[AES256_GCM,data:EYboxXfkfEWw3cYZfYfoDaSa5prUmxMG,iv:/sS84wiHItKhhH8hQgZQPRM2X8RqLLoQwrgkqsWteQU=,tag:Kc5gW5CzukyKxRGnf06Mag==,type:str]
  username: ENC[AES256_GCM,data:wQnvRjRjOqw=,iv:xlXesA9YP0DzRGMaUoFBu9o2TiSpEsb7FqJhXZS4Evw=,tag:lwy/8SSE8cgrlUNUmfkeKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPekROdFB5V3pHbUhNd3ll
        aC9lZkpCVzZEcU5aM2pUUkJ2NElxM1l4Vm5jClRvMHNxdzVyV25McDhrdktQSDdI
        S083aWJPWHRHclp4M0JoZG5KdFlDdm8KLS0tIHNLSXZWSU9JR3BFNkJ0T0h2SS9q
        eEt3bE0zaitsV1hsODhRSjNBSjFMOUkKiG6TxDBLKKsTo3MceAkSCG2fhc84NxpK
        sfKco/GBtdXZBnPWTYTuyhVYIkkwSAfW28h1807QbcK6CJEXmBjKjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bDJKd1cvZE44bGJPc05r
        SHdqd3ZhQlhyWG5TclMvMlc3dE4zaU96VkNRCjJtWkVCUDdSL3c2b1QyMm9wTmJY
        QUJtbldtYTM4NmJDZUx5RUlDcys0dTAKLS0tIHJxaDhpaWFQM1E0M2lMVllLbExv
        UUhhNWNYQVhxNUpRRkhWUUdjV1F1OFkKM6j09fKLxEVI/x+vc706fUWTglw122qb
        vcU1Noj8x8Ro5YuoHUnJsSqXnvQvqP5YahLzmkTwYMD49N9tjUBANw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNTZOSkZxTlZteE11WHZm
        aEZuZklIczQ1dTRMRklOcm9odzgyZHBiekJzCms0SG42VDNJaE1ySmczUFJyWGhK
        SW1CVEc1aEpQRnhzKzRvMmVrZXp4VjgKLS0tIHlsTFJHei9NMEVxN212NVUvYm9B
        TGhpSnM3NHlvYVdEUWlrU0ZodmovOE0KCRwFhv9sa4FlVXXbXR75dX5d0OvpIfFH
        NtVfBnyIx3LwsU6UctHoA9NEBkFdWR/VjiDNInOmo1Yq4UIW7h8hmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VjdudXVoUnluQ3Q0K3Mx
        MVlRWmFJOU5IZkVkS3dBYXZ2bU56dlQzdm1FClJZSWd2RkNLWEVSY3BkcWE5Ymc4
        SHRTemF0QjJyeWxLa0J4U0RSNXlLZDAKLS0tIFJMTU1rZUpma0h5a1RLZEFJNmZz
        eVl3aDZ4S2ZuVFNJOGNocEs0U1pSUDQKOf1YifZ79iwkMCxZwGbTx7f8H3+70EZD
        4QOzyLMJDnvlRyC4e7h5UC/lI5Y6nim90M9RHitv01s+R2R25SIL/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZTg4YkdqZi8xNEpsN21T
        cnNaWVRpZnQ4QjRRRmdwc25OdDNOVE53anpBCitpMS96T3JpZmg1WmxXUXdNNzJl
        bGtCQTlSWSs1eHd4bDF3NFNNbXVqc00KLS0tIG8rMjhqYm1hNlNtNVlEK2lVRmZo
        OG00WktYaHh4OE9WbzQzQVQwV1g1OFkKLc3IHj7RTiGIY1M8IKTW7Jvbu1mVxTGU
        sHH3XAx8O9NqauC9pmiuX8YBvpvgR72DrTnKiHVcS95gkfuNdg49kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWVdQcFQxRnpyUTVVRFB5
        TE1tbjhmd1MwV0RITHVZandnTDV2aGJwTkV3CmxxVVJJdU9uRUtheWU5STZRVkRu
        REFjTzlOWlhqMDVLaVd2OG9TQ25SVjQKLS0tIFd0STYzayt3c3ZUOUZIUkQwaUl1
        bmJNSHlvT2F6RFA1SjM1bkhOSE1JWWMKD1wN+tpeiiOebf2sbO1eYmjwSsvM8y+d
        DxcLcndkfFdNfvcjh7mzHIyecsMIfjSdVGPFC+Gx4KbNXcjTHckE/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OEh1L1Z0MjZOUmJyZk1i
        SlJFYXpDcTU5TEppOU0wUHU3RHN5cFRFMGswCisvLzZpZzl1WHZrT2ZTbXI1bFh4
        NVlvK2Y1a05mUTRkdys4eXIxMnZGVDAKLS0tIFRFS1RIa3VXWWlvSHc4UlFhODAx
        eXhocHhRTVpFWE5ublpjWjBoT1h2OVEKo7r8K/qGVEKSSaW7KcStWn2eJLDSxOvt
        Di8TKGP0opZn2nUz22ylhwB2T9eRlmyOkX4mSMEe0RJdjEE4P0JMHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZzdXTG5WZlpNV0RCRUd5
        TDZzUGlmdmtsem5BdzBJZVFNejFMRXA2TDAwCkt5ci9IZjYvS3RVRHdUdVJGVW1v
        RDByT0J5U1YyNFNoQ00xN1JmVGJDMUUKLS0tIGRrTGdwNm5DUmN6U3lidTZGcEVJ
        S2hWSWsxVHlMNEExekRLUjdVNjdDNXMKZEhs0YHYvJTEtvp4rONLiqGJ6ZF7H8CB
        xcnm05cvCCZy27tkSB0ZeJoKoGLTM46mmwR/JShOe/B6wn3krf54Xw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNDFROWlKMmRhMHhOV1o0
        d3BzbkIxRnBNamphNXlhUDBMVjgrNXVlU0ZJCjZMc3kyQVpHeEFCaXI0bmozL0Zr
        Ymk0RzZaYk9pTHd5Q2RKOHd4SzJ2a3cKLS0tIE5aZi9KdDh3MjZrVjd4cWVyVEY4
        c2tmM3JNWTdqR2p0b21MbnZ5R3A3cjAK14g82dr5PFpnUS4LMEtPlRgwCPeq9tit
        m1RNNPi8E/Np9X9PVA+3GVRkz6V4N3ZGarzqw9sSG1P/ffq0m8zQXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweUdvbm9CWjQ2RVZhc1hu
        TnNEejZHR2VYNDhMVXFoZVZBVHVsUkRuZjNVCkZZL2RMajZIOW1NR2g0Sy9QZFV2
        UE9vK0dqNDdGMUhpa2dDcHBXN1FHWWMKLS0tIGxPb3k1VklnUFVkSnhLcituR0or
        OGVsV25kSnhiT0h4RzR4aFNOdkJNbGsK38vrN+mQgmQuz0zkQWh9BrMvd3Y4Ykgh
        HMArTfCaBYlAwiDq03TChZobSx5Nb4U9lXoVA45BXi8vslg2KCI5Yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:RijTtxRm6GTZ+AJgnmuNm3fgYl/wXQLyHIR3548EZbxL2OIcPnbs11EYgXqv6NWzVTMsiKoHuZFG+IFox8bZ5ZYST1rJwNKy/sN0GuYm4m4hqEhXkJdW8pBVZOwleYuEbb/JkX1NzFySJhLKO7X5iMOFc0Fm70d14a+mguhH4f0=,iv:VfvRRjrO3oolXgihQlSYulKkF/6Aa7isakdmVUb2v2M=,tag:k6eonOg21EAfC7BnQf/95w==,type:str]
  version: 3.13.1
