apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./registry-pass-secret.enc.yaml
configMapGenerator:
- name: reloader-values
  namespace: system
  files:
  - values.yaml=reloader-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
