apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:pRUCg1l1AspRAGvmrT/ZZvv4z6Pz6MqhMN7RoEneOw+qyuWklOCDid2feAnt5zHQFycsVrXJdfaWbp5U2YvKPoTr11ttTEJu6HgQLsP+6K9f1qW+hpYDYHwcA038J7IavEN80iZnzOGxDCandz1x3v+2Hz5b5EOlct1DdzbElfYjj8jtXN1pyr/9l8H0/BM/UjtT13KfBH6hyMsZmqDN9wqLEG0vOswSdi1AfQJyBbgn4bdt,iv:Cgnh39LdykJLUD8uTYSFpPQ/9PBKMx2/jeI856gB2Gs=,tag:EtKIhqnduAd1/wz+7GnCvg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYWg5OENWYWJ6U0NzTjJ6
        Y2lqVjdDYjZuN2hJZ01TVW9Wd1FlRFlmRFcwCjk3TVFBZ1paY1ovdmpva0RYMC9Z
        Nzl1YlZRdUdVV3V6c2NYT2szSUM1K0kKLS0tIGpOTzlzakdUYzBZbEwwTnBqR3U1
        WktJU3FIL2dta0dCT0FLQjBRMS9NVkUKcdYmLUv7dEqLbI5yr6rTfEGtQ6avd6qu
        ACxusDEa0xJQM69PIDJrewVFBxZUslDVCSPJTuadXpQrD6rmqOn8sg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWFA0VDhjK0VCTDRBWEU2
        dGJOa1hXN3ZkZGwwWjhGZnROUDZmeHhnTGo0CkxtODZOaTVOeEE3QUpLOVVlanQ5
        ck5vOFZ0ZklDYlNFRzJvQ2FlYWxqcGsKLS0tIDV6NFIyVVYzaVVqREdOLzdxV3hZ
        WHVhdFVsTk9CUmVLdUVxZWV6aC9oUzAKak1V+IK2lihHy5rBdAcIEpI0kYGTj1cZ
        w1kgrFIQikNxxVFhySFf5WbPCqbr3/HzAk+QxdZp/5AZCAKhJ2fqQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUUpqclBNRUZxM1Zta0My
        bjZHNCtJRHVwOWVzY1VLNmMxTXd3bG9BYVRBCmozQ1pZcmlDaVpoWVNrMkdZMjhL
        WmJmb1UrVkdFMUJDZkV2QmEvMjhTWncKLS0tIDgwbjZ0M3dubzVsV1pvRU5td3hh
        TCs4V0lhbVo4eklLWHplRGJTR0ltQncK1elZCMCVv0COOHwIVE78EbIQQTbtN9QT
        z+1DddYaiQuchnj7OwGvq+XJDBjsjFDv/6Al9KpyfajpL/Uzusq2HQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSDVlWjc1V2lQc01MMEQ2
        YkNtVWNsc3Q5THVMY3IvUVN4RGhzcGdnL0c4Ckw0VW5xUmRjOTVKUHVqeTVJS2lu
        T0FWZXpjUjJFWlYzeFlFNDkrVnhmN2sKLS0tIDNadGlSdUNjaDIwYnI2bzJZL1di
        M1luOW4zMFNGZytWb3B3aGN3VEs0d1UKJUUAJHc7lqcwuzHstEx0gAWYMJji/WRW
        lqpqI4oRW3LJa1dC54KUmpVxsyCFavntHOE1852x+DdlRkvHo3PyBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNWVBVXpidVFpRE4veUtr
        RUxaYjdRbHhaOW9DRWRMVm4rYVdOVWFxOFN3ClYrU20yRlEwOC9zaGpMZkNnTWda
        dDVSS05HZHNzb2p0ZU9Ob2krSlZZdGsKLS0tIFNGUEI0am1UZmxnMXhHbE9vVFdy
        Y215L2hLWFRLRTlqcTBLSXMwN1gxS3cKZbl/F9zQ6OAXiGgmH6R+uGEyjDnX+52z
        sYxo7+uUz/JWeniTxGS/E1F/e3BQ3vX9w+ZDTFuhHV55Lkrawbur7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBac0dlbFhVWDlncmp3Ylpn
        UDRiMWhtRCs4bGtiRlN4aVhYVERzbFpmeEE4CjlaSmd1RnpHTk1OK2U2K21mM2lm
        d2czbG9uNXdtV1ArejBMZWVuY2lUMmsKLS0tIENWeWY2N3VReXU4MEVmanFHRGRU
        cTVjOWxHcEpBQlBhN1lxVzZCQWVRNncKwEvJtm9NxBX5tBGHoX0z5ARyvlHQ5L1c
        zW86DBLZHkbHhaGFUL2BUWCmDNSBOkam27RiRD/mfEzl83uyqgYCJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTVpKWEN4Nk9pbktNeEpz
        a05Ndy90RXQ0RDc4U2U1dGk1OGVUUTJDQkNZCkpnYjlKeG1YTmpucWg4Rzh4ck9X
        NmNNNHJwQVpWV1NtREJvUDM1ekhPWlUKLS0tIGFxV3R6d0Vwd3pTbnlIV3g4c2x1
        aFpzekpJbjdlQ2Zld1lVcW9sYVBFQVEKYZTjVTKNcdPIGvoVnSHDR2MdKbEJqia2
        pjNAaNQr2Rs2hgPYc7+wRFk8MVew7uDQuC1u95NAIMKGGUt8hfhwHw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T2pSN0czSWZmL0VrcXJP
        Q0dEZ2dSdmtOWXJDTXFNQmxvbjlBVTJXUUJNClNvK2JudjVKVFRXVVBZMXRnREtG
        eUk2dGpnYVpybHZnMGpNZUpJTkt3NEUKLS0tIG9hZ3NqWUR6MGU5V1JyR2NndkpV
        ckxlTkRheWF1b3lRdzArUkVsQVo1bXMKIgpWSs1ScfRYDt71+RH4dMCjTFoiNezY
        MYlarYZ5d8AUM6AaRYDb/OGJxUgODm/eBJCHX7GmgShsFxgTy4+dMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa1hyQU5JR2N5S2lZM2Mr
        MjI5YXozaStHYlY2QmU2VThobkpMQ2RRM3hnCkwrdjVoN1ZNekU3VHRoNklZdXN3
        MmlOSksrSmNnSGdBKzVNM3lTK1hiT0UKLS0tIG9FVzNFVGYrVzFUOFVkVDR4NUpH
        RWFtZEQvN3orYnFMcklnT2ZmNkZQczQKXo7rcQJMmcPallE0wGLkhw41jSooEEGU
        ddB5rblkzYfR88/89BkWkGrOBEKkqLh85LMFkY1jJnI53K+9vXP+Tg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZnZqcHVSd1ZTMGRxeEVT
        UXpYTlFvZEtTR00vQ091NFhFS1ZUcUNvQ2pZClRVQmxnNExtM3ZQNjNaVHBhZzRh
        TWt2RGhZYWd2RXFIQTNXMlJJdzJJMjQKLS0tIERtOWFVNmEzVStENUQvWWd6c2lr
        Vld5WDJoZHVGYXUzWnArS1Y3WWUzbjAKbtwi/i9ZfLipJUEPfTG6Vpygph0T8P99
        OnvnWqImfl7FLGqFikFxIMRD+zcxYdWrEFeJ1+4zEXc2/xXnlQ05TA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:CNmc8HSBUMtvltkgIKz/yh3n5jY8w8leVXKyjQjker2trhOjipVIT3HjcyCIUhueI2Z7CbgSCs+sF+94GvnzcorfQC272wNYosYem8YmRJUbxMDRhQzayS9L9FkvZXH7E/Y55FC1eyju+MPJMZwLev5k3+5T1bOXxBGbJZHBqLI=,iv:GqL6iVdnNvfiFTrdzeE5YTc/YIXAP9+FalFsqoKMoi4=,tag:RI3IRg1jaGVYzxHGUvAdqg==,type:str]
  version: 3.13.1
