apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:bu78FYkQT16R1uf1Aulp3SDb0b7SAIiM5NOux4NC24iOvud9mtn35oaRDorD6Z3JKjiWmbRTFeAd8nyG7RHXzSMOVGI6Nq45jX5y+pUcdkk9xsKi5RJ4wHr6L6m6OXAGQ79tMTNS0HsBx/zxcNaZhWO95nQQZ9SREFkLyI+oxIHfcaGBtlihZpvbVoMZhgtQ5ecqEg+CycitR6bZG8ZWUy82lSf6Z6FRMF0qaZ7AIoNAj/xq,iv:JLYseUfS9zwhr/1be69bnE09NA6WW6iz7aRQwEplWKc=,tag:VXzgawVAY8y40PAIXg7D2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbFpOVXE1WWxzaHQ4VUxr
        QkpkSXdXdHhrNjc4SUhmbXVHR2RtUkFUc2pRClhvcEhHOE4xYWY3OXFHOWlUYmFx
        MFMzMmJEOFNWSnJTeURiZWVVNW5DeE0KLS0tIHVJRG9NLzVVNFNUN2trQXlZTlBD
        a1hQNFJHR0VhQjBxNjJvZzlkK3grR1UKzVDOItbn+IydiKxRYE5iJb33tHs2B5CH
        M53CGg8Qxy1q8Nd/rd9cKdLzn52tA4QIWikifPo6kjxN0a2UtMQA/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YTlMYjByQm14N2xEZnFC
        aWdFWGpEeVR6RHJRalVsSm96SStzUnZ4UkdzClZBYzJOQ3R6SXVFK0NSMkY0V2VR
        KzV1RUUxWWZGdU5XMUZpd2VGL1UxZWsKLS0tIEdUbjRuencwRGRhaXZEMExoMndy
        T0hmZHY1K1lDbEw3Ym9MWEJiL2dQNnMKynJLlro5FEU+WQhGGae1MgWDSsusFWj7
        PovQ3EChI9U8Fw849dBcLd1r8EBZLGzNhje+M7Pz2F4aqqbcYOh00w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbWhpNUR4dzJmTEFUQklX
        NndkdWpTZFcwRTBSV09KY0ZleGlqSlI3ZmxBCkJ6a1VkVnlkcEJXUDdrUWpZdDJU
        TlNuc2owc3AyZElmVHJJWk8vKzNYQVEKLS0tIC9NM1FkSzNNT09pa1ZMbmVQVWU1
        eUtRcTBIdVErZE1RK2pvNEdUQWJmSUkKSfY8lSnQ6g4zfTZ/AKya95xlwlHteAVR
        71+L/NuygSPP93Jl99N5STJQXssVVntoIqrehHwEJbAmXl4gsIVqeg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:EgIU6cQYdEvzGTEvn1In4278AnYlLZp1LIAzWI55fhF2/S5OpZ8cQaMCJLe3z0Sgeaomdyb659o1JD5lmUlft/1F8US9Tt29Wdq2VXYhYE58sxTdLrIjmWPQLqou+J6mBDLpbxpqzU4KJdEek8yNgfo/R8hhW935LnxBEsJ+nsw=,iv:fHEqziIsn69loyAdbpwO3lhABMbWCXDDuXp6rtKGsyw=,tag:cnbSwaLpE6083/k+Vyo4fg==,type:str]
  version: 3.13.1
