apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:DJ4qy3pPTYGj8qTJF7t6zSt3Wc9NMsQlzDovH/08+e5HPmaPLqu7AiArXFuEIr5tPHk84NyyWDye/ZKn/E3QTyQ0Q/6wP9IAkJMelGxdVkAxVUwB85oyy98lUxicimWRy0wKq8wdGgucwT3/l1zExDEpog6m+yZiFYS3lCYBQQT2E3Eo8A==,iv:r0Py82zLUrwJycsXAM95byunNatXFs/30hRZflCfqgY=,tag:Waks+ni0NrDIAtcpsHVuEA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c2E3Z25pckpqRzZnQWpi
        T0NWUE56TDZIc3VFdFlRRThGNC8xMkovWlhnCkI2RXNkc09TbFdJNG53VHAvQ29S
        VnN6Wm1aSDcyY0pHZ1E5L04ySmlVWEEKLS0tICtkNXFCQzc5aEdBTnJsa05jSXRi
        R0E1S0Yvdlg0diswL3pRelNjc3U4WjQKNiwaLK2PlyQ28m2HU5XYt9+Ylpq0wkSU
        AjtGQXCNQ8YTvnoWci2/ZWpHDEoifMhdWO5dJCDiTLZOlseiDy4M3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTXZocVlsYU9yUzdjaHV6
        dFNpZlgyUVpWVDJGZ3ZKb2VqaVpaVlI3V0djCmY5M1puSklDYmRVNzhqUU03Z1Bt
        b2ROdWR5WkN0MHpNVVhaVkhoODRoMHMKLS0tIEE4cEd4YWZMUHRlWHU3RG1HUktE
        TDZTOVp3TGF0REFEbTIzZ29wYWdRcGMKI/3gbf1Bu7wlnP0B73o15nHn6KoVhmWT
        w5/DewNgJyx3ROP4d6vTSQWT4Qkx48jM8at92c3UOeltAbqQdAcN8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbk4yZzNUaHdHZ2dISkcr
        V2g2RnRpTktJeEFZNlFMcEp5K0xmV0VGYVRnClVFQWg0VVJudFgrZ1RoZE1VN0ZD
        djNISUthSTY4N2ovWlEvdmgxYlEybjgKLS0tIGFlSWJ3RFlkTkVUUnJ1eThBS0pV
        dXQ1dGpNRDVSU1dJNmkybWE4c3pZcmsK3Ao++iFLaX+Rvq4jkPQdbyXXm7qr2Ed7
        uTCdFAMqZDfWtxeKFpbq5dV4pruNaHrdZp8pjtAwdrf9Ghb52o1vkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:Ym95mLKq8FyOqcwrj/1DcWhvuqFzFLrPQatGEubGzSPooeAS3qK/xrwXHUNhu/sevMcjXcvyt08j0XjRnvcLv1hKpJFuLsMyh+nQ8nCP/ivz+3+RZic5Otm+TVjTSt02ioRoyGSxJnGGdPYye0nH5Y/eyuChhjbTTFOCFdYpoio=,iv:3teuesY/7qEBNo3SnqdTVdNBAtNTZIYcparrPwTpPx8=,tag:bZGa73NR/wnnYYZX2yLQtQ==,type:str]
  version: 3.13.1
