apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yaml
configMapGenerator:
- name: ingress-values
  namespace: network
  files:
  - values.yaml=ingress-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
