---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-operator
  namespace: system
spec:
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: intel-device-plugins-operator
      # renovate: datasource=helm depName=intel-device-plugins-operator registryUrl=https://intel.github.io/helm-charts
      version: 0.36.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: intel-device-operator-values
