apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gpu-device-plugin.yaml
- helmrelease.yaml
- node-feature-rules.yaml
configMapGenerator:
- name: intel-device-operator-values
  namespace: system
  files:
  - values.yaml=intel-device-operator-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
