# -- Configuration for the RBAC resources.
rbac:
  controllerServiceAccount:
    name: csi-iscsi-custom-controller-sa
  nodeServiceAccount:
    name: csi-iscsi-custom-node-sa

# -- Configuration for your custom provisioner (Controller Plugin).
controllerPlugin:
  # -- A list of image pull secrets to use for pulling the controller image.
  imagePullSecrets:
    - name: registry-pass

nodePlugin:
  imagePullSecrets:
    - name: registry-pass
  image:
    repository: harbor.stevevaradi.me/stevevaradi/csi-driver-iscsi
    tag: "v2.13.0"

apiServer:
  url: "http://192.168.0.151:51084"

  existingSecret: "iscsi-provisioner-token"

storageClass:
  create: true
  provisioner: iscsi.stevevaradi.me
  name: iscsi-csi
  isDefaultClass: false
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  parameters:
    iscsiServerAddress: "192.168.0.151"
    allowedCIDR: "192.168.0.128/27"
    fsType: "ext4"
