# -- Configuration for the RBAC resources.
rbac:
  controllerServiceAccount:
    name: csi-iscsi-custom-controller-sa
  nodeServiceAccount:
    name: csi-iscsi-custom-node-sa

# -- Configuration for your custom provisioner (Controller Plugin).
controllerPlugin:
  # -- A list of image pull secrets to use for pulling the controller image.
  imagePullSecrets:
    - name: registry-pass

  image:
    repository: harbor.stevevaradi.me/stevevaradi/csi-iscsi-provisioner
    pullPolicy: IfNotPresent
    tag: "0.6.1"
  sidecar:
    provisioner:
      image:
        repository: harbor.stevevaradi.me/k8s-reg/sig-storage/csi-provisioner
        tag: "v5.3.0"

nodePlugin:
  imagePullSecrets:
    - name: registry-pass
  image:
    repository: harbor.stevevaradi.me/stevevaradi/csi-driver-iscsi-arm
    pullPolicy: Always
    tag: "v2.10.0"
  sidecar:
    registrar:
      image:
        repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
        tag: "v2.15.0"
    livenessProbe:
      image:
        repository: registry.k8s.io/sig-storage/livenessprobe
        tag: "v2.17.0"

apiServer:
  url: "http://192.168.0.151:51084"

  existingSecret: "iscsi-provisioner-token"

storageClass:
  create: true
  provisioner: iscsi.stevevaradi.me
  name: iscsi-csi
  isDefaultClass: false
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  parameters:
    iscsiServerAddress: "192.168.0.151"
    allowedCIDR: "192.168.0.128/27"
    fsType: "ext4"
