apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
- name: nfd-values
  namespace: system
  files:
  - values.yaml=nfd-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
