apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresdatabases.stevevaradi.me
spec:
  group: stevevaradi.me
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instance:
                  type: object
                  properties:
                    host:
                      type: string
                    port:
                      type: integer
                      default: 5432
                    adminCredentials:
                      type: object
                      properties:
                        username:
                          type: string
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                            usernameKey:
                              type: string
                            passwordKey:
                              type: string
                            namespace:
                              type: string
                database:
                  type: object
                  properties:
                    dbName:
                      type: string
                    owner:
                      type: string
                    ownerSecret:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                    extensions:
                      type: array
                      items:
                        type: string
                      description: "List of extensions to enable for the database."
                  required: ["dbName", "owner", "ownerSecret"]
              required: ["instance", "database"]
  scope: Namespaced
  names:
    plural: postgresdatabases
    singular: postgresdatabase
    kind: PostgresDatabase
    shortNames:
      - pgdb
