apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yaml
configMapGenerator:
- name: home-assistant-values
  namespace: home
  files:
  - values.yaml=home-assistant-values.yaml
configurations:
- ../../common/kustomizeconfig.yaml
