apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "csi-provisioner.fullname" . }}-iscsiadm-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-provisioner.labels" . | nindent 4 }}
data:
  iscsiadm: |
    #!/bin/sh
    if [ -x /host/sbin/iscsiadm ]; then
      chroot /host /sbin/iscsiadm "$@"
    elif [ -x /host/usr/local/sbin/iscsiadm ]; then
      chroot /host /usr/local/sbin/iscsiadm "$@"
    elif [ -x /host/bin/iscsiadm ]; then
      chroot /host /bin/iscsiadm "$@"
    elif [ -x /host/usr/local/bin/iscsiadm ]; then
      chroot /host /usr/local/bin/iscsiadm "$@"
    else
      chroot /host iscsiadm "$@"
    fi
