apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.storageClass.provisioner }}
spec:
  attachRequired: true
  podInfoOnMount: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  volumeLifecycleModes:
    - Persistent

