{{- if and .Values.apiServer.token (not .Values.apiServer.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "csi-provisioner.fullname" . }}-api-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-provisioner.labels" . | nindent 4 }}
stringData:
  token: {{ .Values.apiServer.token | quote }}
{{- end }}
