{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  annotations:
    {{- if .Values.storageClass.isDefaultClass }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
  labels:
    {{- include "csi-provisioner.labels" . | nindent 4 }}
provisioner: {{ .Values.storageClass.provisioner }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
parameters:
  {{- toYaml .Values.storageClass.parameters | nindent 2 }}
{{- end }}
