apiVersion: v1
kind: Secret
metadata:
  name: convertx-jwt
  namespace: convertx
type: Opaque
data:
  JWT_SECRET: ENC[AES256_GCM,data:RxIHAxDmKrRvhobMcV3S6kKuSI1Ixj86,iv:WBmXx73CXC0HX2bwKaZnukDwCJI6ToPIP0uJgFDQ9WA=,tag:2FydBq17kzG/JpGeO+K/BQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTGdMUE4zNWtKZFJWOWZa
        emlSMWVkajNlY3lFYm5yQVZaOGVCUitUdER3ClZVVzNPK3E2U1JEajVsRkFZNVgz
        ay9xeDVaeXhDdFJIZHhGNW9rR0duSmsKLS0tIFBSU0loU0xyK1RVckFzRGhDQzg0
        QnIrTXpQYlRPN3ZxQkxyV1oyZlZLYzgKPIFi/YSfmZpAPcVhwdebISiO9C+DFkgF
        0vkygznDxwVpBbrGvJ0Q184+qyv+ugun94vt7Zmw2Ds5RkE9qL22OA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVmtIQUt0L1dWQzlMdmZJ
        QzIycmVzVDM2TnZZMEFFcittUUNITExCNXp3CmVsc21lb0V0TWpHTXhrcmpFdjhX
        R0k2RUN2Zi9IQWdwRDBua3NLNzdNUzQKLS0tIEpNbkg3YkFpeGNoWHZwMmR3WmE1
        VGdOME9BTXVBTzU4c3FUOU9nRE8xYk0KehgOTnW3P+Z8+1aUy7moSRc5z6p1GaFb
        +p+LAXHHaZAwogz+JPvodUT1vQdf9EblW2eC9pBedXCYoHi22ftM4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ0lJWW5xeWJ2QXorK0ZU
        cW11UGN1WGRMMm5VNDRpOHppTFkzd3VGbW5RCnIvVWdteFNPbmN1ZWpsTzhSU0hI
        RnBGZzdNbFlETkt5NTNRR21aZVBqVE0KLS0tIDFHKzRBV0hjcU9BdXM5UmM5VnVu
        cytUZ3VDWkdqd1lCVjZrYTZZRjFEaGMKV4esJBX4jYsPOBFfZE1v5yeMO1A+Fn6Y
        ff+jrA+4pIoF+IlW/fyLjKvpkUqJfrPVA11SkdlisrwcL8EiaSC9mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWKzBRdzQ5aUNxMk0waVRz
        ZnQxVmVJR0RDMTh3Rmg5Qi84QVQyUWdjRTBRCjd3MEM4b25HTCtTS2N6VlA1djhH
        d1ptVTZSZnRaejFYbnFwOWhQaktDU3cKLS0tIERpMUZHVkJPa0dIWnQ3MmExSXkw
        YktrYUdsZFk0YUFHWVBjMm54NnU3cWsKDx4l4H3M1qNmhHMf1rg7nf1Z8cXR8QB2
        vteE62AiiaaFQqIaQAE8mf7rpsAUMZkSsBP3sr9jWwrFio2mIuukvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdXhablJIK2hMNGo0aVdO
        OHdzaTdQem5sK1RPU2tuYjcvcndsaG4vMG5VCmFTR0djTVFLOTI5VFJTb2puNWlP
        bnNZRldqb2JMeWtQRnYxSVM1eHppdG8KLS0tIDdONXcvelYzSkJseWZlU2Juc0Rv
        c0JQZTN1WUJzZnk3SG9YUkljNExRWTAKrkjtWzFWnL6qUP2mFg5Bz5KA7+Jir+7W
        ak48mOkQ/QXBgaYQgaMrDw1jG7nasP9w/djhD7NC2p+K3OM5DL2rRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMTMzUG1BcU4vVnJTKzc5
        VjFreWRtcnREcWpsSXg4RnA2ajYrbE56eG5BCjF3ZXdIak1wUE5KMUpCcE9RNVVO
        bEg1MEcxNTdXNlJUbDZoQ0pzbC90ajQKLS0tIFhtanhSZjRNMWl5UWxCdWZpV2pp
        LzhsRWF6WDZEZEx4OXViS0RmZVR1UVEKfNbKMz6cklnh4J6aj+26A4/Rz6KqgyGm
        V3uzF597FIKVvDprrmnufMHzRkiStGImxVLCk1v2H6WpDs9BnYaqAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTE4vbndkUG55RVdnNmQ5
        RkZqT3Zuek5PTDVsTzcxS2JCd1hVZlBqZ2dVCkZPbHM5c3pTQkZSVUJFaHBCUUk5
        cUc0NDFCYitCVmZaSGt6TFN5SW04dVEKLS0tIG1hYUw0cmxIUFVnNGNKTUVDZFg4
        cjhoWThrNzVHNmp6Yi9OTW9wclFFWDQKIatE1tBWFkauTOfZeFll8l3beYcdv+l5
        fQI2o40hxD0V2BFU7y7tX37kRHgPi28oJMuPMtqj9rrRd3YQ592ANw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbENYbXB6UHI2Y3l1VVht
        WjAxc3NoYitXV3Q5aDAvcEFCd2Z0SnZuQVVzCi9hVEdKb1hBcnJ4RHhNZDdxUmdj
        Zmt2eVQ1QUNUOXZyNmNQek94VWJsaVEKLS0tIGRTWThzZHhzT29WUGZtV1lGR3p1
        dmk5YmJOcTByTWVLMmlDd2pSamkzU00KzXLRfPQk01Yuz70PR9JYR8vO7TgZ6fvt
        KQwKyhgxjtIIkGBIJ4KA7eo/yRWQ+0HqiqGWJ2Y0/vOaIIvvRvPHcg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcERsclhXaElsT0JvY0M0
        dzl2UnRVK1Zhck1OZGRrall5OXpRUVdsUGlVCnhxL2gxaTU2c2NVcFc5SS9zSGVL
        c0pjQlJiNStaZUtXRjN6RHRPQ3N1bmMKLS0tIEc2OTBDbUNqUWNOaWlDMU9lcVNH
        dHl1REVnc0lEaXJUR3VrRWlNcUFkdHcKJA+Fo7TuQzbtA4WILRf4klf470Jf2jCD
        sX8VWoLemADRvSGhZYOGMYNIOl9S4uC87/i/JlgRY3z0wkDuibeQFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL0pPcUhUVnBFL0tMa0pG
        d2FRTU56WUp2ZHdZcmd3MTNLZTFsTzVzNkZVCkJaSVJja00rcUhWZlBmTXExczQ0
        K1UrMW9MaER0TkI4TitPNmNGaTNRaWMKLS0tIHBhNW5pNEVQWkFCOENVRWZJbDFH
        UWVJRjFzelpSN3FPNytIaWZJMnMrY1EKKmNHkDFhh7lvvmJC9J5A/txIAR0oANh8
        KbRH+rSOetMM98HYIExrvmE6wWy47MIRDlLFBT3t4PXj3kjvoZnZKw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:d/okNqzymOyi2VHBu1YMtZQ1qX7Nk4QY4ei71p4mryc9rHFY3wBg9pSzhHUILZlQqjLxNr/yta8LImBJ9axzPN96IS+pBzBmu36QxrmUtXG+KFfq901asIENKrOJFTO0BVS+kErpFUNvAOdOBcqeTN3c0Mz3Ik9RkpldArpa7lo=,iv:RC7N7iVxS+J2YK6CmUXKX37B4dmLjkShjGQWeLuV5KE=,tag:FIGciUGERjgjJ/BnPaS1ZQ==,type:str]
  version: 3.13.1
