apiVersion: v1
kind: ConfigMap
metadata:
  name: convertx
  namespace: convertx
  labels:
    app.kubernetes.io/name: convertx
    app.kubernetes.io/instance: convertx
data:
  ACCOUNT_REGISTRATION: "false"
  ALLOW_UNAUTHENTICATED: "true"
  AUTO_DELETE_EVERY_N_HOURS: "24"
  FFMPEG_ARGS: ""
  HIDE_HISTORY: "false"
  HTTP_ALLOWED: "false"
  LANGUAGE: "en"
