apiVersion: v1
kind: Secret
metadata:
  name: convertx-jwt
  namespace: convertx
type: Opaque
data:
  JWT_SECRET: ENC[AES256_GCM,data:MA/M9EhjKd0coQn0Y/RG7W8C0Y2T0CnU,iv:XUx0RC7nXJ9y48E2y34t1RGgZZmzMPvJGZ7hVsfUiD0=,tag:go2cYKWWqCQB5weBQti5+Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc0NkUHN4eERlcDVxakRq
        VHorZVY3cUlXVHZRekhKdW51Ti90WHQzWWxRCmtUak5aNTEreWFJSnNoRWhvZU9m
        cEx1b2pUeFN2R1pqQjAxZGdiQngrWTAKLS0tIG1FZHo1ZitrcDZKUWZkcy9ia0l4
        NFl3L21FemYxSlc5SGpHcCtmTUptVVEK/jFZvUBysovVdzoJ3aJ3TqVhdAXTuDh5
        vot8c+Jy8b4T1eJsdinzUb3gNYTUizjuym9bhdmlESmkY0L6a1O+RQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMkJ6Q1c2SWlwc3J5S0Rk
        RXpVS1Evak8rNDFtS1JzQnY4TG05VVVoYmtjClZaaVd5T1hVRjhwa1JiVXlpMHRH
        QmpyM2FhQ3gvZVdqOWdXc1RGbG5TQWsKLS0tIHdsRmJUZlBOaSsxTU1TWHpHUXJo
        bzd6aTFKWVNiWDc2WUhOZXROMVN6ZVUKdVtumOeImGp6VbQSA/1YUoqZd1ONCo4u
        d0i0gc1N4rB8RYyKX+ddqlWJrimEizxL/bHO6luHoT14dwcMSc7qkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNVNDRFRvU0VvUnpialJ4
        a0VTeUpNYWxUak1oeUUyaU1aTTRhMXdTOFRrCjZyK0tIUU5YZUV2S3V4NjZBWnFn
        dmt6dktKdGNmdWhtekJRZWFwMzlHNGsKLS0tIE5ET0hXTTlPOWVtZnN1bk5wTEZL
        ZWJYV1BoTlVYZDR6YlNKMkJpVnJVU28K/WNcerPxnpLWIk9MZs9DGPbDlZ73qmcm
        ygUDihKWXsPNgLShj6l6DmM3CaFByJ2bt25iyQ4Rp73Xjrdq4BtL5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:82ZegHazo68+A2BXbJ88B8Jri1ck+pUzeS6OVMZt+GSx0DaCI4dhvMYUoi0ttoe8iZwqACuycuH4+3VETfxxnLE4PR1SpP6WUDvdH9ewO+xAIaa2xE0b744DgkPIQxz0coB2OslWZxvR778XxnrfBJfVHMXB864QBL2QoeOoebY=,iv:FpeVAyiicQDHxxMYVJQih5EcJmHuOUFSHAAR/u/FiWU=,tag:EWJC2h3UC3zXbYMh82joxw==,type:str]
  version: 3.13.1
