apiVersion: v1
kind: Service
metadata:
  name: convertx
  namespace: convertx
  labels:
    app.kubernetes.io/name: convertx
    app.kubernetes.io/instance: convertx
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: convertx
    app.kubernetes.io/instance: convertx
