apiVersion: v1
kind: Secret
metadata:
  name: convertx-jwt
  namespace: convertx
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:mS0OyG3/46OgP+wlr38eug==,iv:5x5WUYxOjVNr+cIvH5JbTa88TD8wm+RYgSDJ9202iV0=,tag:dLILS2wP+DIdWtOogM6vJA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTTBsM3pnVTZnd3JiRmt4
        MUtKYyt2SzA0ejNIcG1UU0s0Nkw5Wm5YdGk4ClZvMTV1YWlEcU9IM0gzRnc5V29v
        a1Npa2p3bkZvM1RYdkxoRURTaG4wMVkKLS0tIFhETWQ1c2dDZml0SGNNL0tKQkV5
        MFZyYTBvKzRLY3lIb0NUZDNSTDZMa1UKxIUEHrenl/xVjEXqL556hxd2wxEnk6M2
        38wn9KtMtlloZBvPdgFtSOyFAtK8vy0YgxLnLt6IhOZzv++rpyHScQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYVlWdW9OOXVxcmM3WDE4
        d09EQk4wNjlYc09sSGZFQnd6U0VRN0pVd21vCjgxOVdCSW5lY3BjQm1Td1lxVmI4
        dlFQOHZmeFQ3WWxGby9IaWFWR0xHUWsKLS0tIHIvN2NpVXAxOVFvYkpPaG1xcTlr
        eUhZa1l2elZRRi93cVorcGZJR0E5TjQKh/6U3fBUZY8lS2BU+6ITrfQqkzcRg8jl
        dNSP3BqywB3aojUNZ/pzwaHDIOZC9UEuIiJhX/mG3U4VjzWbFLW0dg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaDFseWhTYjNYMEIwTm9I
        cnYxM25hTW4wNXRQblhlNnFlTkJ4NTUxTGtBClVuOTZUSFAvd01wRU1ScVNYanpk
        MzF6Nkk0VXJjN2xTM0EwTnBEOFpwV0UKLS0tIHI2QmdwbUFHeE5NdEQreC82ZWJt
        RXNENXpSc1NoUnp6aFl1RDFMczR0dE0K33ZiOLT8JoJQCie6kYKbJjSzvplJY6gs
        doFaEz4+FEZXqtLa4aWTPgC2HiZmJVIVzzQacdUws9r022My+pfBZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:1TQ7oNYSJIbNC14bWyFD8QOY3z41/6yzy0248Iuj/afBQqt4TSeY2grp0A+rXalzDbIMTSibPv5Uim+Ek8dRWUALTSEBiW6eObiVko6ggZN0UtA6eMEHvi16NUFMqyitVHZ4yPwYrJMTowO5WNxZJmb8ca9cqh7lTGjk9AMiW6Y=,iv:qTXBP0QAgTIDU9G106/BxoJ/aWn7QfqrGRoRpS2QM8k=,tag:v9Lh9v9TQsn1Bl57achrow==,type:str]
  version: 3.13.1
