apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: convertx-convertx-data
  namespace: convertx
  labels:
    app.kubernetes.io/name: convertx
    app.kubernetes.io/instance: convertx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: iscsi-csi
