---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: convertx
  namespace: convertx
spec:
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: convertx
      # renovate: datasource=docker depName=harbor.stevevaradi.me/stevevaradi/convertx
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: convertx-values
