apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- convertx-jwt-secret.enc.yaml
- convertx-configmap.yaml
- convertx-pvc.yaml
- convertx-service.yaml
- convertx-deployment.yaml
- httproute.yaml
- security-policy.yaml
