apiVersion: v1
kind: Secret
metadata:
  name: iscsi-provisioner-token
  namespace: storage
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:pI5W+n/Cfrs0kkYMBWk=,iv:6hyCOa8YcMuWZdgl29ZIj3vFPtBppJdnxQc9qWgL/5w=,tag:0UKLkIIWkDMvSehycuuwNA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NHdrc0p2Um9LTkl6Wk0x
        Y2lMS1V0RkQ0Mk43Tk0vbWN1ZHE0QXpYaGhjCmQrLzZyeWIzRmIwTC82M3ZlVDRI
        QWgvODFtRnF1bEdYZDZXWXp4SGc5MzQKLS0tIEh4bGYxTUZqZlByeUFMaDZpcHJR
        Z0E1bzlPYWJUVHdKMmpKd2Z2eVQ4YWsK6ZRoSWFJM1Jv8GMD21lDtUP5sPzRKtix
        x6PlRxT1W11tMcgiG0fJJD70AxGhh/iNuYnipaGb7fnuQjO5pFfWnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaTBtUnIzRGxHUXQ0SVN4
        T0tzakdTZFJoU2ZOVWtlV3BOT0pTMDVDM0FJCm9JNUJNMjlTaGIyOUtVWUVoRWox
        WG5PM3p1NDBsbzVtZytKODdhY0pHSncKLS0tIHVYTENJTVI0VDJCVm4yV0FTWFQy
        RENVZGIrWTYxb3puQjhoakR4WDRKdkkKTXlESGz/RW8/1srPoXOQvtBEfC1N08N7
        k+oxziAZFyEQscU6/lz1Y91AFG0Jh5UuKlPjRbnfpbZCiEj2kkgdZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcEdTNlhEZEc3Q0xyVWFW
        YWozc3ZPdkpLalNiaEtFTkJBeW1NWHUvZENjCkJTa2lRemVWYWhvMk9jeW5tME9S
        enYzNGRTU3ZtZWd1TTFZSlBOU2F3U2MKLS0tIDFOM21oZG8vZS9ka3U1bDhIK21U
        U2lhQkVybTViOTc1TEVFR3QxTFhPSEUKZocgrjpyxUw0c3hlJSusjjAjWHsx9V9L
        a4HzoC1KvYmfLN+XaJx6YUMJanCv87GGA7v5xXfzdCrzlq2qhf7beQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:iq6FFOjnWnlCa8BVZFCn4otGMvhuO6E1wbvsOfJtTOdcJ3gu4T+R4PKuU+9DnA6LeLZw31cyMyD5z6pAh4q+J7rCTseSJWnbeXA+yoJIBBrwn6faDphyHWazqlIlGICYKR/anxOTa6vmxEJaZsrLFcMmpcBGpyb3AZZ2why25Yo=,iv:g4kj8S7aXSy1TdGW5G6KC4ArFnjaN/z/8gAjuyVaFy8=,tag:fticpQwz2OngXT3RKoC+bQ==,type:str]
  version: 3.13.1
