apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-iscsi-custom-controller-sa
  namespace: storage
  labels:
    app.kubernetes.io/name: iscsi-csi
    app.kubernetes.io/instance: iscsi-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-iscsi-custom-node-sa
  namespace: storage
  labels:
    app.kubernetes.io/name: iscsi-csi
    app.kubernetes.io/instance: iscsi-provisioner
