apiVersion: v1
kind: Secret
metadata:
  name: iscsi-provisioner-token
  namespace: storage
type: Opaque
data:
  token: ENC[AES256_GCM,data:NvpxOgipUJruEqQW+6O+qpf6nGc=,iv:uY5CYt0IARYC9ZAZEnt/wqxbRqOHmHDYzSAkTmWAF4k=,tag:3+XtUpELoZ5AYLg8eLnhrQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFREFTWHEyNitPSmJTemEw
        dkFuY0tzQkJtNk9zUU44WDFVVjFuc3dZUjBBCnZpY1I2eW90ZDJ4VTdSdUEvQmhO
        TEJtd2ZJNEV6RVIxL3dLY3pzNE9oVXMKLS0tIERqRmtMWDJQMGkrdVJObml1WWFI
        WHprQzJyVVNuTEw5NWtDd0NrL2llUE0KkPYz0bFJFaZsHbUf99pY/c2YTWp76UtN
        f59dW1MUP2rfUUu3h/Tf7qnI3fFg1LQOcLhkzyf+lPnOvSy6u/XItg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUUR0OE5FVS9ZYzdTZitY
        ckRwa0U0ejUrRFZiL2RGdkVOVDZQR2hKaUhzCjRaL2JLMkc4aU9aZzZjNDVsKzVZ
        dTN5MjZUOHU4S2xSMnI0dDIxMUpvWkEKLS0tIGVPYXZ3amRwdU9jTi9xNDMwL1Nh
        V3ZyMHRiQTAwNFFCNFFpWXBrRHBBSWcK/itjzHtLG68axs0v8WfBvd7cc+HGbQcR
        haU85dYRnM8IiBg4VcyZIgvLJxPwDpr0yI5tCKYdMTIOfZpvlL4M6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieDZMQ28ySXJhUENBaTNn
        L3I2b1NsRWp4QkRSWnJnME9GbVAxbHp2QnpZClFMZ1Q5QjArcVlGeUZsK2ZyaDY1
        RkQvb3NYem03bTRHSW1TTFRSYkZRNW8KLS0tIFVDOTVVRUVFTkozS1B2NHI3aWky
        aCt3NzhpelNzdFQzSXl2alh3M2oycVkKMyOVgbWgur1j2/LJN837omhuAOhWt6on
        fRdwnUMI3ba36xhHrrB4myZncmh9JfHLl4DPUuDgNfWypRTin/th8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:rYCCi56YUO/wGW3EGLry+fxLPHjblN0TFzFf0aFKKWu8bE89JE6n4/WzARDTiCfS/krV6uQMCJGXgbhLEhQg/IYgHN82+HYRNkD4lwNARGTNKwJHCqR8MMgPx/nFEUS74CudGyWfuPn3O8eKen2EhkIUIKLx3uE5hHnOHnUtm94=,iv:BGm3GrpNCCsFzQdtyE9RoO2TNiOaRiJQso8zDjPdBe4=,tag:UVOyrST/n841ZdruUI30Yw==,type:str]
  version: 3.13.1
