apiVersion: v1
kind: Secret
metadata:
  name: iscsi-provisioner-token
  namespace: storage
type: Opaque
data:
  token: ENC[AES256_GCM,data:GRKMN2YK48nWpfYpld0/av448RI=,iv:I3GOsj3uYVnQh+rtLg67bWbSpgkYZejk0CdoLFSj1ew=,tag:ECZppP73irevYXh/tbzfTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SUxha0xNZTJuVDRLYmtz
        WmgycndhSldFclRiNkV5QnBJNTJWanhGbWtnCktmY1FxK1liQWtRQ2dTTW9oeWl2
        MGdPSmp5RUtzZ0JKRU5SVEdjTlRtMWsKLS0tIDZqQldWem5GYUx2K05YUHd5K2Y3
        MTUrSUhveVNHdjhESDZGU1dCVFlHRlEKIopqh0lvGnMQ0KEZld+akY0iZ37twLdM
        d++n3bPNZdTb2UKw3il6pby/0y8WypMpBol7VpPD9VFr5FKGPs6p+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Q1JHa21BQi9wZkliSkRr
        WHJYbGw2ck9lYWtBTFJERGpFQUpHeFh6a0FBCnc3R2NFUW4vSHN6SnlFU2Fha0Zj
        emxTYnBaTWZoandzV2tDUFpQTjR0TVEKLS0tIENlVUYzT0pnQ2cxWEVnVU5pNUl3
        dGNLQkFGWndzNHFndU1oMTlXbWJyWVEKPFWwQSvCoEvR4wtD/S++K6DFd3E/KzBn
        og34tVfQJoaPcZoF6YCkn89I5TxWfgERN0r4LlYEwDXVvBPZObB/kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOGRoWTBhb1NjSXd2eGw2
        aHFKalI2TVlRZEpCWHp5aHRNd1FlNVlsZVJnCnlZSW54RmZ6M3EyeE9aSU1oby9j
        cDl6RGs3OVBSZVd6RTFlbHhJN0xYbWMKLS0tIDFzbHhnNmhTVlhPZ3VBWTJZVll1
        aG1YQko1SjFkN3pLajZBUnVxaFVmc28K0MsbA6OA7jqbfFC9IhSn381WQ6afKhGX
        ePEBfdNJxPSVQhYc5hdQmbP/BfCt9a1LdCEk1xmHmmPMjYEZJ7DzMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQm9Ub0luRndvOUZjcmpB
        R1VibkowcnNPd05XZ0lkS2gzY2YyZS9rdFRZCmxLTDFqZHpocFhwaDAzVmpSbTBV
        WXZWWHVVZTFGVFJPbjFHYXBpdzhIKzQKLS0tIHJycTVoc3F4WWJtanFxM0psbzcz
        WjdNREhoVFZoZkJENkRmMVhudTZnMlEKHrA1CC+a4nGCHBHQaVvBgbrJOhrFEUz9
        43zlP7z+YK0Gn9XlL86Hnzr/FORU/oUivtLpqwChhVWpK7tnfgSGIQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaVFJelAvb2c1K1U0cDhG
        NVN4a1psaHg5bDV3TjlKOWg5ZDkrRVBwczBVCmhnV2ljTW9rTG9TTDNJRkl2clNQ
        RStmd0YzdzVLOUwxTnE4NjBuajUwMTgKLS0tIDdKVDdyK0w5MngydlR2RUsza2ts
        b3FvWUVIaDI4SlRwK3JhLzkrSVJRY0EK+u0YxtFIvrmuY2vHflcg/LNUWavqa3Up
        9Lu4dbIYo+bghbGrdu4cWrMhmLArrB37X1db1Ihwa1ATYmX6nxLUYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL0hoR0dML210N1hhak9U
        TDJQZDZ4R2hwZ0ZLN1gxeDV5QzJjeGhBQjNBCndYZ0dSdzdpc1Avc0hPVHBCdnNw
        NGxkZUR6S2t4WXREdFJDZmhhT011LzAKLS0tIDc4Nmc4OFNqRVhRNGtEUnlDUy81
        aDcwMTVEM21GK2p3ZE91SThRZGNsYncKQ8zDraHSo6adeKdiG/iNQGXTa9MjkRZe
        63dpTqalvpE4tdQV4n0qIzrDlgV/a7PMWmMyIFHe9h1YCOoGMdZDgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaUtCeC8wWEFlVWhpSlgx
        d0Y3alIydWpmaDFNemh2MnhuUmRmTnZJb21jCjRxVmpmL0JCQmtrZ01jVGxhdmtM
        SWU1UHA1M0tnOG50bmpDaDhsLzYrd2sKLS0tIFVpbmxGZ05kNVFHQmV1WmwvZlRW
        RWluZWZ6eE1KclUySXRvTWFUdSt0V1kKnAWwTwUrDWEhPsrM4136x8z8ZF71+T6u
        rdN7+JwsT3ooldrwzk2t+sWOkrQuBnz0DXYr0GzY8EfV+VlMEKJVAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWktCR0dLeUdmcGVBSG04
        c2w5T3BPREJ3WGl0eDNPbU5zYnh2akplZXlFCk5Uem9HZGV0bXVJb3VpUnIzcnVs
        YmM1eUhsS0FZWW1GazBveERhVE1GVEUKLS0tIGtML2VZUUtMTDFicWVMa1kvRWlt
        VHkrYzEyaVQrMExTN2NqVEpzYTJ5eVkK0fkpXoGHUUVbwvq5iDUesgv9yuZmKALk
        nXqFAkZkBzz9YYRB1oVKjQ6qvXPUycLHugj3hHZxhUsSa8I/U/L+Fw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdTF2REhNcWJmendmYUVh
        ZWJYbWt0RDFqWUlTVGtFOHRVcUNTZHR1elJZCjVQRytsSllTR1VKZnd5bmJld0FI
        aE1CZUtUTXQ3MjNXajJsSHV1dEk3ckEKLS0tIFBTc1FiWVFTeTkzL1pxTHYyZk84
        d1pRZ0ZWM2k1MXNNZ25iUW9zNzlzR3MKVsd1ZwOq1bKc1sdo/JPSmFSO80o2TqWL
        6WUKsw7+0Dafs27WS9zdxhbX13fut6raKt8QW+HZskXTP90VSQLieQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M2FGQzdVZysxV3lRVDRu
        TkVJcUZBN1pJRzZOR0JRVllaUHl3SWdkY3hvCmtzRFVwcXdoOTZMd0oxa29DaDI0
        YWE5UGFxOUFiTi92MFJJR0xaWU9OLzAKLS0tIEpZSjJkaWI5UExzbDVTa1E5WU9L
        VzNUVmM5VVdaMzRnU3J3UjBvekhsUFkKd+SvNkR9s/xF12lF8EVBGLbBBaCoMY1O
        NvmsS39AE+5IUg4t7+E3xcwB91GHnEeebJdZidoA9yvdRJENnRnLSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:DLjyHusiar/XFALvuXe2w358nomPcvHoFrhNpTXuxpfSN/e51FLcVIUqgz9N2eVMH7lhxbeWk+nj9rmzjXZH4kaQ+3eTP4poY6Agqe0IpQvC1NFhNxj4ang1Il8yzLxpmpmstIaw+RnMopnKPHE7m7LiWJDKEIgF0VB8l4prH1A=,iv:/8Dk85K8OV82Odp7qPPAtEkUoYaeHoIm3SWbvt0Zm94=,tag:4MI/YIaKe8I3oeF7TK/rjQ==,type:str]
  version: 3.13.1
