apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- iscsi-token-secret.enc.yaml
- registry-pass-secret.enc.yaml
- iscsi-csi-serviceaccounts.yaml
- iscsi-csi-rbac.yaml
- iscsi-csi-csidriver.yaml
- iscsi-csi-storageclass.yaml
- iscsi-csi-configmap.yaml
- iscsi-csi-daemonset.yaml
- iscsi-csi-deployment.yaml
