apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: storage
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:EuS/TUX9d9H/ipWlLKGhxQkR2qc9jLJo4eqZGCyIs+Q48phny32jeqHsAfPx37yFEGnO9IZ6c1K5o8WB7OS7ls3y9eMkbLFZgMFdawmEwj6jRlJEd1+pOW25Pq5Sz5oOmfx9gy9rk3LXHeJ9hFtJBGLuA97qCUNzwqOa2kUu+9xh5cn7GMKW3C5PPrlB/Kuc5yga3YFcyys7/XDI4IT24i1rBAVJ1Le56FxM9hj8CvBWUnsU,iv:tfh5wC5Ph7Q1rMwGRFFyJP0SrfgUxFjw8vJkHtG6mzw=,tag:CaPU3FRG9xwCX7IOHUDlMg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZjZpRFk5b1FnZGJacDNV
        V2dFL2N0RW5qVUMrc3JxUnV4eGRTQzE4NndZCnBWOGY4Nys0cmJDUmpkc3gxMTIz
        b3Jib24wOUkzNFFuWkh5SU5DcDlwUXcKLS0tIGhncllvSXFMUUxXUzVKR0J4Y0ox
        dmMvdzkvMnltcGRHWGY4ZDNGZkRkeDQKKZw2IkUB9vOs4VluPweXEaGoazNyaOcn
        zdcG2z5AzzG2hkfbizFq79dBXSwqq7K7UFdyRjxPRpXAjyYHFJktLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNXgwRlB6dTBuM3pPV2hx
        bVh6eCt2UFJjQzRMK2FYa1Nqdi95UFN2czA0CjdGYXRzZ2JkdjUwWE8xaEx0V2c2
        amRVenlSTUJjVGN6QkplSmJSeGVTMWcKLS0tIC94d0RLRys4L2hSMWdyYWJ3bmJL
        NXdzM0NpdHVnSkZNaGhnenpnQ2RzTW8K/W3XE+t7/Evn0/oCk/c6QouM3AnbknGY
        eeRWhStOdFqYOgSF1sU6Vs1HL+/kU4UPuTQ/DlaeoOwY0cSI9YkfTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbml2andYWi9lc1lwRytY
        UUMwelh1VXFUTmpZTGhMTE9LMG9wVWhVWUZrCjJiemQ1YVVZYmE4L2JUVURHMUdQ
        VWp6Ulh4RWdLYk1wbzZRRVUzZDBRbncKLS0tIEhLUVVzYnp4bDZFbTRTL3FjNFAr
        OTZTemZham0zZWh4eUUydWlRVWkyUHcKN7CnXlQYK7aoNst3bNMmstHOKyx0hWOn
        pFWtSOfNhJjOiLOLYZciqhUiFY2dOu82pJq24PBTnhY9pnouskJcpw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:kgYb1H6851Z2OqwuKAOh4lJJNlKh/fAi4S/KTMIrglRWMwR5eLrd2+ypTJcls8OsrDNqDbnJ8P8lgNN1P4FGzAKOAtAOuWd8RXwf2TU3kT7c1nzB7vTYQY3C0U46si/ef74MXU5EfoOz3kdSbjF45UaOePQhi64us6UDrbJbN7E=,iv:bsXxkKU1YmnvhtH7I+8sdvIIriv8OtpY61nP+r9I4n0=,tag:G9u0jrOOOQM4jRh67XaCQA==,type:str]
  version: 3.13.1
