apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: storage
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:0qYiMwUBcufPkI9zYqHtbHdRizofqMBsCtUH08g/ljDtOMC9giBbM8AWX/WJTYo0+20lm2ZCXtZWA85kI6omzQiaN/A5u1YnYyCrgrHiHuC0CnUMuRKuFW/VZxV5k/xlWq/+vcOBbPxtRTmDbZj33s6uEUnWootXUXhAzpnGv11pjPL0Nw==,iv:/Vofl3cnVFauNd4TXE8l48FTShN8ZiPIx0RjxyfLovs=,tag:02uyurBe9Z72PRDb0nrCIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRyt0Q3hEaVBUcVhhQXdk
        bjdlVURVbTQ1a25wUjFMNkdRYzFZdmtkSDBVCnRyRU5GWFI2dDBWZHF1WUo5RVNG
        RnluTWdIczRaYVo1WVRFV0o2UHQraE0KLS0tIDlZZ29pVEFkckVOalkvdEU4TUw5
        Q0dGbVFXQnhTSFdGZ3djWVdEcU1yRFEK8CMiaSSHZUJTtd7F+kKtNpljJugNe19Y
        AZncZ0ZjuJY3mxOdMdsPWTp9YgFDhaA96cGLz5+eTYxwUQJZc432iA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b0dwWVQrNi96VjczQU5i
        S2NWY3QzNnNJcUpvTW1jalhneXg2ZTRCMkVjClQxWGRERnpucnJJUG9ZNlVoTEVP
        WXdpVG5qcFRVTWNncUpEeU9YZG1ZT0EKLS0tIGovbTZ1K3ZVbGgrOENjUGs1Y2pE
        d0VrS2tsVzF2Q1hxQUtWbUN0TmhIR0kKJXPaqH1dnRmE0b/FuR+V8RDbd9ZnAwmd
        dfQOBc0+WmKgeZ3igeCffrqco7XI15g27En9mPNRpDkGhhviIiKVSA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWjBQUENuZGNpMzJIT1Q4
        K0djMG8zenhsRm9SMDFrNXlLOGdhcG1RWGxnCkxSUDRFK2k1NDVITWlyR2VGVnRP
        YkRwTmtPUUxabGpYTFg4TGVZQ0hqRXMKLS0tIGRmL1UzaFI3cEdwM0hieUk4V0pC
        R0hDWkJ6UklIK3g1bm1NL3QvT011cE0Kqn8MWOGnfDQ/0jaRNUhGXX9E1qpbignm
        R6pcLGyksxURim4LRHqPTwtzmu+vsngIBx5yOLq1xynkkdOYY6qOwQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:JlXBtXvXwJOKGgNLw1y5hFOvHZPrynZ1Tx3mXPUXVkO58xalpmikNfLKohT/8LPv0yc4WmOxVwUUpoT/Mj8kNRIgBGhZgJX0NW9DAjSfsti2zYDvgfelZLkWakVU54spsI3owxVAib/6ijDrWh3sPz4k1js80Gl5lOA2HVaSuZU=,iv:ycXHlLcI/kfSSUz/cX1r4DgHc7byyJwGWmuO54DCmoU=,tag:G1M5g9VnSdfTrO6ZQGDz4w==,type:str]
  version: 3.13.1
