apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: storage
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:ibmwQqMVRl8lDTn/1KCMmwqv64RNhczEAXF8qVZKAXNC2F2E0YETB9RHVim6mTY5+PbMu10bbkW5nfsk+Dgsnq/aLf3yXL+/pz4prxxwQxX0t9MTwjHM6n3nqIGAS5lO1qivD7+S33ZZFpDGAqOirrUXWbUQH77DZEgsjcTbY57NlzBAhDTzpyNoUcD1ulCiKK2+IYHKHvRVUeP2lfLWupZgk07Dn4myYuVyGSJYTx0JKSH3,iv:eP8hwt5JokeWiYnFDjq/Z2V2sv2gafPxHUhiIn4eKMQ=,tag:JDS5YD0T6KAdccSsIimwwQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a3o0dnVlVG1iaHJOWVBx
        V0xGSjJpNGRRRUxoZmZIdGwwbU80L1dTV3pzCncvTUF6ZzQ2c1U5NGRaL09LSm5F
        YmlIdlZTb1FEQisrWXBxK3V5cjhSMVEKLS0tIGV2RHdhV3MvV3RUanArSlI1bVBv
        cFoxRGE3c3VTSkJZYUgvbFB4SG1BdDQKdpYxGWM0OOhyqU02qg3M5wle9xHFuANv
        iT/heym2ZWqrBb6tU/56Bc7TIcMVwfaePMV7b4oGTZp59DvmjQL8lw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTFRLV0xsUUVrTTZwS0oy
        L3BHNjh2c05uTk1PN2drcWZzWjRCTGZaakVJCjhTbDVBclFMRTVZNUVFUm03dGgr
        VGRHcjUyNS8va0VHREtoUS9sOHUvYm8KLS0tIHA5aDkzdFljdEppMWVDZTNITXl5
        enExS09aZVpSYjQ4d0cwcVE0WGVMbkUK26CxJ9I1FwPjuOf84gtP5jfzP+zFDg6d
        L9hI5enbXOztC/WgKI4oaKM1bodGbJ+HqxaST+ZUsFI6QsDL2ioZzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNnlNL251dGh6UmczRHdZ
        SmJ1Y0RBOVZxd2NRbENwbUlrK1Ztc2ZKVVVzCnFQa3laMXowN1dHWW1TYmZyQkJM
        SGU5aEpPMVZ0Z0lJU2JON1BhTHZmN0kKLS0tIDdXd0ZoTzJPUW1QY3p2dFBJWkR1
        UTk0L2pwbHRvbnloUUxMbnVNc3djUFkKv+qW2Res0FOt55olQWXF5XH72HYYvqYC
        5ivDvIUVP7WmZpU24mq3dP6JWHqquVL1X4L9nkksXRkXMPAcoqBi/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSnl5SkxGWGp5dVdJUXZj
        clF4NklyWHc1N3ovU1RWaDUxeHZxeHBZaG5rCm5xSmJuL1p0dG1CZ05HSmNXU1Fh
        TmVnbStkZk0yTm0wYkVuMXRKRldRL2sKLS0tIDRLWXZTNExHbTBIL3dtSnFjV3Jz
        STlLc1Ayek96VnJkS1BRcWxrcWJkMlEKoARWyGZ8ihJVxMszPBmBOE9BfG0KKsV7
        hOmStDvZR1T7327j0myuwiCHFOP1UZcmSEPFXHuEmzusJLhCh20Y5A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndjVOL0YvbU5MVVQyRzZL
        QWZJRy9sSFRxYUVjREp2RzRlN1ZpVUNockR3CmtYeEVoKzdxV2cwakY0bWhEZHBR
        b1lnMkpScFVnUnJlZ2E3VXNDK00zdTAKLS0tIHZVN1hpNWtLNGxJUFdqLzJLOW50
        WEhURDg5aHZFUE05QmVQM0hVdXlLMWsKf7uJQIIwRjKH0yTydGf66sJCoh/MAc75
        jrY9Wpg+cYyadiAsLj7VCd22p1Se4yETro/7DboJu/DO4BDKVXivhA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRWdsdHdCZFRMZnd1UkpU
        aDNhK1Q3MFE5aVBiQ3B0VGhzVW1UVDVZRDF3CmNGaW5LQksrRDlmQ2RHUllBdmZQ
        TFZkbVQ3TVpGUHVRRklKMXpWaDZGUFEKLS0tIEx3SW5XSWpRaFplYkxYc1RoaFdR
        dThzSXBaVE5CejN6bFUveWoxNHFEazAKW5mje8iqQo/sBU1/ZvrzmPPNQPwajsQf
        MbO6GQ5H3yoGJOMujrIvQW0+3cdxw0zOCD3KSauucW0DWSeURqRBRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUTB1R2lzSSt6M2cvcWUx
        cHdhMEdSdFo0cWY0U0Z3cjBFKy9BNFAwQWxRCmgyYlliWHdmK2RxQmtISjI2eVVW
        Y3d4NUExdVlHTmpaeVBIVzBrT3lwVXMKLS0tIGNWK3A2OC95eUs1OWhsSi9Oejk5
        M1JvOXVtdW1FWkVXcFJiOWh0dTlaVVUKuMt+c97S/UR/AsHrJmjms7T59UWa+x51
        fwPy4gm5AEdT8iIqiFLCLkxQS+GPYKEgci3ig0oOkAWiBGDh810Vkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeHM2WEdFczE0NGJnd2lX
        ODhBYmJYMXNCZFM4S0pRSDlZczdDcEhTQzBFCjNMbUNLNENGMXFyd21mdER0MzJn
        ZWVwMGQzOFk5MXlzUW9YSGNQdng4Yk0KLS0tIFdBS2dwdHlPcStJZ3hQVXlzOE5X
        cmRlbmNaRjdVRnNJVFZTUEh1Q0xXS0kKMNO/vF0QSlxKFUokI9XHfIQ8QY1bTa+e
        ucw50cEZCnGbcJOeJ66nLM5QXyZpYGMNuukZFcve1PghCtX3eyevsQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUFZoazM2RWV4MFROVXZj
        MkJPd3J3cXZqWFB6OTBaeTZtSjJ5OEkrM21JCmpuVlJCOW9ublFUWWRkVlBORFpp
        OHoyK2dhVGtYTHBucGlxNCtWZ0JkRk0KLS0tICs5d0Q3N0JucjNEZ29NVERtR2Ix
        QWhkUXdscjFkY2tlWElUUDdxbTE2OEEKgZMJ23r8lvl4cfsF+8gg27BaBH4+GHc/
        1WbCX28rimNZKk0tg3NKWSLO0OGRa0RyLRHdrqAsHN2lXK7VoVImEw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNUxtVUgwdEd5alBvL0J3
        QVFJTkFHK2I4YWpCOVFncG9RL0J5M3N2UFdrCkZWbUlRNmlhOHMxM3UwbzlvclRD
        WmJrN1FKcGYzWXZWWlkzSTJkazFXcWcKLS0tIGdHZzdEN0MxZFB5Y2Jsc0VPN0pp
        cjg3QTdQdXUxWjl4bm9QeC93RmUxdjQKSCaAlyV6VIKUT1vPlK96T5Biim7m7oat
        CuCIhqNJeah1I/vLyevwzhFvB9aQkV2Ed5G33xQzPS/htWJiHhmRfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:kuu5uwbPEw5r/qMMIHQjLVHCFsvS+Z+z67c3bGyziwbNFRE7PphkRsgPx8hP0MSKvuHz2rtiDGqXAW8mfPGI7xTovWghxXc9Fhb4nK1iEHIC8BnV+0C4egfLaNTuTCxHN/UdNrKI1axgwBUwT1rRmJ2OyAhZQX3wp1s6WIQS+NA=,iv:/5Qg0gWjqY4OE7ZVqVXT4APxKz7xLw58UcgRweLVqvI=,tag:C2svNttlnjzSaiDVVPGj+Q==,type:str]
  version: 3.13.1
