apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: automation
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:hmSpLDBtn0aZnJ2D8ezPcOUhDedyxJLN2cndk2oLAB0crR54pWBdIr7uGKpdI3+nU8iv8Vw00ITH6GCemHt0Ernul8KV+QGfQBILWIEQfpuT+D4dyqUkNJO9DpdAMUJKDx85AcMLcDHM5eVFYHA9RdJzIIBuC3zUpify9tP7j1YAJ4cmlg==,iv:BoN7sRKvIOgVhN/wwsYJw+boFysAqJ0tNZhPAjyRr0U=,tag:oDEJS/qH6flcjelnmASqaA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS0F3Y2JhSVk2VU5WU0pw
        d3EvMFlIZnpnK0tXbXZIbDFLZXZxMlpOc0NNClQ4ek5iSVZoMlNpZ1kwL2JPaCtU
        cmpnb3NXOUczOTFjdmlUQlllWVRXVkkKLS0tIGlhYzZ3UkVBYmJFbXJDbUl5VFZn
        bFVKUzYxdVl5eTcza3Y4NmpNQU5WeHMKqCgZA0c6sSwe5ZUruAJVzx4reRPJurrI
        LmyjLWq9o8/vy9zrD2w8KzdInaUA2duTW9mJOF42aXdBMz1E6viw9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaGF4YWdvTVhwdEdsUWtL
        S0lITDNzNTBkVERMZjFBTzhkZ2R0NkFnRnpZCkh1MlM4dGNhV2RKcUVsSm9oNWlm
        MDFXUTd2bVlVb21HSnpsa2tVVC9CbzQKLS0tIFBFQncxQzQvcEI2YnZXM1RpV1dG
        MU5Mc0FOVnBBajlBUnAxRThNcnhUeDgKhPpQ2srqSic/qbhz5F6YC+uoXfJnSRm8
        4UbA/DRcw4B3MdoaybPKV00/jhDI+meRYEbxhWXjtijykbxTejNB2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSWQrYXFuQSsvbnFqYmNh
        cGhxekFFK05kS3JEYUNCbmh4ZFlkaEhKZDJJCitNZWNkb0FLUWZ0RnViQ1hNZnRP
        ZDZqajNiTkYwZU9jNlNmMFhjSEV1SEEKLS0tIGp5R3JEcnJzaGMzNDEybHJvVk1F
        TmFaQnJFcDBHd0o5bDZiaGk2WjB5Y2sKWj7eNHj75KZCLocSId1yjtL53GA/WZru
        IJA58241sA492th09poGjkPlGf5dy2d11UCyxPsCmpzI65xDCK0sLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:13Z"
  mac: ENC[AES256_GCM,data:SlenXSUS7Fbh1PjU18IEMHUaplda0mPnVcfz4OtgBhJIF+6MrR9wkB5q4RkJRlnr9XNAiOzkkSgRkswvV0oTr9ULQ3fJSkW3Zv7iF3LfrSdC5D7aYc86pGA5Qbh9l8/lD1sMb84xK7mpz/lxvyQfHqs64582spawSjPoo5ybHWg=,iv:63eJ9XaDSWPZH31KOlz5VcWKdnIIEzqosjo4rnfcEw8=,tag:2/f/l3EybFyWHIz/mXfMag==,type:str]
  version: 3.13.1
