apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: penpot
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:jvL8CFAlUaY2Tz/HsEplrjttC7WYrz31o8Lt38TOf8p8/Zzgrztko5lk9qM/2uyms6iLpE/SmfE8eblakmw6+a83lmc893XFtozBoAj4zW0NzgMFszhlWsn+f33MafPvCnRDeXSAE3ePwirRz3sZ3C1mWmD8WOqrBp1Y6+qG/WEqz3uRkzxlICZGVUIn7h1OZe9QAE+5VYEeCDukhPbP3i4lGWKEtujJ7WO7PKGRIMGVUbcB,iv:cYge7bNyLyg7uX1PcXvvGzrCyp+Y8AsHYdSZSUw1E2s=,tag:sRW2qu7JS0hNRyrbZe+b2Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOERiUFI2WVdZNW9ZaXVV
        NkR4SGtZTnBUWlBEUWZETVJNdVZ2czgvM2hzClZjVGJnazJMTXIvb2lHNEk2U0pz
        M0lSc2pSd05rUm5pbHVqR2gxaHNYVWMKLS0tIHQ0ZVRJRDhxbzlCT1RNOExRTmVE
        VkI5QU55eVhGaTRzZGtkenFCdUJLT0kKLlTgSH88Q6IK2Ca3x6p47n62DGXlOmhG
        Ju/SuF10Y0NQO9cf3x44XWzeEhxhgN7d3YpcmoddSdDmtdjgBzDqLw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUE56U3pGSHpId1JZcjhn
        dThGV1FKaVB6RWNBN1kzWkdqanNBQ2VlR1RBCkJDZWFMYjhTL29zbkxSSFIxYXVh
        QUpxZGx4VHR1OHZ5OXMwTCt0Q2xtRDQKLS0tIHZINGZHeitvc1VFWHI3MEFtNjJS
        K2xkQXd0ZmFFRWpSYkt1ekp6MXB6dm8KcejVri9vd+H+UD+HjgJ4sF7LGYdsrN8Q
        l9YnOQ9hqMVreeoJoE0ZozZQm5W3aJNZ2hmZa/DpoPAELzlYNpY1xQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSXYyYjhvdGk5ZmQ2KzF5
        L2hGWVhHandXajVZYnp2a0VwazRaTXI5Nnk0ClVQVTl1bnBSNWkwZGN3aWk5UUxI
        UjRoQVBjTDcvVmJWdDZJdUdCVVlvaUkKLS0tIGNHUTZld3kydDF3K3JZZ08zQWVn
        ZktZeDk5QWdsV01DaDBIN3A4ZnExT2cKZD0fuJgX7UZ2UN+RMUWMHiuucH4SshYp
        1xBDRXaQJ81BJazN8/CyczGcLkxwBh/v0U1JOCO4wXun5+O6ABIheg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:pHV4nTgNdZEhgSSmv6IBoRPsdwPAwp+YrVQ8orbC8kfG2T4U0g8zKDIXgF5sQ0X4G8SGwLEFC970s+wrWDVoRVXP2I7uqBLloyi9+fSD2jGG6Y155bXv61LHFxJjx2in1UEMUgYvmVT35oC4l6jSfbj7auQAU2v+t94P0LhRnbo=,iv:Lr/6Ez6s2NC6G8Zusou6gqJ/cggPFF5j0zmfUq6E7qg=,tag:E+xTlhOi3yxGJPAD4jiM9g==,type:str]
  version: 3.13.1
