apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: copyparty
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:MHE9m6lVrSzqLS0nfSudLMrKsFGr7yR1Ri0NNqJH0QqyTCdLgWL+32o37G/8DQhpnANmdoiXSDH0/7kJxUlxIKdEYm+hmtVp4IbQOn4kdEgso9d+R5KQ9U0aJFIUtP1a5QqiC8RpLqOKmAq3IbVPIemVnEQgGT6E9A5KNMUW5SioCv9Rfx2NYtRMYZ1oLBamRmn6CRI1gS2CJ5uDFhviX13scBD/wxM5bHpgMEkJJ19Ex5s9,iv:5G8z/9aFHdLN4wvvT9l9TeZdtcDwr60+0uDz0vqNpBw=,tag:lnaqKZhfHLps8Ada63q9wQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ejdSYk9kdUI0MkJ0ZGZI
        VzA3VjA1N2kxOEsyQ2VtSHhmd1FHNjBpN3gwCkQrNzdiU1c4MmxqdVlCRnVqVlZo
        ZUMwanNCUHFXdCtjN2JDS0h4a3czQlEKLS0tIG5aNUlXOVlPUXcvc2trV21RZUc3
        L3U3NU9qbmNXL01HQmtSV3ZuMUJXNE0KoqBJtZ+JMIBjmSkyp0u6P1W4KnmQKlzw
        CuaZrhJkvECgCVhHqpQ0AV6ZPDq7AGCs6dfS6SHz2XfGEVu1GM+3jw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RExaZjc2R2lWVUp3N2N0
        cG1IWElESkd5ejIvNTlFQkp2Slo2dDdNbWhnCnk0WExxTElxRll0dTdSMkRkakI0
        cHJTbnF3MDg5WnRiMHY2Qm5kcVBPWXMKLS0tIFNrcHlEWmRHRWVLaWdGWWJhcnpn
        SnY5TXVtL2ZPUkhZais2WTFQU2ZwSXMK7UnSNtl7MBze8gPvv9qJXqgkZfX6Yian
        dCA2BFchHtKH9dKptaKEFoC5ur6845eHrZa2wpuHCvY2AkoFZhxl6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOGJzNldWaE5sRFM2amVr
        YUhwZFl6OFhkSWJHNjVieGdtcm55RWFsWDNRCkYvVGFGcVFGVitvaldkUWFhQW10
        ajlSWW0vRlZIcnpXYms5L1lHZmR4clUKLS0tIFFiVEtKMW1Bcy9NKzhiamhUZ2JI
        aTVveFdjWURBdGRRS3BzMXZjdWdTY0UK/IsCKjZsjFNMiQS0pHQpCDuYF+Jr/l4L
        JE6oGUAJHGbZAKPLLY+RNfbAJ+wS7SR1qpwGc2pOh26zzIWnzJBivg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:oqmATtNj5UuLpEjDUJP+9pmlfbhUOGujoKaQrMGzPBcIwz/JxwIzQRj9YY2knkjoVxgkvauD9cXJqyotRvYHO1UOjHRZlvmCCsE2ILaBMaTicgc3fQDsFlH1ySsTumuLjh4gSaSk2tQK2OuSTlNjIPkAZI7thDZlSJrUFIsjJP4=,iv:fnXj7mufSpssOj0rHKmDwHRA8n4ONci8Hsu9oOWBlEo=,tag:WH34nU5o/wQBCSsw+Bx5Dw==,type:str]
  version: 3.13.1
