apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: penpot
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:kW+IhhZd366Dc1nl5HKMFCEYC+DlDSQFJOHehom8qel0ojriVUoKliNg1p9kHqOIF7LkncSlQITM1T/5N72qExjjtBN394TICi4ssIfa7PfjuC7NJElUSXiWGHEiymw0Hmg4NpqGLigHEywvqV82sMftnQxqXXcfipohel+KTSyS0Sqz7w==,iv:AULYe8AB9IjRjA+WU8d5xdqcKyhXudsjqTT/KY5o3zk=,tag:UsOqw+4NI+ObX+BgOMsAVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN2czZDlrcjA4eE1USzJp
        RStxV2JDQWt0ck1ySmt1dFRhSS9yT3FmYkFFCm9JaDdHRDNoRXpCNU9RMnRhcnpX
        Q0hsb0UycDlhdEhBT3B5YUo1eFBxcUUKLS0tIGMwaG1nOTk4a1hOdE5PUFlkSy83
        VGZqL1VZQmVISDNGU1BVZU03SXVLZlkK0jcCze2WymGgTZNVWYRdgmVvH84mv/2F
        XcWUmQ2sT+j0bgPLGdG562sA2RlMui4kJF1OF7ku6TF8cu1hRKIh5A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cHM1UUFTZTZUc3VlbmJL
        MGxRMVJjUHVNNU1ldll3SFJ5Ym9OWWxlWjFJCjFLeVFIKzdnSnNGT1BOK0lOdzBj
        ZHFuKyt4TW1OemVUN2NYdkdMMWxhaE0KLS0tIHFtYlVVaTRPMUthYWRlNTZ2SnBV
        d2NRUC9FTk1jcmJKVFI5SVNmTHZNaGMK+kWNme2hP8WxSiHGskW8f/JSGDgl7AKa
        iRU8Sc1KX2mFWrTxDgjFT5BWrW9xrzojZY1WbZZ5MEO5dw6maPrLrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQituYndlVWkrZ0lGNWtG
        YlYwKzZDSlVuVXRzVG16M1htYzNMSjQzcFcwCjFmZXJXUUZNNDNDT01wWUhTY2cr
        NjdLeWxBdzdIVzlCRDVWWVhLQllkVG8KLS0tIEd5bU0zcnVvWEtHQ2R0bW54MFQr
        cHZteSt6TnpNOCthYURxWU9WRWhRQ2cKuUdO4xsj/yN4UgjCMTw1Ffimh8PYmkZY
        gAcPPmzau4kV/hTt5BCj1SjagSi3G9q646MEIgxNNaXq7WpYbASZ/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:gGNkaEJGrqSkgxxBhULRD4vmEphdPhz+eaOdZBnZAUxtKuaZ/bY5AUQEqA0n7egNNFBSTulG8+m1N6X30hHLkUZmTirqpcZatoOlt0YyJPG7SlQ2hDySkrBn6uMNijITrzpcc6XFcTPxdyDrxH29TEcmnKIRNojgV6GDBoCghWo=,iv:NPxNw+oxSKnuULYz0+zl23qptVOelCsVguIwE1TMg4s=,tag:UYbk4WHRi45xxQOaRgAUFg==,type:str]
  version: 3.13.1
