apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: home
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:8Ab/ztoL99DmLf/UZ10dWopsogiS9eiSxim02rEmc/zjTA+LHBokZZdOi24JcFL7HzA544ENO/0Zfn/mhC4bThPudn0UuIubCotSuC82CSKxRhz6/W+l+m4U7sstBGsEzTz4MbqndbFi/W9g/MW75bELEr9yOT5Q8ZfSvK+zDdp8zDGEhQxdfRjP86x8rYKDIgqCSBPDWazdKnIC68dxy7fZcHPXGAtlX7StAvrIUy2FSGA6,iv:MvfhczYch0e9wNsYQSg2m2MWwHGuEXZgGeABzvukQBY=,tag:vimHQX/qp+MjiVCqZun+oQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWkI5WFJobnRWUVJhcW1v
        MVVJK3RXN3pLZDNCdWp0MWMwbkk0a1lKTTJRCi95bEVzLzVsYm4yck5NVHZVRGdo
        QzFTWGM4b01GV0JMYWtocGJCMlY1akEKLS0tIEVHRlBQbXYzYTlRWWNvaEt0UWhp
        UWlSV3l2d3I5ZFZqNmVweG5CZkhrODgKLvmReQamRuFR22d7ew3zpX44V8skJxD7
        RKwVqL2kPnfpz3IAdYCurPRtfap0TB7bzCdRd7QlOp4NfLavmEB90Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRkVYa3NlUTZSQW55ZVll
        eGlUdEhZd2RsbzFMZnZmR2hBNGFhN2ZibWdrCmFDNHVtWVRyM0M1clVhK0lFU1Bq
        Qi9sN0xBclgrcXR6L2dXMlNDMVZJd1kKLS0tIDUwdmlmYitFVjU1S3J5Q25zRHBQ
        K3FldmlDUllNRngxeXZObVNnMi9Zd1kKu1Ce1jO4cJFAOcSX5woLgwzh+a7q/BXg
        xLMLGjwOkqFQPA0xcy/lpWhL/sox5jPZGfTrc0fWC/fysDWDTtVo7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVnZxM0I0bkhadGllUlZm
        YzZlYzljUTlDYjVPeWYwNXc0SzM5V3ArZ0NJClVHMFZLdVU5V3dZUHJZVXQ2MFBY
        TjNKZXFNWU1JNDdldEJRMEJFNkpXeHcKLS0tIEg2VnROREJ3dVFzTnNXUER6V1pm
        MHI2STdaeTFyY1hjQXFMVmJrUkFKeE0KDntafILOAmhvM1MPFeTFMJb56bVNLBO1
        CQsYJ+DmBnb7sKRdtQp5PHvGnT1HRFxM/tdrLpcUcI0VORyfvVcgDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:rf758BoUgBa9gLT+SxzkM4Yff0x2zUoAOKc+rl5s7v9Sfq8zaAFbb7u2MIqmcGmQJeRN679eYtw5SElXov75yu7Hor/wt96k8Y4jRd6Asmp02CkpxYQ1qmjUQeVAyZgswDy6qmDfwMWBYxuJU9HKAYrDRWm5bpiS+PZYIBqm1c0=,iv:PtOcfe+nn8W9SPR5tvJ3IVxBFp91iPvM6sltVGg70Ug=,tag:dvIfluMMUAQ3Ax6BWNGDbA==,type:str]
  version: 3.13.1
