apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: planka
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:s2qHldSpden9w/SEIWaaWmMKRaHAySfqjPrc/+sH5VC9D+19P8RTNW9mSlcQ9PirfVNFsGc/Ev8Rf1wfLD3t/LZ85IRAcKoZq3w7SzEj+yS2ED+D43c9wqz8CVsNQ+p3pB4tg6HOZBDiiAhAX3P4bzOLs91Yp945ccVgeF2obkvYWFzf6sSC8MxTwD5eHk0vK33ORo9b4syAtRFoUxn+dl6acpIBlsS1dC7L4f8JxTgO9tuk,iv:/bRZWKg/LWFiZIOYyqcOzU6mCvE9VY+DQRZnBM9vrso=,tag:iiuxOV+35G5XI0kRNUxjAQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERU5KSlVKOUs5K1JRTmth
        bmlRVG9GcEl3aVBYRTZDTVhoWk1YdCt6YWlVCituL0p5dnFxSkJSWlpVc2RTd0h0
        NGVCeldRZWsrZEFLa3UzQnVqQU5UV3cKLS0tIFd2OU5FMDNyYllQaG54b0ZBWE9j
        VlBXUTNuTVd1T2ZZYjV5S2JHOFQ0RUUKAglz4nljzUsLpG9MevDaJesr4jNOS3aR
        CEsUTVjirqfpG2a5T4sUWbVQ9eUFC4D0iPhusmrcdsJbk3jjboVaoA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdzFyZm5RK0h6QUFuMmhh
        M3h3NmdIcTFhMi9DZUNkVTRwNjI3TlVpZEdVCm1SaUMwUVBqNC9qTHpZQm9WN1lX
        RnR2Wnp6K2dRR0hlWjJKSEhRRzh0MUUKLS0tIDJIOGk0bTN5YmQrL1FZbFZqdXdz
        QnFwT2tpY0thWit4VGV1MDk3b25xTDgKgoC3fPsW5de658UITYfS/R37jNwV04ev
        JHNug6LtYQEiKU35JyRo2Nek0r3gng/BS313KcM197jfxlPAz/wLUw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YzBTaktXQi9LbHZBYVVu
        MG9GMC9Kalo0WklnV0hnb2FDcWdRKzQ3SVVnCm9Ga1ZnR0VNRGh1ZVcwVURjTHI4
        TE5nSXBJQUZOU1lteVFuVk5PZ0xmcDQKLS0tIDBDekxlYzl3eFdSbGxxVi96S3Ur
        YnJrT2ZBQjg4Wm1jM0ozT08wZ0xjZ28KLVXim/bXdRazU+2lA35P2/uxTXmbqOhc
        Cx+ojuXlep3MK6CiRy34THHkW8pgEKV8hCnkM0M4IuWZG4AUZmouAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:/0kkRZ7P9uCEWXBSfitCUvshn44HNH4F9nP10NQhRQ+dukPsKwuME60+EtolExFkZVbvffuyAnoFI/cBp/jl09LiYI2iZutWHN+8GVCVovnWelU4cxk7M4tpXubQAje5UUVQzOCo3DTIZrsQuaRz1R/PWYXJZ4DM8jftSe1mO3Y=,iv:qdIdeyxQFzq46PTc4S5dJDZ5WLAgeoxBMiRBVXRYL6k=,tag:2bUiZTeGB1hVB7zrbLfO9g==,type:str]
  version: 3.13.1
