apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: media
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:/wkkLI7IJE0GDAA0kQwZBu4BMSKQwPQ1B7Ckkqr63d1LE1VJpH1eofbIux2m7+XJEOJ9aJngM79O7hGO0XpNqDqSUCDuuf4H9nZDCvIz0Alux+dQUkwVY1Q2ivQ+3wTCk2NNjxjneRXJVQz7OcIfvkJV2B1Lku/PfCHWVlz56eoQndP+l9RfqY/sxvzHNQMCvWHWG5pt5LG70FVVFRk60mk9NqE5spIk0htY11ajgbhKfkhB,iv:bcWkbdB+XwY1BV1kf1EqP1Iz5Qm7CLZZFqd6XZUvMlI=,tag:jRicfTWpoT0EYSLiRDDPeg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q00wZzRvSUNhZGZOaWtS
        SFViSXliM0g3Nkd2K0gzdWJuWVVjME5RYTJrCmxSc2syVFU0K2I2S1FqbUlRRGhD
        RTJWQllNanBQSmJTQ0tOUkNaM3BxRXcKLS0tIFc0M0pmV1diVGdOdS9ic0xZWjcv
        Q0xEakFaQ1RvZTYyOUF5VStoNjN5WmMKWA8gTHql2W4bAHsqbZWm78OLqDft3OFG
        A/kpo5t0D3l0wF0RCt/qzaiynElrWNObfnsA5uOZuB8FJCoAWsn85A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTem8wbWY5cmt0c2U5aTc1
        Z3RIQ1FBUS84WFlVOGpFTDFhL0V2MU81d1RNCm1iMnpVYVZOV1N6RFViVHVqd2tt
        Vmw0WGRoaUd0YUJkc2hkU2JPU2ZibHMKLS0tIER6MW1mQkhBMGdDWDlBQkQrbUhO
        N0tDWlNTUm92ZFZVQXA2OU9hV1RLZlEKsVy9JGlA0+N19+q4diNB3EKSTlmBqdSq
        y75FkNicw2rM7z+ebfY+rtyQSRctV1RZJOIuJXONitDtPbOyxL3gNg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV2loUFcvSGw0VXprVW0w
        MW5NTkpwODdIVjh5dktzSTFlK0ZjNG5ZRXgwCnpadytPbzFhYzJHNkFZZW80QnUw
        aGtIa1pLVDFsakVvL3Y2emZiVUQ5ZGsKLS0tIElTcGNaREtrMnp2M1RJVkZaOWk3
        bktzNDJkL09UcWMyN1RhNWhXcEdmcmcKmRKm9w7xf6YgKjwzun7kSQt4LscQwr3A
        pUx+dXi3rCDVyb8KVoSL4LsS0L+DRwCSel2tQgnc8CcMrqf6x2xtZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:CmO1mkPLE9E/IB16RKO0Ekl55mSjvSBUMd7L6+rDMlHfcD7ySr6/raz6DUDgl8qFn5WqObjRFLOOuIBmXhiCvROreM2CIjxue1Q4ywei2hc/Lg8P7Hm3GfmLrXbkmGaREHE+r183onbhQ/cFlMbRm53UCXKEXYGenqMm2BjQiHU=,iv:tymA1k/N9w3byB14YptUSroevoCVwmbqdfCg0V5SM6A=,tag:V2Tj9NgKdOTAMt6E3ELgXg==,type:str]
  version: 3.13.1
