apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: automation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:2ppUs7rhbs2CbGn2JPCQR8jJK3TSn/6QIZ8s9jplLBhZXtnVMKNJNSJjgnxhE3mC9x7NxjatffY76c9gB8ToGYpzIFmgvPPzWdWtV6CQaJj9DZF22a2jh35JJajirnmldIcl1uSjNQzr95AK6zPp4Hj+N+O5FIge9jsqlcBfA1M0FkJhwbSyEcjvqlTUDr9dbsvlmdJImMv8WTsPc4mv9p7FatvCeqoHa7zD9KQovLekDjLP,iv:cSmJvkLO1gKEthqClu8VD7/UgLFfKVsb7o0vFP+38Js=,tag:rSOeZdwlEvpVit68hroATw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdlJXNzdmcnpMOFRyb3pt
        ZFZVVUhpb2ZtR2FYZFY4YndIcS96WkhoWVRBCmx3a1g3MVozcWlKNWtBbWZNdkVB
        aHZIV3kvZUg5MUdQbkd6YU50NG5XTUEKLS0tIHp3MUZtbE9QZEVnZzU3ZWUwS3dT
        dDNuQ1UrYmVSQ1U5WHpLRXgzNTFNcWcKcoDy2YJJNS31wTmlxwx4Lxg8nJNsEaRQ
        NIrLnDf3xbiyjpq5BGJM8OWj3mUKwxZpA1vBbH8COiD3pQlc83zKKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNk1VSWFiNXlTU0pHaE9O
        MGhleC90YWZJTnJIWUFPY3haVGRTOVNBQW1ZCksvOG05RjZvTUExbXAxdnEzS040
        Wmc4d2EyelVJZXVXTXBabkVuc2RZUjgKLS0tIGhrMTMrczJxaTBIcTVlb2dVd0gw
        U1g2aGtoQk5PZmhGVHdrbEliMkdySUUKts2Vea6a1wk1kRJ418eObLnCQD5dzG7R
        jDDv2atoeUDlCGMwFKgwBiH//bRRgoCsg+FHGljBdSRR2c+k5SniXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQVhMbnBpeHVkeTNMQjNT
        UDBwNXFURUpONXFzSUdYNWIwaW03cDhwdDNjCm0welVnako4RXY3anpzOWZuVElS
        VXRHdDdRQ0NESG40dFhRQTNZZ2YrM1EKLS0tIElNTHQ3bFY5ZUhzaGNUdlhacUNr
        djVaaXhHekZMa0xsK1JZVHBLTVRVUEUK70+bGr9k533OgM73Z/O0akqf386i+4f5
        ElBY4lOobQrRa0WLw8YdF5sizlYclOmBB1M5Ar62bhisaVXTxj6RzQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:77F3Wd1pGNjiReQ+QuBTQb8DC2a63GYmT4gGUTes2zu7jynuTJobdJZuXMfUh+m1rewBK5X8PvVCwWsoILmZmFQmukDRPq70PimQGH4E0CtiesKSvTyAbXsMuVQuBzSFndTg5m0TuZP0fqYl11YIecmfu9De1xJEIe7dLHIkOCA=,iv:7yyd3KiEARX1nU/9++nJHnfn5x/Q1P9aFsh+YB22HgY=,tag:qx9VwMfq35eEX69Zi2qSRg==,type:str]
  version: 3.13.1
