apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: home
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:fgFiuERQJRjCicm0o5ETUymr2oqu5f9CnJIs7cQyVNw/S2blWD61vJ/0CkJmEILx6dmk3IsAPMwSB/iEr1IfPjP9Lc+f3TemaVMhsnXJpcXYaPSEJs2LHIpzgaHMvHvah9IVnachYjr0rfvc6nk/4hlKFN/SIm3/b8yZc+WsyJv7AgjfBA==,iv:poOI4LFskIkPJt0a8NUkaRH4Ig1VRuLK0T1h8R0LzdE=,tag:QEFoAZwfHYV64xN4iw6zjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUldEWjhiWVFDeDJnMG5x
        UXd4R3Nic1cvRFBHQzZ1MnZXekxDbk5VY3hnCjJabnRuTzYzY1lRWEM3VkVoTi9h
        MlZ0Q003V2V5Z2RUL2cvWHVoUmkvUHcKLS0tIDFsUDRFM3RNNlZPUFdYcGRqVVpv
        QnhxUnRxVXJPaERuMnBzL2J4c0V1ODAKGP1L43MT6GO/L9oIZnbO6pazcRp+q+Px
        D71kGM/4pVWT0PT/LgqrHw0XgT6MY4K6aAl2nkC9s/Jft8XCG0NieQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQkF6Rngwemc4ZlZkRFpz
        N05tb1paYTdRUm9SVnZNL3VITDdBQ3YyMDNrClk3M0FvQWlIUVlieVVyRUVkdlBV
        WTExdWZFdmp3cXhVcXZWWEpndCtNVDAKLS0tIEZ2bGJsM2VLb1JWdmxMREpHOVQv
        Rmc2dGN1Q3UyWW41bDlhci9FREdCTlkKX4eRuNj+EP4HB3JUs+wzquANMy5wEt3W
        9FxIIWNSGUKbkZJzVjh7Fm6SudcgPXcBX/ayL6B95EidvROpPD6Tfw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OVdncTRyRnhDZzhEeThn
        d0F6NHNjUHdKVDZzczlrUzU5emdkVy81RHl3CkJYNno4OUJVdFJtenpNZDNjWlBy
        L0dEb3UvRmVNWmNKeUpKbHVTL3VvYjQKLS0tIEd3cDdReUFSRzZDRGttS1pLR2F0
        aFNCK0RVMXZTYVFQSVBSSmhGQVdGcEkKc8zzWTd3dDC7LXH4g2L6Gg8zS0//KYpk
        kQJ1V6/6hazMo8iRf1270dF3NOdvCSgIDAuu5VOxQX128RVvqIZtLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:l2iu6Zls7I+kGwcYAJUaME/e17nkqSsc978j8pdareCjyqShDdwQ7KFyuun2L/IXo3Oy6LViCrNPgpsBfm9osKpfAUvsoaN/tDdfhqUNpvGkS9S3c8E1lxWC++F/wnbwHxztPEtMHHByRJs0v82fZvUDbw0xxfQNyesgAa9TLHM=,iv:NP88vLUzLqM+6DMTR/RnJcyi/udvqMukYqfcctxYa9E=,tag:0kZ7wUZprsIyObe/V5zr/g==,type:str]
  version: 3.13.1
