apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: syncthing
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:/eyjSGpN1b6QitESt4BRsXyo6WimeEINcSkZuYzYmG5C+vphZq3jpxbXLMaSLBVIXgLdZmfTkkGoJHx5uutaKWfSShkeGR/PH7roT+QN9r0DRHR1P/L1qIYW7pSCrDxIV4qJf/1dIiDb0NpdrV4AVJnT+WUpBJsljpb4LrMMGNlwqzQxxg==,iv:Werl6I8UfdR613vGuC4BVilV+E2YQ9LG162cGvU/7Ww=,tag:AfVkazulV8cXihAmXR3ugA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cmhITXNCNUx1ZW1JZ2Q5
        SDRiQVdCRlB3OHl6QWtCNFhncXJZYnNCN0FZClhjUTJtazYwWjhMTXNnWmdnM1Z6
        RmVFYThINDV1UmRsOUg1T3hnTmo1UlUKLS0tIE5uNEd4RjUyaHN5NlBCSnU2aUhZ
        VE5kNGxVVHJja0JLOVRHV3didGx2M2MKMzgtkzxlJYkaSm3Ofd/QZBlqjsoqbnuX
        yQi1tWJ0NfpxyaHrlpS/XR+XuYau5vwB3MjMmNh87Qf+CkOcPi4N4g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdkRCaWZtLzBnZllIa0hR
        MkhHUEdBVXo5YWdyanBhVjhlRVNsdXhWMnhvCkFUY0tGckR2WmgrNGQwUHdQVEFV
        VEp0L2dvRjJZUm9WVWVoeVVDZDZ3cWMKLS0tIFQ0TWFrWXBhYjJBeXc2T2FlM3lN
        aWpaTEJ4YnNsYXdXeFZmME5ZMlhrNDQKtoPUXtpCnNfCf0oajKL4ts8hsqyt4Ip8
        UG2ozRjA7ELpPuTcYyKvFSQVeJDbHqeFFW1pEIG0ih4mBq4OOJk1UA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUnVkckdQYStoa1pIRDRx
        Q3kvME56UTJTUldpRXJieXNqQXBHRDZ4QXhBCkFJYkdWejZoTHVkTyswRFNKbGdo
        OFBwK2hNTGZzRzdSRW9ub0hNRHhFbEkKLS0tIEwyeVZBQk96cEhKaU84VWJkYW9S
        RWxaVEttMTBkQ2ZGeVMyUzVkMER0V1kKE0vvWVq5JLcxrRo7gZV2bUAT6FCOtWVU
        GQzR+sGAkQxf1q/842vJdPtjd9D7szoQ3TLDubmkObhVhS+iSTsI6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:13Z"
  mac: ENC[AES256_GCM,data:E0GGQQH1wyOVQ5ljDnXQ6vcoLkvWoNrSlkUSWlXHo5o90hXLjkVMZEQLe0LsjFmlguilx3/vOFcsCagWBNRgDYvVNmT3ra3/WpEKUQuJaJMQQfuFjw3Hj7v1wEur0Sox+yfjZ8gKxgDySyPLV6bP9ITLRMaQSfNyAyLDeEJ8zL0=,iv:Y2c/kAZ4KYO1uQ8DE/0qJrxa8sLH2ojXLh1OF+KuNng=,tag:eN428nwVEUbEliF+coQytw==,type:str]
  version: 3.13.1
