apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: media
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:Kp0WcUyxMtxYXO+c3q8Z5BLD2mo3XwtEa0Nj3ab/J4BVQE+XXAO1b3gHo/M/6kXHxZs7f+AXgtNVeuJb7zTJ2nMAKpJdnEgDMHtco43UTzd8SOLQkoZRpXjStoCFe+KkYNY5w+qIYADrzLlTb8ia2iwfIfJr1l+rm8WGFhaf9dseGldiJw==,iv:pE//xnYJyuq1zP4rmuE/m3G4It4gpuUO5oNxawausOA=,tag:tSgpVKl33h9FU6wVpb/OTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c3NzcW5OVlVQcERGSnQr
        dWZka1d3WGVucmIwM0prYzhKdExYS1ZvT0NrCjVkajRZVTBKaWtSWjcxL0UwdjlK
        TGFDakdlY3FmdGsrMHRseVlSOVFWWDgKLS0tIEcwSkVuVjY1R1ZBZk8rdW8wOWdo
        eXY4aVBPeDMyZTBST1NoRFZTMXVQWEUKzf1RFmYq6VJjhgv4PYwxKzPpkbYTE8/k
        ElzCQ0r+Cte6nxAWV9urm6xNBiHQaH3hOFtDM5J2LahR0FxH50MREg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVTNsZ3NGMDJvT25aQUo1
        NFBBRUVDL2tpVWY3d0IxVFRRbDNyd2RaWkY0Cmo5M1lrVzI0dVdjRXJhL25WTkpP
        VStYVnZuamkwZUMvWkRSZ2R4N2ZVZFUKLS0tIFBzWGJWNVB6T3pMcXgxNzIvOFRJ
        ekVBUTMwb3U0MWlkOThVUFZHbTh4NUkKKR2z/zhNqjuLzJLjJhykOB9KrV/Bn2fI
        yuoTtG7JeY8DHFmQ0KN64LtxTmKlXjtGMSA403H2DKpflbkzylwFhA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdktaeDdTRkdTdVlETHp0
        NTZKdGdjNlc3L2Y0anNnaEtvbzhHZWlSUTJJCnFMN0JaZmNCOFNabk5rZkl2NU1k
        emNuM3ZMSHB0YVovMnpjWUJpTDNaRVEKLS0tIGpsdEpjMFI4c0s1UTZYVHgvMjVS
        MkZGNU9oKzlCcVUwZmEvNWtFT0dpNTAK4XKAXVXYiVo0jOaWnDDDQ7WxwHBDdRM3
        9Ir/DfvoEpgJOJum0Ou7VPr1MVDw7LQnQKOvqmnJ9VjJnC7QiMrikA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:Q6wnD/e2qwnwTEf4+x7lUmOoPm6H4YcnE1PrmiIXIZmgd2uIoG4AT8IQNN1KJa8k+PgCRZzll441bdUxo4guicYAEbm9ua57h4miO3Bb6i+1qYWyF77lwKwdgTQTUe/mhzArIhz3TKQfM30A8gxPKAGsQUOr4t42f/T29dkAHpQ=,iv:KsqHG3nN9qEQHb3TesWt2sp7Tl1rKQGAHKzHesTWhxs=,tag:THeiXRTgj79kT6PFIEAbuA==,type:str]
  version: 3.13.1
