apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: planka
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:6t/iK2LIClHH7xo8EbNcr3KNZpnhNDIoJ1U6Gyoiy0/iiJ6yBeKS6awyTIk+qsMfiDjqS8mNQtnyBMGzqoqaUSnoIGuLyUOMzKE1KqmsdFoq1ZlTasuIvXpPs0dnS08osCjzqfyO6rx7MIkUStFuHrOA5C7Lm2bcziU2aO/bK8Nx4k5hIg==,iv:KjcA4kjuU12j4xEASee/a8K2GK/X/Roj3aWFuB7qq6k=,tag:nTWecYd7wxIHiCyI7BUqyQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSE1zUnNrY2hDZHJIMzk3
        YTBJU3loVTFnRFNFc29FQ2dDOGM5Q0FPSFZNClA1dHNBS3hkYUxUWmNJa3hhUGpz
        Q3F0STZCbU4wT3FDQXMvRkNTTU1VMUEKLS0tIEFIZ2NEOSsxZ1NkeEkwTncrTHkx
        dVlzUWxROFdPY3o2RjRSWHZvNWtLb3MKb7FftGuPRlgI3xRGi2TEzJb54bqg6I51
        zBj/HZ/lDSSkiGanVI+D0C+CGocrzddPoNquAL8OkeHG2ZVaVgoZEg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N0w1STkyR05uQWwwa01V
        NXd3TGEvRXBtR3NkTjRTTmsreSs4akgxOVFRCjNjcTE5a25ibFVHSXhBeEV1dG9z
        TWRQaVd4UzdkaytNV3pDOE0ybG5QMk0KLS0tIEMrcTVmVXVwSEdVRGRjOXdZNlZ3
        UFZnOVRYcG1UUU9mdjZEZG9adjhtdTgKHzWnDeEcWuOwt0EsqVuTQo7nOyBCAPcL
        n/au49JOIo0HjUcl2lPUaONCdbpgdPPGu8JDon02AVwID6NeQXzLLQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeVZjWk5VVEZwdW1ydXJQ
        M1ZuWmt5Ym9yNmd5QjR0Wm92aWNOald0VEFRCnlkS085R0hvcCtxWmx5SERPcXA3
        OHFtTUJTRGxhL0F5L1E2Z2VkTnAvZ0kKLS0tIE9hQ1ppVXRUQ1NaZWNHYWgrSnpR
        RWJEU0E1TjNqSngyMkFYeEd2T1JUbTAKFWo/TSN3ULGaHlpQdTnBGqQWFUaF82xD
        tJmA+0+XLRhJes3kDdpYpFefnXpPlxsg3uv6l9fWzwxyqFkgH1T2Mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:13Z"
  mac: ENC[AES256_GCM,data:j6GiZ4UkctZXfVYdrPHalJ6cIGPGVkxWDWzvmwk2Q9ZBkTrZsU7GgJhtP1JTDFBWF/gq0ZWzuYndKH5jtj/hqTO2PrP6v5wSeHaHFnEL7FtB+wXzY0hXoT2Zf0mhBJ8Tv2toxlnO0dD22OfLPRgvgiGLNTCcz0KwqbVsEPdiQyg=,iv:rwbdH53Z7zdCWfmqFKLw7SfW8gjAA6fFiTKDdTluxsU=,tag:4gTwmb5vZXGc+MhH7hHfvw==,type:str]
  version: 3.13.1
