apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: media
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:lhFCpjOCfMncieaXSODu0SahZQLiMM5wRDkebKozD8TB+0W7iftOvi1OQs9idVlOYXh+wCNlkVTzpvQj8OCzPwpED7cKGfulZt73DnRBpMeTt4aBHrX32Gu24b/hgygP/GIZ6SUYW03GrrVGhSDXlScefic0G1hj03x516vFNsB6LW3wQ/XJ1FKXNpoJaRba8q2gbrmSf5bGnGc5m5Bholp0YmOqurggepNbJTxm2ap3KfFX,iv:JN4WC1SFRgKJzaEEFqcJTt4z4yRw1SjUF0gA4tz7efs=,tag:F3cz+QWJCPWZ2ST2c3S6qQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMnIwbVpUOGk4R09XYzFE
        Vkt6R2NBOUVXSUcxRG1WcXo0REhqRGcyZEUwCjZYcXZTeEZNWHA5UVJza1NTL1pS
        VTVvSTB6K3pDV3BBUzBsRGJ4YW5MU1UKLS0tIEFJSm1GSUFUMUd2Wmw2eTNiWDh1
        VTVteDJWUklmQ0RCR3k3dFoxbXFHU2MKlzu30i+XUI0K9dpAehh/nKDsH1bl7/hD
        rHJ9pNNIJ6HVcb/MjzPPl4VrzV/Zy7M7EK5ZNTdyEUE/Qy2JlJ3koA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTjJIcTJTTmZ4Z1FicUxZ
        NitJYnFWdHhjRDI1RFJZbSt3bWRWckNiSkcwClZaakhYdVNNckYrakYrTGFnWE5Z
        K2NNaGpPZll5eHNLblU2NTAwQWR2eUkKLS0tIGIwUkt3NmxIOVlENzdTMzd2b2xX
        M2p6ajY4Kzk4SmJ0am1pWnNmSXJOdmMKo1ewxjdfQ9LHpQuApfFxGzVBKboesxxk
        3ANFBVLsnAhrvWjKrjxta2fSFZKLi6hYWqDB282lpuuzKbJ5q+4k/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M2IvWDkxQkhXbDh4VTBZ
        T2IyZGRMSjBuQ2V0cXByZitUT2hvdldVZ1RFCnU0RlhuV2tSUkxmcEc1WDlUb0RE
        TGt3QmxDSFE3NFpPTHkxVzZQL3ZWQWMKLS0tIDRJZ0pvazdVVmQxd2R4VjNUVW10
        cjR0V1p6NS9PeSttK281U2h2dUkwencK45kSdpUDlIjoUTl+uB+mwDvmaUKo8B26
        TCeKbSdappNsGaVZgyfy7t3UJKu/iq0dMvRy4ckveMhbMXpHBaDYMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcml5VHdJbkh3VFllOG9H
        NDFrWjZadFN3all6VThuZ3hrSUl5cGhXSUQ0CnZiY2lqaUF4bk5qdHh6YjIyeWRi
        Nm80QmhIQ2V0TFNZOUV3VmJ5YU1qZlUKLS0tIHV5S2ZjSkhzOSsvNG1kRUpocmcz
        SjdxZDhvRTY2eEdXTm9FNE9ocHVIS1UKzxGR4yZoYYFXZhbUQFucLPSyGjPFkf2a
        kSH1cLnXCZ7qyG3hjshJr3UWIO670cKS5rq72c8QpTCNbyArFhXt0g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZHNITmFEbEw1RnRNK2hR
        aWFsRnptdkFjM0lLWFBXRVNCTVErdFhidEJBCnpuZkR2TzZUWS9jNTFDSXFKYkoy
        ZWI1NTNCdm40Nk5OblM5Z2Z2bWI5eHMKLS0tIHl0cnJicHUrcWxxYnFzSDlHQU5l
        cHZJRnJUNWp2QWJxS01qeDhzdnAzMFEKK0ulqwolX2hx2NkZRHXLm9zL3wHJEfar
        B1JMS9YO8n7qPymb+HlFXNGRVr0GQH11W8v80TWHFaaYNK9fUtqTLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVDk2SlRhZ3dranR2cXRj
        d1ZkSm4xWmJlY3RROWN0YjlHditmc3ZqOTJZCklqUXpoZ2FPQS9UbVpxQm9jelJJ
        RTlnRlEzN3kvT3I1SUJQTGo3SWtQMVUKLS0tIHpJSi9UcHlualdlQU5ZWVZJTjhQ
        ZlNmdFhROVBQdGthUFNZeE9JcjUxRlEK17qRxOqTxOJ/1Rm4y5x+jtu4G7XbbDmt
        k8hc7JMrrIzlLO8PL7oqcRw//VhZwNm5fl3WHdBcRqEoeLqfDCiJwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dWxiaFZaQjBPcEx1b2NV
        SXZwL0RzbVozUHZCMHNLQ0pQZ2JQWG5xRGdFCjRySExzV3JiZ0NPWVAvQmxhY2F0
        MS9MbUVxMXg2NitNcGgwS0h1ZkFDTmsKLS0tIGZEamhHZXdKamkxSzFnRWx5NnRt
        Y2dEZzNlSEVLZ21zYWFCM0tTWUlHTzAKXM9/USGGarj8EScHlyD+hN3ZAZ+xQKlt
        KT58N9NV2R1MWyapaR+/cSfXPF30NxfkisxiCLEfRHHm9bzfJkcx4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTWhlc1ZDRjd0c1QzVHQv
        VnRoTnA1ZjVuejQrWHE1MGVXQ3BSWHBBeVRNCnQvejhvVUpJZ1ZURW9ZN04zVS9z
        cldBTzg3RU96MjBPWFV0cCtKNG9Eb3MKLS0tIFRZcC9jN0xuUVp1eXZaTzJwdllR
        aWwwanhRTzNMZ3dKRVFLMFlXb3NNOVkKGwIxrdXTqF9pSaGnpuV5pU2Ro+2ZUBpZ
        3qvBfflCWKPFL/AWnumgkfD+TGH/P8GbbJ2JynKKhpBki9ctf5OQLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheS96TS9FcGprNnNRd1Az
        YUxZT1V3Q2JQamRxeHZOa0thQ3A4WEpnNkQwCnFVaXBVaUcwRS9LNUZOLzJXTVc0
        eUEvY0NLVXpHd01vdHdPeFhxYm9COXcKLS0tIEVxSCs2RHUvVzhnV1FGUEdIK0Fu
        OFlzamQwN0NyZytUL0ptbGxVdHFNRmMKko//MKnmzoQKfayS5xXGUzXjOdJRaHYv
        cYpKay47D1kp9lxbm+Vpm3Y1FbnawCDpzpCtt+yubgmHfqAVMQ2/Eg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZFJ0QzF4WW1EYUFqb0J6
        YkV6T1Y4S01xMHNjYTVWaS9ON0R1anh1NEdRCkpjd2tBcC9PQW16R2xMZjhqdDRF
        a3RNd1RCN1VmczZqWG1PM041aFFKVGMKLS0tIDlrU0pPYUc4ajlyaTRnWStZWHF6
        ajQ2T3JkY2ZwZ01IZSt3QmVOKzk1RG8Ki0a2vIq7nVox9fBNTcIEgJ+/LPeCyH0n
        xMSEo+1t/C0K/Mc4/42Ifx1528W0LM97PqtIoCASwJ35DLlEpWneiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:C3LXPSUQ8e/apqt3OJJn9jydEiKmJGsqQtPn7DicS3GzPRrzPKSxwFtE7dvvGF0RIBXtbX5oJmiGMh2JZQTG1UrCKWzvJN7ZuD33gL/fAzbQiTYMLs7sttvTL9hDSq851DGDNg842upAGHZXwURm/qGQLZt82Yzkp3qXsWZfDC0=,iv:la/nhQnxsrAk5EqAkxrfrJqM/pQXI4ehUhghsSqXS3w=,tag:jNim4fgFsA4kK440u734uA==,type:str]
  version: 3.13.1
