apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: syncthing
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:m+w9ELEVWeZETn4x1IvH1w23krR/18L4B0PeG1zhZ8qpYnENxgstezPzbOKqARBFT+M2MOsVoPYz0UmCTa4wzkqeGRsc1KxdCHdvG4eAMPK8zyDHBlPairtdZGwh/xfpCRbZQ+fGVEroZq1X5CFccc6BoMereNBu7fPS3gzvCrBbSJ5p5Gma9zzqOBhw0F7/M3scwBVT4RqD8jAn50pIQ+mwuRhw9TsknPlhqlpiatTM+8ts,iv:jh6GYf+qxwIbTNrJfieh42RR/GmdApshHVKvGLaXrdI=,tag:X/KKmCUHY/A4HOsBncZSuw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYTFna3ovbDZuL3g1dFNp
        WWdXL3hUTjB4aG5MMmEvLzlVZEpiZzNBdEdVCjZnOU9CcEZoZW1qR2dwdWNneDNM
        SXdtRlpuQU9hdWlUVEJpaUxlTHJtVVUKLS0tIG9JT2FOYWFJY1V1R3YybEFjb01S
        MGhmSFJCTlh4VWJsTGY4a2QrVmhZYmMKpCzFTMpvx6VptoLZqZd1df3t6HaDpADI
        Az7hqKv7LbOETjuNcwKxMEGr0vs76KykeHuM3req+4Uc1KNtb++8dQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK1F3OEs3RThFd2E5Rzlm
        N0d1R0oxNjl0U3AxZlovdDhwb2FMLzExSkVRCjhLTlJHRGlXNE5ueGRQYmNLWEI3
        K3JLYWRCcXFxRDhueFpsSENTVStjMHcKLS0tICtRWllST3ZuZXFWenVUN0h5dEVK
        Vnh2Qy9iakZsd3dlQVN2RVZtWmVrSncKG3BCt5BLCRy4gwKCpGlzYtOpOQ7KNq1v
        faj/hzZg76dab0ws18sexzGCTmTf36/7iNTK40Y3JrGsY18oA8nSTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3elFHL0R3cVZIdlFjNHJs
        ZGhwNFBLRlU1Vlh0S20rdTZudXRMWXpsQ0hFCkZQZVpuTWk5ODNaaUIrN1NEU3dW
        MGxvL2kxZGZrbm56S0ozZUJTdXo4T2MKLS0tIGorUThLNnhQRThXaG13MTZBS0Nw
        U05yV2VnTVlRaWp6Z0dNbnBMYjZBekEKQewUuY4shNjLNGBMwQA4Mm7Ig2Wz/XC6
        JM69E+CBJww/rQ40+gdnYy169yAuyou0DND6ZdE78LGJk/rGmIOGkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:9n3rh0DAne/TOPPDtw36qv7ZvM/EhAKBedqhjcyWl4PakqlEcN+TPveuF0VlEnpuDvicUj0B77Wmw3ZGnPkQCOD+9U2J8WKJGwMzsQQg/NNnp1VQSK24wvpbYzXE4aQTfmKsidw/DtOHG/fyorvTNT76l4urkNa/QaH/8EKUaGg=,iv:L/ZcLm/IWxWCO+aiYLs+nfJd0UzgoVSUMs8AnoRxj40=,tag:+Wdqy3MSxgs6P8MN3N3rLA==,type:str]
  version: 3.13.1
