apiVersion: v1
kind: Secret
metadata:
  name: registry-pass
  namespace: copyparty
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:6QjUy//9aLkiVdIHZZLE3PsqctS0HeRccmLt4FOTdXyfmgm9TDG/P+ZFTbiJ0iBshdFc3NFC4SpW/stl4wC59ki3qq3kc4hRmK/AYNfU5IMIJ8bsYhtvWGdEhNK82yWHiXUHvgz5uieQUdv1GhIxGRXFndCpc9ljWJJsy3N3T0H7T6QXVQ==,iv:XlmIsXIt0i5KuEVRU8vS5AXxMzRsWweQDXfbLrn5cfY=,tag:+LpIoESbB1tcHqCw4QqaaQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL1BxZE43YmI3ZkhaK0M1
        QXhLYXNvL3g5UEdNWWNqWmZzN1ExL0w1UWxZCkF1N080UmsydEFWQzl5NVhjMTFo
        eXRWMm1CYTFxVXZVLy9nZlhxcW5RM2MKLS0tIHpuNUFST3BaaGxzSWdpcUV1YktV
        K3JNd1FhWDE4NHEwTTBDdjhrMUZuU3cKdGyvqmSgLLOmhBRe5f7i+oiMYiyec3+H
        ZRtFHg9M2+97ZU3BJe4YBSgK+sL7fBwgyu5v0DAqmvLv6uYvQFiOXA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUmNWNVBuNGRUdVhhYmk2
        VFhvZG9RdkFqaFF1MDNyNlkwbUJHQnBwdkFVCnZpWTBVNnpYSm56WjhUZTVVSldP
        cjZ2d3A2SWVpd1lvNVV1cXh6bUFIencKLS0tIE1jY1ZBUmV3RWRPY3prQ3FSTk16
        RjExVmtubVhVS2dmVXZpR0lsUWkrZW8KWvw6QQe245NdNiCnHVppJNBIbttORwOS
        C+aQx6iKmV8ksvrhV4dfSEZwK2aE5gWo+1hObKp1JsdApt4cd5l92Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc2c5cEFkVDBacDJ5Zjdj
        c3hNbUd5OTJlbVE1YkIzUEFEczl3Z0xKZTNVCmNIZjBPUEtzSjcwRS9iY2tMVDdG
        akpYQ0lWOHpVN0NZRFpOWDNMYUNZUnMKLS0tIHlWS2YybkxkdFphamNVSENZSC9y
        eS83bGM4TFNRWERGVWpiYm9wc2VqRncKUSA/a+HCw0nkWJ6Gum9GX++0CN9hj8wW
        cUEuO0rHVaJVBrmwNq6iuBqOooxkYSztnr46ug5gdQQOvkR5ALnq6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:oI1PvA7zMQ9vyyMf01jo4ryvtHJ4rXE+4u8m6CO5jrsBK0pdlTgaM4Jl9oe2YhC7n5AoTiQ1lkDCL6yo/5R1jt6F/KwNwLxG4hJlATmRd+9Ewd0zpavpMBQmsQ2lQVSZvcCkkaYRCDX6kTB2X1ngy9H4LHtUBH1P+f/OY6YqrEw=,iv:M6QgplTgmzrus08OcWWN94DBhiRD0Wzpt1Qis2UuV/A=,tag:w2bgPSF+t+zsESDb8NEvrA==,type:str]
  version: 3.13.1
