---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: syncthing-gui
  namespace: syncthing
spec:
  parentRefs:
    - name: cilium-gateway-local
      namespace: network
      sectionName: https-syncthing
  hostnames:
    - syncthing.stevevaradi.me
  rules:
    - backendRefs:
        - name: syncthing-gui
          port: 8384
