apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./syncthing-configmap.yaml
  - ./syncthing-service-gui.yaml
  - ./syncthing-service-data.yaml
  - ./syncthing-statefulset.yaml
  - ./httproute.yaml
  - ./security-policy.yaml
  - ./ip-pool.yaml
