---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overleaf-redis
  namespace: storage
spec:
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: redis
      version: 22.0.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: overleaf-redis-values
