apiVersion: v1
kind: Secret
metadata:
  name: immich-redis-auth
  namespace: media
type: Opaque
data:
  password: ENC[AES256_GCM,data:xABI0jM2GXjbNPxeYhAN54h8sF1s2o3A,iv:jmdTxcmLMT+TPi1/jX0z2zt/wJ7NeF8uiyxkQ0WB7e0=,tag:DkbMOp0VtA4iy40YzOZarw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwalk3My9DeFROVXVRSWQz
        clN2c2tWZHMvejdYc2IzWnhpc0RrdnVlbVRZCmQwNXN2UldmVGFCSnZWSHdabTAv
        dWhFZnBUYXJZOCtoeFRIYzVkekRJU0UKLS0tIFh5NHI1SFRWQkQ1UzZrelpCaGpI
        RjU0Z3hBNkVYdWpLWUg3b01LQ1JVY28KXSBGpdGag3ylg6hKw4FjvhnDKir5rjq/
        OooyY1tvOZT0axUJ0TE85gbZ2fxsD+JI3j85rcTv3S/uvZ37qlRNGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd20yQ3VHdUxWbVc4cDBv
        Qjc0c1JGaE1jL0ovS0dWNGFBaDErYllNUnhVCnpLa2daOE1OQ05pUkRtcEFwZFhr
        RGZFOEVIa3kxc0RNUFM1TVBqQWhJSWMKLS0tIFhISDUrdzRWckxNUy83SDFpeXY3
        T2t4QklkNDZiMXR6YlZ6dVRoTnRIOGcKZTAcmiEG6PEi1IqMg4pm4dioAStWZDHL
        QOmFJup/31Q7mxoagceNFH2ptT6/wWdwLSYgJNo42dq9CBzUCTHdXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eEd0QkpoblhEb1ZOTEtC
        UFNRdkpZU2dUUWY4c25nVGpuejJCREZERFJNCnA4UmpmQUkyaWJzRE4wblFTendx
        SHAzYzF3VEtGWEZrWXJneDdEdFpCeHMKLS0tIFJTTVZYa05iODJXZnpvaVJIanVS
        bXpjdmVmZFg5eWRQM3loVEE3TmxMWEUKLIQzD5HoRPHmzvwy8kUEo3gbSIKAUhuO
        kzuP9fp+ybIwQwmGRA7UA/95ydfMPlSbxydweWhJfQprzbEln0DRgg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:whn+4Mt0Uayj1nbaNoNDyz4+8lDi4qIAxNCvXkx3TfdumoTqLVoXVp4NW0iDeDjBYlkYnYGOopnFEgqg0NTOIqSSierjfAZqbVj2nNFqa7Esekfeq4jEGm6nV0Zsr2GYKvZ818IqGufKzhtgBe3fvTyxKTVEcW3BrcKJehbAMvM=,iv:TnibG0ezzVrKzLobjL7jMA4Nt/FL3iqCAo+JLwqcCFk=,tag:uy1nxe5NKt7QklrmEDC8rg==,type:str]
  version: 3.13.1
