apiVersion: v1
kind: Secret
metadata:
  name: immich-redis-auth
  namespace: media
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:xDfeqAPeh9tCYtp0UP3mYg==,iv:PEKq5H0X6RT0CkzJzGSjdfFQaodn6Qxmt98NlztBYmg=,tag:J0r1BtXtyoRc5Lzf4TixDQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4c1NYY1prS0hPUU02OEM1
        bDRCYkxjN2dOR3pZakJVVW5IYVNoM3ZXN1FNCkFWc2cyTDVZd25mTkFYdGVTUGxU
        cWpyblZMckRMNzROTlB2T2hZVW5OMGcKLS0tIHFFcHZjMnBlOUFDSlpQZUdqRkhQ
        OWFrRTdVUHpDVWd4MlZDMElQM3BjdDQKJHkpQHQ3w/SIDaiDxMI2pSHz4cvXFi+p
        p5icNv3TYA3bFkB3ZTCHYJTtaOYHQY1YTsU+RbwjOVu6GbjkRYmaLQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRThoNmtoa0xFaXladmtI
        WGhEQ3NJeEcvOGtDRC9oNlNSS0tST0ZQcEdRCk1RQ1B1VUVYVDZJd01IS2xMUUZt
        ckVwSzJvYzhjc2VkWTZiVys5clFoZkUKLS0tIGdDdXgydWU2a2lLUnVRNG1jWERZ
        RDRrT2JIZ0pma085SVhWamVaTThiczAKgi1YxtvCT7Ikp+ai7O7HFbbN9PiunkYs
        r1IYZQ4AGdheg5tVxdAwhfjbNe1M5WtbYn6z9AQEm10tBB4exJsRXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YmFnUTJYV0xNS2F0M2Zu
        eDYxZ2JUWkR0NytOYzFHRWhkcHYzZGtERkJZCm84aTBDL21lUnR5c1BreGV6YVlV
        UCsvcmJUTWc0dlU5RlBpdUd6WkVYZ0kKLS0tIHZneE9rc0FQWmJGMGNFWmoxTVpQ
        ME5PcXJQK2pwNWYvcVdpakV2NjF1dVEKtdJDi27R9bmpnvpVu6zUDp6FLbtIMfw+
        MMa1sgvCfq7WHZRLUFtGqM+jYL7+XVFfFtmNIDZO9BNYOQSI0L4rMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:Ir+N0F5aw3GReraeI2RYc+82+e1xk6EHG3lrj3cjx7nVFan2yD6RddGRivpwOaRKOyp5tRfXK412kTbGz03YHqwbI08vbtZZpe/4qzykMw6401S/B3NpG5BgYktNgs2gmUVrPXbyBtKfu7Axa4p93b9g6Hf8nha03tG3OBwpfXw=,iv:phB4myLWi3wmocxBsb4lvUccYV6RJwd9IC+GFmQzx0A=,tag:rNmGgXSNa7+d/VkNiP/8ng==,type:str]
  version: 3.13.1
