apiVersion: v1
kind: Secret
metadata:
  name: immich-redis-auth
  namespace: media
type: Opaque
data:
  password: ENC[AES256_GCM,data:L3vxtAbgK/F8jwgGvkuD1ZkQGyaJE7Rl,iv:QIvvklHiItdVdYbA0OWSaCv6fGdXU8iHHsKkQgDtplA=,tag:AqcSzCvohOa/WeGn4uQFFg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWUYzbkJZWWxHYmtBaVgy
        MVd3Mndza0VBRVU0Y1psMHFOV05iOTBHZ0UwCi80NEJXd3lRUkI5b0dpNVRHOUhM
        LzVVWTFubUU3TTRnK2gvTGx1eUtSUW8KLS0tIEdVdHZJamk3eVFPWExrYmI4UGdH
        SGQ0Q1V2M3c3VU1aMmIyNGRXNXJzMk0Ktl5TIxC4NOKrZh6oiXUJHYqC47wfNd2R
        ousULmrytZA54zaYIlk8l3WDde5//gXLXYfjTPQd+nvCQryVakpEEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeGpCYUNpeDZRbzFlWmp1
        WVZXcDhRVkJtZzFwUWlUenE4VGVOZjluNmtrCi9xV0RxenRlOGpqOVlnOFZLMU03
        Tm4wZUMvdjFWenltVWlZd3NOeGhuWTQKLS0tIGJHUXlyR0Q4TUU1aHBDc2VYWUhh
        OWt2dThNSFkveVBjS3VCbGoxOUZkSUEKMf6N/ydtoGO8RDS96Ro26SkqCuBl8Fvz
        2oMVE8MXLWQwvII1idG1NRfVEEY9Defnttcm/dC7X8Ez0pvFBOKm6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR3JNS01zSTk0Yk1wSEV0
        dmNSdnhXZW12TmJESUdIekpPajFabG1pYkZZCkRaNXNZaUFiTS9JTkR3WkcvT0NJ
        bVcwMW9kUXlCTmhSU2pDZ3hNcjZhQUUKLS0tIFhmNStKdDd0VGppQzA0YnRCdkhJ
        dVNCUHVXZExvN21kdHpDVStNSzgwMmMKlkesEeJeRSU4DKE0pC+OfHHTtoBUa3cA
        7kz3IaY6jrtFhAIOn07wAzarjr665NMexrpU5QWGNopnQBqC5WwkyA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeXBPTklRMHFTbU1hc1p1
        Um1SbVpkVmxHSWljYTRlU2FEcjJ2ZEVkY1FrCmEwcnJJMjdRU2FFTHZnT0RZTHZ5
        UytXUHVZNDVWVC9xeU5TMnc0aGpkR0EKLS0tIHgyWExqRnRuNzJ6eUh0K0FJc1ps
        ampxWFZvcUFnQnd4dXNPcFlyMHYzMzgKPhctHMm6lVRDbheD1GmaBf0WSSkPicaa
        PMMVH9jIQdfqDgC7QrT0ryGmn4SnVRMTR2x4brs6MqTxxw+HCIXG2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV1JlemdpSjd5MHdRUkE2
        VFBaYWs5aUZ4Nis3TWNxYytOaFlMSVltWEZ3CjA3c3BqR0lZUklBOVM0b0lzbkVu
        L1NlNHIyaFNsc0ZFUGxreEo4L3lQT3cKLS0tICs4aFhacjFYZ3FieWozOTJwSXpq
        ci9iRVNFM2VnbHhrRE9FRGJNa3hDK00KjkC73MjwZ5OF9uiKoltJRuM3O8vtIuv6
        g4IJMv3XzBQjMj8gZbER/o9h63BPrc8/l4RaA1uBgPB3IGWrONfb2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTEhTNTRLN1N1WEh0Z2Jz
        ZW9taml6eGs2S1o3dUVaTWxxdkVTVmZiNlZFCmYxaEQ0WHpydEd4TW1INVFTSE81
        Q01OeWFsR1Fwc29sSk1RVDFtcTE4WVkKLS0tIElhQ3BBTTdDNnc5MkkxKzl6U2lZ
        bElyZkVDNHkrdTZlMStEb1JacFc1WlkKqQONRw2kTjrvQiqV7wJmoElHiXfJ/kQh
        OcxHqX1Dcn2PHe9PWq3NQ4YjP42BFG0peKX6lDQ7hLCha89WVFHnBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbm02QVMvM3BZNHlGcUta
        R3pJNGFRbHU1NG1ZSHZodHRvYU5LcUJDSmhzCkRKMzRPd0dVUmdQYXAvTEpKUzYw
        KzZUTkliY21oelh0dmYvbzhyMEdVblkKLS0tIDRnZ0lqWWxSR1lvYmY5RjQvUGhJ
        MlVWU0Y5WVJycU4xOXhlWHlNTUNWSG8K17SzLIy06WxBWRdeegap3johu3RI4tgv
        xZ9j0xoTTldn18tFI3Wg7e+sorgX0t0b1itp94MgE4XxvY0JTvQ1zg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUGVud3lybHh5dGJFWTJL
        L1dDRUFaZnJLWVRiWU9DTXM3dVpGQjdDY3dFCkxES1pXZWtuajZaQ3FtSHhjQkJQ
        OG1BMVQ3MW5yNGJlWWRuZ09iOUx4VDQKLS0tIDIyV1NiQnk0bU4rNElKZW5LcTVW
        VE0zZVd5K1ErVUhCWU5rd3QycUp6eGsKg2BbHGC3rdlq8Wle8TTV7ejK82f+1+Lp
        Yu6qIuVUqyTLcXyR6GveuZQNzzY187iOWKfBzyrF6j4WBhEzEoJcAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQnFaWFNYWVJDSmVwT1RT
        ZmdlVnAzeFg3eEFvQklpN3d5NzNXZytYK1Y4CjQ2ekhodUp6VEVZdmVtTW1vR3lH
        Qk9yWXlFT0ozdjVrYzZzbk9hYTJjTFkKLS0tIHp0T2JXWlc5Q2I4WE9scWxra28x
        WVdvU015cVp0aXVpQ3BtVGplZ2FRV2sK+pgquoKs8gtqLVDKezhoVeGM1None405
        qR+blrzzCbZUQv7RH7Woc3k+H05R5CywDECcefoluFbO7uwoQm2d2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETVdWNTBTMWpnUkltcHU5
        S2trdk5kWW03RGVqaGlQQ0plRmh0dzNSaWlNCkgvdlFJWVBRamtGS3RmZzdvMVNv
        aFVMcU1VSmM0L2UxY09VSnJTZFZac28KLS0tIGlhSThvcW54SlZVam16TFVlYTFT
        TTlhOUZWMWZuMUVrYnRxc3N6dWQ4TFEKtWeKIEEmqpisOn+a8lQ78sPKz61lCz4w
        eSxa0u3+WvVo09L0Jzs0fXtatvqdTU+wDqBkvaT6yKH7ly/DawKDkQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:1lUOEoMlwCtXYjTe4ecRSkvwHShFa9XsW3goDcsMSE1DyDsQMJFasHZGTV1ZpjDOxK6p3KAviMhHQWeu5DXqnB9kQH2qGTGgAx2f5U05M8anQLP8CYHtSlYw68dyLKedAB7KXoR74n5SN28ldgnCxpfvv+kAWG5BXEdwAoV4zf4=,iv:XuCMDvjZ4TymDldOHb7BE0ZIikrQCJrtYPs/fAIE2oM=,tag:8wn1o7pyUrOXnCdYVheIiQ==,type:str]
  version: 3.13.1
