apiVersion: v1
kind: Secret
metadata:
  name: overleaf-redis-auth
  namespace: storage
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:SHdNSFFjG+5DBCLyXSzvOg==,iv:WuU0gUZt44GhCM9O9l/HJosxzQPbHT4hne+4pDdZtJw=,tag:adbIVUOtCYIGG4kLC/vQsw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUnE4ZkNrcm1NSGNUaEli
        eXBBLzFram1BRndCTmU0NUhFSHhDL0pGbWpRCkxEbk9qb214MlI1OVlFa2UwQkpt
        Q0hwS051YlhCb2lxZXVIU1l3RjFOWTQKLS0tIG5iSldDYWt3Q2JRbDk3eUxzMkxu
        eHRRNkx1TytkMkJWT1ZRSkovRWdOaG8KLPTE+B3A7rubNfuPsfanQiKf0LrR6tbH
        O5H7NjogXl62ezmQcDhX1Z31JLuATaUZFdLe0Fi9RwoTxf87EeyO/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dEVZQktHeHExNGlZL29o
        eXZFYlZBbTF1M3c1WHF3SGRta1B3UW92YTNrCkN1ZHFvdlBwSjByRmRjd1BqRUow
        UENMVklMQW9ycXoyWU9GUkNLaGgzYnMKLS0tIGlacFQ1V1k2WWpCejVIRmFEcVVE
        Y0lZWHN0YXB6Tk9UMUJ1U1dkWEFtc3cKx2LohDMmpQcQSSxGdXWTBWTClfS5uvgr
        Nos119LE+qOO2HwVdPzudJfWa840HZkkI9ED1gXXFRmqWsJ43h1N1g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVkloc0t1TXF6elFiU1ls
        QVlReVJaK25lNTVIUitqbFJvS2xmMVZSYmlZCk1zTmhoeE4zT2xORWtLRGJtVU9z
        RE8wdVdVM1lvaVJScWJIbW5hYjg1eHcKLS0tIC9HbU5nQm9TWHlRdldkOFhuL1Bx
        K1RwRDYwZjRRUlNOTUZiUXNFLytndmsKXPluo1Y6CNYpQO8B2tR7hLtBBdZR7UzN
        54KLNawZJw+DYlwAZb/xqUqWPjRPI6Q2TmryLbN+qYs5ZuQ8TZQAOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:0DZC6aNg8cJfcKliqsUahJ9nEBRbdiJR475ith3yAJml6t8doBLx1t2IW6QW3c2BNGvkt4P9t8umyNl95gbhYwpo9+GuYVY9F1hxytEp4i+AzLML4lILfy0nPTQNT2JBZCdrdEHlsdiELrswQh9PVAPkmZnK2YA3S6iztHouRA0=,iv:LHYiDLw2Gmv23b538+1CxdzGFSt67ej0ahrAvTjfaHI=,tag:FRgh8yrcfC4rqTjpLk+LcQ==,type:str]
  version: 3.13.1
