apiVersion: v1
kind: Secret
metadata:
  name: overleaf-redis-auth
  namespace: storage
type: Opaque
data:
  password: ENC[AES256_GCM,data:N5f/UFjC37pSrPLs3lWKtEOSI361nKKb,iv:v2/0xIkWSOLw9gJg1s50Ks+8KuNJKVT0izZzmXoBW0U=,tag:nF2R1csjV8s8fPZ53Ctaeg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NEo5UmcvUWU3N2c3ZGlG
        VmlreXJSTTkrWFdoWGQrUUNHZmRlRVl1ZUJFCjhMTkc3RmtjR3dqazM5VjhyOTlZ
        WHNpU2dHNHpnOFJYeE5JU0lNK3ZBaEUKLS0tIHFNVkJtWms5c1AybXIzcVZuc0J6
        am1tM1I3eUxjY09hRURxS1V0NlMyeDgKBxmWhxLqR2FjxJgm3iP4ubuCCDG+guBi
        jq/PkLFUrgqxsEIVTup69rYpIg4X5Obbt0aaG7SskOvziaIm3GwpRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQanUvRlpxV1BSbzZVYUZE
        eFRhK1VqUXRjd29qbWdvbDVzWDhKS0ZPZkMwCi9ORVRZTXluTmVjMUwzd0toV1Ra
        OFo5UWRtWWE5N2tsSEFJbmMzZDVrOE0KLS0tIHZibTZlYmcwWHJVelNWRXBrbGIv
        elRsRTl3N2xnMUlWKzZVWS9GeVFNRG8KoFclLW4kMqf8zcxVAocNh0D1M7ceXHJJ
        6i5MCI6V5fTmddW2od6chxfE5Wu3lf+8CxbtzR6Ahy1VLHiWo9m5ew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYTR0aWRyeDFvZTJEVmVt
        cTJlc1lWSTh0ajVoVXRLT3VGV1YrOWhWOTBzClhpVzE5amRWMERJZFRrb3Q4K2Jx
        cUNBVDFEQVBTZlpOR1A1dTE3S0MwbXcKLS0tIDQ1bys5RXBlcGV1RDdGR1VNNU5o
        ZUt3NEl2NDFxcU9JYnBqa3hYaWxDOXMK4MJZ3Xi9RaJfVqeZtPtWqWHGJ7zVoaIo
        7VhUXXD8i1O38UaFiQkoyx9+bUizUQQHtLon6VqiJUsiHA/IDSNO9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN1ZwVE9NM0NaM0dyR2pX
        K016dk5zdDcyeklhQm00TjVYanpaS205UUZzCkpycjhZeFRBUUx5enlQcHJLOVRm
        VzFrV1JoeDBYTnZCa3ZwL2laWmk5UzgKLS0tIHFRSVVHQ0NjM05uMmtSdHhCQ0s0
        V1NUOVdJdStNK3RNbHhKREtpS3crSDQKWhwUo8GkNbLzaC7YLuUGgUvlgx+cWtHn
        leBqiVEA8LHk+EN9oPkOtRv13Cwo6qJdocA/U/pGS9cFXxBKLY8/Og==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZlhYUXNsZXM3QkN0SS9n
        TGovV205K0lhOVAvTFlGb1JZTmFDOXFoVFFzCllDNG5QUEt4clo5RUJ3MmZqOWtn
        TmtJd1hSVUZDbzZHY1BOVzN5M0M1OEUKLS0tIHZCWUNXek9hM3lveWkyOTJhYkRt
        VFNIdG9wTXlzQ2VpazJpc2JGNmI1bXMKMUhVILck+B+24dxN3EQ7iyKombtMM34C
        RyNeaieuxhczrklmIc9Or0X+UIcj6RjjoCUL5lBapNVD0kVMO+pXhw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YXZZSFlQeGk3WGdIbTZx
        ZzRRUzVWaWdFVHlCUFdodkVIQ1BreTdrVUVJCktpZ3IrUEFJVWp4UHM1clFBOWtq
        WDJ2RTQxMERoYndja1paTDc0YjllZEkKLS0tIE92TExFOGtnUTdUUUwyT3l0UVF2
        eDZSaHQxTVRtMGVpWjY2ZlpzcFJtdXcKiD5ayk5ABajoe7EZ8XNH6S33vWGvdcAn
        U2DFr6WQkjWTyj/DR4L66Y9GHVgk53tztwafp8UKN9WizxoI0i+NwQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVXdXTjlnMlpaVkQxcG5R
        dHd2QnZwZ2ZsTWhhRFNoQ1FCK0lMby9CQ2lvCmtMWmFwemdGb2FpY1hNSmVicXhV
        dWRUNkxtVTdoS3p3Uk5NbmdsWENZOHMKLS0tIGkxK3J3bDFsT29Vb2lzQm11YmRH
        UC8xUXFyci9RNDR2cmJZZUdWQU5vYUEKGYuP3xoO5s9zKnd0BfaXBwC/XBeuAArH
        IRl0zk3cK/+I3OgUtjWGVlUS1VFJm9S0sxeYtaDzfBJk1aiwUOpkXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVUpaT29MMU9vRVRzTWE3
        eVFVT0tvTmVkakxyaUx0a2pSVzYyQTFZL2dRCnVTMWwvVlFoaEJib1VsdmUzeFZ5
        Z25OMkZnbmFRVUNKem05UStSZXRJaXcKLS0tIHI0cmNuREJVU3lCRjQrS3lzMjRr
        Tkc4VlFOTE1IS0I0VnJCN3ZqTkkyVW8KwYBgLiV/rYykdHXvk8u6pBGzKex3vj4H
        w47mZ5vsThWtEWOc7vRGJXW8wiJCC8ed/v6KskZDeGY8j6XbDI7wNg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSzNUVUJSMjc4YU93YTgx
        N1R5bENmUGNwMFgxMHZFUjYwT0NsbzZFSkRNCndNVURrWFZkMkovSE5hNEdNNzhQ
        OU9UNkpQM0FKbEZGaXJsajUvcFBjcFEKLS0tIFZtb3VZVEc1TXFBYnBLSzhQNEE4
        Z0hBQWdPT2gxNXRPUHRTSXBPMEE5cDAKVrxsG6T1bZpWQRgodSQt/UnPA7iRXHrF
        l8GxW+xhScVuAsqtffFIoGJxX9rHs0+yJCc09XJxdpHdMMe3++/mIQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM0NiTGMxZ0dTN3FtNnAy
        b2pjaG1MNk9PeGxQcVVJTWJJTGtvN05VdlVVCmtiekliZFR3TVpIMDNoMzljbkJt
        NTYrSmR2NExTd1BsUVZxVFBvUVkwZTQKLS0tIDRPMUFKdmJqVE92MkNHQldhOHFL
        N0RVZ2E1RVA0UXAzTzh3L0cwU01nU0EKobs5EA6fvcjhOgFg/infEW795bKYozoS
        uMtncwE0fth3BU44JP8AMAgIFDbFqLF6IBUekdpS4GKS/YvV+BWNMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:LX/C5/DKLnP7qht4feM9zuR8sMGnC1tv6Q2HUA18V+lWYFSuDmzSefHp98nosboB1hJYsdrHkPVCxLcpV6OTfCnW8KeiDyv/PeC94VRrl0LGoyXn91VjEKf7gKyqwaO7p4P4nmaEyaqqPE3QiHp+Xgh93XbxyA0fbHTujt4FWW4=,iv:hKfne3KM6u8o3AVzEEvGJ+4h1UbjcSxQ4TV/JdIO5MY=,tag:glLlwTX7LDWM8/7oq5BCrg==,type:str]
  version: 3.13.1
