apiVersion: v1
kind: Secret
metadata:
  name: overleaf-redis-auth
  namespace: storage
type: Opaque
data:
  password: ENC[AES256_GCM,data:QLaJ2N4LSEdqAoPIlcQ7noGO738UH8si,iv:dNqDrgBX7ILRB75ZVyyqjD9JBxi3QT4DKcwWbN4TD8w=,tag:SZu19d07XmKvG4QuR21+gQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4azRRbit2TGhwSjF4V3Fq
        R0R6Z1h6SGFpU0s1NHk1dldOemEwcmRyL1RBCmpsT0ZlamlQelYxQU9CcThoZGl2
        WVlneTRTNUtGN013c1hGRmU4TjFTRmcKLS0tIDdsa2lvcm94d3ZLWER1RVFNbnp0
        ZUtQTTZ5c0NPOWlPaHVyLzA4R3QrUTgKz1zBqx4JwWirw2cjVgiavGVfMY4M/+Ii
        xevjui/7eSSfYKlVKzKemzcCyQ7GxT920sL6KHXxgqJxXzIksgxR3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMDB1OFY1NHNoMHlkUGFj
        Z1RNSlRvZElvdE5CU0ZVeUtLVERxcHNJeVhNCnBXNTVnMHF4T1YrT0M3eVJoT3d0
        cHdrQmlndlhUTmxVSWNvUFkxYktzUXcKLS0tIGZ1M2xDN0N1MVR4S2szNWF1S0V2
        Zm0rdEY5VkJPTlhVdmNoOFpONU9UUUUK59qxQjyF10sJAwxlrdGaKLaxn5E1AYkU
        6aksvHdvz36xuwNvUGqD0sWNGo53Q10pnXSgA7bkiNoY42BcH7qLhg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZXdaZlZ6Vnc5eXVYaFR5
        MFlXdkNpRXhPWHZaaE93bTNKaTZuVFNSVzNjClFBOWRVVXBQU290YlU0K1ZsQnNS
        eE5Ibm9EVGI4bHZvNEVBNWhlQ1V2UTgKLS0tIDJudWIyRWdNNXNPNVB3V29DaE1P
        R2lUbE9uUDkxQ0tNc2hWOFdHMFF1THcK+5xeVuQnpkDiV6UM74YcEW/MBwe20xxk
        QWEFpPUb4c98351RPLrp49ftb2HgdzWdSbhQivznV8LmUdRElpYjcA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:DhazQppjXGIJqwM74GoVG8kx2UpRV9PTSCRmClfHWwEtIgbzagf/osvetLt51AHBsiSCs5qnP41g3gPLtbYCSIB3SuPZsXTU5N/t8kQ/sfYBRyOd+JmU+MGMgimuZtRPyQQ3sSKDEQ+VGbkoCrKDdPeQTKQgxclTuXGKNiOSKeE=,iv:4ZyTaT82AQKhyTdNYIl1ofMwyGwphS9fDa0y9lgP4jA=,tag:OeH5zqFMFSWwBfFXBDLFVQ==,type:str]
  version: 3.13.1
