apiVersion: v1
kind: Secret
metadata:
  name: penpot-redis-auth
  namespace: penpot
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:Z+KHRqUMl/Fs6AzNeaj2tg==,iv:v8l1gqgYZYLOoU+tmgh22EnzJydzgQ3AOYOFwkoEOqc=,tag:i7YBhaDegANokXALId/cWw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSEJCLzB1YWhLZk5XS2NQ
        bis0aCtienFFV3hORWZ6THNmVWJUbEQ3L0QwCldOSW5Kd3RKQ0l6QkkwWWdnNzls
        ZmlkblFQUFpXWHIvOXkyUEw1VFVWdVUKLS0tIDRhVGd3SzhleithazlHMXpLMWlO
        NWlvME00cWRTWjJDZXdTa2JPZjR5Um8Ks1sVG4Fq5ZO3zDap8eUIzZyp6tHs+Yhp
        Bto+uaoYUqyLX6J2RRDaXXjEAp79hMcH+7H7EZ96rC4rQjMYN5I9Tg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Tng0TE53dGdHdWg3dTB2
        SG1yOUIvZG1NY3ptcEF6b3llNnZkNEZMbGhRCjR0T1lFTC9oVkpWSWdNVmxQa0o3
        WTMyLzFhVE45T0dmdFFmYUIzaGlSWXcKLS0tIDZ0RTZ0ZERLNVBMYnVsYng2SGY4
        S0dPalEvaVNWeEVCUVNvZUExN2t5REEKRDJO7ensS2gC0zCim0wvnrwNsR82V1xu
        jPW13ApgIoQII0SX26Ww3XKS9d3fqWVD9gzKF/DaUdmvBzSTmf/n5A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbUJGc3NvTWJndmh2WEp5
        am9zQVZ1ZkNhdTY3MVpVL3lZaWZvMVI4K0U0CmFkdzhydUFGYk4vYWN6Nkh1SVls
        cFFvVjkwWmJ6b2c3ejAwYlhCMHU0Y2sKLS0tIEc3QXZ2am9NY0RLUk01Mnc3bUw3
        R01KSWhHYVQ1bHNBTVNOU2orNXQvSGcKmtm+WN7dQIJrqvPx55P+O7p1I4pPo543
        F0OpW8ODasjFD+pSbei41X9DhRcKLkQJNisKjzivlUVRvA+Fr1Sddw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:rhq5wx2yLQfW+MV4YqdT5wyzovF9pWmCTlty+1bqB757/jUU3zOZx0X9CdkkYTiyECG2deDEVPto5YdIVH4+5J6iZMCfHuYweke1crXGHo875ohG3b0HB5v0mxzSuLmm+Va9lFDX1jkFqDXH59/Lh7NLjkPT0LaMC/nxO8RI9mc=,iv:8YGH4w2GwAWZS2DXercHT4L5CfKTsusoaXaWyOMEZeA=,tag:6oYVawQRjRLIYclPenUlJA==,type:str]
  version: 3.13.1
