apiVersion: v1
kind: Secret
metadata:
  name: penpot-redis-auth
  namespace: penpot
type: Opaque
data:
  password: ENC[AES256_GCM,data:pIVn5fWmc/pE+2AS0P1Ttz62sJlCvgSH,iv:MASuiVgzfD1Dz/V3okXSOf53bNFoxeZq8PY5ydND3io=,tag:kccp7j8QQbIHBoBLxvMKlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcHlram56UmtKd0tYYXk5
        ZjlnbEUzR012Tnl0Vm9GMnZGa3laM0RxRVNnClQ0SmwvYTFabWMvblZna1VOckR0
        aXpoZTVHN3R6bkc0bnR4a0FVQlE3Vk0KLS0tIHpGWGIwSnI3TGpveUNoUWtPNFdR
        WmM4VnFiM1VpdWU3a2N0YjhIeHloQmsKrdMAZR/yiARn7OqsDOzlj23IVPYeqRvk
        BMXFEKzDM6iP2za/UGBMqAx/9A8N6Lfm6tycM6hT1HAPGM4juVI/zg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeTh0ZlRvWlM1RXRSbFdH
        Y0Q1VXZYWVdzQjROQ2QxUnVrNjJBTkVVYzFBCmRqUlcwbmp5eS8rOUgzOVl4TUtS
        Mitzamx4UEpmWnY0RWdMMm9heFQ2d3MKLS0tIGlzWWhuQjNGVndyb3ZkUE9WQkZn
        bHVqYmVzLzdXZFVWN2Y5SU5YZnAxbXcK8XI49zlwzLjwcjoq3QViP2S3CH99o1CT
        XnT5EMT7PVTZurErg3QLLNKSgwR++ngJsCc5wKlNtP9tERZZxzx98w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeFdUMUNveXp6OE9JV1U4
        RVNVb0w5V3RwYTBFbE1xdzFoaHhIVmFiekFjCllZclpwTW1wby85WEZvZGl6dVFK
        Q3dUQk1JVHBNUkF1N2gyRmxnM2xmMkkKLS0tIEQyazZ3OHhYekc3QXhIbnBYSFRu
        UmFlYit6Wk1SREk2VHVtQnJBZ1ZBeTAKRAztGoPjybtXEVaRoTaCQFbRzDPJrGm9
        XoQzUnauZHYzwS322ES029tjY61Q9JEVfcAXoL2F/8PuuP+ZeQrg5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcXZtV0o5blYyR3lnZCtD
        MFRLbEhOZHgzemY0RmhBaWpoU2IrV3JVWGtFCnJiUTNnVUR2SW0zZHVJS205Wjgw
        UnpOVlUycWVpNDMzUW9tb0pvQXorMk0KLS0tIDNPcTBhM0ZUemFPM1E4U1hwNFR5
        QlFmMG1OeXorcVF6enlpU0xqQlNMVjQK3LYw9l4WCDEYNXwBLcjlbuqUVpZatUw3
        U3LltMtIf/VfY8x7/AMNcRK7cUdaiHk89puVagfzxNW3uAZdqArjVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaDJ6MDN2Wml0RHkwZGV6
        RFVLUnNST2poeG80dFU1RjZxYmQ3aXVSK3hnCmI1cktWeHR2OUFwaHo3MVhhMVNI
        eUlpWDR6Mkd4dXJOVXpHQ1M3VEl3bzAKLS0tIHB6NlNiUkNSR0k0WUYwdjhBbEcv
        NGRGQVJqQWRGU2tEdk9qWnR2MWZvOGMKy2GjAsfFLhphXZ7uZ2RrMWc8eLK+Lx7S
        N0EDE7pYqHeqaljpti29PBiXAk9O3WzkRIJl3jKntHp15TmdTpSNsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dFNiSFZVME9yOU5YTzQx
        YWl4YWREZTFwdVVVNVZUV0s5ODVOZjBGaTNZCnVIR09JdU11MTdNSWoyVzVtakFC
        NXVBVTM0U0lneUlVSXU1dHZsWVRkRDQKLS0tICt6VzJlT05NeDB0cDhkZS9PdTYr
        MGhPTS9RVWc0S05CVXdMSHA1WVFrZFUKu4waUJTBJuDYDrZT1TNYwuseJ2IIlNM4
        Psv7x1COne6Geg0XQ3WdGj9z/G2wlk1x2ixZkOH6KKu4sHxkAeuJ0g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWC9IcEJKaE9mNTV2NEsx
        dWQreHpFN1V1alAweWh2ODVwSDdZQ0hnNW1RCmg0Kys1LzdnaWZBUk5GMCtKUzAx
        eEJpU0dFS2lZV2Q1OVRyNHI0Z2JBK0UKLS0tIGh0UlFHT1BmQVYwMkJGMWVCNXdB
        TXJHTlltUDZrcUxtYTNUaVdUdlNoM0kKfnbEjFYjgA0A0zy4OaSOWy8nMSBPYed8
        amaJcsAf5O0m3XgskapeTmWuGOypy/JBp5rWHzHbuTrWJaontR3cwA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OW83YkhsbUdGTk8wenMx
        R0t5Ukt6SWFhdnVLS2Z5SGt0cGVHOURNSHl3CnU3VFRud1RaeitqRGNSUGpGdHJB
        NzFYUWlUMTd5SzBZalRUcjVoR1hNd28KLS0tIDhDcm1Qc2NwZHVCNFA0QnhOUm9Q
        TUFURkpRQVdNNGU5Y2U0OVU0aVFUVU0KpUs060IvHtpEMyomI0kA5x8aV8/Nm2z4
        AdOktBVzHBKp0FRZ03O607xZb5WleYrTSwHhNxB9Coz1wGceJw23KQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QzlVcjRoc3o2QXZka0E1
        WHF3T0FQbVRlai83cmVpeDZrWWdVRHBobmpVClFEWXdZc3pRWUw2NU5Hd1E0Zkhq
        bk14KzB1OExlVXplbWg0VllSdjkybGcKLS0tIElsYngxb2Y4c3dXdGtGbDNKeXds
        QTRKa2hzbSt5aDJuSmZLSElobDEweGMKbDhTls83rhLHYy+0mxDOiM7XZIiwzA9e
        +DFFMTZIOQZPYmCiblZ3iDOJaAAmShfsgLgvyspN/9voWaVjG66/yQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMWJhR3pnOW43ZUhyb2xE
        MXRzZzhjTjJmMFBHUUJvY3VMRysyNHZMeEQ0ClNNMitoeUc3dlN6dUN4RzZRc0hG
        VEFGWVMwa05ZSndnVGh2bEltNkltYVEKLS0tIDBGWVdQWnVKQnV4RlQ1MlZNTGVn
        aCtWMmhnMm9iN3pnc1FVSVJhRHVGWDgK9H6CrgIjkcmtLy4RRFsdy5KL92adEy6s
        3jYKudl+K5RS6ZNX8QdH/AILEyGrJNhD9QtL2i6dDbuXkDBjtkSYWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:3sMuHPrFuNpL0yPGkKO3rpJNd8uR2b3+cEUehqOq8P66SGGcWoVVkhR+TkeE6Vifq8xF0L+GKtHgetATELHCKAfpw0XhRfxEaxls+XjGYc+2uSj3gMTeT2Wod7pvG69uruWDdbf/HsV0AXXvv83bbrDOMKJpUbZZhMIAQUa6Yho=,iv:3KiZt8j2ZegpnVarl0LSKZm89ZXk2oGZ/DlqKrcs8WE=,tag:fK2BFu3X8FBrJMC3Iv9y3w==,type:str]
  version: 3.13.1
