apiVersion: v1
kind: Secret
metadata:
  name: penpot-redis-auth
  namespace: penpot
type: Opaque
data:
  password: ENC[AES256_GCM,data:U2wSQ+5DKkdtoRM3hG3Ecdv4ri0oQPko,iv:hN2x6iRn04E3GojrhHP2+hB1nzGCjTyYn9O8AVQolqE=,tag:OmK0UKVv14B2SHvvwwItQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVakdqTTFQU0pST3hHQkdF
        cEplMUd4eHJXaDhaTk9SUVdWMHU4blFIN2o0CnlUdnNCNThBS0NYQmNTL0Y4YkdC
        OWZiYS9RSUhEU1pUU3U4OVNTQUJXSmsKLS0tIExuSjZGeWhRMFJhMGZvbDFJN0Rv
        eWowdTRiWWVxeGVuRHhLZnN6LytxTTAK+Np/FWGOS5eM4oVEjACX0fqAMXNEZtfb
        mu5Ju1oQ/dMCMvoBMnD21NL5EtXxCc/rJwWfytx8BTJjB4J5i+4xBg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbnZML0tzcWpWM0twZW9q
        NnRIeHIvSTkwMUJkQmdFTGhkcFB6VDFEVUFZCmxOWU5TRzA4Ym9GM1pUMEg4RXR2
        MkRRMGxVeUFuU1I5OEJtTnFDeERlOTAKLS0tIG4xSFpXeGVyRDFIM09naUh0cVpI
        aVVGc00zdzdvb1E0SjUvcGFmeFJQRG8KsRLtIqKZQQnEdGeotAHQSKA3je2whSBY
        msutyTdUxRp2Lho1sli5jh80iC2jq6nPckDrJryTgcy5nUkwM4Dsgg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2R2dqeEZML2MrZ1RZYzI1
        eXZjQnZvL21VbWJJQXVmV0w3c2JwNDR2YlNFCnp4OHBVaWxKcUplKzZ3Sk5UMnRX
        KzB3MkVLZHBlWkZxaUkraUxXVGZyYjQKLS0tIG82U1g1MmNOMXhWQXlrVG10YTZV
        YVEzaVU4WEtIeUNkMmlkVGQ0bktyT0EK/bg4VYB5gRCOMl+gMDdJR70tp6y2/Aw0
        BDOaEGEYqdLOAe/4XiyAH4ZXazCKiZFBZsN/BMQoru+Ef+dvaTTRFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:XBHf6olhxVegA+W3y3GrMSfcf8JZ/Zk3OpXn38oW36p0M+/r6PTinkbD68DKBjcByEyz7GuwW9UB3AG3Ur5fW3G3umUPSvqCpE/bLoyjAQCfKaXUAePuB+7OlDRXAwqMhUpV/B5/htWcUSvpucj1navRC8Qr4iVKhwcdNdJv0QY=,iv:PZOEGinSE9lVhDPx11l9rdKcOKL3d+1aB7B8G+JiikA=,tag:G8QP4OCXjeTELpOsTaX59Q==,type:str]
  version: 3.13.1
