apiVersion: v1
kind: Secret
metadata:
  name: renovate-redis-auth
  namespace: automation
type: Opaque
data:
  password: ENC[AES256_GCM,data:7lH/M7eLONq0WX6Hus3SH04DPIpXT/GD,iv:eoF3xeoATdYJhYcVz4VEmhYutsFdp4o69GXzQdvb0j0=,tag:5jtsTJpvD+c1JXwrQ5xlsg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTUxZbVZEQW1GTFBKRmVV
        OUo3dCtRSzFSYVUxQjRhRTNGUmsxR1lFaEVJCnNqVkJlODhSZGVjQnBMSXVNZmpZ
        N2JrWkdodEVJM3NURHNFK0dlY0JSdTAKLS0tIGcvLzJHejVoWThuUFdDNWRsSjdh
        dXZ1Y2lDUzBmRUpqcGtjajhnQVVzaWcKvQaMTWlqbkPLvOJWAlLR+0Bvw6kiw61Y
        is4JPQDXmxm7w3MInALrkBWyWyrPbG48jG8JDkBTlXa7CgoNo1RoiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaktEMkV2bWZMTnJXWGZw
        Vm13QjRqZjVVbEpwdkptWW9OWk5IenFnbVcwCnM1V21wKzEwYU4rSzdVMWw3aUVz
        M3B0bmY5UXduTURwTWRBRkJjZzFRS3cKLS0tIENQd0tMaDRiSkhUNnJFYnFGMlB3
        bU5iUytLWHJtNXZ2czlzZ3dIMFF5Yk0KPaKy6Zi9xikxEqiJl3yWOK8YtGu042KJ
        qye0QhKXXqLW40MIv5Vnac8qdxZ1krECD4rB4An7jVS7VzGcTBZVVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMWtKWTJUTC9FTU8rMEti
        bC9wQnZVVUtXMWlxUTRxMFdLRFZLdTVReDNVCml5Qk5rWTVCZzlWTTFzdWc2eEVp
        Zm1pWmFZYVdjOWRSdHY1TktTSVhZVnMKLS0tIHZrenFtTU1LTTB2dWExLzM0R2R0
        aDJWVjZFS0E4TUVaYXp2cS8rbkJkM2cKihTFaihue3AtKWR/QZewXUnpV/uvaeCw
        piyRNTew7TLxN0s/UxHFVNFtF+Vcda3kuNLeIgm6A2PwTZB1LlR0lA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:yTK1Xa6ElducF1lPgBsSCkIhkkFOwGK7pGiP+9R5NgcQSeicuZEC622LIqCEFOIzUZUOdKgSirw22BuAtaPHArCABLdnPsnFCs1BBc8iOoWDGX9YzLsb3j2A7B5e2yF1eaQpJLD8GVNOz0HADptVLpRsERLKKlsJHcqltsKorxQ=,iv:QrwoornJRyTRlVkZ0tko1esr6sOyAoqBZoKV+15a5Es=,tag:x8wiqHyRwQRAYRO8alj3jg==,type:str]
  version: 3.13.1
