apiVersion: v1
kind: Secret
metadata:
  name: renovate-redis-auth
  namespace: automation
type: Opaque
data:
  password: ENC[AES256_GCM,data:GS8a6NPJwjrc01y8iijNs7RPeo/QPh0/,iv:sKXoCUaBJV5NVgdaqztWl9+t/Kdb4kZSSXJww/ejIwM=,tag:TVnPrlwx92QfoObQCfzdkA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbHo4U2hMWHNFSmsyNG5B
        M1JRK3RsbWJwOHgyeExEcUZsT1Bpci9zT2xzCkNzdnI0aEtONUNIR2dyd3lpcjc5
        VzNvSnhNZUtlbkNDbUp0SE0zM2c1dlUKLS0tIG9keXVBdXZDei9ObVpqN1lRRjVl
        STNvUzlGc1ZNK1JkdTJNbEIrTi9ad1kK6hH8CHVBGiE+GQH0QSgsmmF3N3NXyl2v
        xdk47g1uomWdcJpZRqH1RK+KPYf91eWLWUJW4TxWEkWDnMKPvUpFiw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMXAyMm5CQWtGNTdwSUZF
        OWJXZDNFMkZCQXJkOC95azdEN056bWkxR0dFCk5UL0RnU3ZKRXJzZzU2eTFvMTc5
        aGVhT0xjanJiOHJveU9UcTlDanpHSUkKLS0tIHh4NERNYUdlREFSNzhiaDhZRmZ1
        L21aSkQyUHdZZmVDVmNOUFJHSTZBQTQKPtgKMn83vZM7yg5oVLFRT5DIdnOSY0wp
        ESjZA3TjwEf7wBUuho1I1a44zxEteUNjFuGz9kiS3G562T1RmP2Ldg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOUYwMFY2bGxTb3F4RWhV
        dXRodW5ZdFpZT21xZUc4VDZ3M2UrclNRQUE4Ck96TlJXeDVZbTdNR2d3RlVQa1hR
        TVp3OTJXT3VVeDMxL1lJemFyQU1vS2cKLS0tIGxCb2tuU1hwODVCMXdVeFRGdUNk
        TDRKTCtjcEJZMXBDQzNPaU9acjFyZzAKj/s04EKdxr7uc/NTQ0QWpWJtVhtZisUG
        eLOWr37pwlWqX0zkxTTIE5SePzx/TPSltkmJmelYn8p2/xGuE04nyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNFNmclZMMHBMWmtZcFBv
        VGdmcWs1aHh6VlpEVkhhL1JIT0dSMDJMekRnCnNXTVpyLzNoTExMQzFCTEhRanZG
        ZjlHYmpTUXVRRVRCRHg3ZjdjVnluVzQKLS0tIGE1cTNCbXNGQVFIQjVtQ1FQQUZG
        UjZQdWFzRXRVMGJTMnFPeUp2MHZxQjgKzli3QI9CwOWO2Kue2H3rD0c7Fyr7iVIe
        OEjzCc8CR0rmLeu1XYFKHXOojUwWhRJKaB6iH7o6ZSdd246r7S/jpA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RCthNjJKSXIrUWg4eWZt
        WThkTzVSbXBEVjNpWVNVS2w3NVovbngyQ1Y4Ckg1NE9IZy9heE9kTnBob1QzSVpk
        ZDQ3MWdXVG92S2NSSXVXSld3dGYydTgKLS0tIFBEVmhLa1VGMUN6ZG9kVjMrSTls
        T1A4cEZRUFluMGxpcEYvbFRjQ1UvWFkKK564ov/9LstRq+haxzo842qYBxyVrFQu
        qzA+fRxUTR8aSYX9sfEMGGD2jm/FkwXMheG4iEseWD4Xh8/630au9Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbDFUdkdNTE53UEN6dkRp
        VDg3b0JtdHJ5RDY2NDdlejc3T090VVZHekFJCjhZTEE4SnBmZ0VNWURycHFVdnZH
        Ym9SRFAvWmdKMjZXdGg5QzdVUFE0MG8KLS0tIGhMdmNtNTlMN0MrMFNBcGo2cVNL
        UERDZmdRRTBYR2NyTkZxeTVFRUJ5azAK3DM7teII+e676DQ5bO/jER3o9G4leERg
        ScYBAC5IMoC0HZnrswSfQukWbmw9m+HTtJxqYCvqm3J9h4WVQp6kUw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDU3V1ZRWnB5RDJYQVFJ
        NkM5Nk1jSUd6c3l5aytPdzdXZGEvOVRBT244CnlneWJ2aGRDVlVsR0V6TFFQbnRY
        WjMwd3N4ei9DZ0dBVSt3NVpsVE01RFUKLS0tIHI5eWEwMW9KdTErMGk1eFk0Mkdr
        TXJwaVBtN0JFeUR3eWwvSDBZdmJOTEUKX4FTZfzNPvqPEC6f4CXJd0iFpfuDm4aJ
        2QAWBOfOK5VPpzLD8IoT3CUuQWgH/TOb+GHBuGYPib8/JSJGMEan4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza1ZoOWw2OUV0SDNuSFdW
        UHdIeThrRXlXb3hrUzM2d2JJQkZPV1VreEV3ClZiaWwzREg4M1VFSER1WWhCRis5
        bm15ei8yS0crblVpenErQ1VINi9YUzQKLS0tIEcvTW5sNGpXUzJsYkFEc0o4VHRG
        ZXovdE9ZN1prcGxxaVUwZE9yTU1UYkEK95wFvsqOkUPd2DGTNG5qMSUTkuv6f/Mo
        94D+vyMOzcvsVDgdCY8iZHKVK17kzmalFGvHmMmAz8sik7LPsU1wrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1NHYWt4UlRmLzFubFNq
        YnJLNkJBV3NUZE1IZ0ovdjMzeWYxR1Y0clFVCjZnQ1VRbWxlZ3pudnZLSitaalJP
        YjdMekw3NUtoLzEvT2Vhb05QcUNqOWMKLS0tIGd5eVVEZWphaEVwajJoU1VTaytJ
        ZktBUEhzejJGajRWSytERjJGNlhqMGcKLJAjOK221YzpZ11Ro17e/K0HjD8kning
        1nLbHsWbhq43g9VsJ9MtqHoEzXVGJ1L4+hR6LoDb5AByZ//rgiPGuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTm5uWXg2bW5vNlBseEVz
        VHFHWVM1K2VZMjVZbGFjVUFDWlRpY1MxWjBnCm1rc2JJdkp3MGdLVHlDcTRPN2x3
        TGhmaDBrSDhzeGtjUHlqN090ZEhrcUUKLS0tIDh3QWdUT2p3c3I1K0RnZ1JjdUVi
        SGRnZGEvOTJvZDBheWN5eE5nNHU1aTgKwGko0SAFrtGUMBpfJAnczxUeU+bwGaoJ
        j2JYfhCPD2dFNEsJmFdWzQLSiYkYZnCvkHITcpEjE7c0W+NgTxYUgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:wreogBedFfjXoOfzLLktuf0TSIhm1A4ez+DaaEa1fHWOr9iD1LCoUMeCfHo+3DVXBpEJ/noWDB6LkBsBiU0aYSdWTyNoTDXSQhi0qnH5qFlZefaORR0Za/011VJJfUeGlEzKgE7+FH/wYneAAKW7CPw+TpX3SLlkmpPExLLEdSI=,iv:VspRx9b6hChCDOMP4QTzRnA1OUqsniZTEGQPAFOh+6I=,tag:ZcFB+th4cnMwFKFhQx/NNg==,type:str]
  version: 3.13.1
