apiVersion: v1
kind: Secret
metadata:
  name: renovate-redis-auth
  namespace: automation
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:GJ8H7rnh9WysFJ8u0GlgFg==,iv:OTDhdH+CpXa6rLUye6hsdHMt/vTfx2iFy8qMtwqYzQ4=,tag:xlDClNGsiXHMa6WpqRI79g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MVFsWjBGVFZXS25DYUt2
        U0tDLzh1S0FTcnFNeFZqNk43SlYvUWI1RUNjCjVwYUczZW9ycFB3RjBTd1QrSWlO
        WWFoMitKdDVpbGd0THJsVFJSRlJ6YmsKLS0tIFlpRmV1Rkp1dDM1MkhJdld6Z0lN
        QzEvY2RyTksyT1dGSkphVEF4YkY4cjAKgN9+ikdw5R3gYUv0ksGIOP/YYQWfxEcc
        sGDFVed5EIa4+D+r9IVJNJwRGipPNTcG+sr9xd4b7xxLw+nMNeZBBw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUTF3T3AxU3pXZUxYTlgx
        cGcrWENqZE01OStVTC9TZEVhR2pQYjZTTURVCmtNM1dNTlpMNXp1QVBHdEswZHJ0
        YkZ6T2ttZWxnOThydjdzaWxKYWhJRnMKLS0tIHQ2bGZ2Ylh4NWY2dytSc25sOHVY
        bkpwUHNsV3Fiak5JM0s3M0IrM0VEcncK7pGPeAqllKcEtawYuug1wYPP1weh5eVU
        sJFt5TycFkzSNKjixf17ogJs+AqLP4Z0rje9tkaSImZ26fKPYztv1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVWhmemlOOUNlRjRoVmo1
        d3luUzBXd2JHMk01czQ0Q1pFd2ptMDdrakJnCkhTcFI1bmErakFrT2ZnbXV1LzI4
        S0hmQXlMcXBLZ3l5QXFxUEZISU51VU0KLS0tIDRscGhhTlc2Z3FwbXk0a2ErQXA1
        Q2xGVXdhRkZ3NkwvSHY5b2xMT1ZwZnMKVjKN9V33aVhpbzdZ3BqrC+WVN9reIEbo
        VnRS5FqUaJYMNkDFHt1lDujPBWalgqMLL2qiOD7DlKZ2/RbWeBeD7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:Lwou1Nosne+KuAE7Ou7jPTXCj7wA2iBvg413+qMxfw6PIcsHHS2bLpr/cXX+zlrSqguO/ywLAygxd37dpF8tbfsU4r1spoABx/8jVav7dWukiFE/ExHtGf7pEv/DUfPhy2q1cWUTk43kEYDSIkLrBgT2+oIYsuVpfx6QRVZ3opw=,iv:B5OytfrUWIp5Aaoa3S0y8OLHhxP2Ssx6XI6oOVTmWWU=,tag:7yA4LMwsyKrq6sdfdoPGEA==,type:str]
  version: 3.13.1
