---
apiVersion: v1
kind: Service
metadata:
  name: minio-external
  namespace: external
spec:
  ports:
    - name: web
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: s3
      port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: minio-external-1
  namespace: external
  labels:
    kubernetes.io/service-name: minio-external
addressType: IPv4
ports:
  - name: web
    protocol: TCP
    port: 9001
  - name: s3
    protocol: TCP
    port: 9000
endpoints:
  - addresses:
      - 192.168.0.151
    conditions:
      ready: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/24,10.192.1.0/24"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minio.stevevaradi.me
        - api.minio.stevevaradi.me
      secretName: minio-tls
  rules:
    - host: minio.stevevaradi.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-external
                port:
                  name: web
    - host: api.minio.stevevaradi.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-external
                port:
                  name: s3
