---
apiVersion: v1
kind: Service
metadata:
  name: ollama-external
  namespace: external
spec:
  ports:
    - name: web
      port: 11434
      targetPort: 11434
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ollama-external-1
  namespace: external
  labels:
    kubernetes.io/service-name: ollama-external
addressType: IPv4
ports:
  - name: web
    protocol: TCP
    port: 11434
endpoints:
  - addresses:
      - 192.168.0.145
    conditions:
      ready: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ollama
  namespace: external
spec:
  parentRefs:
    - name: cilium-gateway-local
      namespace: network
      sectionName: https-ollama
  hostnames:
    - ollama.stevevaradi.me
  rules:
    - backendRefs:
        - name: ollama-external
          port: 11434
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: lan-only-ollama
  namespace: external
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ollama
  authorization:
    defaultAction: Deny
    rules:
      - action: Allow
        principal:
          clientCIDRs:
            - 192.168.0.0/24
            - 10.192.1.0/24
