---
apiVersion: v1
kind: Service
metadata:
  name: ollama-external
  namespace: external
spec:
  ports:
    - name: web
      port: 11434
      targetPort: 11434
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ollama-external-1
  namespace: external
  labels:
    kubernetes.io/service-name: ollama-external
addressType: IPv4
ports:
  - name: web
    protocol: TCP
    port: 11434
endpoints:
  - addresses:
      - 192.168.0.145
    conditions:
      ready: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama
  namespace: external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/24,10.192.1.0/24"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ollama.stevevaradi.me
      secretName: ollama-tls
  rules:
    - host: ollama.stevevaradi.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama-external
                port:
                  name: web
