---
apiVersion: v1
kind: Service
metadata:
  name: voron-external
  namespace: external
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: cam
      port: 8899
      targetPort: 8899
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: voron-external-1
  namespace: external
  labels:
    kubernetes.io/service-name: voron-external
addressType: IPv4
ports:
  - name: web
    protocol: TCP
    port: 80
  - name: cam
    protocol: TCP
    port: 8899
endpoints:
  - addresses:
      - 192.168.0.91
    conditions:
      ready: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: voron
  namespace: external
spec:
  parentRefs:
    - name: cilium-gateway-local
      namespace: network
      sectionName: https-voron
  hostnames:
    - voron.stevevaradi.me
  rules:
    - matches:
        - path:
            type: Exact
            value: /stream
        - path:
            type: Exact
            value: /snapshot
      backendRefs:
        - name: voron-external
          port: 8899
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: voron-external
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: voron-cam
  namespace: external
spec:
  parentRefs:
    - name: cilium-gateway-local
      namespace: network
      sectionName: https-voron-cam
  hostnames:
    - cam.voron.stevevaradi.me
  rules:
    - backendRefs:
        - name: voron-external
          port: 8899
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: lan-only-voron
  namespace: external
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: voron
  authorization:
    defaultAction: Deny
    rules:
      - action: Allow
        principal:
          clientCIDRs:
            - 192.168.0.0/24
            - 10.192.1.0/24
