apiVersion: v1
kind: Secret
metadata:
  name: penpot-api-key
  namespace: penpot
type: Opaque
data:
  key: ENC[AES256_GCM,data:S33X0A7mC7rObGtfw03L+2OComcxe4qiJbMaYkCtf4den2zkM1aru1ssRp5ry/l2iZiASpWwUq7l+mjAFI0dOBmz4FM9Vj1pCgsrur6NZLkTZUaxXmB8f1li0hruLLvpkqc23EUpQmprL+0pOOFNWd1/VVI=,iv:4AIxmskR2dLD4GQ0u53suYfv+A1BoV+zgzaoAKlnkSg=,tag:KbOSuNOtYaEhpxL81RFeCA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSEpYb1Q4aDI1dnhvVTAv
        dE1jWlRld0pXSDN0WHBWR3BYSTRDaStENG13Ck9CS3YwSm50OXZ4TDU2SlI3aUF4
        U0R6R1JydDRJd0h0Y3hhSm5vS2NkS2cKLS0tIEY4K0RkUWdDYk81d2QxWlhlWXRN
        K29jekh2WlROV3NyWi84WnUrMkplcFUKfvZLVTCU1bq2RvACq84qjORS3OEFjpzk
        05aKLSd2z/Pek0WYYyH5U66328RK99SjsP2HWoOJLdQ34eiEr/h8zQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaUtuNnBhVkNKVVFab2pU
        OFcxRUZvZHlxeXhORjBFbnpTNFQ4RTYzNzFzClpvS2ZJdktyQXFMU0p6dkVFaFVW
        M28zSUFPVVFBTHNVblBiMEM1OVUrZ2cKLS0tIFFpVzZlRkFjTk0zZHdnVkVONThO
        ZDMvdmRhYjBCOU4rb1BXK1FFSVdRdUUKrshWjW4Y5dbUsy4ykpI42elcwuba+etK
        NEFWAcYzuxSB49quI3NT1bQWA0fXpezqCd81Ms7W3E7tU/FNhwo8pQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVW1DZEpLS0ZnMFh5NVcy
        MStkeUpLNGswSVdHWFduQnFwdUg0dm5uZ2drClJSZFA1cGVteU9JZ09mTldsRUhr
        elJlTC9OYUlEQ3lOZU9DTkljdGliZkUKLS0tIDBCdFBDbHRmdXlQaFY1d1JxTFAr
        UnFpb3FFSEJJZjA5U2ZMWlBJRWtQcXcKxnlOXRDgt/0eclrcu6KpBmdTJED8Z+Mg
        3P+2LbHinQKLheiIQxy2baAUUQ63xeptcBXFUnrwcj4aIx0vxQuGAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:a1vG1exT0fgVnFTtyJ1HPUnxT+T2opt4a8PvAUr/oW/mUnHXWRDYsAgaX+dJeGC7hqcMReNFMa/eWDUPAlwbygKz/DptEqzZ78+PmiO0qjzWc/ynE91nGPhBVBoMSejZwWYNkY5Z7gV8FXTIbva8fz+hB6IS7EXw5Vl291DW8PI=,iv:kYRrr0LZ7OX23Z/thQvvEim7XzYR9+07/QNeq86+FHA=,tag:MCKXxv87x6Yx/uNepTfjWQ==,type:str]
  version: 3.13.1
