apiVersion: v1
kind: Secret
metadata:
  name: penpot-redis-uri
  namespace: penpot
type: Opaque
data:
  uri: ENC[AES256_GCM,data:oFebyPplSFAeBnXfgQcipvKDjavbQH4JrQ98gQl8uktgdkzEr+SGoXrr8NZhsnKmGrdCD3eZ/qS1YPGgOlOoEjKBUR4nGSDQ,iv:Wl+m2yQkdCpHzXZXm9ljPxZRPGjVTGwenSCEETQJqfw=,tag:w/y+NNLB4atG4+AE3gO1ww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndzdBaUhaRjFkOXliQkEv
        cll2YnZFeFFTa3lmZHdES2NFKzdMU3pHSTAwCm1XTUxhMitBZjdrTTdoaGFKMzdQ
        bnQxNnNyYmNOS0R3ZDFIVGVvQkcwVUUKLS0tIFYzOWRVeHZvNk5sOGpCWFc0QmlL
        b3JIVEdGNXlyRzl3Q3FOcWt3RkxLb2cK8I71VHjyE4RthWIxIKRvn01erZCuuB2v
        QebA0gbuJhhttTa8Yfx2S6jRmdebfXO7JzUHx624sdTXlgxSzeNx5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M1J3R0swd1IreEZqVFBa
        d2tqVlJXU0xrZ1lvcVNxL1l4SDRLOTVBQXhzCmZINHRQamlSQ3Y4QTh5ZWFNQ25C
        YWVKbzArM2tRTmVPdGEzRGY2bEcrMzQKLS0tIDloTlpwK2QvekN1N3M4cmF5Qzdq
        aFA1YVVqbGREVG1rVlRJYk5acXZZVmsKIeLLpFGuoEM1UgNzQKs/sxM286UKi1nG
        f0XwGbT1+aH5oEXGzN3e6RG5xozDdrQkytdi+QGqs2UQ03RsXht39w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RHcxQkgyTnFYM2tEUHJG
        ZTlBMHRuanE5dmFUUnhsM0hYdm5GZTZHSEJJCnNMSlAwSXZaWno4R3hFQWlWUkpp
        TVFmNzhRSm9QMUdWeUVVdDZ0cEo1VWMKLS0tIDluNGp4MXdvOVVHNExubS9YQWhr
        aHgzZUF2WUpuNEpRaitLRTB4QkNZS2cKhbDoNwgJXqLSXs137KELVIpGvWEBF4Xc
        oxiZgqVTl07fVsSAufVfO3tCW3fexyEojTfG5A52LD9U0LaxHU7cVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa09vTGlSaUlSUXd5RFYw
        VDNtUnBOVnpsalV5czFES0pPbDdXalFiZ0V3Cno0TnN4cUhacEVQeTJHZE5nY3lE
        eERoVDg0MDN5MGVhWDk3eGxmbE12QlkKLS0tIHJSdEFKY05KRFVSYnhhYThraTAz
        eUhVWlFVdnNFa2VPRE1TckJvbzBpSncKNV/LH5vg9WJ5iE/4s7s6pRo5bX7F0YZa
        aCqfhv74kGculZynxw+yMzBtDK1XsudRAM9QFKJ46Bkh83cpKlKXhQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dFVJMkFkQTJpajRpRW1W
        TmFWejhHSUNGc04velFwd0cyNHJWSkpubHg4CkZQQ2xyQkhrSmQ0Z3NIRmxLV25I
        K2FTWGM5bXJaWi9CbEhjS2pCMFhJSmMKLS0tIFlsaytaTHNzYUkxdnY2WTVsNzVr
        UzAzWnhvOU9nNXByaDBHRVFXT1doUnMK2VKbJcSXTlxmrZ4ZRWUekmhz/ULS7elX
        QrsqEKuJRLGadaJUqj5q0f5207rDPQ6DDdq2hqQT3o8dmrOhr1M1gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WkdmUE9MRFZ3aWhic1dm
        MUM4U3pBeHd2TUtIM2pBQ2ZlWHlDZ2F1U3hZCndENGNFVzlrMjAxek0zNGZXU1FM
        bC9HanFqTit0YmtDZENCNFZ1TjVRVXMKLS0tIGdQb1JaODl6dW9XZ0xOQ0hWcmRz
        bXJheVpWeUZQcVhtSXBoMEc2dVdzc0kKOLZJgPgoafCwkLI+LgjQwPlgymgS4b+C
        xF2JLQRv8jsJcKkYNddLLN+nYupspN4t3KhbGjcxXN/WTuA6pe58dw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUHZSQk9SUWQ0czNCWmw1
        NDdQMFpDOGR1emdpdXBnUTBEVG0wSGdyaUU0CkR4TGNQUy9mQkJOK3B2aXJCajFD
        TUFLNXJyeWhFcG5ieWtpaDg0OXlPdVEKLS0tIDk3aWJEK3J2MU1KbUZJRWFMY2t2
        R0s0RTh5S0lyL3NDaHdkL3cxeDJNSGcKwqo38y3syIRvNzum982SbVGATzkPNGCw
        VNQ7wX68+wRf4tQioB3X4hEsB7dk+vtdIb7Ve2tRCsr6RRTSH7ZBEw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQjV4SWU3WDFUU29lc0FP
        Kzc4SnU2dUtSVHE0dmFmYUhndmxPZEN1R1V3CkhiRTZnbVpJWHZzUkx3TlFpOFZk
        blFHRTNTVVVTOHo3UDZBZFFPajZsbHMKLS0tIEtqdHREWkI5SGdURmxOc0p6THdk
        ZHR0MFJIL0p0MlgySnFSZmE4UVhPQWsK3+hAh53qKzxlfHLz/93iz7UVgqpuAVej
        j63QGxbJ8SNbav7eig14Ptco1CMJ4ZL+f8ji12UPLgGe9Ji1wtZDuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaUdVREFOT3lOL0lrOU9W
        dUkzRXIyQmhRSDFUd2ZzTGxvVVJUVHRBcEJrCkZRYmlVQzB1dWsyME44VTZCZVlt
        SklDTlJJTnpxaGtLVEZEdUpYME0xVmMKLS0tIC9leVNzRXhPRXcxYVJwcVBnb240
        bWhOS0NzUnF2OXdKcllxSklJZDgzZTgKSc0172MDsKgjAU8C3HkFVQQsBhUUMwp0
        +8I7TE8yX0ymcyh3IGE5OKaERy3zL9Vn3eT3ZtwANmEIUkidNWROvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL3lEa3EweU12Qk43cTJi
        bUY4d0pMNnVTUzIvSjU0cGt6K0FOVm1VZmdvCmlqNTVaK0RjQnFLSm9LdUhxQ09I
        UjN6bDB4NnRwM0VPRjRZaHpOcStqVjQKLS0tIFYvZ2hpS1pWY3RtdVVmZDdOVEVE
        bHNRdHl0N2FVeFJSS3hOanpWeXdocUEK3KJykZJ/uP/tapQTKPAWZxkN+Dit5BJi
        8KBNqR+FqZDg9mswsahZh46t59kejcJO0w/SyiF5Bli1V0FcJHt2UA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:ytPtj01CTNA0LKHymHwVRJSKdXkThk9H30bSNXwsti02NfcF3XNT1+FLpx0Uh2YHuCyHGG2o31PrqwVA+GvlBjSPwTpS+eFrpoe9j/QGAuo4i5savgk2y9Fq9igPcBxIug1TGspMgj/JDF86xmFzd2XCnE0csVUVnyQRwwIB6tI=,iv:EH9sl8XkGqq31pDi9tnD4wkOoh4MOKQwVT7HTeoVnrI=,tag:7QQglwbVog+uqohNXs1hUQ==,type:str]
  version: 3.13.1
