apiVersion: v1
kind: Secret
metadata:
  name: penpot-redis-uri
  namespace: penpot
type: Opaque
data:
  uri: ENC[AES256_GCM,data:bAIHKYC/DFR3+d2BlDS/EpLMyWpOxJ/iJ+uCMLKtBcByv+jDc7oGDKsFGwQCcV4LqPb0F7/27h/UUUQQM7LeeZLS2UDHCz4P,iv:Kq9N97DtxoQ0Grejc3WOqaHclUv8n9A4UmLcxYPM/do=,tag:/m6DPOKZDX3uNiS6UVXY9g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc3Noc0FDMk1UQVBFTUZI
        RDBOUC90cW9IYTVKdkhGb0kvMWNlblZjQmxjCmRjdFNUVittMzcyaU5GazBsTmd0
        VmFiMW1zL3Z3TWhiOUQwYURhd21Bc2MKLS0tIGFIL3NhTUpiWDRHSDRtRDNBdFh5
        NEdaRjNtLzU4MytEd3pPS0dlNHkxdE0KaR0W3FHhXw9aOU6HdA7hwhlT2IlEYnrI
        cO90Q62Ta2vSlCSb4xWxo+q78AjFmSzuKrjPHe155anLIitRFKGUxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSWxJUUZZVEFxd04wd211
        TnBESGpIcG5mTkJDWTQ0VG9sUVpNYU9NdGhZCnR5cE9za2pETHhCWThMSDR3a08z
        YkZDOEtsclB2clBGSlp4TFc0L1JWTGsKLS0tIDRxVC9HMk9nNlNqWkcxaTlvUVYr
        c2NNVEZUVWpNWEROMEJOaGF5UFE4ZHcKmBqRDtjFg58Zv53Yy8XcQflRKRrj0iYD
        muEeSMh6+5MNr2GDZQFW3FakK9USjIDcyX1NijE+czWP/xRsiy1+uQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT2tWNVZPSmw5aGI4UG9u
        K1dPWnB4NFpNNnNkTU1vN2p6amRwZjVaV3hRCm4xZGVoSG9tZjgzZzJXSGZwaWlQ
        RGxiN0hYV1FHc1BpNGNNMmVwTmIxdjAKLS0tIGd1SDVRUWFDTXRvZHlaemFIODNJ
        a0dSUDRuVDJXUG5BRkdYZ1lGQUYzWU0K1nH6TJyXDmuQiIvb7yX6zNVRskGCIycb
        Hcf5hxuSXNfu/ogJOCOhn6WPoG+lHcUhVtxuOZ/Z4zBxJdiLMiVjtg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:pjYqxju2MHmGZTUAqXlTJOkQ4EKAEL90NZ6FMmvj7w3bYGUUwAPt+t6BnMJd7+UW6CxoGtn4BURdd4k5uk7uFRKAOgKJCYd5UZDqyDm1AAzLnVpze4gbuvKrYkdcfRRzzxVZJdlRdx7u1pcVgL945NSjfjx+AFp77rvkT07F21Q=,iv:bfFIxf78+jx5QK5zpP+NQorNG0HfC7Z45x6EklQ2yDI=,tag:8PO0Dur3HJH0B+IxXzVIdw==,type:str]
  version: 3.13.1
