apiVersion: v1
kind: Secret
metadata:
  name: penpot-api-key
  namespace: penpot
type: Opaque
data:
  key: ENC[AES256_GCM,data:XGk/6VLgslD/ffkAN9zHlxGs7ntLEpHqEw2GrFntN6Y+kfe2aoiJRA/ZNTZGsWrEP012g4UpD35rvYMwNtcJq/Lv5NuFxnl83Ob0NXDSwI0lXAwvE0NFMOF1dcy4fSTEbb77rl/w0NA1Xw2jAbnLJQHOozA=,iv:Jw/Iyw/2oL1lSYe0wlnCyBWz5SSWNsTu2uLAX5eFHAw=,tag:XlS8kqEJlp/VJJxbI20uWw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZGxCWHlEWitUeWdqcDkz
        dE5iRzFQNGJyQi93VDFMeDVIQm91WVl4ZzBZClQxKzM5VCtDM2lTSHNmbGpVaXlC
        RldoL0hqRU5SSENvZTM5cVQxZU5tbjQKLS0tICtFZzIxWmZvVWZBR1d0R3ZEc1Ex
        VjFzd1JFL1pBQVU4clljWHJzVkRySkEKmQ4zEkGy7/rC4yD7FqG//vdanWG76E1z
        atJbuXLt5KUmZyac4OKSC1S6iLCvTriiT0/6wpoXRkxwlv4GZ8/Elg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc1VDVVcrQjE2bGNocDBx
        alJEOUtiSTZURDAzS0F5eG5GSFo5WG41M21vClZqUnNGbFVjTjdJZ0xpTU1lbTVQ
        N3FZZU9oS3dOV09hNCs5R2d6L3RxRHMKLS0tIDJtWmc1eHhIK1FwdW53TlJLaERl
        YnN3TnZ4QXNNZEZoQjJScmlGMjcwME0KwFRdo2s6/n5OxjCbhLb8yyPMisvlWMMr
        AobD1RX0hwSNynodt9hKVuC7+A93CQVkuLkGEzopgTMjNMShGvk93Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxL0ZnQkdRcGVqTXp3MWho
        S2I4dzFlaGJNY0VSVFpHcDZxeWF6bC9vVFM4Cmd0Rld4OGJSbFVQZG1MbEpWSUhW
        RmVPWFhGTWtoclVGT1ZCdHh3Y3p3ckkKLS0tIFlLQUt5cmMwTTM2QmtEUWVsT0ly
        UDJ4NlE4S3pHanRaTWpaUk5UWG1rWjgKkVYg2InOVUF77MhL9dMbZJwKEzrYpQ92
        MvxvSWhUGBPszv3KUaeYYDuvXgmzwkK4uziUPw2SbzkBr1uq48vCXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK2xwejFZOEM4eUVoZFNB
        dzFzU3NrOHBFVUpRcGtQSDJqL1ZYNlVRazNnCkZscWpST0IyNGk3K1BLRTN2MVdh
        OUVxUm41c082US9qb0gvdHRYM1IvUk0KLS0tIE9yTDdDNFpaaWFSbkQ4QlZJNGFh
        REM3K29qRGZIcDA4bDdUdW1GMVVXRHcKr3+5Lj5cgxwNDe4lRewq4LLfji4+3AKW
        T31Y7Ph6oDhs060FHkPEPkLQuqZB+9Kk0O0CwmlogbKiTmPv918n4g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SU1LeFpUUnlvUnozeFNi
        eVdwZll5WUxmNmNXYzJpRmlXL1VMcmd5ZWhNCkFrTXNoNGUxUEtpS0ppVDZEd3lZ
        djFUZ0ZQSHQvUjZabmk5YU9kcnFsQVUKLS0tIERqY1pRSytNb1loWmhBVEVYSk53
        MFMrRWx0QzcyVHRWNlNTT3JLYnlBTXMK3yGSTWmtScX//bb2/GkTsLQOQyQN8/S1
        HlkwR3sP3GcqjR4VhZUc/kOUMAgwTEo1N/f2SsSBRchavwKbyS+plg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VmFuWnpJSmVscThOOUQx
        QWVrTVNaeG1CTjRvQTV0azR4WFdpRlloN0VrCmpsK281T0dUTWlQbmtqRjFlUXI0
        cGhBdlJpamNNcFhYYzVLcUEweE1QNDAKLS0tIFh6M2JhRTAyQWIvOGl3MHNoRDFF
        OHhTdHdvS0wzWkZkS2dwVFpQT29ETk0Ki5qfMumfBKh3YPoG2ceL7+2vtayp6/mz
        I2zNfqUF8rw3lws3RG6VRVHiUqBvPHI4s6EwrriSScjeXUMJTANYRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcW1iNkpCd1NIdVJDdWhJ
        TFY5OXJjM1RxNnZxZTJCUzRNd1VGSi9tUW13Ckk1NitRK3UrS3BuQ1k0VHNvQ2E2
        VG9sWXZRMHNJdTBNRW1TWXJEeStFVFEKLS0tIDQ5dkhtMzR1Y3hEclgyNUplRi9n
        ZVRSM05uTjNkMHlFR1dVTU9wa2VISWcKaB+4xHDBfZp+y7X1XFvSTVnLV3J61VVO
        0eWOG3ldcwd5FxarZ5F8WIcGRMGT13cojL0zFOaHI01mZ3tak1/9Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaTM5T2MyM2t5MkQvVEdi
        SlYwR1pBakVqU0tkSTBjN2NYQWlueWRVc0NRCmZXczJ1OENTTmdwemZXaVZVV3Yx
        Um9VVlBwNzBkemhZTi9kWXkrVUhGa1EKLS0tIFBrRURpNlFRd05YVVJQTFFtelZQ
        c3dsRy81YS81L3pzb0h3c2hWa3c4RXMK0riNlzMJQjRSF4OhTj6KK+bcz/2gGVQM
        iql8VGhESgdcUfYf/tzEFlOmkOCgIUXJG17Sa2jFX0l4Gn0gJeoonA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY3VhNWFqWDVxY29ndWZB
        a1J5MU0zZWlNOFJCRFZpY3dNVXFtVERDb1RZCnJoanRkdC9kRVM1WGM5VllmUHFF
        KzdpcHhKaE9lUks4dFdTUHA3NEdnUzgKLS0tIGdPR0dpMUsyUHhWaGNHVVpiRTV6
        OTJuMHpoQUYvR3V0RGV6ZFZpN3N3eWcKNWhy2X/YqowaMC+shNab8Kf2gZDE6Ap5
        qRLkFVXdCyAhG3VrTfocQeuNWF+bYFajMbuENkkdX9UdFKES/weGbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUjhDa0RWSlNlQzRTakVC
        b0UzdllQb1d2TEduUE16NnRlZnk4UHpmL1JvClowM0hINGdFdkZpOU51dm9aM2lK
        STZIY1krN1FMS3MycVRSejBqbmI4dmsKLS0tIGVDakFLSUF4WU1TQ2YveTZDR09Y
        cnBQUElqaC9kaHkzTERkczA4bFlvNlkKwpZxwxunYjAPRzufv7etOQF6iZD2SoV0
        BWhJ7512lFPaPuEDeYjNliJBRsBrydG1X6TlyYVv1aEIytuo3+HckQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:6kaq9cZEg/M2nwkppEx3yiuiXMKmGOg3nOV0m5AfzHuTc2oNp+VqybM0DE5OGho9aiNNG0wl6W+cNNLM+/IkSZf1VCy+srtk6hdUzosRAPiJhfuK1n4giClFKi8GwC1mkoH+H9coGHMyWZO9VpcOtBPoHA7c+bDxnnnxpNPzB9k=,iv:lDhhu8indCrlMvUF1JQAziQOQsg6Rb6pn7hz53v6JBg=,tag:vA1nmbrko3/mGzUeZbXVZQ==,type:str]
  version: 3.13.1
