apiVersion: v1
kind: Secret
metadata:
  name: penpot-api-key
  namespace: penpot
type: Opaque
stringData:
  key: ENC[AES256_GCM,data:LCPrPQOZi91Jk82DA6MbQT8toXECnMGf5LWIHQmDaLFeol815irjdJE9nOyOUU96Q8t6j0YPklg9sBeOzSfIpA0JMB/bWsMCm68z6lkdrgQULv2qLsw=,iv:4wQx66mCUk3NdeJC1jdJciULPCl5uVpLgGMY7ssBFyc=,tag:70g/faggVGVgEbaU4uQw2w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZnVEd1ZrTnYvbW1BeVZW
        NFVObFUwWUpWZ3k1U0VYMWpPTUFZOVBCYlN3CkMwdExHdUR5Q1lLMk5hQktsUHBY
        Nk12RzJlaktpaDhjdzROaVJwaWcwanMKLS0tIEI1UFBTdE03TnFzVFE2Y1ZrSCtQ
        OEd5M1NuWHVjYVdUU1BVeEEvaEJqb0UKEuSI1VFNlS7GcF1acbQTMtt/9IA4Bywy
        qMqjRLixZCK2RpBGTeOMo/G6Fhpb2j7i9ER/RuUUxjQfJi0aeTns8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ0dzc3F3cmhuNjVaZkdC
        QS9rV3NoMUlUUktSeHVWd1BXdkUvNDBMWlg0Cm0yOTZBbzFYQ1dPQTUrcG1Ec2tQ
        NXRmT1ozYkUxbDRPbS9IZzh5ZUNSam8KLS0tIDVBU1ZuMllhbjZrUm4ySWNRcXdq
        SEhrZndKQ1VvenM2SmFTWGM4dzFhN3cKam0YCJvsNvV5Yq8NPX4I0muBnzYw9DKH
        8tDJzYGS+cSguPAvA4gN9YKtnoc5sUdSkFZmjuTHR0TAqzvxOSgckg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d3Vya3VzSndSdkxtTzJX
        UngzOWRwUFNTZVkvRVVFa3h3dDhsSW84YWs4ClovQkEvMkxIVE9XT0Raclgvd0FP
        c2dBOWh0VSsrQ0NJUU9Kc052ZEJCSGcKLS0tIFVFZWNkaTFETytFTkR0ckIyQ1dC
        THpnVlBVVGZNKzFrSXdnZCs0a05wQzAKlIzHT5SlGIAKeznV8AJkEYctuSiuH2iE
        Szj/xy8pUi1THtzL0BgkjKBAkIJ3jzyAf5Z6pRxbutYg7t5GGWhiTQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:9JsRigSbI42RoJds2eTEGtwQrZHThIiCKwxnnuzHpAcTYtOUXdRO4/LTUQu65ATdV4eDybLLFvmRlSklgzr00KMmTSjbQ4+REC3rgXqq1QHg7k2aMaTepNcZSVbxhUk9v1GEF4KbbdP60FJX4UIDeggs7z0G45xMbJlMfdp0rGE=,iv:MLQ7yByCH6Y0LyXHuGB6bJjdo4dnvaZRcWNAtAITijE=,tag:nYL49pnmf8Q9jVCC7O3uuA==,type:str]
  version: 3.13.1
