apiVersion: v1
kind: Secret
metadata:
  name: postgres-penpot
  namespace: penpot
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:afMslZwJ90o+rnRPB+N0Hg==,iv:k91zNwaw2ikbTzgmK0x1EH2V45IcNPVSiBbl226PACk=,tag:h+kfDf/rOYZlroMFYjy/Mg==,type:str]
  username: ENC[AES256_GCM,data:urBax/4Z,iv:86jIEC2H3F6kBafyqtY5hqwIEdUz0KMgSEx0VjvrYpE=,tag:+Wq4oyOmUKKQUwnE4focbg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z0VJaDh6WDlCRFVYU3Bt
        SHd6SERxNHFpQnJ2UnFmWHdObm5ZY0dVK2pNClJrQ2hWWEpQZmx2cWd2NWZ0dU9x
        QU8weUVCcHU0enhWQ0hZVmoxbkVIS0UKLS0tIERpaGk2MjN3Y2paMVhjS2p2MklI
        R1UrRXRXc0NvdHI1NHlrN2Y0dlhrREEKqppEzpJg9WeB9DvJuZX7PZ7AOTsYpOOh
        DdMD7Q8RCDTN9DUGrd2/csjHas+hzlDUp86Qp0prnfSo9jLmpLs0iw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SkJIT0FhUWtNWUtjMU9X
        UVNSUW9CaHZIbGxoQklLdHpsY1F3RHZqNHdrCkJScmNBSEtYanFrZ0JmcXVUaldz
        QzNwUzJoTVlmSTJpdW1hZjdZdWFGamMKLS0tIEZBRmtwdTdETERPblVvVzU1TXJD
        VTY0UUIwS2U4YWZPUm84aFlaVUxRT2MKa0qTyWUwfMDUNLYqQuWtCKVct+19EZqP
        0lI5j0TlPx4s6EYpiKBPRlNFjUWWxrhjHReG+UBRz2Y0Dzo/1NEQyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ODBIaHJLbHg5aExJWDF5
        N2hKcjZzQlV6TGNjQlNuNUxYSTBmUE4xWkg0CkRFMnNrWTEvSUFGK1JqVWdHcEZ2
        bEtnMitVWnBJV2ZQRG1qMktlTVpDZTAKLS0tIFNqSmUvQmJYNm5xbENDM2ZPaGts
        Tll1TUg3NDRlRXZjczBpbnFNM1VZd2cK+Zm/nEg1CYmBsdrzJacb14pKEsAdmV+9
        dtPOXM19+Ko3Iyu2+zjQRbKN/KJloDXwRJH2yYPk7o46Mmtpb3AoFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:dBRzO31sta1ZiVRsgraqj/emLfp0dLMooiNkpRZrTn+IICMauR0xxENWOsyYGh3HNtb0Vx8/qCkojOR9a/nNXYXQw1fGjqlFRAPgV6H5RfTWxLg3gHq9p0myOhtH4s70+eHFnvLjLoF1UyozkqThJ6YMsj1ZKse0aoOAkjHb4uE=,iv:UQMQ4cIKvbX732MYZOo2/bZ04aTLMZdnU7FQ259kvfc=,tag:SBS7u3pyXk2Q18NZGjGh/w==,type:str]
  version: 3.13.1
