apiVersion: v1
kind: Secret
metadata:
  name: postgres-penpot
  namespace: penpot
type: Opaque
data:
  password: ENC[AES256_GCM,data:iIqBf2Fa6Igv29WDrvXNHgERWrD+WAdZ,iv:exreFG/tBl1g8FfYDQIO+klfcpqI5p8MEUXpTyX5wQI=,tag:sCoUeEnxfj8gvTGvakw2Dw==,type:str]
  username: ENC[AES256_GCM,data:LD1/TtojBFc=,iv:vNaJlhfo542/wBvC9Yb/jcNNKiBiJs/LG9H1FccJLfo=,tag:1MdOfqX3sO0jhs3AJU4xbA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxU0FtSzRIQmN4WW5XSzdw
        Vi9Oc05wMjg2KzNHUEFreDlhQVNOc1Jad1M4ClNkR3NYUVZpQnhrcjlhc0hyZ3Jy
        MUtsZVRKc0ZKMGxkODVTYW1NVXBjYk0KLS0tIENJbndQcTQ1bTVOdlZxajgxaEkz
        TXhLZU4vTFJ4WGlialpHTzdJNTBSVFEKLW1P5dZLbRBjSYVdfVR4jipBq4s+n3Jg
        3J/nu26uoP0B1YXzamDlIjb9BRg3PJNI/NJ+Xg0J2ejjmie6otlEEw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbG5oV3djRmpGZ2U3V0hQ
        cWZLN1hKWWF3TmdDTXIwaDlyMjdvZVRiRFR3Ck5TNDI3RWgxQTEvUzVqTFIyb3hM
        eXM2ZzJRaU9OLzdTUlhOcnNySjFTQlUKLS0tIDRYY3ZlN2pjS1ZqMlF0ZzNTMzN6
        UlV4K0x6WWJpRkdObzZFQzZmQkVpWFkKiDO3ovtx1RsEM0Mv4rJ9ZM8eYVezl7pL
        O29ge/jXWbdBG7A86EIz5gupmOXy6ek69NxVjg39Y06o6miitWPHHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VW5nWkREMFZzdlg4TjN6
        bkNTY3JJWDNJOGp3L05hakdYRDJseGEwR0JZCjJxcXBkS21JUmgzei9KRE43dk5n
        b09TaXZ6cUpsWUdCOFhNcFFEVGtOUDgKLS0tIGV4ZW9LR2FyVlpRR2F5Uno0SGZO
        UUoyZGpuLzF2MTZ5ek9KbFFIUnJrencKrnDnoC/zCVWGTwZeKu7cwwJzAUSxoWC1
        QeJM7Ho9ctK2/Amw5cu+3YH57CuhvupmUMbPLCK1L8jqusIqsIch1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:OxxoYEH7nrJlkRVN49uqR4DUw74cjYKkGyXDga4N0kaD+smg1kbvKq5HvKeM3RhoeZDbSZ4C/3w/lG7XODyjNJbsb8xRjn7xuxg1XHrIPp0qQIF79MyO6YqYsxyg2BH5aihzjckuj/i4DsduVewvJgai7AOcOH1FA8GI0H6R0VM=,iv:6/b92EDPhO/e55qkrzM8ameNHMYzyWPw+cUkSex4xeo=,tag:w/fGFi+R6RMEMTZ9rg+kQQ==,type:str]
  version: 3.13.1
