apiVersion: v1
kind: Secret
metadata:
  name: postgres-penpot
  namespace: penpot
type: Opaque
data:
  password: ENC[AES256_GCM,data:FX/SZHaDeBokEkqdTGLfZGobP2J/bvYr,iv:Yr2YlabwwZOCZl8tO11jG9tv8AiG/rkhxlVXYRul1/o=,tag:JapSVPZH/c179LArZB/2ig==,type:str]
  username: ENC[AES256_GCM,data:8UwvFY24AY4=,iv:VKXuDSg400+W3mxfp8F4cttwUd6w9Z7eJA5zvvVoiI8=,tag:8u9Fvf7wK8v2xzdOD8ZqgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSGJoYU5OYlJOTGdETC83
        aDZRQm83ZGdTL3RuWWtKeTZTamx2QWVnc0VRCmpKUzJ0aDBKSkJKZ0g0Z1VQVGgx
        QjhacTlmSHZXcjFPbDdyMjV2Z2Jad0EKLS0tIGdTUmoxLzRaVW9uOE9FVnZrc3pL
        SHVQNXFrRGpaUGRMQzJ5cGVML3JoaHMKBwlrV7dXVsffnCaTu6h5/vp3DUDJ0Yts
        witJvI+i9JpjPaBtwz271+1ZrUbNhahSwmvmWSQSHSWVL+ky0pFvWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNy9iVGZOSUgxRlY2QzZD
        cHkvN096ZkcwelZJbjRxdXIvMWRVc0JveUM0Ci8yOE1ZSWFNK1lna2g1MEM1dlZY
        TW5ML281a2lFK05BNU1ubmhJWm5HWmcKLS0tIEp6dzloM3N3ekVGTGJ2d09vRThr
        eEVMUlVCRnVTTkxrK3ZKQm1nRHlFaXMK2JDzaaMhcrEyCZSVSnzcc61kPdtd/w0r
        UaLqegOFmnhlDBwAOJYN1dhJSx03OOjxilmdHLPh7Av5MFfsa988yw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSVlSU1dxWklEMVF5cGhE
        TWt5cEhMM0NsOVdDK0tjVE91YWlZdFUzTTIwCmMraWV1bUV0U3cwdWtxSkFNWXNh
        QlV2ci82b2dKTENIOFdIZDlmeE1pNVUKLS0tIEtjVjYzMnYyaW9WTGxyYnhic2FG
        TDB2Y1grTEZ4a0NMUTBQRFcrZEdodWcKObiIV231dekjxctm9Fu0eKXcLnKwkznX
        JDMr0vDYg7RqMm1vhVCXpDwxiLt1tzt1Tc0SKz/hg1d5wVhCjRvUBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbWFaL3p6R0h5L2FvNzdL
        aDlQMXE1TzlJN0FxK0MxTjVYZzBtU09GU3lFClRGeUxIbHlHRnlZUm9uR01uOHZK
        SHB5UlpJT0FXTDRDRXRER09iYkd6dlkKLS0tIHhwakc2YWFpK2NaUENNcnNDMzNE
        V0ZZWEVwMXRGN201UkNOWXJBSTF2eVkKoxCd6F/mSGZo2dCJvelEazxey1HB8Laq
        n+s7/29yIQi7TOg1mT1j6QFNvV7GC+4A0n6Pakek9yqe/lLLhEFAeA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVitCSU5wS3FIYzhpb05q
        S3dYSi9xVUpXTWpsa0hwNmF0ODlhZTlKbHl3CkFvUHZBWTBETzFBaW5oZkhCNDZm
        cE5nZ25nTkhHNXVxN2I0UkNmNW9KSGMKLS0tIFRSYlRsaCtySWx1ZU11M2lsZzJl
        RFlCbGNTREN3UlhIY3pReUdSTTBGOWsKvzZtYh6+Sg5TZR/2RhT5A+cpwORIaPUF
        RT1GyD/K29yPEODHuXcD/VeAJA7n00FQmiLuKJ+T2sxLJPZ3+Lphgw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYi9kUE9FNXhUdlk0K3FS
        RnpGN0NJK3I1RExNc0FOSnRwZ1lzYnlGUkRRCmg4LzlBb3RFcTRFbHFKZ01ZQi9t
        cmU1TS9tVjQ4TUhYVnlnTmhneXZKTUEKLS0tIGFhNlUvaVlYUkRRNCt1UFUyYmNL
        Y2VCamMwT01pM3VmT203SnNHdWE0U1EKn9s1gyjdtu1me2jCqSSk20mXloPSQuqc
        KPRvrVtBvqz5vXSpn3E4xN4Msr5sTjhHAudf0DdloHP9ugyOPqwNLw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ak1OOGl4K2dzSjViRU05
        YzRQckFLODc4SFFYNnAyQjEyd21nSDZucFNJCjhiQTVBNTUzZWNxQmpCM3pPQnRj
        Y2psNDBNdmFySnJ3UzVwZ2xuSTAzM2MKLS0tIDBveFhEbDAzZ3FjUnRka3pvVjlr
        Mk1zNVE1WkVPMHErU0U5RWtNWGFvR1EKRRW3fqTHfiWDuK0T4/O+dA/+4wLuUGah
        uevELe7R9Uh5Zy9wacD/ZcyiRdrc580+M/s/Am+m1jnWxFgFILzPwA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RlgyYlErZllpYWFqVmpE
        NlNCTUtnMXJmR1hjWEUwZTdYL1d1QUtqYUcwCnhNalo5aXBQTVlyVjVhcVhiVkRq
        L1cxelJ4dE5zamNrajlpSEtpdGFPMUUKLS0tIEg1TVRObFNFUjM5cWFJcG5CTGdi
        WGhDNFZHZVQycGF2ay9CVDlsWUNRK0UKUjqEKxGC1hP9Xan1ZGd6dCytgEWshvIT
        NsUGz8dJDm2JGYZxQYeJJj3X1om5U/Yk8iJHz3EPK/Q9hlx/41D26w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRzd1eldlT1VwYmZNOE9C
        dE0zdk5pZWVkM0lGaVhibEJzN1NJVXlVYUFzClBFUHlydmRKZklTZ1lMRWdGalhr
        S2hLVHIrcGtFV1c2enNKZmRhb2RnN0kKLS0tIDBtemh4MGFIYkZ1blB3RHhERGx2
        d2tPeFVkTW0xcTE2bzhFd1NXM2ZOWlkKQg/8Lqz2S4qCK2tqBIt+BG0tbESahn/4
        FcSiEokfOGhzhtxjr7YDWXmNvkSFwMe9H4DR5J4UrdMSkgq3EgQ+jg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VUgxOVk3NC9WbU1tWE9R
        Y3VpS1lKN2ZXWnV5OEJwTnE1dmIwcUVmNUdNCnVnYUljYVlBWGZ5d1lSVi9mZUtE
        WFdiUUpHWEIzU296YytwZHBmeDhWWTAKLS0tIDA0MnNNNXlFN0JWUC9NNlBtOU1Q
        T01aZDJVNlAxMVY1eUVzSlZGNGE5b1EKwLkrS4c+VNNqRbw95SSDKFod3Ri09VSS
        xLoFfvz/YetEIEnaEHVDQ3oj1rpYDaNy+NiKFM7bUEmzeYO8TLc1nA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:1GS9m9ZSk0lQJ99cEu4D2waUcg0u7Y5Gztwmg8wQIhVBOTGRd+ETfe4HyjMMv+Y1UbJvdKrOb7QXS2uMLczbjAAJBtpfIayUIl2RyFkbOw9UHWBsLUEDONVi9vEx6asTOfMO1fHy5dUrBik8FVpfdfUN/WlkBiVnGv4476cx9rI=,iv:Vv9C5Pp2k8GTefvfrBdmkVdOI+wePNjAPsuxkG3t9GI=,tag:mme7BZ9mFz6HSxA3JEK2Ig==,type:str]
  version: 3.13.1
