apiVersion: v1
kind: Secret
metadata:
  name: quant-ux-mongodb
  namespace: storage
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:4Xm39VDvFgjy7sQiihJIZuJa+qmdYR9f,iv:q3yUXkCREiNzoZBT+no2HAr3ht2ZR0iAyp4ftEw/p7Y=,tag:zjKwNkdgD2Hkp5uW5bpS2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QXlySFpWVWVyYlNwQ0xn
        K3pXRjdWWkdKVzU1NWxRSUJIbEQvc3ZFMW1jCnNCS0Q2bHRkREFxVmMrT1Y3TzZE
        WlhSN0crcXNreEE1MThSS2Y3ZGUwdFEKLS0tIFlWMllZS1FJenVjVGRPOVJwTU1B
        cUNXNXA3OUZ2dThQS3o2aWhKVEc5WGsKvYjMNGwLCjNd/jatsLIuoT8i5yAs4gOb
        3yGvDj7GLTfaNg+z7gG66V4aH8V3lqMD9z76gjmb1kD4c7PxRXdJaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOXk4ZlhtNFF4L2FNYjl5
        NUxJODRUa2htWGFiUFl1b0p1b1BVS1doOEgwCnVRSGQzenYyOWI1Mjk1bVlxVGxX
        WUtCWnNZUVRSMndJdHRsaUpyNkwxbk0KLS0tIGNtamhOTWp0OUhWUmtqdzRxTzYv
        VG55eXd6SzNzcTVOeE1CM29XM1RyR2cKUhfrqEuFlm6j1Bl/QU7QzZzozigQBA5b
        MIA1P3TWZXCQsfTntKZjNLWfVZIL5NI9pikXgno0gLyrhk2tnRg5eA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZDFJb2ZDYkxKZkRsUFpw
        OTFhdkVjdHpLWnVDak00UHAwVTRDWE95aVFrCnI0OEI3a1lSOWVESjJqZnNoUG1B
        NElFRnhyMkFydUpuWGhaOXZiSmhqY3cKLS0tIGxHcmlUdnk2KzByaURGVlBHdkpT
        ZXM3MFNpZWU1SG5TSHFYeFNIQkZZM0kKYvUNjsKHUYzgGt1wn8lhbRKB3z0v95EF
        4xbUzwEvVltKwjYB4QDHR/PEBuarcmaV+BnNzPnBm40/fihbWRaXtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T20:14:52Z"
  mac: ENC[AES256_GCM,data:uPwzmUxFUHfn/xJflqf7n/Bz5GNahm2EvVQQ5/zrR8FgIHdeZ2W4w8pKVJ/8sOfxFPZ/Uu2VB3WA6Khr1EhI6w8X4tGdeSmRimiob4gNrJJnPgiPgO6TlDtEAToiR56BoiLkN91vrOKKNSkQY4eoSsfcmMc3TV+S96ctIaahwJ8=,iv:82+OwcVxI/dF1TUdqH2T3+nnNKjmTL9apvBwjYu7S6c=,tag:hXfhkElOPQy7YDvVbClCjA==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: quant-ux-mongodb
  namespace: quant-ux
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:DkgzOBS8CvmIjZStj3nsj8zJqNuqV1FI,iv:REswH4Aokfx+a5uOOVD/00UM31ljgZZGM6Iy4/QHGDU=,tag:gS6GxdQrwN1h3DdzPMLXQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QXlySFpWVWVyYlNwQ0xn
        K3pXRjdWWkdKVzU1NWxRSUJIbEQvc3ZFMW1jCnNCS0Q2bHRkREFxVmMrT1Y3TzZE
        WlhSN0crcXNreEE1MThSS2Y3ZGUwdFEKLS0tIFlWMllZS1FJenVjVGRPOVJwTU1B
        cUNXNXA3OUZ2dThQS3o2aWhKVEc5WGsKvYjMNGwLCjNd/jatsLIuoT8i5yAs4gOb
        3yGvDj7GLTfaNg+z7gG66V4aH8V3lqMD9z76gjmb1kD4c7PxRXdJaA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOXk4ZlhtNFF4L2FNYjl5
        NUxJODRUa2htWGFiUFl1b0p1b1BVS1doOEgwCnVRSGQzenYyOWI1Mjk1bVlxVGxX
        WUtCWnNZUVRSMndJdHRsaUpyNkwxbk0KLS0tIGNtamhOTWp0OUhWUmtqdzRxTzYv
        VG55eXd6SzNzcTVOeE1CM29XM1RyR2cKUhfrqEuFlm6j1Bl/QU7QzZzozigQBA5b
        MIA1P3TWZXCQsfTntKZjNLWfVZIL5NI9pikXgno0gLyrhk2tnRg5eA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZDFJb2ZDYkxKZkRsUFpw
        OTFhdkVjdHpLWnVDak00UHAwVTRDWE95aVFrCnI0OEI3a1lSOWVESjJqZnNoUG1B
        NElFRnhyMkFydUpuWGhaOXZiSmhqY3cKLS0tIGxHcmlUdnk2KzByaURGVlBHdkpT
        ZXM3MFNpZWU1SG5TSHFYeFNIQkZZM0kKYvUNjsKHUYzgGt1wn8lhbRKB3z0v95EF
        4xbUzwEvVltKwjYB4QDHR/PEBuarcmaV+BnNzPnBm40/fihbWRaXtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T20:14:52Z"
  mac: ENC[AES256_GCM,data:uPwzmUxFUHfn/xJflqf7n/Bz5GNahm2EvVQQ5/zrR8FgIHdeZ2W4w8pKVJ/8sOfxFPZ/Uu2VB3WA6Khr1EhI6w8X4tGdeSmRimiob4gNrJJnPgiPgO6TlDtEAToiR56BoiLkN91vrOKKNSkQY4eoSsfcmMc3TV+S96ctIaahwJ8=,iv:82+OwcVxI/dF1TUdqH2T3+nnNKjmTL9apvBwjYu7S6c=,tag:hXfhkElOPQy7YDvVbClCjA==,type:str]
  version: 3.13.3
