---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quant-ux-data
  namespace: quant-ux
  labels:
    app.kubernetes.io/name: quant-ux
    app.kubernetes.io/instance: quant-ux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-csi
  resources:
    requests:
      storage: 10Gi
