apiVersion: v1
kind: Secret
metadata:
  name: quant-ux
  namespace: quant-ux
type: Opaque
stringData:
  QUX_JWT_PASSWORD: ENC[AES256_GCM,data:fAngFgOruEBR5jAfjKFYA49OJkYfUQCi9waiYA/6ew2duHa1N7tclYV3df2Uqycs,iv:iHGjXixUlV5rl2QS1G9+z0h7mx1mTDF7BXdPBVSRlz4=,tag:RkhYw7F+Qpy2oyOKM951wg==,type:str]
  QUX_MAIL_PASSWORD: ENC[AES256_GCM,data:PnYiwBov,iv:2ik4cxhQhZmqtx7ySpim/Oxjqs1VXe1sDH5QOrc25aA=,tag:8P7muFzmoef6BpYAhlVPMA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZlM3V2hjTng5eTcrTERm
        OXppRGJvZHU5WGxmaUU0bUpDdU95ZG1vY1ZjCmpob3FFSy96R3hDNWw2eEZld1NK
        d1l6bXZzVmg1STMyMmN6TWZuM1lYWm8KLS0tIGVhbGVDR3c5STZwaytraEZBa2hX
        ZlpBSnl5TWp0K09uU0RwVHNMMFo5RmcKk0ywOLprvPHemh7szlW2lblhflfSjX22
        AyHTbxkrjl3oKbhkOAahgwiH5lLO0/QyXbtKlyxBo0SiTgN51aAD2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR3dXQU9pQUM4YTdlSHh2
        TXBvNzY1clM4Sjd2cXZZMG5hcjRydjFCQ0dNClZNdGFqZkdKOEVTeUQyL1VQTVV3
        QTZ5UlM3NEp3a1ZzeU1rRGR3cWNBeW8KLS0tIHdzUlBuR001U0xKNlBxQktoVytH
        dTN0TlFkWU55Q0EvblZ6VnhWODVkYlkKfu8lwSITnU5g8fdPT302e2hOoRBWgrzP
        ROYqRXPDbKZUbydWnljpWzPEcM33QvOl7ZHiAg7oI3vveAJfAOMavw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNjA1TXJqbnpGQ0Z1N2xH
        cGpxUzU4Zk8xSGpvdW9NelVuSTFsWkJqaFNNCjlCYXp5YXR6VlRDeDcza0JxNVV0
        MWZBMFhsaVhBWTVMY3pUTzJkeWRsMFkKLS0tIDdzZ1hXQzdNbFdPdVhyNjBCazFa
        Nk5QcllhaFlkMTR6cGlXNDRCYXRURmsKZklnsAbAmDzpPN7L8BwLkpNNu6qo4CED
        9pr9yzV9/BrRp/+W77IcwgNekb1dqtlf+j6yxRZ4N6E+mlzyvJx7Yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T20:14:52Z"
  mac: ENC[AES256_GCM,data:BDTI64I3nXvsdyg1MVeTtfE6wocnq4Hmrma5v736FX4VvE1YJ4S3bDZ9JOsVjBk0qsNbd0Y87uoJP5QDs04bV6RIP8nO7Z6iRRI3nO7o1kF5kpJKOkYQ8SbwIw3suwc/KsDT2GEPq3nz6dFK7+rDsm2yEbHYg909QxmtJ5ulsOU=,iv:hqGonVgwGU7D0MEd1uDFHwyvgJzVukw3IViXqBsaIhk=,tag:YRFz3JJuSb3bZUtDlHOCgw==,type:str]
  version: 3.13.3
