apiVersion: v1
kind: Secret
metadata:
  name: harbor-auth
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:SUsHWqz6fHpY3W34Eieu14FxK/nQx4mFDnm+GU+hhz40kmyA2GMy9VApHwGwC37y+rD5krw+jER4/bMsaGtQJkMPQPIx9n3lyDAVAkJynq8A3S2Rqaxxt9T7hMjF47xPqMIddCZMyXG33LYm9XXgKjAgRksjM6o6+APiI69oLckxngHS5F9SbShE06t/NXYFqSStDdHer3/emVZWO2/kNOODGsLj+T/QfyfTBXi8uJvcmKBV,iv:cBXgzsIzbPSlq7AxG4QwHDknIG9H9Ee6/5NR7PEvmsY=,tag:SGusg+LbijlE0UiIYtDwaA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL1ZrWW9vd3VyUkVKUkhD
        OFZvR1RVeEVoT0VNdzlyR29lSTZ4QklQekVRCmc4dDRHTlZhWGhadXpVQ2s2VWUv
        Nkc1V1JmZ0ZCN3NqQk12anEzSERUeVkKLS0tIHc2ckhZdGRnTzF1ZDAyR2FMdmNN
        V2pGa2lMQU5lR2FNNTR5RFRXL2I4MmcK1wzIo1O8/g+K9/YWplwEI0w/DJdIyoyE
        gnfWsKIZFLGvKuxrDgEzmTKN2S8jl8xu2epGlkekl/mYCnubAL0+FQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOVdoVy9Zd2h5cGNzbjRt
        QzVSQytkZlA3STFXVk11OVNkMnVRa0VSSzFVClB5YzlkVitvUUJZci9udnN0SW85
        S3U2S29xcUw3T21OaEpacEV0djNqUXcKLS0tIDM0Uy9SVVpsTlBpdzdnWXhzRk5L
        c3h0Rms5T2pQYnB0Y0ZGSjAxemlwWVUKNe06/PnS0smvQIEuhr1imf1JlT+aT02s
        KFjyQZ0v8KJPrwQ38ztOkpZcpUequhJnkGFbvxv+d98HacYV4IfnXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aFZYV0VUM2VzOG53SmRn
        UTJVdk4zS0tTQTBSdmdMZU15SmhDUXNkNTJVCkJDZ1d5RWo4dXF4ZjRHaDYraE92
        UGp0V2h2Ty9zSURrVnY5RWZJbFFTOGMKLS0tIG9OUEJSaVpKNXBtMEZkNjlmcnJk
        cGNsZERseWlobVphZ0lWTW04TGFDaFEKaXlg0AelBuiZBqI6LfsY4uEnR4eKodk/
        9r6mna/CLs0paebxTWLqSsg/ZFCQXbm0DTH9XbOqvNRjsqOB6MeR4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:95iE6JXSoenIrGXL02sq14sLErFriVKncy50IFUePJGy22x5Ohvj6YMhwdBeoaeeFlWLzOWK+nieelQobQ77uEWYtbNNLNAoSIZjCQTZN2r5779FVRF2yY6jUcr6rhHXuowFrjbFKU6u4YVVhTtdea6eC5O+EsnqG8Wl5GkFzBw=,iv:3kUMrp8jITFuQ/9J15tVCVnmMDYAIm1BygvTyMUHpG8=,tag:NuaJAqQKJ25gaNZwVw6IzA==,type:str]
  version: 3.13.1
