apiVersion: v1
kind: Secret
metadata:
  name: harbor-auth
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:z3lspQ/daaUG/UBSw2hXtzTWSGAnPG+/QnX844yWm5DPa+NCTKmKkqLYmwKURyzLa/HDGPmZ9dp6JBBsM9Dd8Iq+XkCcLt6FCXW62aotBRRVU4gqIUBykT+FOzWn1FFGKd5BRG856B7tew6qOIuquCibGTN7FzgIJBZ3/IIcdmHviDZ6+joLVO7AIuS9yb69zpqY/KhbOzEikowSIUN9g47flft1+Kzzlrdl/m6GLzJjq3nc,iv:z6OHh+0MO9g9NScdNVBdRHO3EHCOEi8/mAmSWDf8P+4=,tag:AYJWjcx1DEtqoNlT2xHlIw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNllLTTdKMG5SVTFWS0tx
        TVlCTHZZd0tJMHdBazJjY0RPWWFMb2pTZ1ZzCmFqRVRPLy9XejBOZDBzTVllbjVs
        RzhlcHJXTitZVTNsSUI0SjYxMmxpOGsKLS0tIFNRaWlpb1VjdW5xckI4SmQvK293
        ck5oMnpta0RzODYxaVkzc0NObWNaOUUKflAgoFbTO1q0Wbo9nxaJaEK+id/3CJh7
        gIHYDf9+jaK2gr51soWuozu10S0z8heRl47qoEip68dHqjSELKDeGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZDJtMjU1VitJNk91T2Qw
        WjhUS0gyVWZOc1hDaTFLaGVCZkMzV1hvekNNCnFnNUxmbi9BMWQwYUhwOGNsMjVK
        QUxVU3ZNYmIwNWNxZmpVZHhhMGNuYVkKLS0tIGRhb04zMmoxR0tZN0cwN2U2bTAv
        bXowSDVPa2NHODQxV2RCNS9OZ3dVYU0KTT9yrG4jsvvXKZYD4cbze16U4x52GbkJ
        EGfslNaSe7IjbGP4kNCg2sxMraYPdC3L/ix5i3dUleJG+O0wCn6vKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOL240UUFyY0FTV3BZMXY1
        ZS9iQjZsSFgxUjJnMXhhcXFubDZtWlhEWTJJCmxibmVFTVNhdGp0THlDViszbW5h
        RENQUjRwUFdBY3ZZSjVaYjZFNmJneUkKLS0tIExSQU4rV2sySncxUW82RGVWWG1T
        WmZ2VDFCckhUblZGRGdoNGRsVFkxL0EKlZ5Qoe164n05sZN5iZnwgf8COdyvbxaX
        5djLuxJKC0AcFEwJOD3+DQ4+vfly9wSyl/T3ZwH29ajYXZKzqHgyOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTDlMY2x4cm9qK0hvekVS
        aTdYS3FTdkhXOTB5aTJkWlNQUFIxUXBlSUdnCmZ1WUxsalZkUVlSNjRqKzlpbFRp
        RUp6dU9pUkVzdk9zMFVJSkI2VExOOEEKLS0tIE1ZQzVwdUJUOEJBcUpyVWFuMXVK
        QnFzSGVnWnZGWlNFZ2czVlZpejVNMmcKIPN+68foNyyQ69ngAm/q0zSTKSIy5ArD
        /TWD9kUEZcGSA7zugqh2c4Zs5jzu8cU/9LcVkWaF5kZPb7wyp8WByQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOWNKQTJTcjVpdVJKMEg3
        YjZ6Nmo3ZncxTytkRldneTF0R2thSmQzaXlRCkFicWxlbHRHWEI3cXFqUGIxa0N6
        RGN6NzV4RzlOQVZCVkJCYTZYU3J4TEEKLS0tIHdsdHRDWUpRTGZRVDdIQU0yRmR2
        Y1JZVzAzamhReTI5YVhjYU9NUHhwdTQK2zw5DQ2ABCuhFLiRazfHlY1tlsSCjP1E
        UtfUP98kXUrBYDTks44CNZr3msxBVF8IwbycxmsbIdjlOacSA64dYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdnc4MloxL2JyUGJJb2Fr
        RU5LYXYwZkp4Q0JNTjk2OGhLWXBKSzRSbFZRCkhGSlFZeHJKVjRhbVg4NFVOcENQ
        bUxSVU1CT0FCZisrNGcyNzFQdjdPejAKLS0tIG9PeGpJTnp6WDNha2I0Q1BxOVBj
        U2krL0lJZHczdTNzWkx6czB5ckNSMncKDs16L18LMp+iZMLNQc0sbAq1Zyao8iCD
        v8vddr5XY4DrvO+AI79Z/mE7SgVnCeC3kCY5RhzxgR6rfnbw3Zj0Gw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT0lIeHZWQkdtaHArUTBL
        dklHczRQbnhRR3RzMjhVeC9LWFNPRi8yQ1JJCmdWdUJEWUFwc3ByaUh1L1prUkY1
        bzVXY0prdHJYVVYybkZwNnZkR1MzMGcKLS0tIEdJODhuTTJpTUZSMHU0ZUJCWDdM
        UWpMcnByM2NHcWxwTXNIejhNTGJRK28KcrSbsExcKV+z5Vn1SPhxH/0Fsva3muTG
        l2PRDc4ehf64m/SSfjIIAUSrICIHVy0lKXNOaJWR+Ysx26EqYNidFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQldycU9TY3MzL3YvZ0FZ
        dmxtQ3BXZWVvaUF1MUZCeVZvT3cxQ05vSlRnCmlEZy9UTEtRbWNMYm44S2tpM1M2
        Q0YzUUJheGZOd1lxUDY0cVRCSVJSNmcKLS0tIGFxeHZCZ2dtK2FYVUw3Ulc2RU13
        UHFlNWFmbEZWMXB3WTZmK1lwUk9pVUUK2NYAGZOMJfmokv78wo8qw/6FTdjE+9rs
        umL8exgh2FRAKnQBhTrHkZOwkxUCFYIwHgWdiSnCMNjf8rn0VHWRww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeWo1TUFuMENwWUdZZFF1
        WUFVOGVFRnlkUitMUFRSMkVWN1puQzVGSjJrClJNcmdjM0JKL3F5S25yaklMNzZs
        UnRDWERFODlCMTdHcmFpQWdNRE43ZUkKLS0tIEg0Z3p5VnM4anJ0V3N3ZXc4WElR
        UzNVL3oxWUlkeTNjN1hlbllTOE5HaU0Kj9YM4nNadbqEBVxe1iDnJLpCqBY474Hq
        76EswK/izrGq6mRNRZ2rET+63aFSlwvr0dTSmK1VV4e9KWYpGHTdKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT2lXd3ZhRVkveFhUbDRq
        bDRFQ2VjL0xhYzl2SlZTNVh0ck1HbUFFc253Ck5lYTFHaTJCMHVaUTdWSCtRYURX
        MVhxQmFhcHJNRlBpWnNaMEZMUnVzS00KLS0tIFlTK01qT1k1THlBUUhzS2pUbzRK
        WG8raVVsU2FsL0ZkYVVWSWthUll5OVkKVRgNmN9NnCzvK3A8THiqtwHhCYwpecr8
        zzEYDlbOZLgTQltdj26JWk8mY7mBl1rfrA6+rVHLBfiG+cqsXDLlXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:DcBodwR/h8cfF7wKJn1b3MkNONqBhxJ68Q+Amk5CDNqlxYNfF6C9/9W7eO8WFGjvNRt4xM/aujlqFsAkAey3utfjJMUvIPiKcJopdr2T5rvFd5YYRlL+FGHoyzgYhUXmdueBgB0m73d5EITl7Rg1XloKAq2OziwW8sefGfl9828=,iv:8HYG1SrhCr8QLxetlh2u6XFwGNm4aDyjxmtJk29e2sI=,tag:iUFrFBZxQt7sWrY9EGzZqQ==,type:str]
  version: 3.13.1
