apiVersion: v1
kind: Secret
metadata:
  name: harbor-auth
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:RnLPyZo/dA+aX+45CXuMR+N3fg1LhMaK9Q07qYHvLcPIgZjY6A9Og/nJYq6rFG5rprNXhDny2dWOCUHE+34ybOeu+C7daUm6Nbp9E41OpJ8+9LvRjLZ1owg2BZbN5sgIVzc3qxNzeaP95CaXw2IAVLPyJ9pW6gTR2pIZLpmDLhbHPFYCAw==,iv:SIA9gAZYXogAHP/cxG+dfquKMtIbniY4JF1+wXhtfqQ=,tag:ZefD9dYoZ0GXmKJhcyKD1A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidlRkM2ZWaGNjN21NbzlK
        ZHNKSTJKRWdyQU1MVDhIWnNBOVBHNkZRcnhrCkt2SURNVXBoS1lkNWFVa0w3L2dn
        Yk1FdC96NFR0WWlSWUJzU3hhM1E3K0kKLS0tIHFrTzhOOEl3aE9QZ21XbWo2bWd5
        OFdzc0txTE0rQ2NzNlhucmNsSS8ra2sKYG/3jVn213cZ/a+rz/G8TnlDdCrx6gk2
        HQ5Ol1jtRGhFO/A425OBvjD+X1SWEVjOq3EkRtJBtfcXCcfMVt6kpQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZk9ObzFZaWxWU2djUFNu
        U0NES01VU1FUOXAwY1JRekk5Q1Z1T3V1V21jCjFaVFNlekFDS0FEc1Z5Yld1K3JL
        bFdibVYxSC9IVG9JdC9uY1BVcXVjQzAKLS0tIGNIeDAyeWJ1eHNvblJ3NHNFQ0ln
        d0I4V2xnUVVJMW9oZ3kwbmVYT1BrUmMKcRkGx/kyFkamktyutirDd774PkQy7Thr
        lEdPVuhR485cXKn7YcD6lzTU5P1143b8d1VXZkfaIGBWMK7s1DiIGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM2dZZWhDY2hqSGlLdWtm
        dGRkNnJNeHdsUEJNQlo0K2tibUNqZTlPNFE4Ci9rWFVMdGRnNFNNQzBqcjYzUXNu
        RHFFWWVCZlNFaDl2dXFJMHE4WGlmRVkKLS0tIHlNeFNhUTI2UlFGKzVicUY1cERm
        SFNuMmhaRHpsYUZqUU1RbVQyemxpQ3cKNlsoaVho4g8K7CJTEWaU0873CGJ+5ugd
        AM61aaiZ0YLIF5ZRTL9fjs1rk67qeQJcOEmh+ipsKKqjhT7HULTytQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:14Z"
  mac: ENC[AES256_GCM,data:jFX0JLyDD+IhjAX6HLflJULnJBMwDpQap7xcUZRS2bNpaqu3qJWTCXkD7IQIV6nRwvF02QEGkLV3YYufaa800ZlchsFhVchkT2mYkrzqivubuFl9YnUqlWRaQmNYdc15mdl3793de43wipBH44ud30fwQA2T8lZSsOADtHwKs44=,iv:4vigsEmF345rxxfLJPncseYsanqUJPSTgCeMlFffvxM=,tag:PCYfZPf3tE60N7q8wbtNXw==,type:str]
  version: 3.13.1
