---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubito
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.kubito.dev
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: flux-system
spec:
  interval: 1h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfd
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry.k8s.io/nfd/charts
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: flux-system
spec:
  interval: 1h
  url: https://intel.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/grafana-community/helm-charts
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: obeone
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.obeone.cloud
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pajikos
  namespace: flux-system
spec:
  interval: 1h
  url: https://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 1h
  url: https://immich-app.github.io/immich-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 1h
  url: https://jellyfin.github.io/jellyfin-helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mongodb
  namespace: flux-system
spec:
  interval: 1h
  url: https://mongodb.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vernemq
  namespace: flux-system
spec:
  interval: 1h
  url: https://vernemq.github.io/docker-vernemq
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.zigbee2mqtt.io/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gabe565
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.gabe565.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: penpot
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.penpot.app
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: planka
  namespace: flux-system
spec:
  interval: 1h
  url: https://plankanban.github.io/planka
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ex-trim
  namespace: flux-system
spec:
  interval: 1h
  url: https://ex-trim.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stirling-pdf
  namespace: flux-system
spec:
  interval: 1h
  url: https://docs.stirlingpdf.com/Stirling-PDF-chart
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ghcr-danielr1996
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/danielr1996
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ghcr-seerr-team
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/seerr-team/seerr
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ghcr-renovatebot
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/renovatebot/charts
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ghcr-mkilchhofer
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/mkilchhofer/unifi-chart
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-operations
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/home-operations/charts
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h
  url: https://kyverno.github.io/kyverno/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/envoyproxy
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: siderolabs
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/siderolabs/charts
  type: oci
