---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: z2m
  namespace: home
spec:
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: zigbee2mqtt
      # renovate: datasource=helm depName=zigbee2mqtt registryUrl=https://charts.zigbee2mqtt.io
      version: 2.6.x
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: z2m-values
