---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vernemq
  namespace: home
spec:
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: vernemq
      # renovate: datasource=helm depName=vernemq registryUrl=https://vernemq.github.io/docker-vernemq
      version: 2.1.x
      sourceRef:
        kind: HelmRepository
        name: vernemq
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: vernemq-values
