apiVersion: v1
kind: Secret
metadata:
  name: mqtt-users
  namespace: home
type: Opaque
stringData:
  DOCKER_VERNEMQ_USER_findmy: ENC[AES256_GCM,data:U6WAu9bo2Xlk5OEog7Ek3L8qsM0bi0mq,iv:fIJ1BdddlwR8rJsMbRNzBPiCO2RT0NNg2WEa6L31l98=,tag:RA987fM0l8OEKK2UinVaxw==,type:str]
  DOCKER_VERNEMQ_USER_homeassistant: ENC[AES256_GCM,data:qtgjEbTzGQxmrK4h4u6wFRTpjaMA2Rz6,iv:GNjpYaeXhxvzd10SS/RQySm+L73gSnLv3YPvpLuMcvs=,tag:ZhTHujpfQIipBaCTKuD5Gg==,type:str]
  DOCKER_VERNEMQ_USER_zigbee2mqtt: ENC[AES256_GCM,data:jkJTIJY9HsfTtH0bW4M8CEhDHBwhqTUi,iv:s4vRIJEqdwhF033cxIslEa5NGiMBaLMdCKxRRhPmVrg=,tag:PtbkTWoVwWKIEo5160EJQg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRzYyKzYrdEV5Z2Rkc2Vy
        alhMYmU0RnFQZE9jREJOWnRIcFVIR1Q5UEFvCnJlcVdPcTk4QTZRTnRqR2YxMlNZ
        MWwrSzlPS0JLTW42bHBrUXlGSWNicG8KLS0tIG4rcHd1TCt5S0xONzNpT3NWUFl3
        dE81ekJ1RDlxbHUydnhXTTVPbmVPZEUKKjzWyanHO0CLhrdWZcouF3bulId23j2i
        YrHRALXoBY++GM0+gpBx7plKDX45qxGnnNMDmpS51NacvSOoEBiDJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdGs5cnB1OHdvWmlnY1dV
        djNmWnZzbkFsRXhETjRTdDdMUHNrOEs4UmxVCkxuaFQzTDJxSVhucmllQTNreUpS
        c3J1M0c0Q3BLejNpQzdaZGljRmZ2aWcKLS0tIEFENU1CVkNicVlvUEpyeWtuY0NP
        b205YjJMSHRrak8vR25iRUd5ajhjRVEK7yDTE4cQ/J/s/3c5R+0nsV6IYqYK/MRp
        P5Mi2c5eeHLX1zoMMqTiYjnxrEmRT7Pq9XZatdXQSkbunCqQy3+u4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b3h5bytxSklkcnNlZHVN
        NWJkc21wUSt3WHBqSzc5dWsyam5wcy9DcUVBCmdCRktJczNEMWxCczZoQm41UmYy
        N0EreTE3UFJsa2lwL2I0VmpyNmpFTjgKLS0tIEVRLzNYRi82ZTQ3WjkwZStzeENt
        cmlYL3Rrc2F3VTB5K2toMUJLU2Z0aVkKNqUr+z4QzrpwlzY9a+9zsdGo7fozhE5P
        iu64DIt/KPRdwevXlNMDpnaR1dp1Ymk3T9xzFwIbmu138a40eqd12g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:13Z"
  mac: ENC[AES256_GCM,data:GCMB+lgSrjVGwzbOyDCqZleYtoOiw2T2s5fdzgKAU+EJgSkSCpXBsGjVQIOyEIRlcdCvmbHtCmRfAdq1t9EUmkQGzJlAzZGOUbAVy4N72ZbWBrTTwJntVpK7dndNABk32uzHFOKmezTuth7tSyTjfzcwjH2wF3B44FGmib8zI4k=,iv:0bVyDJg1hmqUDBsaZmjuuHnFs/CDLPot0UG1Y2ZyzpY=,tag:4+MkVGHnUJ3T3PWKbHRBGg==,type:str]
  version: 3.13.1
