apiVersion: v1
kind: Secret
metadata:
  name: mqtt-users
  namespace: home
type: Opaque
data:
  DOCKER_VERNEMQ_USER_findmy: ENC[AES256_GCM,data:c1JWz3mapC39gSg03H7fLWwkrXCd1bhdESGCjcAlEDw=,iv:MdwcPMH74Hnfa5qZEIz64PEshN7BnPk1BdrTDGUNDyY=,tag:MmWr9gdOkGeTTvRQFU6X3g==,type:str]
  DOCKER_VERNEMQ_USER_homeassistant: ENC[AES256_GCM,data:40MejTppHPTBvsbtt1QcaBL3VWrt8+Jr+K/OB+rXQuA=,iv:3+0M9WqWHvFIGXyHp2WXqyYmz9Ed8Jsk7e+i92JKy2Y=,tag:zkqmYClN58neTOagkUj1ew==,type:str]
  DOCKER_VERNEMQ_USER_zigbee2mqtt: ENC[AES256_GCM,data:ai1OJk5KdJNE8vnftoECJWxtakul7iwr7aunbiUdfnc=,iv:X3Cit+zgIRDTvxgilYTbO2as8nQuGqKa3/9fk5e4vKk=,tag:CAlzj0dKeUovFfTRi8wk8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU2tpbDJXUUtwQU1JUmxz
        Q1ZyamM0YWtseHZETThYZVdvV2hEK2VWT1ZBCmlaUjQ5akpTNkFlSVNSVkl3K0JE
        Z25nQlg5bmgzQmlONVNmeUJwRExNVkUKLS0tIDRaOWFIUUY3MTQ5R29nTExNeXhT
        UkRhN2NuOGNYOHozRVF0MjNVTUduenMK9kpjrqtDRD6wI9AEj462d/2wnpi6QWWf
        9AXO03s1juGcf/l210tKPtmBfMIeHTvPnrqCu3HcKzRbXTi2+wt13w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK0tkUjNPY0lHTWNxd3B2
        U0x3V3NWd1pGSXkrYzhsLzZwZ3NGcG9MdjAwCkVWVUpFTUxMUlBvLzBtaWpIOVd6
        Y3dNbVpFTWVYTldheTQwanE3QmlPVzQKLS0tIFAxN0Q0Z3RBdFI5UVBNYjZtZVdk
        OHA1Y01aak5xTnR5RUVsM0FZL2lDSXMKD9ftyuCMRm/IWRkEAgYsIgA17yvNZNqA
        26yO/WOfdYHjMflnzF2E4/qkbIsl0YR2DfVS5N/6OrpuK3/Gt8uYFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudGUySVdwSFhSa3crK2h2
        MDNjR1BDeW40QkQrTWtLNFkyUnJyeGZxdURJClhjWHJJbEJsK3Q1TFZvak1RN1Zm
        dk4zbVFXaEdPdzBzYzZ6M1lPcHBzR2cKLS0tIHZINTJ5bENVUmtvWGFnK1JzR0hZ
        amlMcWw5c1Rsc0tHRUxzVU02UHlMazAKlPqBQrDRi9LKvQ/NcXEeVhX2JiMNOmF5
        FkYrQEEj7v1H/qDUEDbAa/qpP7iK8B0pJrxdC72GXmdr/vcWnJmGjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeUxUTEVFaXVaQ1JhZ2tW
        QWJqVkI3T01QZWE4SGIwem9kQVh6N3dvM0hjCmh5KzV3QzY1NE5VTUMxZVExUTIr
        NEt0R0NBU1BudFlYYlpnSzU3OUhJYkUKLS0tIGtvQVlIdDJWd3VpM0NCS3prMnpE
        NW01emJTY2ZkZXk5bWdaaFhoVE1TT0kK0yyma7BRvX0AiE8n3yq+SJR3vvtsmJlu
        SkFWBVHmhM/bGgjECbiKhkz6IEbsADms+Ajuzmw3rjFJDbw2QU5Slw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib1VzTE1WSWxab0s5ZTF5
        TmNnMUxmZDJTS2dNdXBURENQRnBPRlJyUlhVCm5yTFpMVjN5MkNsQmVQUFRtajVu
        Z3Q0UldOMUg2QTJSSjhqKzZmaHFhUkkKLS0tIHdvbXdaZnVWTUpNNXNoQmNtbkhS
        QjBWdmxzWmNLTEMxby9YcldseU9KWUEK1B1XhN5Y2wFyjiNhFQwoKEEHdEmeIKUK
        kW1QfPozoQkGbqI2iQ8Zx8nyNzW6IY/VHUq2HFH2Zb7itmypXTDHrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa25XdWVYQ2d4bGVELytX
        dHFmUE00NHJickEzQXJISVkrWjhVMzZWR0ZFCjN1NDdhZ2xMYUVodnFycWZyRVhG
        NVZ6SE5ZNHRESTZyOGRBVTZBdWRQOVkKLS0tIDFRUjZic1F1WUtSa2FjN0FsU01q
        Z1JlSE5GTlAvVG1JUGFyWElNelBjc3MKE90qp9q5QpajdkuEsrT7G77OfC7wS8Uc
        gHqssnx89tt3dWYfUVokzBAdIvXLI4ed9oZPD3VJjdTFhYtCC0rJnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dmVWNzhpd2QzR2pRNlpG
        VDUvUUpwOEVHU1F2T0R1WHh0MlkzTENVbjBBCnhKd2VwNTNleDNDcVhsSWdoRlll
        UkNTR1AvdXZUa01acHpKdmFRSVp1bkkKLS0tIElwMFc2QUdHTW1NZGt4RC9WckZC
        TTJvRmRneGs0TDkrU0lVajZZMVRpeWMKfw5LvckzlHa5bTgLgUtyeBkeUJ+y5fgs
        5Y/kjlIrKxTeE8V/JQbNw1wuN0pSOqsKNHyJOW44YqdYVAlC6407BQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaUhyY1RqcUx6OXNrSnBr
        SHlWZzBmdTZYTk9Ld3E1YVJ5QWpyUm1tVWdNCjkyVHo3ZlVVanJCV0VBdHZ1SGdz
        OHBhUlBQUkwzWWhoTFU1MFVJeWZoREUKLS0tIDhpUmlGOU9IbG5ld0Z2VlFSVzVC
        bTVvek9qMVNMRXhzemVlMVhnWlo1a1EK2MskK5mPZQKvNlcnYykdpJ1JLerFUdOh
        1v2Bd1WIViC8Oox6omkRg7NLWT5Urldk7SqrHP2cpLfthXplvZ5vLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNkI1ZlNFYTVZdTE2cHBu
        UjdPVUl5cHpDRTJsdU9aMWhRUVFrMXdBMDE4CkVaWG5na2prYTZyYkhWMGExci94
        N2k2TlRJNDlFZmxlajFrUDBqb3FDdncKLS0tIEN3VFdaNHpVM1l5RDdQbUZQTnhv
        b2FtVUl0RnZMaVhncjluMjNuMmZzckkKTH+nRHr9OQgEgos7G8wu0sUOG9aK4sgD
        GlAH1wqFBl/s4HzEiySuloJJ1i/4LBjkgWI37Mt/poH1Eoy+pElRVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaC9nVnZ5eHNhZldldEhK
        enU1WUxPWXAzSGdtcHozRWd3ZW52VWU3Zm1RCllMUHBUNStnYk9hUW5sRDlaNlNu
        QlpMemovRGFsaC90K3dxQzZHc1A5QkkKLS0tIE01SmQ5bkJLQS9nWVhad2Y5Q2pJ
        eTMyMzViTXpFRTRkajR0NW9BUmh6clkK7lkw1LqG/1usx58Yuv6MCPDHEKsVqMta
        RPW3oSNdhhwjsjQLcJpmOiqNHkGrozRafUUf+btbbbum9Vttg0QRcg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:NGba8hE7lSfASrTmnaZDG1dR0tABnAfR/uZ87PkELo/mptsImQ7CmBt13NJw4jna9cUgpWmqv8JJjgimjGZFOig3tce7ZhTVkaOG623tG+LEUnLhL9VEu1Z3qjyviOBpiZw27Dcjh2WH4yPniS1IV+aaBJ4EQz/z+sEDPbS1k5c=,iv:OK3Rt8hOV0JDM9lkJyZfqni/T0J4By09hUIRWNyUuzQ=,tag:T4tcuRwfHtMuWz3c6L3Fbw==,type:str]
  version: 3.13.1
