apiVersion: v1
kind: Secret
metadata:
  name: mqtt-users
  namespace: home
type: Opaque
data:
  DOCKER_VERNEMQ_USER_findmy: ENC[AES256_GCM,data:/gLGVairT7+gf3zhRmQl7Nb4wC07DOEQnlKgMVUwZYc=,iv:HpmFO1mGAtg6MGVMy/Jah+dE0XlWcudqV9H4h05A+Uw=,tag:AQ2NKN7wNviza5JL3nN/gA==,type:str]
  DOCKER_VERNEMQ_USER_homeassistant: ENC[AES256_GCM,data:uaiHmFDnCPUVKx4dMt+i66XS1j8FSkoQ4hZb8T7BBpo=,iv:vhelyQFeWDp3jjLDYMJVLh24OWo0Kff4TGUrXwm4mPQ=,tag:2DdaNzie/75vv+U9MYNZ+Q==,type:str]
  DOCKER_VERNEMQ_USER_zigbee2mqtt: ENC[AES256_GCM,data:qXtFKZdc7cRCAb0/J7Z8wj9YNrjEwtqJ7Rb5/fEoneo=,iv:o38lcs73g/KxiQDjBZGqL/pgqBFEJyNTM+vnmEqq/bM=,tag:D7rVBjFwMfLxocinb/e5ug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZWFYRitVTjA2YUNqVE1W
        aEkrNDJOMXRUWnpyZDBGb2tXMjN6VjZNbHljCklmejVpWjI2V2lXUjBjMTBndkVa
        TDBBZThUOG5jN3MzaGM0SzFlSHRHYXMKLS0tIEpIeU4wc1BWYXFSa2NrT3k1V0hw
        MkdpcEJQR3BoRU9XYlcxdlhTRzltOFEKncFqESBtkDMBSSqZH99OLP5vPKoMYP+p
        Qu1HW7OXpZ/76aMqAZyIhZA8uwP0Io/LeJBlOhnwcokizO2RlMhU7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcmQyS1JISEtDbjl0V0Q4
        Tllmb3A1T2FFa21aRU1YcVRMa013ZUJsbDI4CnkyWTRUWDJlamFoclJzM003RGhT
        WmNMMk9mb1NmMnhxazhNYVQ0ZVBKb00KLS0tIC8vMFZHWkNTRDNsRDRvQVJtU1Va
        WHVCSnhxNHBEb0sxYm4zUEZNMWltbFUKaMXHXRN0Ml3is0Z24S4UFZhsY4B2FvRT
        qH43BYCdD+nQF27sILZFoC/owkuxVDxfrwiDrsdE26Xx1QABHJtVwA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSlFvc2dRdGh1QitnZVR2
        eE9iOW92Uy9SZGtPbnJTQ3dyMllUWFBZS0J3CkRJVTNaakJka0lyemw5MFVlTjRT
        QmV1b0tWLzF6T1huQ1lRcEpIaHhhL1UKLS0tIG10V0VmMnpjRHZ6OXc1akR3b3Yx
        OFJJYnh6TWJ1ano2bURFanpTT2JFRmMK55bBONxAZv80ojYOjEhnHaFowC9U0XY4
        yKgPSq/zTEtqjDlgPnpD6Bu7M2C8aPlBuuZAxIvz3p6t7GinCFor7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:ynpYpTQMSfQaafwlDcWC1ba+v813RsVodKTDOoPHWTYuRIpYaXOt7OPxDcVidF/jo2J7vfHJiHBpVvLmzchMMvdvew7Xkt7syDU8Rtj3ulrq3Lx6dl8+MpOaT+ITGcU1Meafd1Oc//UGv2ep42SmGA9BKfIf2YnYrlcdbO5GeIk=,iv:ffSaB4doSnTbwhP6nOmzfKmbcWxVb7/5c3osk+OgenE=,tag:bBjxwhlLVty+56IjvLv+6w==,type:str]
  version: 3.13.1
