apiVersion: v1
kind: Secret
metadata:
  name: z2m-secret
  namespace: home
type: Opaque
stringData:
  secret.yaml: ENC[AES256_GCM,data:HA8bO6/DsOGkzeKe+/KuFeaORab0YZ46m0Wtjxg3wQHM+/w=,iv:yRSkTTnLPeNGtVfrQulK2fhaKFeEfPgOUUUsfEtcf6E=,tag:408HcT1uIaYFnRJK9wzmbw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ME14R1JSN0JkQTNjR3h6
        b0E2L1lJeklhRUpCQ3lYTGpKZysrRlkyTDM0CjI3cVNpSzNXSFVZNG9TZmFJc2Qw
        T3lCVmcwN2pkN0lyMzdPdmtIVVdUcEkKLS0tIEIyOXJ0ck53aVU5UytPMnBETjQ1
        cnVxTmtiVjVlMjZ0ZTRqMFFjVjBXWmcKEOMvoFk4/BFYKpy/MM8ujSboV4VN0DrU
        wxAoRN7nQa5iWxlAKEn9TIAaAHr9t0FxxhktLWE+XaZVQk+qnvja5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeU1Za1U2MTB0VUNSWGxk
        SDFONXFkU3BtdXJkVm5tOE9pTEpBb2xQeVNnCnI0Qlo1VGJCNVlZbEVXVUtXYndC
        ZlU1YTZmc3BIZkZJbEkya1FkcU9kWEkKLS0tIGtnbnNXRzFLQzBnemVGaTBiV0tk
        eEJZa0pmZzJNd0xDWkdML2orb2I0dDAKJ+HWrilAJdKfZeeX2UyjlOZfVYTRAFzi
        csE5LF7MPPqlA43RhQYvcpZ8FQ8troCY4xdfXlXZvLY0u5i64XAQfQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeEJqNEsyaXM3L2xIY1A0
        OGZHN3RXWkVmR0doeWIzZk53bDhhbEVmang0CnlkcFAyTTN4YUpqQW9mTDJJbXBZ
        V3NSTFdyV2N2Q0ZDSVlPWEJkckc3ajAKLS0tIHZiWG9MbllhQmVPYXhFZWpHWlVR
        L3VNVlo4Q01UWDFjZlZoYXl2dkdYbTQKvAHDcUJfQXNdSOJb/r79cA7XZf+TSoq8
        BIhY4AaRqrFWI1CSwcBEhe+eJd4DaqbgAigRjBP8lqgsIGn+WFfb7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T14:00:13Z"
  mac: ENC[AES256_GCM,data:NoXIz9uGUuQ8PpLIGdwYzniM8iMvrAj6Zf6IIOqVgMlUsU4/hwE8fF4Y/E0AtlCj/Qduh9MQD2kuWiZucDkCi68pr5G92SIaBEruY+RjzkdjRz1cVijf5GFRt9GEAz6UV/AZ5OVJvw8CWWDUywtywr9DwdNprZ3C63qaRGC29TY=,iv:ZFjuHh/Xf1d1KH4FZ3MgVZpj3cpximX/HG5MWrvb3RI=,tag:N5E4DAsc/56rX5jx2l+8ug==,type:str]
  version: 3.13.1
