apiVersion: v1
kind: Secret
metadata:
  name: z2m-secret
  namespace: home
type: Opaque
data:
  secret.yaml: ENC[AES256_GCM,data:wFQobBoCKX2dRHWUgdRnJoWgHjkUMCwmiUQU5YreWjseklhmsuQU24pb2imwk3OK,iv:sgc48Gd933Sti6Wz6LwEqbgpzFhMXnPjmYRiPkJv7Og=,tag:hLFgPtNLfh2Psl5tqAia9Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRU56ejQ1S0c1eWhMa0FD
        R3Y3amlHVXVhalBBaTdFeVJWc2NXS083RWhrCkNjNnBQSmZHWlQ3S2R4OGhXbFlT
        LzUva0cwV3FES2RodUN4MVdHRWZTVmsKLS0tIGo0Y2pZQVdaZGo4RUNPU2lNR0Jr
        aHFnQTUyYlpYT1E0YWRtbUdMVWI2WVkKsvIz2Q0TQb3Sl02qKDwVuNiJ6a0sh8zB
        0D/7/cyRGbJ018tyS2nmq43Vh2SHdtnovSAT4ZUKVVvG01px+J/Tng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdTM1ckFGbENJY09DcG10
        ejVib1JPRzJCWVBEdW9DMkhsNDFUTFcvMndrCkNLN1dSV3ViSFhxYWJsZGFxeHVk
        ZkRQVHZtYXJpelFEQXVtWHFFNWJxOWsKLS0tIFNOZ2V2RVZqZ0VTRFE0RVdnRTNP
        TzhRSGZweEJFQ3JuWmI3WldLMGhkMWsK+qCcwqTQfIeMPotGy0gVRsuRtvOSJ/j0
        85OerZ8BKhPTrAg0GDJ5ZLUwFgdXtwQ0hCgstR0mpJ4Zwc0b6KIU4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age13qv09asag3lvqcj7qccc85shaz23k77038wtmk7tqukeuex4sgss7f8yun
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcUxkMDRyTGJ6UUI2Y0Vp
        N2s4OXFuWkpPdERHYVM2RW5YVmtPYk9pMkdBCkpPZkY3cUlIUG53bXl5ZWRsa1ZN
        U3VwVVNGTVVQRGRMaDRrK3Y3RGJqMmMKLS0tIFdqTTg3R0xBaUFLcm85VzJXcDM5
        eUJ2aUFieGhWQVAzZG95N21pTG9Yd3MKT/YPswZf9z1ftqSLDjWgAh+AJd5nV6xY
        KDCWeuDVNZIzb++zXJfHMVgUoKXbacpQWczP826Hna9XwzFjG5fn+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeHQvKzFGeHN4Q0QwaDZM
        czFGUU55bVNMOTJNSjM5WVFPdERGT2dtWDNZCjlwWW1VQjVIaFVIMUlWQnhtZSt4
        TlVRZmJXYS9NWVVFc2UwNmNoekRzbXMKLS0tIFk0SnJUVXRkckkvOHdaaFZIbFBa
        TTREZ1NEOHdLMHpBSjlQTVVlaFcxdm8Kp3ZzfyXiPuVzmcJxuFKwnPkGEFK/++kN
        SNYwqX8a96bMl1AH5H1espdOQs0nj14SbKqJhdBgPVnKaQt1+pBsLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10tn29nmrls9j4hd8t048ha6nv6re0hllps5hmsl8gsxetrzmterqevm2ks
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T3YxL2xEbGN3TWM1bmpx
        ajBMdzV2K0FqR3RnZXhjTE5TWTI1REhtSVNzCklJNDVlRStHdUZ0WHAzTzcrT1d6
        aVA5SUp2aFlHVzVzakE2dU8yQnNxMEkKLS0tIFNkYzJwQTh2QnowOXp1Njd5NFNn
        dnRNd0x1bTNTbVNRbTlaeG14WHJMaGsKGSAS72b2FKJj30RTbRruvYduNDBz7t+i
        FwVfKgqNcyZ4grsqGdMsjoJj9MsrKdXKl30gv5E8vDC5IbbnA3qAAw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rsx0gz0s0rxfyuxxgpzhlv7vqnt2g3e4xmtwm6qlgdawh4n6usdqssucl4
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTY0kyZEJydFdXRlBPMmEz
        WkR1Y25UK0lMaGI0MW9yYjFSLzVYMys0eGl3Ci9jdXFaMzhJMXUxbzdYaWEva0d5
        TWFDUU5CRFJWRnBGSjY3YS9KQXhabWsKLS0tIERoUDBGcVpRbWEzdHpZcEZMUHpC
        YnVyNHZvcUsycDJBNUhEUUNLd08zVTQK3LPPk4GzYz33JiPGYhY6M4NGbPf7fMLB
        Kb8GdaSUanS+4bSCd/P349/Y1jofNGg+kf94Lc70aemURGi+tOchsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dqyhvgjxv39ysnwqe3rjfee93kv837f5jxlar244n4fcwplxmfwszdn4qm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcnNIQ29wQVFlRWptRklt
        a0hZbUxyMmJpMkVZamt6UW8wc0lCc1huNTFzCmJlWGNUd2s0cWY5d1hkRWVZdmg0
        dVkrRXVrUzRIelFuSUNYMjVoWGg5c3MKLS0tIDlXRytldWgwMWcyY2xEOXUyWDgx
        VTFxNFo3Ni9NR2lVcUZCVjArekl3MFEKb5T7JHRhrCG+8ZAES06I+UJu/l50o47A
        k5hEbGtMgXeaRegrPQQvCFQqrq/Cz7/Bce9v8GWkX+k8rTXr+aOtRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14djszculchacjam60zjqnh4sw2hgkptvnc4uxt6ecswjt6cpjecsct4rxq
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S0JYYWZFa1NDcHNNeXR3
        ZmpqZEZiSGdqWDhoTEg2ZWNwNmlQZVZGUkhRCjlwNnBQbGxTNjdGNGt4L2ZOQjlN
        YUVaKzVqMHNWRlFNQXVqamJZbXFjdDgKLS0tIDRQb21peVU3dDA4K1ZPVUI2VkZW
        eGdCMkJscmkxcTJlT0lieDFEWjZIZEkK5H1ut3xrOThxnAc4yNal/W9A24w5t7iF
        9fJDEJZY/MQ6uhq8IiQYc7GSvt2/yuyl8ZUNyLgDULScO/5/9tyqKg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10lyapeen3ef7zy5qv430rcjkm6mzm7cskjymu2ldky9n3zxrgcns0ws5dc
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueE5uR1BYalVCSFdCUG1X
        SXpGZkJtbmpvM0FoOGIySGIrM2pSbWVMT2trCk1hRGIzKzNxZVh4c24rME5SU3pq
        QlJwejRscW5vZUFaOFNkVWw4RUI3VFUKLS0tIFRjM25Td0RtQ2NScENZRHY2Mks4
        c0FZUldSWWtnTTNtVW5jUS9qRFdnUFUKUUZ4Ho5i/+7IhxhSqMHzxG/MUAMwuCRR
        Ih6tvrMkDPSAsM/Pb/wvhHz2bJK8m9woj97K+zqIaltK8yngONEkaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age158sqm6c2dcaut5a67dvceaypxxulydjcgwh8mld32rkwlvr8mdksfatdjw
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWnU4U2tXN2FZRXdwK0FG
        SzRpQXJZTDhZcW1GZDR3d2RkMVJZZEZhUUIwCmhWK1VsVHJvaEMyLzZ3cmxXZUty
        bmVsb1dIYm1lRXdGUkRZM1R6WFFjMXMKLS0tIHdubFlCYUIwWWhjOTVBWWIzUndB
        akZVZnBJNElRK24vZEt3THdLUTVLUmsKlFD9+RdrhFxzJoEE1ni2GksSJ7uNYgjG
        CGMEWocB6KNpySE1AQQ8tsh/1EdmUmC8SX4VSyIfZsAN1HlJ0TnG6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1u7zfagm2mu6as6w6mxy70gk546q2m2jg83sv54zkr665am8ruu8sk6zhj2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T12:21:48Z"
  mac: ENC[AES256_GCM,data:mD+5TX13eksGalLbg/vkQxfPhiKiarxd3O9vPPQtHELjyrjanH68W2eKMTuzt80TiWHbX1G5hgQNWpwaGCwcb01xtCTUGzkLkS8y2tCf/T3IwP/INfAb103rmIdkLvGb4kMZnglts4YX6sB5/0mxVTBLxqhWKGoPRqmM0qb/MQg=,iv:3zPgqnZaeZDgyJVJ5Gu71r3tclXuqiKlJwpCrLTGm58=,tag:mNktVFObCK0btJA4vSAhbA==,type:str]
  version: 3.13.1
