apiVersion: v1
kind: Secret
metadata:
  name: z2m-secret
  namespace: home
type: Opaque
data:
  secret.yaml: ENC[AES256_GCM,data:dbzVPeTJMrQdOMkJ0QW/huQ8XUpuYR1iK3IeZTHB26MZ0MuO2miioVJqEBKjcE3I,iv:WPPP5Hy0l09Ec8pm8M8SKVBY3OdebJ6CuVE5GKKGGFY=,tag:eEYwjm/wwjcOWZglNfl+fA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVDBQZjB0Q2NMc0VNMVZo
        eUVDWWxtbVJVUmNNeDJJalM5MVZsR3U3a0ZJCnJtNmFaQlgrYmNRWDdyYVpOU2VC
        QnM5NTF0akFQWjY1OEROM1pDRUFOT0EKLS0tIGh1UHhxMUh1algzY2JZK3p5UDd3
        eUhTR3pBemI2M2xjKzExVlRGeUpJaWMKSKS2cTtdgem3sZ1fgiR9oGnpXdVo2Hs8
        ENOL9e2Z6r6qiFRniH4Qb9rdOR181wd0oJcdQauxE8VBxvLKh5VQSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qqj970fl5nksjr5wzk0t5ycgyhytngljsy3yctdm9ejs028023wqqhkxw8
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU0tvMVdtOWFCK0VmUlhV
        T3l6dXVJQTJiZTM2dlRSaTRsdnkxTDJQQmxrCmdiWGZydlJLejFoamQ2WS9WZXJV
        Z1BMTlFEMndtM0w4TE9wa052eGtMMHcKLS0tIEJUWUVTL2s3cnpIYm1wWDlKN0ky
        bktVenJCSDlHdkc4R1QzVmJ0anNpT2MKgSX64AdCY34FeqhIsxZrsLjIojznbVxl
        TUC6SsKrakygetDoSqbNnIA6zaJgGfS0kSDkBmcVJdDlzmqsAQP/KA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5evkld5436wn3jexc49j4g272eq0avhspsldjzs0natc3hy4unqkrlqdk
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGxqY1kwWlV4cGxUYWlH
        RUxNNXBYME9oVHdocXlFUVpFQUhxY2pyRVRVClZFeWpYK0NlNkthbFE1ZjBOa3c3
        aDFzM054bjRjY1ZkTkdkTnZERitFd1EKLS0tIE1uaDlERlJNWVBPUzluM3hIdHNr
        QkZuNFRhZXltV3BJSG1WZkdCKzZIdFkKgzB7m2bhyzUGocvcxlvhWq4dmUAd57ia
        H3xodB4QAduKC6Ej4sPwrpi1nn61Vx9cs7EOTrA3Hk9vahCduFXZuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1frw660yfg3n6m2z7e39d2x0l3yw2k7lj5xx789pzuyt6x4amlvxqnnd7pc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T12:19:35Z"
  mac: ENC[AES256_GCM,data:NSsb1wEZ24/uWDFlOvNJ2FtJAvu8ncIWwtjHbsvXGVpkkn22Jn6eGewDAF+QlbB5htuEgDmsO9gF2mleRG+/w5AWNEz6khSvgD3qkXI/YPzQqUO9+APl+S7OyvX0iXGwwtK8nvDSabEOs1o00NxLIoBOPdDWQJ1W7uM8DIRW13s=,iv:nBXyvKxmoGqx5rxpfDzMmKcjbLuCb3deQkm9BldE72g=,tag:83VeiApI73dnq0ifBvY2pA==,type:str]
  version: 3.13.1
